'use client'
import {ScopedCollectionLabels} from '@/features/product/integration/ScopedCollectionLabels'
import {useEffect,useRef,useState} from 'react'
import {PageHeader} from '@/components/PageHeader'
import {control,primary,Tabs,Drawer,Status,PreviewNotice} from '@/features/product/ui'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import {NamedOperator,exactMinor} from '@/features/customers/CustomerDomainPages'
import {OperatorSelect} from '@/features/product/integration/OperatorSelect'
import {productDate} from '@/features/product/presentation'
import type {OperatorRowV1,PlanRowV1,PlanVersionRowV1} from '@/lib/contracts/telecom-collections-v1'
import type {CatalogInputMapV1,CatalogOperationV1,CatalogReceiptV1,CatalogServiceKindV1,CatalogTermsV1} from '@/lib/contracts/catalog-v1'
type Page={items:readonly (OperatorRowV1|PlanRowV1|PlanVersionRowV1)[];next_id:string|null}
const serviceKinds:Record<CatalogServiceKindV1,string>={mobile:'Móvil',fiber:'Fibra',fixed_voice:'Voz fija',data_connectivity:'Conectividad',other:'Otro servicio'}
const sourceNames={manual:'Manual',import:'Importado',integration:'Integración'}
export function IntegratedCatalog({initialOperatorId}:{initialOperatorId?:string}){
 const {repository,role}=useProduct(),[area,setArea]=useState('Operadores'),[operator,setOperator]=useState(''),[kind,setKind]=useState(''),[status,setStatus]=useState(''),[plan,setPlan]=useState<PlanRowV1|null>(null),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),key=JSON.stringify([area,operator,kind,status,plan?.id,cursors,revision]),[state,setState]=useState<{key:string;page?:Page;error?:string}|null>(null),current=state?.key===key?state:null,page=current?.page,[selectedOperator,setSelectedOperator]=useState<string|null>(initialOperatorId??null),[creating,setCreating]=useState(false),[planParent,setPlanParent]=useState<OperatorRowV1|null>(null),[terms,setTerms]=useState<string|null>(null)
 const canManage=role==='owner'||role==='admin'
 useEffect(()=>{let active=true;const common={limit:20,sort:'id_asc' as const,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})};const read=area==='Operadores'?repository.collection('operator.list',{...common,...(status?{status:status as 'active'|'inactive'}:{})}):area==='Tarifas'?repository.collection('plan.list',{...common,...(operator?{operator_id:operator}:{}),...(kind?{service_kind:kind as CatalogServiceKindV1}:{}),...(status?{status:status as 'active'|'retired'}:{})}):repository.collection('plan_version.list',{...common,...(plan?{plan_id:plan.id}:{}),...(operator?{operator_id:operator}:{}),...(kind?{service_kind:kind as CatalogServiceKindV1}:{})});void read.then(p=>{if(active)setState({key,page:p})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,area,operator,kind,status,plan,cursors,key])
 function tab(value:string){setArea(value);setStatus('');setCursors([])}
 function filter(setter:(v:string)=>void,value:string){setter(value);setCursors([])}
 return <div className="space-y-4"><PageHeader title="Catálogo Telecom" description="Operadores, tarifas y versiones comerciales publicadas" action={canManage&&area==='Operadores'?<button className={primary} onClick={()=>setCreating(true)}>Nuevo operador</button>:undefined}/><PreviewNotice/><Tabs prefix="catalog-" items={['Operadores','Tarifas','Versiones']} value={area} onChange={tab}/><section role="tabpanel" tabIndex={0} id={`catalog-panel-${area}`} aria-labelledby={`catalog-tab-${area}`} className="space-y-4">
 <div className="flex flex-wrap items-start gap-3 rounded-xl border bg-white p-4">{area!=='Operadores'&&<OperatorSelect value={operator} onChange={v=>filter(setOperator,v)} label="Operador del catálogo"/>}{area!=='Operadores'&&<select aria-label="Servicio del catálogo" className={control} value={kind} onChange={e=>filter(setKind,e.target.value)}><option value="">Todos los servicios</option>{Object.entries(serviceKinds).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select>}{area!=='Versiones'&&<select aria-label="Estado del catálogo" className={control} value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">Todos los estados</option>{(area==='Operadores'?['active','inactive']:['active','retired']).map(s=><option key={s} value={s}>{s==='active'?'Activo':s==='inactive'?'Inactivo':'Retirado'}</option>)}</select>}<button className={control} onClick={()=>setRevision(v=>v+1)}>Actualizar catálogo</button>{(operator||kind||status||plan)&&<button className={control} onClick={()=>{setOperator('');setKind('');setStatus('');setPlan(null);setCursors([])}}>Limpiar filtros del catálogo</button>}</div>
 {area==='Versiones'&&<p className="text-sm text-slate-500">{plan?'Versiones de '+plan.display_name+'. ':'Versiones publicadas de las tarifas. '}Cada contrato conserva su versión vendida.</p>}
 {current?.error?<div className="rounded-lg bg-red-50 p-4"><p role="alert" className="text-sm text-red-700">{current.error}</p><button className={control+' mt-3'} onClick={()=>setRevision(v=>v+1)}>Reintentar catálogo</button></div>:!page?<p role="status" className="text-sm text-slate-500">Consultando catálogo autorizado…</p>:!page.items.length?<p className="rounded-xl border bg-white p-5 text-sm text-slate-500">No hay registros de catálogo con estos filtros.</p>:<ScopedCollectionLabels rows={page.items}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{page.items.map(row=><article key={row.id} data-catalog-id={row.id} className="min-w-0 space-y-3 rounded-xl border bg-white p-4">{'display_name'in row?<><h2 className="break-words font-semibold">{row.display_name}</h2><p className="text-xs text-slate-500">Código: {row.code}</p><Status value={row.status}/>{'source'in row?<><p className="text-xs text-slate-500">Origen: {sourceNames[row.source]}</p><button className={control} onClick={()=>setSelectedOperator(row.id)}>Ver operador</button></>:<><p className="text-sm text-slate-500"><NamedOperator id={row.operator_id}/> · {serviceKinds[row.service_kind]}</p><button className={control} onClick={()=>{setPlan(row);tab('Versiones')}}>Ver versiones de tarifa</button></>}</>:<><h2 className="font-semibold">Versión {row.version_number}</h2><p className="text-sm"><NamedOperator id={row.operator_id}/> · {serviceKinds[row.service_kind]}</p><p className="break-words text-lg font-semibold text-indigo-700">{row.recurring_amount_minor===null?'Precio no registrado':exactMinor(row.recurring_amount_minor,row.currency)}</p><p className="text-xs text-slate-500">{productDate(row.valid_from)} — {row.valid_until?productDate(row.valid_until):'Sin fin registrado'}</p><button className={control} onClick={()=>setTerms(row.id)}>Ver condiciones de versión</button></>}</article>)}</div></ScopedCollectionLabels>}
 <footer className="flex flex-wrap justify-between gap-2"><button className={control} disabled={!page||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Página anterior del catálogo</button><span className="self-center text-xs text-slate-500">Página {cursors.length+1}{page?' · '+page.items.length+' registros':''}</span><button className={control} disabled={!page?.next_id} onClick={()=>{if(page?.next_id)setCursors(v=>[...v,page.next_id!])}}>Siguiente página del catálogo</button></footer>
 </section>{selectedOperator&&<OperatorDetail id={selectedOperator} onClose={()=>setSelectedOperator(null)} onChanged={()=>setRevision(v=>v+1)} onPlan={r=>{setSelectedOperator(null);setPlanParent(r)}}/>}{creating&&<CatalogCreate onClose={()=>setCreating(false)} onCreated={id=>{setCreating(false);setSelectedOperator(id);setRevision(v=>v+1)}}/>}{planParent&&<CatalogCreate parent={planParent} onClose={()=>setPlanParent(null)} onCreated={()=>{setPlanParent(null);setArea('Tarifas');setOperator(planParent.id);setCursors([]);setStatus('');setRevision(v=>v+1)}}/>}{terms&&<VersionTerms id={terms} onClose={()=>setTerms(null)}/>}</div>
}
function OperatorDetail({id,onClose,onChanged,onPlan}:{id:string;onClose:()=>void;onChanged:()=>void;onPlan:(r:OperatorRowV1)=>void}){
 const {repository,role}=useProduct(),[record,setRecord]=useState<OperatorRowV1|null>(null),[name,setName]=useState(''),[error,setError]=useState<unknown>(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[review,setReview]=useState<'operator.update'|'operator.activate'|'operator.deactivate'|null>(null),[receipt,setReceipt]=useState<CatalogReceiptV1|null>(null),pending=useRef<{op:CatalogOperationV1;input:CatalogInputMapV1[CatalogOperationV1]}|null>(null),inFlight=useRef(false),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict',denied=error instanceof ProductUiError&&error.code==='access_denied'
 useEffect(()=>{let active=true;void repository.collection('operator.get',{id}).then(r=>{if(active){setRecord(r.record);setName(r.record.display_name);setError(null)}}).catch(e=>{if(active){setRecord(null);setError(e)}});return()=>{active=false}},[repository,id,revision])
 const canManage=record&&record.source==='manual'&&(role==='owner'||role==='admin')&&!denied
 async function execute(){if(inFlight.current||!record||!review||conflict||denied||receipt)return;inFlight.current=true;setBusy(true);setError(null);try{pending.current??={op:review,input:Object.freeze({command_id:crypto.randomUUID(),id,expected_version:record.version,...(review==='operator.update'?{display_name:name.trim()}:{})})};const r=await repository.telecom(pending.current.op,pending.current.input) as CatalogReceiptV1;pending.current=null;setReceipt(r);setReview(null);setRecord(null);setRevision(v=>v+1);onChanged()}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{inFlight.current=false;setBusy(false)}}
 return <Drawer title={record?record.display_name:'Operador'} onClose={()=>{if(!busy&&!uncertain)onClose()}}><div className="space-y-4">{receipt&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Cambio de operador registrado.</p>}{error!==null&&<div><p role="alert" className="text-sm text-red-700">{safeMessage(error)}</p><button className={control+' mt-3'} disabled={busy} onClick={()=>{if(uncertain)void execute();else{setReceipt(null);setRecord(null);setReview(null);setRevision(v=>v+1)}}}>{uncertain?'Comprobar la misma operación':'Volver a consultar operador'}</button></div>}{!record&&error===null&&<p role="status" className="text-sm text-slate-500">Consultando operador…</p>}{record&&<><Status value={record.status}/><p className="text-sm text-slate-500">Código: {record.code} · Origen: {sourceNames[record.source]}</p>{canManage&&!receipt?<><form onSubmit={e=>{e.preventDefault();setReview('operator.update')}} className="space-y-3"><label className="block text-sm">Nombre del operador<input aria-label="Nombre del operador" className={control+' mt-1 w-full'} required maxLength={160} value={name} disabled={busy||uncertain||conflict||review!==null} onChange={e=>setName(e.target.value)}/></label><button className={primary} disabled={busy||uncertain||conflict||review!==null}>Revisar nombre</button></form><div className="flex flex-wrap gap-2"><button className={control} disabled={busy||uncertain||conflict||review!==null} onClick={()=>setReview(record.status==='active'?'operator.deactivate':'operator.activate')}>{record.status==='active'?'Desactivar operador':'Activar operador'}</button>{record.status==='active'&&<button className={control} disabled={busy||uncertain||conflict||review!==null} onClick={()=>onPlan(record)}>Nueva tarifa del operador</button>}</div></>:!receipt&&<p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">{record.source==='manual'?'Consulta de solo lectura para tu rol.':'Los hechos importados o integrados se conservan en modo consulta.'}</p>}{review&&<div className="space-y-3 rounded-lg bg-amber-50 p-3"><p className="text-sm">{review==='operator.update'?'Guardar el nombre «'+name.trim()+'».':review==='operator.deactivate'?'Desactivar el operador para nuevas altas. Las tarifas y contratos anteriores se conservan.':'Reactivar el operador para nuevas altas.'}</p><div className="flex gap-2"><button className={primary} disabled={busy||conflict||denied} onClick={()=>void execute()}>{busy?'Guardando…':'Confirmar cambio de operador'}</button><button className={control} disabled={busy||uncertain} onClick={()=>setReview(null)}>Volver</button></div></div>}</>}</div></Drawer>
}
function CatalogCreate({parent,onClose,onCreated}:{parent?:OperatorRowV1;onClose:()=>void;onCreated:(id:string)=>void}){
 const {repository}=useProduct(),[name,setName]=useState(''),[code,setCode]=useState(''),[kind,setKind]=useState<CatalogServiceKindV1>('mobile'),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null),pending=useRef<{op:'operator.create'|'plan.create';input:CatalogInputMapV1['operator.create'|'plan.create']}|null>(null),inFlight=useRef(false),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',denied=error instanceof ProductUiError&&error.code==='access_denied'
 async function execute(){if(inFlight.current||denied)return;inFlight.current=true;setBusy(true);setError(null);try{pending.current??={op:parent?'plan.create':'operator.create',input:Object.freeze({command_id:crypto.randomUUID(),code:code.trim(),display_name:name.trim(),...(parent?{operator_id:parent.id,service_kind:kind}:{})})};const r=await repository.telecom(pending.current.op,pending.current.input);pending.current=null;onCreated(r.id)}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{inFlight.current=false;setBusy(false)}}
 return <Drawer title={parent?'Nueva tarifa de '+parent.display_name:'Nuevo operador'} onClose={()=>{if(!busy&&!uncertain)onClose()}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();setReview(true)}}>{error!==null&&<p role="alert" className="text-sm text-red-700">{safeMessage(error)}</p>}<fieldset disabled={busy||uncertain||review||denied} className="space-y-3"><label className="block text-sm">Nombre<input aria-label="Nombre de alta de catálogo" className={control+' mt-1 w-full'} required maxLength={parent?200:160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">Código<input aria-label="Código de alta de catálogo" className={control+' mt-1 w-full'} required pattern="[a-z0-9][a-z0-9_\-]{0,63}" maxLength={64} value={code} onChange={e=>setCode(e.target.value)}/><span className="mt-1 block text-xs text-slate-500">Letras minúsculas, números, guion o guion bajo. El código identifica el registro y se conserva.</span></label>{parent&&<label className="block text-sm">Tipo de servicio<select aria-label="Servicio de nueva tarifa" className={control+' mt-1 w-full'} value={kind} onChange={e=>setKind(e.target.value as CatalogServiceKindV1)}>{Object.entries(serviceKinds).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label>}</fieldset>{uncertain?<button type="button" className={primary} disabled={busy} onClick={()=>void execute()}>Comprobar la misma alta</button>:review?<div className="space-y-3 rounded-lg bg-indigo-50 p-3"><p className="text-sm">Alta manual de {parent?'tarifa':'operador'}: {name.trim()} · {code.trim()}{parent?' · '+serviceKinds[kind]:''}.</p>{parent&&<p className="text-xs text-slate-500">La tarifa se crea sin condiciones económicas publicadas; sus versiones deben registrarse por separado.</p>}<div className="flex flex-wrap gap-2"><button type="button" className={primary} disabled={busy||denied} onClick={()=>void execute()}>{busy?'Guardando…':'Confirmar alta de catálogo'}</button><button type="button" className={control} disabled={busy} onClick={()=>setReview(false)}>Volver a editar</button></div></div>:<button className={primary} disabled={denied}>Revisar alta de catálogo</button>}</form></Drawer>
}
const entitlementNames:Record<string,string>={data_mib:'Datos',unlimited_data:'Datos ilimitados',voice_minutes:'Minutos de voz',unlimited_voice:'Voz ilimitada',sms_count:'SMS',unlimited_sms:'SMS ilimitados',download_mbps:'Velocidad de bajada',upload_mbps:'Velocidad de subida',access_technology:'Tecnología de acceso',roaming_zone:'Zona de roaming',commitment_months:'Permanencia',promotion_months:'Promoción'}
const addonNames:Record<string,string>={extra_data:'Datos extra',international_calling:'Llamadas internacionales',roaming:'Roaming',static_ip:'IP estática',device_financing:'Financiación de equipo'}
function VersionTerms({id,onClose}:{id:string;onClose:()=>void}){const {repository}=useProduct(),[state,setState]=useState<{value?:CatalogTermsV1;error?:string}|null>(null),[revision,setRevision]=useState(0);useEffect(()=>{let active=true;void repository.telecom('plan_version.terms_get',{id}).then(r=>{if(active)setState({value:r.record})}).catch(e=>{if(active)setState({error:safeMessage(e)})});return()=>{active=false}},[repository,id,revision]);const r=state?.value;return <Drawer title={r?'Condiciones · versión '+r.version_number:'Condiciones de versión'} onClose={onClose}>{state?.error?<div><p role="alert" className="text-sm text-red-700">{state.error}</p><button className={control+' mt-3'} onClick={()=>{setState(null);setRevision(v=>v+1)}}>Reintentar condiciones</button></div>:!r?<p role="status" className="text-sm text-slate-500">Consultando condiciones publicadas…</p>:<div className="space-y-4"><p className="text-sm">Vigencia: {productDate(r.valid_from)} — {r.valid_until?productDate(r.valid_until):'Sin fin registrado'}</p>{r.terms_status==='unrecorded'?<p className="rounded-lg bg-amber-50 p-3 text-sm">Las condiciones comerciales no están registradas en esta versión histórica.</p>:<><dl className="grid grid-cols-2 gap-3"><div><dt className="text-xs text-slate-500">Cuota mensual</dt><dd className="mt-1 font-semibold">{exactMinor(r.recurring_amount_minor,r.currency)}</dd></div><div><dt className="text-xs text-slate-500">Alta o instalación</dt><dd className="mt-1 font-semibold">{exactMinor(r.one_time_amount_minor,r.currency)}</dd></div></dl><section className="space-y-3"><h3 className="font-semibold">{r.is_bundle?'Paquete convergente registrado':'Componentes registrados'}</h3>{r.components.map(c=><div key={c.position} className="rounded-lg border p-3 text-sm">{serviceKinds[c.service_kind]} × {c.quantity}{c.addon_code?' · '+addonNames[c.addon_code]:''}<dl className="mt-2 space-y-2">{r.entitlements.filter(e=>e.component_position===c.position).map(e=><div key={e.code} className="flex justify-between gap-3 text-xs"><dt className="text-slate-500">{entitlementNames[e.code]}</dt><dd>{e.integer_value!==null?BigInt(e.integer_value).toLocaleString('es-ES')+(e.unit?' '+e.unit:''):e.boolean_value!==null?e.boolean_value?'Sí':'No':e.text_value}</dd></div>)}</dl></div>)}<dl className="space-y-2">{r.entitlements.filter(e=>e.component_position===null).map(e=><div key={e.code} className="flex justify-between gap-3 text-sm"><dt className="text-slate-500">{entitlementNames[e.code]}</dt><dd>{e.integer_value!==null?BigInt(e.integer_value).toLocaleString('es-ES')+(e.unit?' '+e.unit:''):e.boolean_value!==null?e.boolean_value?'Sí':'No':e.text_value}</dd></div>)}</dl></section></>}<p className="text-xs text-slate-500">Esta lectura corresponde a la versión seleccionada. Las condiciones vendidas no se sustituyen por una versión posterior.</p></div>}</Drawer>}
