begin;
insert into auth.users(id,email)values('a8100000-0000-4000-8000-000000000001','port-owner@example.invalid'),('a8100000-0000-4000-8000-000000000002','port-viewer@example.invalid');
insert into public.workspaces(id,name,slug)values('b8100000-0000-4000-8000-000000000001','Portability Synthetic','portability-synthetic');
insert into public.workspace_members(workspace_id,user_id,role)values('b8100000-0000-4000-8000-000000000001','a8100000-0000-4000-8000-000000000001','owner'),('b8100000-0000-4000-8000-000000000001','a8100000-0000-4000-8000-000000000002','viewer');
create function pg_temp.assert_port(ok boolean)returns void language plpgsql as $$begin if ok is not true then raise exception 'portability_assertion';end if;end$$;
create function pg_temp.deny_port(q text,c text)returns void language plpgsql as $$begin begin execute q;exception when others then if sqlstate=c then return;end if;raise;end;raise exception 'portability_expected_denial';end$$;
create temporary table saved_port(op text,i jsonb,r jsonb);grant all on saved_port to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','a8100000-0000-4000-8000-000000000001',true);
do $$declare w uuid:='b8100000-0000-4000-8000-000000000001';o jsonb;donor jsonb;cust jsonb;con jsonb;s jsonb;l jsonb;n jsonb;p jsonb;i jsonb;r jsonb;begin
 o:=public.catalog_v1_command(w,'operator.create',jsonb_build_object('command_id',gen_random_uuid(),'code','port_target','display_name','Synthetic Port Target'));
 donor:=public.catalog_v1_command(w,'operator.create',jsonb_build_object('command_id',gen_random_uuid(),'code','port_donor','display_name','Synthetic Port Donor'));
 cust:=public.product_v1_customer_create(w,jsonb_build_object('command_id',gen_random_uuid(),'account_kind','legal_entity','legal_name','Synthetic Port Account'));
 con:=public.portfolio_v1_contract_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'customer_id',cust->>'id','operator_id',o->>'id','start_date','2026-01-01'));
 perform public.portfolio_v1_contract_activate(w,jsonb_build_object('command_id',gen_random_uuid(),'id',con->>'id','expected_version',1,'signed_date','2026-01-01'));
 s:=public.portfolio_v1_service_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'contract_id',con->>'id','service_kind','mobile','display_name','Synthetic Port Service'));
 perform public.portfolio_v1_service_transition(w,jsonb_build_object('command_id',gen_random_uuid(),'id',s->>'id','expected_version',1,'status','active','effective_on','2026-01-01'));
 l:=public.portfolio_v1_line_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'service_id',s->>'id','display_name','Synthetic Port Line'));
 n:=public.identifier_v1_command(w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','line','entity_id',l->>'id','identifier_kind','msisdn','canonical_value','+12025550180'));
 i:=jsonb_build_object('command_id',gen_random_uuid(),'line_id',l->>'id','number_identifier_id',n->>'id','direction','inbound','donor_operator_id',donor->>'id','target_operator_id',o->>'id','requested_on','2026-02-01','owner_user_id',null);
 p:=public.portability_v1_command(w,'portability.create',i);insert into saved_port values('portability.create',i,p);perform pg_temp.assert_port(p=public.portability_v1_command(w,'portability.create',i));
 perform pg_temp.deny_port(format('select public.portability_v1_command(%L,%L,%L)',w,'portability.create',(i||jsonb_build_object('command_id',gen_random_uuid()))::text),'40001');
 perform pg_temp.assert_port(public.portability_v1_query(w,'portability.get',jsonb_build_object('id',p->>'id'))->'record'->>'masked_display'='••••180');
 perform pg_temp.assert_port(jsonb_array_length(public.portability_v1_query(w,'portability.list',jsonb_build_object('customer_id',cust->>'id','limit',1))->'items')=1);
 perform pg_temp.deny_port(format('select public.portability_v1_command(%L,%L,%L)',w,'portability.complete',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',1,'completed_on','2026-02-02','evidence_source','manual','provider_outcome','confirmed_completed','line_action','none','expected_line_version',null)::text),'22023');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',1,'donor_operator_id',donor->>'id','target_operator_id',o->>'id','requested_on','2026-02-02');p:=public.portability_v1_command(w,'portability.update_draft',i);insert into saved_port values('portability.update_draft',i,p);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',2,'owner_user_id','a8100000-0000-4000-8000-000000000001');p:=public.portability_v1_command(w,'portability.assign',i);insert into saved_port values('portability.assign',i,p);
 for r in select jsonb_build_object('status',x,'effective_on','2026-02-03')from unnest(array['requested','scheduled','in_progress'])x loop
  i:=jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',p->'version','status',r->>'status','effective_on',r->>'effective_on','reason_code',null,'evidence_source','manual');p:=public.portability_v1_command(w,'portability.transition',i);insert into saved_port values('portability.transition',i,p);
 end loop;
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',p->'version','completed_on','2026-02-04','evidence_source','manual','provider_outcome','confirmed_completed','line_action','activate','expected_line_version',2);
 perform pg_temp.deny_port(format('select public.portability_v1_command(%L,%L,%L)',w,'portability.complete',i::text),'40001');
 perform pg_temp.assert_port(public.portability_v1_query(w,'portability.get',jsonb_build_object('id',p->>'id'))->'record'->>'status'='in_progress');
 i:=i||jsonb_build_object('expected_line_version',1);p:=public.portability_v1_command(w,'portability.complete',i);insert into saved_port values('portability.complete',i,p);perform pg_temp.assert_port(p->'line_effect'->>'status'='active'and p->'line_effect'->>'version'='2');
 for r in select jsonb_build_object('op',saved.op,'i',saved.i,'r',saved.r)from saved_port saved loop perform pg_temp.assert_port(public.portability_v1_command(w,r->>'op',r->'i')=r->'r');end loop;
 -- Outbound cancellation and rejection preserve completed prior workflow and number identity.
 i:=jsonb_build_object('command_id',gen_random_uuid(),'line_id',l->>'id','number_identifier_id',n->>'id','direction','outbound','donor_operator_id',o->>'id','target_operator_id',donor->>'id','requested_on','2026-03-01','owner_user_id',null);p:=public.portability_v1_command(w,'portability.create',i);
 p:=public.portability_v1_command(w,'portability.transition',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',1,'status','cancelled','effective_on','2026-03-01','reason_code','customer_withdrew','evidence_source','manual'));
 p:=public.portability_v1_command(w,'portability.create',i||jsonb_build_object('command_id',gen_random_uuid()));
 p:=public.portability_v1_command(w,'portability.transition',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',1,'status','requested','effective_on','2026-03-01','reason_code',null,'evidence_source','manual'));
 p:=public.portability_v1_command(w,'portability.transition',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',2,'status','rejected','effective_on','2026-03-02','reason_code','subscriber_mismatch','evidence_source','manual'));
 perform pg_temp.assert_port(jsonb_array_length(public.portability_v1_query(w,'portability.list',jsonb_build_object('line_id',l->>'id'))->'items')=3);
 perform pg_temp.deny_port('select *from public.telecom_portabilities','42501');
end$$;
reset role;
select pg_temp.assert_port(not exists(select 1 from public.product_commands where operation like 'portability.%'and receipt::text like '%12025550180%'));
select pg_temp.assert_port(not exists(select 1 from public.product_audit_events where row_to_json(product_audit_events)::text like '%12025550180%'));
select pg_temp.deny_port('delete from public.telecom_portabilities','55000');
set local role authenticated;
select set_config('request.jwt.claim.sub','a8100000-0000-4000-8000-000000000002',true);
select pg_temp.assert_port(jsonb_array_length(public.portability_v1_query('b8100000-0000-4000-8000-000000000001','portability.list','{}')->'items')=3);
select pg_temp.deny_port($q$select public.portability_v1_command('b8100000-0000-4000-8000-000000000001','portability.assign',(select i from saved_port where op='portability.assign'))$q$,'42501');
reset role;
update public.workspace_members set status='suspended'where user_id='a8100000-0000-4000-8000-000000000001';
set local role authenticated;
select set_config('request.jwt.claim.sub','a8100000-0000-4000-8000-000000000001',true);
select pg_temp.deny_port($q$select public.portability_v1_query('b8100000-0000-4000-8000-000000000001','portability.list','{}')$q$,'42501');
select pg_temp.deny_port($q$select public.portability_v1_command('b8100000-0000-4000-8000-000000000001','portability.create',(select i from saved_port where op='portability.create'))$q$,'42501');
reset role;
rollback;
