-- After synthetic_product.sql without final COMMIT; no real identities.
create function pg_temp.assert_sim(ok boolean)returns void language plpgsql as $$begin if ok is not true then raise exception 'sim_assertion';end if;end$$;
create function pg_temp.deny_sim(q text,c text)returns void language plpgsql as $$begin begin execute q;exception when others then if sqlstate=c then return;end if;raise;end;raise exception 'sim_expected_denial';end$$;
create temporary table saved_sim(op text,i jsonb,r jsonb);grant all on saved_sim to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
do $$declare w uuid:=md5('density.workspace.1')::uuid;customer uuid:=md5('density.customer.1.1')::uuid;operator uuid:=md5('density.operator.1.2')::uuid;line uuid:=md5('density.line.1.1.1.1')::uuid;oldsim jsonb;newsim jsonb;unused jsonb;i jsonb;r jsonb;iccid jsonb;eid jsonb;begin
 i:=jsonb_build_object('command_id',gen_random_uuid(),'customer_id',customer,'operator_id',operator,'kind','physical','display_label','Synthetic Physical SIM');oldsim:=public.sim_v1_command(w,'sim.create',i);insert into saved_sim values('sim.create',i,oldsim);perform pg_temp.assert_sim(oldsim=public.sim_v1_command(w,'sim.create',i));
 perform pg_temp.deny_sim(format('select public.sim_v1_command(%L,%L,%L)',w,'sim.assign',jsonb_build_object('command_id',gen_random_uuid(),'id',oldsim->>'id','expected_version',1,'line_id',line,'expected_line_version',1)::text),'22023');
 iccid:=public.identifier_v1_command(w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',oldsim->>'id','identifier_kind','iccid','canonical_value','89'||repeat('0',14)||'180'));
 perform pg_temp.assert_sim(public.identifier_v1_query(w,'identifier.get',jsonb_build_object('id',iccid->>'id'))->'record'->>'entity_kind'='sim');
 perform pg_temp.assert_sim(public.sensitive_v1_get(w,jsonb_build_object('entity_kind','telecom_identifier','entity_id',iccid->>'id','fields',jsonb_build_array('canonical_value')))->'values'->>'canonical_value'='89'||repeat('0',14)||'180');
 perform pg_temp.deny_sim(format('select public.identifier_v1_command(%L,%L,%L)',w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',oldsim->>'id','identifier_kind','eid','canonical_value','89'||repeat('0',27)||'180')::text),'P0002');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',oldsim->>'id','expected_version',1,'line_id',line,'expected_line_version',1);oldsim:=public.sim_v1_command(w,'sim.assign',i);insert into saved_sim values('sim.assign',i,oldsim);
 perform pg_temp.deny_sim(format('select public.identifier_v1_command(%L,%L,%L)',w,'identifier.retire',jsonb_build_object('command_id',gen_random_uuid(),'id',iccid->>'id','expected_version',1)::text),'42501');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',oldsim->>'id','expected_version',2,'expected_line_version',1,'evidence_source','manual','provider_confirmation','confirmed_active');oldsim:=public.sim_v1_command(w,'sim.activate',i);insert into saved_sim values('sim.activate',i,oldsim);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'customer_id',customer,'operator_id',operator,'kind','esim','display_label','Synthetic eSIM Replacement');newsim:=public.sim_v1_command(w,'sim.create',i);
 perform public.identifier_v1_command(w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',newsim->>'id','identifier_kind','iccid','canonical_value','89'||repeat('0',14)||'181'));
 eid:=public.identifier_v1_command(w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',newsim->>'id','identifier_kind','eid','canonical_value','89'||repeat('0',27)||'181'));
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',oldsim->>'id','expected_version',3,'replacement_sim_id',newsim->>'id','expected_replacement_version',1,'expected_line_version',2,'replacement_status','active','evidence_source','manual','provider_confirmation','confirmed_active');
 perform pg_temp.deny_sim(format('select public.sim_v1_command(%L,%L,%L)',w,'sim.replace',i::text),'40001');
 i:=i||jsonb_build_object('expected_line_version',1);r:=public.sim_v1_command(w,'sim.replace',i);insert into saved_sim values('sim.replace',i,r);perform pg_temp.assert_sim(r->>'status'='replaced'and r->>'replacement_status'='active'and r->>'replacement_version'='2');
 perform pg_temp.assert_sim(public.sim_v1_query(w,'sim.get',jsonb_build_object('id',newsim->>'id'))->'record'->>'masked_eid'='••••181');
 perform pg_temp.assert_sim(jsonb_array_length(public.sim_v1_query(w,'sim.history',jsonb_build_object('line_id',line))->'items')=2);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',newsim->>'id','expected_version',2,'expected_line_version',1,'evidence_source','manual');r:=public.sim_v1_command(w,'sim.deactivate',i);insert into saved_sim values('sim.deactivate',i,r);
 unused:=public.sim_v1_command(w,'sim.create',jsonb_build_object('command_id',gen_random_uuid(),'customer_id',customer,'operator_id',operator,'kind','esim','display_label','Synthetic Unused Profile'));
 -- One eUICC can hold multiple profiles: shared EID is a valid fact.
 perform public.identifier_v1_command(w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',unused->>'id','identifier_kind','eid','canonical_value','89'||repeat('0',27)||'181'));
 perform pg_temp.deny_sim(format('select public.identifier_v1_command(%L,%L,%L)',w,'identifier.create_manual',jsonb_build_object('command_id',gen_random_uuid(),'entity_kind','sim','entity_id',unused->>'id','identifier_kind','iccid','canonical_value','89'||repeat('0',14)||'180')::text),'40001');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',unused->>'id','expected_version',1);r:=public.sim_v1_command(w,'sim.cancel',i);insert into saved_sim values('sim.cancel',i,r);
 perform pg_temp.assert_sim(jsonb_array_length(public.sim_v1_query(w,'sim.list',jsonb_build_object('customer_id',customer))->'items')=3);
 for r in select jsonb_build_object('op',t.op,'i',t.i,'r',t.r)from saved_sim t loop perform pg_temp.assert_sim(public.sim_v1_command(w,r->>'op',r->'i')=r->'r');end loop;
 perform pg_temp.deny_sim('select *from public.telecom_sims','42501');perform pg_temp.deny_sim('select *from public.telecom_sim_associations','42501');
end$$;
reset role;
select pg_temp.assert_sim(not exists(select 1 from public.product_commands where operation like 'sim.%'and receipt::text like '%8900000000000000180%'));
select pg_temp.assert_sim(not exists(select 1 from public.product_audit_events where row_to_json(product_audit_events)::text like '%8900000000000000180%'));
select pg_temp.deny_sim('update public.telecom_sim_associations set line_id=gen_random_uuid()','55000');
select pg_temp.deny_sim('delete from public.telecom_sim_associations','55000');select pg_temp.deny_sim('delete from public.telecom_sims','55000');
update public.workspace_members set role='viewer'where user_id=md5('density.actor.1.3')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.3')::uuid::text,true);
select pg_temp.assert_sim(jsonb_array_length(public.sim_v1_query(md5('density.workspace.1')::uuid,'sim.list','{}')->'items')=3);
select pg_temp.deny_sim(format('select public.sim_v1_command(%L,%L,%L)',md5('density.workspace.1')::uuid,'sim.create',(select i::text from saved_sim where op='sim.create')),'42501');
reset role;
update public.workspace_members set status='suspended'where user_id=md5('density.actor.1.1')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
select pg_temp.deny_sim(format('select public.sim_v1_command(%L,%L,%L)',md5('density.workspace.1')::uuid,'sim.create',(select i::text from saved_sim where op='sim.create')),'42501');
select pg_temp.deny_sim(format('select public.sim_v1_query(%L,%L,%L)',md5('density.workspace.1')::uuid,'sim.list','{}'),'42501');
reset role;
rollback;
