begin;
insert into auth.users(id,email)values('91000000-0000-4000-8000-000000000001','catalog-owner@example.invalid'),('91000000-0000-4000-8000-000000000002','catalog-member@example.invalid');
insert into public.workspaces(id,name,slug)values('92000000-0000-4000-8000-000000000001','Catalog Synthetic','catalog-synthetic'),('92000000-0000-4000-8000-000000000002','Catalog Foreign','catalog-foreign');
insert into public.workspace_members(workspace_id,user_id,role)values('92000000-0000-4000-8000-000000000001','91000000-0000-4000-8000-000000000001','owner'),('92000000-0000-4000-8000-000000000001','91000000-0000-4000-8000-000000000002','member');
create function pg_temp.assert_cat(ok boolean)returns void language plpgsql as $$begin if ok is not true then raise exception 'catalog_assertion';end if;end$$;
create function pg_temp.deny_cat(q text,c text)returns void language plpgsql as $$begin begin execute q;exception when others then if sqlstate=c then return;end if;raise;end;raise exception 'catalog_expected_denial';end$$;
set local role authenticated;
select set_config('request.jwt.claim.sub','91000000-0000-4000-8000-000000000001',true);
do $$declare w uuid:='92000000-0000-4000-8000-000000000001';o jsonb;p jsonb;v jsonb;i jsonb;t jsonb;customer jsonb;contract jsonb;begin
 o:=public.catalog_v1_command(w,'operator.create',jsonb_build_object('command_id',gen_random_uuid(),'code','synthetic_catalog','display_name','Synthetic Catalog Operator'));perform pg_temp.assert_cat(o->>'version'='1');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',o->>'id','expected_version',1,'display_name','Synthetic Catalog Updated');o:=public.catalog_v1_command(w,'operator.update',i);perform pg_temp.assert_cat(o->>'version'='2'and o=public.catalog_v1_command(w,'operator.update',i));
 o:=public.catalog_v1_command(w,'operator.deactivate',jsonb_build_object('command_id',gen_random_uuid(),'id',o->>'id','expected_version',2));perform pg_temp.assert_cat(o->>'status'='inactive');
 o:=public.catalog_v1_command(w,'operator.activate',jsonb_build_object('command_id',gen_random_uuid(),'id',o->>'id','expected_version',3));perform pg_temp.assert_cat(o->>'version'='4'and o->>'status'='active');
 p:=public.catalog_v1_command(w,'plan.create',jsonb_build_object('command_id',gen_random_uuid(),'operator_id',o->>'id','code','synthetic_bundle','display_name','Synthetic Convergent','service_kind','mobile'));
 p:=public.catalog_v1_command(w,'plan.update_metadata',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',1,'display_name','Synthetic Convergent Updated'));perform pg_temp.assert_cat(p->>'version'='2');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'plan_id',p->>'id','expected_version',2,'valid_from','2026-01-01','valid_until','2026-12-31','currency','EUR','recurring_amount_minor','9007199254740993','one_time_amount_minor','9900','is_bundle',true,'components','[{"component_kind":"base","service_kind":"mobile","addon_code":null,"quantity":1},{"component_kind":"base","service_kind":"fiber","addon_code":null,"quantity":1},{"component_kind":"add_on","service_kind":"data_connectivity","addon_code":"static_ip","quantity":1}]'::jsonb,'entitlements','[{"code":"data_mib","component_position":1,"integer_value":"51200","boolean_value":null,"text_value":null},{"code":"unlimited_voice","component_position":1,"integer_value":null,"boolean_value":true,"text_value":null},{"code":"download_mbps","component_position":2,"integer_value":"600","boolean_value":null,"text_value":null},{"code":"access_technology","component_position":2,"integer_value":null,"boolean_value":null,"text_value":"fiber_ftth"},{"code":"promotion_months","component_position":null,"integer_value":"6","boolean_value":null,"text_value":null}]'::jsonb);
 v:=public.catalog_v1_command(w,'plan_version.create',i);perform pg_temp.assert_cat(v->>'parent_version'='3'and v->>'version_number'='1'and v=public.catalog_v1_command(w,'plan_version.create',i));
 t:=public.catalog_v1_terms_get(w,jsonb_build_object('id',v->>'id'));perform pg_temp.assert_cat(t->'record'->>'recurring_amount_minor'='9007199254740993'and t->'record'->>'terms_status'='published'and jsonb_array_length(t->'record'->'components')=3 and jsonb_array_length(t->'record'->'entitlements')=5);
 perform pg_temp.assert_cat(public.catalog_v1_terms_get(w,jsonb_build_object('id',gen_random_uuid()))is null);
 customer:=public.product_v1_customer_create(w,jsonb_build_object('command_id',gen_random_uuid(),'account_kind','legal_entity','legal_name','Synthetic Convergent Account'));
 contract:=public.portfolio_v1_contract_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'customer_id',customer->>'id','operator_id',o->>'id','plan_version_id',v->>'id','start_date','2026-01-01'));
 perform public.portfolio_v1_service_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'contract_id',contract->>'id','plan_version_id',v->>'id','service_kind','mobile','display_name','Synthetic Convergent Mobile'));
 perform public.portfolio_v1_service_create_manual(w,jsonb_build_object('command_id',gen_random_uuid(),'contract_id',contract->>'id','plan_version_id',v->>'id','service_kind','fiber','display_name','Synthetic Convergent Fiber'));
 perform pg_temp.assert_cat(jsonb_array_length(public.telecom_collection_v1_query(w,'plan_version.list',jsonb_build_object('plan_id',p->>'id','service_kind','fiber','valid_on','2026-11-05'))->'items')=1);
 perform pg_temp.deny_cat(format('select public.portfolio_v1_service_create_manual(%L,%L)',w,jsonb_build_object('command_id',gen_random_uuid(),'contract_id',contract->>'id','plan_version_id',v->>'id','service_kind','data_connectivity','display_name','Synthetic Invalid Base')::text),'23514');

 perform pg_temp.deny_cat(format('select public.catalog_v1_command(%L,%L,%L)',w,'plan_version.create',(i||jsonb_build_object('command_id',gen_random_uuid(),'expected_version',3))::text),'40001');
 perform pg_temp.deny_cat(format('select public.catalog_v1_command(%L,%L,%L)',w,'plan_version.create',(i||jsonb_build_object('command_id',gen_random_uuid(),'expected_version',3,'entitlements','[{"code":"arbitrary","component_position":null,"integer_value":"1","boolean_value":null,"text_value":null}]'::jsonb))::text),'22023');
 p:=public.catalog_v1_command(w,'plan.change_status',jsonb_build_object('command_id',gen_random_uuid(),'id',p->>'id','expected_version',3,'status','retired'));perform pg_temp.assert_cat(p->>'version'='4'and p->>'status'='retired');
 perform pg_temp.assert_cat(public.telecom_collection_v1_query(w,'operator.get',jsonb_build_object('id',o->>'id'))->'record'->>'version'='4');
 perform pg_temp.assert_cat(public.telecom_collection_v1_query(w,'plan.get',jsonb_build_object('id',p->>'id'))->'record'->>'version'='4');
 perform pg_temp.deny_cat('select *from public.telecom_plan_version_entitlements','42501');
end$$;
reset role;
select pg_temp.deny_cat('update public.telecom_plan_version_entitlements set integer_value=100','55000');
select pg_temp.deny_cat('delete from public.telecom_plan_version_components','55000');
select pg_temp.deny_cat('update public.telecom_plan_versions set currency=''USD''','55000');
select pg_temp.deny_cat($q$insert into public.telecom_plan_version_entitlements(workspace_id,plan_version_id,code,value_kind,boolean_value)select workspace_id,id,'unlimited_sms','boolean',true from public.telecom_plan_versions where is_bundle is not null$q$,'55000');
set local role authenticated;
select set_config('request.jwt.claim.sub','91000000-0000-4000-8000-000000000002',true);
select pg_temp.deny_cat($q$select public.catalog_v1_command('92000000-0000-4000-8000-000000000001','operator.create','{"command_id":"93000000-0000-4000-8000-000000000001","code":"denied","display_name":"Denied"}')$q$,'42501');
reset role;
update public.workspace_members set status='suspended'where user_id='91000000-0000-4000-8000-000000000001';
set local role authenticated;
select set_config('request.jwt.claim.sub','91000000-0000-4000-8000-000000000001',true);
select pg_temp.deny_cat($q$select public.catalog_v1_command('92000000-0000-4000-8000-000000000001','operator.create','{"command_id":"93000000-0000-4000-8000-000000000001","code":"denied","display_name":"Denied"}')$q$,'42501');
reset role;
rollback;
