-- After synthetic_product.sql without final COMMIT; everything rolls back.
create function pg_temp.assert_case(ok boolean)returns void language plpgsql as $$begin if ok is not true then raise exception 'case_assertion';end if;end$$;
create function pg_temp.deny_case(q text,c text)returns void language plpgsql as $$begin begin execute q;exception when others then if sqlstate=c then return;end if;raise;end;raise exception 'case_expected_denial';end$$;
create temporary table saved_case(op text,i jsonb,r jsonb);grant all on saved_case to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
do $$declare w uuid:=md5('density.workspace.1')::uuid;i jsonb;c jsonb;n jsonb;rec jsonb;begin
 i:=jsonb_build_object('command_id',gen_random_uuid(),'customer_id',md5('density.customer.1.1')::uuid,'contract_id',md5('density.contract.1.1.1')::uuid,'service_id',md5('density.service.1.1.1')::uuid,'line_id',md5('density.line.1.1.1.1')::uuid,'case_type','technical','title','Synthetic Technical Case','priority','urgent','due_on','2000-01-01','assigned_user_id',null);
 c:=public.case_v1_command(w,'case.create',i);insert into saved_case values('case.create',i,c);
 perform pg_temp.assert_case(c=public.case_v1_command(w,'case.create',i));
 perform pg_temp.deny_case(format('select public.case_v1_command(%L,%L,%L)',w,'case.create',(i||jsonb_build_object('command_id',gen_random_uuid(),'customer_id',md5('density.customer.1.2')::uuid))::text),'P0002');
 perform pg_temp.assert_case(public.case_v1_query(w,'case.get',jsonb_build_object('id',c->>'id'))->'record'->>'overdue'='true');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',1,'case_type','technical','title','Synthetic Technical Followup','priority','high','due_on',null);c:=public.case_v1_command(w,'case.update',i);insert into saved_case values('case.update',i,c);
 perform pg_temp.deny_case(format('select public.case_v1_command(%L,%L,%L)',w,'case.update',(i||jsonb_build_object('command_id',gen_random_uuid()))::text),'40001');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',2,'assigned_user_id',md5('density.actor.1.2')::uuid);c:=public.case_v1_command(w,'case.assign',i);insert into saved_case values('case.assign',i,c);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',3,'body','Synthetic private note sentinel for audit exclusion');c:=public.case_v1_command(w,'case.note_create',i);insert into saved_case values('case.note_create',i,c);perform pg_temp.assert_case(c->>'note_seq'='1'and not c?'body');
 perform pg_temp.deny_case(format('select public.case_v1_command(%L,%L,%L)',w,'case.note_create',(i||jsonb_build_object('command_id',gen_random_uuid(),'expected_version',4,'body',chr(128)))::text),'22023');
 c:=public.case_v1_command(w,'case.note_create',i||jsonb_build_object('command_id',gen_random_uuid(),'expected_version',4,'body','Synthetic second private note'));
 n:=public.case_v1_query(w,'case.note_list',jsonb_build_object('id',c->>'id','limit',1));perform pg_temp.assert_case(n->>'next_seq'='1'and n->'items'->0->>'body'='Synthetic private note sentinel for audit exclusion');
 n:=public.case_v1_query(w,'case.note_list',jsonb_build_object('id',c->>'id','after_seq',1));perform pg_temp.assert_case(jsonb_array_length(n->'items')=1 and n->'items'->0->>'seq'='2');
 perform pg_temp.assert_case(public.case_v1_query(w,'case.get',jsonb_build_object('id',c->>'id'))->'record'->>'overdue'='false');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',5,'status','waiting_operator');c:=public.case_v1_command(w,'case.change_status',i);insert into saved_case values('case.change_status',i,c);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',6,'resolution_code','issue_fixed');c:=public.case_v1_command(w,'case.resolve',i);insert into saved_case values('case.resolve',i,c);
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',7);c:=public.case_v1_command(w,'case.reopen',i);insert into saved_case values('case.reopen',i,c);
 c:=public.case_v1_command(w,'case.resolve',jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',8,'resolution_code','customer_confirmed'));
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',9);c:=public.case_v1_command(w,'case.close',i);insert into saved_case values('case.close',i,c);
 perform pg_temp.deny_case(format('select public.case_v1_command(%L,%L,%L)',w,'case.reopen',(i||jsonb_build_object('command_id',gen_random_uuid(),'expected_version',10))::text),'22023');
 c:=public.case_v1_command(w,'case.create',(select s.i from saved_case s where s.op='case.create')||jsonb_build_object('command_id',gen_random_uuid(),'case_type','billing'));
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',c->>'id','expected_version',1,'cancellation_code','duplicate');c:=public.case_v1_command(w,'case.cancel',i);insert into saved_case values('case.cancel',i,c);
 for rec in select jsonb_build_object('op',s.op,'i',s.i,'r',s.r)from saved_case s loop perform pg_temp.assert_case(public.case_v1_command(w,rec->>'op',rec->'i')=rec->'r');end loop;
 perform pg_temp.assert_case(jsonb_array_length(public.case_v1_query(w,'case.list',jsonb_build_object('customer_id',md5('density.customer.1.1')::uuid,'case_type','billing','status','cancelled'))->'items')>=1);
 perform pg_temp.deny_case('select body from public.service_case_internal_notes','42501');
end$$;
reset role;
select pg_temp.assert_case(not exists(select 1 from public.product_commands where operation like 'case.%'and receipt::text like '%private note sentinel%'));
select pg_temp.assert_case(not exists(select 1 from public.product_audit_events where row_to_json(product_audit_events)::text like '%private note sentinel%'));
select pg_temp.deny_case('update public.service_case_internal_notes set body=''changed''','55000');
select pg_temp.deny_case('delete from public.service_case_internal_notes','55000');
select pg_temp.deny_case('delete from public.service_cases','55000');
update public.workspace_members set role='viewer'where user_id=md5('density.actor.1.3')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.3')::uuid::text,true);
select pg_temp.assert_case(jsonb_array_length(public.case_v1_query(md5('density.workspace.1')::uuid,'case.list','{}')->'items')>0);
select pg_temp.deny_case(format('select public.case_v1_query(%L,%L,%L)',md5('density.workspace.1')::uuid,'case.note_list',jsonb_build_object('id',(select r->>'id'from saved_case where op='case.create'))::text),'42501');
reset role;
update public.workspace_members set status='suspended'where user_id=md5('density.actor.1.1')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
select pg_temp.deny_case(format('select public.case_v1_command(%L,%L,%L)',md5('density.workspace.1')::uuid,'case.create',(select i::text from saved_case where op='case.create')),'42501');
select pg_temp.deny_case(format('select public.case_v1_query(%L,%L,%L)',md5('density.workspace.1')::uuid,'case.list','{}'),'42501');
reset role;
rollback;
