-- Prepend synthetic_product.sql without COMMIT; all test rows roll back.
create function pg_temp.assert_identity(ok boolean)returns void language plpgsql as $$begin if ok is not true then raise exception 'external_identity_assertion';end if;end$$;
create function pg_temp.deny_identity(q text,c text)returns void language plpgsql as $$begin begin execute q;exception when others then if sqlstate=c then return;end if;raise;end;raise exception 'external_identity_expected_denial';end$$;
create temporary table saved_identity(op text,inp jsonb,receipt jsonb);grant all on saved_identity to authenticated;
set local role authenticated;select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
do $$declare w uuid:=md5('density.workspace.1')::uuid;c jsonb;other jsonb;g jsonb;i jsonb;r jsonb;list jsonb;begin
 c:=public.product_v1_customer_create(w,jsonb_build_object('command_id',gen_random_uuid(),'account_kind','legal_entity','legal_name','Synthetic Identity Customer'));
 other:=public.product_v1_customer_create(w,jsonb_build_object('command_id',gen_random_uuid(),'account_kind','legal_entity','legal_name','Synthetic Other Identity Customer'));
 i:=jsonb_build_object('command_id',gen_random_uuid(),'integration_key','synthetic.telecom','provider_code','generic.telecom.v1','display_name','Synthetic Registry Must Not Audit','source','integration');
 g:=public.external_identity_v1_command(w,'external_identity.integration_register',i);insert into saved_identity values('external_identity.integration_register',i,g);
 perform pg_temp.assert_identity(g=public.external_identity_v1_command(w,'external_identity.integration_register',i)and g->>'external_effect'='disabled');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.integration_register',(i||jsonb_build_object('command_id',gen_random_uuid(),'url','https://provider.invalid'))::text),'22023');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'integration_id',g->>'id','external_kind','subscriber','external_id','SYNTHETIC-IDENTITY-PRIVATE-001','local_entity_kind','customer','local_entity_id',c->>'id');
 r:=public.external_identity_v1_command(w,'external_identity.bind',i);insert into saved_identity values('external_identity.bind',i,r);
 perform pg_temp.assert_identity(r=public.external_identity_v1_command(w,'external_identity.bind',i)and r->>'version'='1');
 perform pg_temp.assert_identity(r->>'id'=(public.external_identity_v1_command(w,'external_identity.bind',i||jsonb_build_object('command_id',gen_random_uuid())))->>'id');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.bind',(i||jsonb_build_object('command_id',gen_random_uuid(),'local_entity_id',other->>'id'))::text),'40001');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.bind',(i||jsonb_build_object('command_id',gen_random_uuid(),'local_entity_id',gen_random_uuid()))::text),'P0002');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',md5('density.workspace.2')::uuid,'external_identity.bind',i::text),'42501');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.bind',(i||jsonb_build_object('command_id',gen_random_uuid(),'external_id','https://invalid'))::text),'22023');
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.bind',(i||jsonb_build_object('command_id',gen_random_uuid(),'local_entity_kind','property'))::text),'22023');
 perform public.external_identity_v1_command(w,'external_identity.bind',i||jsonb_build_object('command_id',gen_random_uuid(),'external_id','SYNTHETIC-IDENTITY-PRIVATE-002'));
 list:=public.external_identity_v1_query(w,'external_identity.list',jsonb_build_object('local_entity_kind','customer','local_entity_id',c->>'id','limit',1));
 perform pg_temp.assert_identity(jsonb_array_length(list->'items')=1 and list->>'next_id'=list->'items'->0->>'id'and list->'items'->0->>'source'='integration');
 perform pg_temp.assert_identity(jsonb_array_length(public.external_identity_v1_query(w,'external_identity.list',jsonb_build_object('local_entity_kind','customer','local_entity_id',c->>'id','limit',1,'after_id',list->>'next_id'))->'items')=1);
 perform pg_temp.assert_identity((public.external_identity_v1_query(w,'external_identity.integration_list','{}')->'items'->0->>'external_effect')='disabled');
 i:=jsonb_build_object('command_id',gen_random_uuid(),'id',r->>'id','expected_version',1);r:=public.external_identity_v1_command(w,'external_identity.retire',i);insert into saved_identity values('external_identity.retire',i,r);
 perform pg_temp.assert_identity(r->>'version'='2'and r->>'status'='retired'and r=public.external_identity_v1_command(w,'external_identity.retire',i));
 perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',w,'external_identity.retire',(i||jsonb_build_object('command_id',gen_random_uuid()))::text),'40001');
 perform pg_temp.assert_identity(jsonb_array_length(public.external_identity_v1_query(w,'external_identity.list',jsonb_build_object('local_entity_kind','customer','local_entity_id',c->>'id','status','retired'))->'items')=1);
end$$;
reset role;
insert into public.import_jobs(workspace_id,import_kind,source_file_ref_id,source_file_digest_hmac,digest_key_version,mapping_schema_version,idempotency_key_id,created_by_user_id)values(md5('density.workspace.1')::uuid,'protected_identifiers',gen_random_uuid(),repeat('a',64),1,1,gen_random_uuid(),md5('density.actor.1.1')::uuid);
select pg_temp.assert_identity((select count(*)=1 from public.import_jobs where import_kind='protected_identifiers'and status='uploaded'));
select pg_temp.assert_identity((select count(*)=2 from public.external_entity_identities));
select pg_temp.assert_identity(not exists(select 1 from public.product_audit_events where to_jsonb(product_audit_events)::text like'%SYNTHETIC-IDENTITY-PRIVATE%'or to_jsonb(product_audit_events)::text like'%Synthetic Registry Must Not Audit%'));
select pg_temp.deny_identity('update public.external_entity_identities set local_entity_id=gen_random_uuid()','23514');
set local role authenticated;select set_config('request.jwt.claim.sub',md5('density.actor.1.3')::uuid::text,true);
select pg_temp.deny_identity('select *from public.external_entity_identities','42501');
select pg_temp.deny_identity(format('select public.external_identity_v1_query(%L,%L,%L)',md5('density.workspace.1')::uuid,'external_identity.integration_list','{}'),'42501');
do $$declare x record;begin for x in select *from saved_identity loop perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',md5('density.workspace.1')::uuid,x.op,x.inp::text),'42501');end loop;end$$;
reset role;
update public.workspace_members set status='suspended'where workspace_id=md5('density.workspace.1')::uuid and user_id=md5('density.actor.1.1')::uuid;
set local role authenticated;select set_config('request.jwt.claim.sub',md5('density.actor.1.1')::uuid::text,true);
do $$declare x record;begin for x in select *from saved_identity loop perform pg_temp.deny_identity(format('select public.external_identity_v1_command(%L,%L,%L)',md5('density.workspace.1')::uuid,x.op,x.inp::text),'42501');end loop;end$$;
select pg_temp.deny_identity(format('select public.external_identity_v1_query(%L,%L,%L)',md5('density.workspace.1')::uuid,'external_identity.integration_list','{}'),'42501');
reset role;
rollback;
