'use client'
import {useEffect,useRef,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import type {DocumentMaintenanceInputV1,DocumentMaintenanceReceiptV1} from '@/lib/contracts/document-maintenance-v1'
import type {DocumentContentInputsV1} from '@/lib/contracts/document-content-v1'
import type {DocumentMetadataV1} from '@/lib/contracts/document-v1'
import type {ExpiredDocumentPage} from '@/features/product/integration/document-maintenance-client'
import {control,primary,Drawer} from '@/features/product/ui'
import {ConfirmDialog} from '@/components/ConfirmDialog'
export function DocumentIntegrity({document:d,onVerified}:{document:DocumentMetadataV1;onVerified:()=>Promise<void>}){
 const {repository}=useProduct(),[retry,setRetry]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<DocumentMaintenanceReceiptV1|null>(null)
 const pending=useRef<{download:DocumentContentInputsV1['document.request_download'];verify?:DocumentMaintenanceInputV1;receipt?:DocumentMaintenanceReceiptV1}|null>(null)
 async function verify(){if(busy)return;setBusy(true);setError('');try{
  pending.current??={download:Object.freeze({command_id:crypto.randomUUID(),id:d.id,expected_version:d.version})}
  const p=pending.current
  if(!p.verify){const ticket=await repository.contentCommand('document.request_download',p.download);if(!ticket.ticket_id)throw new ProductUiError('internal_safe');p.verify=Object.freeze({command_id:crypto.randomUUID(),id:d.id,expected_version:d.version,ticket_id:ticket.ticket_id})}
  p.receipt??=await repository.maintenance('document.verify_content',p.verify)
  const fresh=(await repository.document(d.id)).record;if(fresh.version<p.receipt.version||fresh.status!=='active')throw new ProductUiError('conflict')
  await onVerified();setReceipt(p.receipt);pending.current=null;setRetry(false)
 }catch(e){setReceipt(null);setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')&&!pending.current?.receipt)pending.current=null;setRetry(!!pending.current)}finally{setBusy(false)}}
 return <section className="mt-4 space-y-3 border-t pt-4"><h3 className="font-medium">Integridad del archivo</h3><p className="text-xs text-slate-500">El servidor compara los bytes privados y registra una prueba SHA-256 para esta versión. Sin análisis antivirus.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{receipt&&<p role="status" className="text-sm text-emerald-700">Integridad SHA-256 registrada · Versión {receipt.version} · Sin escanear</p>}<button className={control} disabled={busy||!!receipt} onClick={verify}>{busy?'Comprobando…':retry?'Reintentar comprobación exacta':'Verificar integridad privada'}</button></section>
}
type CleanupIntent={operation:'document.cleanup_claim'|'document.cleanup_finish';input:DocumentMaintenanceInputV1;receipt?:DocumentMaintenanceReceiptV1}
export function DocumentCleanup({onClose}:{onClose:()=>void}){
 const {repository}=useProduct(),[page,setPage]=useState<ExpiredDocumentPage|null>(null),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[intent,setIntent]=useState<CleanupIntent|null>(null),[claim,setClaim]=useState<DocumentMaintenanceReceiptV1|null>(null),[notice,setNotice]=useState(''),pending=useRef<CleanupIntent|null>(null)
 useEffect(()=>{let alive=true;void repository.expiredDocuments({limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(alive){setPage(v);setError('')}}).catch(e=>{if(alive){setPage(null);setError(safeMessage(e))}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[repository,cursors,revision])
 function refresh(){setPage(null);setCursors([]);setLoading(true);setRevision(v=>v+1)}
 function prepare(operation:CleanupIntent['operation'],id:string,version:number){if(busy||intent)return;pending.current=null;setError('');setIntent({operation,input:Object.freeze({command_id:crypto.randomUUID(),id,expected_version:version})})}
 async function execute(){if(!intent||busy)return;setBusy(true);setError('');pending.current??=intent;try{const p=pending.current;p.receipt??=await repository.maintenance(p.operation,p.input);if(p.operation==='document.cleanup_claim'){setClaim(p.receipt);setNotice('Subida reservada durante diez minutos. Confirma la limpieza exacta del archivo pendiente.')}else{setClaim(null);setNotice('Archivo pendiente eliminado; metadatos archivados y conservados.')}pending.current=null;setIntent(null);refresh()}catch(e){setPage(null);setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')&&!pending.current?.receipt)pending.current=null}finally{setBusy(false)}}
 return <Drawer title="Subidas caducadas" onClose={()=>{if(!busy)onClose()}}><div className="space-y-4"><p className="text-sm text-slate-500">Solo subidas pendientes con más de 24 horas de caducidad. Cada limpieza requiere reserva y confirmación. Los documentos activos y sus PDF se conservan.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}<button className={control} disabled={busy||!!intent} onClick={refresh}>Actualizar subidas caducadas</button>{claim&&<section className="rounded-lg border p-3"><p className="break-all text-xs">Subida reservada · {claim.id} · Versión {claim.version}</p><button className={primary} disabled={busy||!!intent} onClick={()=>prepare('document.cleanup_finish',claim.id,claim.version)}>Finalizar limpieza de subida</button></section>}{loading&&<p role="status">Cargando subidas…</p>}{page?.items.map(r=><article data-expired-document-id={r.id} key={r.id} className="space-y-2 rounded-lg border p-3"><p className="break-all text-xs">Subida pendiente · {r.id} · Versión {r.version}</p><button className={control} disabled={busy||!!intent||!!claim} onClick={()=>prepare('document.cleanup_claim',r.id,r.version)}>Reservar subida caducada</button></article>)}{page&&!page.items.length&&<p className="text-sm text-slate-500">Sin subidas caducadas en esta página.</p>}<div className="flex flex-wrap gap-2"><button className={control} disabled={loading||busy||!!intent||!cursors.length} onClick={()=>{setPage(null);setLoading(true);setCursors(v=>v.slice(0,-1))}}>Página anterior de subidas</button><span className="text-xs">Página {cursors.length+1} · Hasta 20 subidas</span><button className={control} disabled={loading||busy||!!intent||!page?.next_id} onClick={()=>{if(page?.next_id){setPage(null);setLoading(true);setCursors(v=>[...v,page.next_id!])}}}>Siguiente página de subidas</button></div></div><ConfirmDialog open={!!intent} title={intent?.operation==='document.cleanup_claim'?'Reservar subida caducada':'Eliminar archivo pendiente'} description={intent?.operation==='document.cleanup_claim'?'Reserva esta subida pendiente caducada para su limpieza.':'Se eliminará únicamente el archivo pendiente reservado. Esta eliminación es definitiva; sus metadatos quedarán archivados.'} loading={busy} error={error} onConfirm={execute} onCancel={()=>{if(!busy){setIntent(null);pending.current=null;if(error)refresh()}}}/></Drawer>
}
