'use client'
import { useRef, useState } from 'react'
import { Drawer, control, primary } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import type { DocumentContentInputsV1, DocumentContentReceiptV1 } from '@/lib/contracts/document-content-v1'
/** File, immutable intent and receipt live only inside this mounted drawer. */
export function DocumentUpload({customerId,onClose,onSaved}:{customerId:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {repository}=useProduct(),[file,setFile]=useState<File|null>(null),[documentKind,setDocumentKind]=useState<'general'|'identity'|'contract'|'service'|'incident'|'billing'|'other'>('general'),[step,setStep]=useState<'select'|'prepared'|'uploaded'|'done'>('select'),[receipt,setReceipt]=useState<DocumentContentReceiptV1|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null)
 const request=useRef<DocumentContentInputsV1['document.request_upload']|null>(null),finalize=useRef<DocumentContentInputsV1['document.finalize_upload']|null>(null),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
 async function action(){if(busy||!file||conflict)return;setBusy(true);setError(null);try{
  if(step==='select'){if(!request.current)request.current=Object.freeze({command_id:crypto.randomUUID(),target_kind:'customer',target_id:customerId,document_kind:documentKind,media_type:file.type as 'application/pdf'|'image/png'|'image/jpeg',size_bytes:file.size,file_name:file.name});const r=await repository.contentCommand('document.request_upload',request.current);setReceipt(r);setStep('prepared')}
  else if(step==='prepared'&&receipt){await repository.uploadDocument(receipt.id,file);setStep('uploaded')}
  else if(step==='uploaded'&&receipt){if(!finalize.current)finalize.current=Object.freeze({command_id:crypto.randomUUID(),id:receipt.id,expected_version:receipt.version});await repository.contentCommand('document.finalize_upload',finalize.current);setStep('done');await onSaved()}
 }catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')){if(step==='select')request.current=null;else if(step==='uploaded')finalize.current=null}}finally{setBusy(false)}}
 return <Drawer title="Subir documento local" onClose={()=>{if(!busy)onClose()}}><div className="space-y-4"><p className="text-sm text-slate-500">Solo archivos sintéticos de prueba. El archivo queda pendiente hasta confirmar su finalización.</p><fieldset disabled={busy||uncertain||step!=='select'} className="space-y-3"><label className="block text-sm">Archivo de prueba<input type="file" accept="application/pdf,image/png,image/jpeg" className={`${control} w-full`} onChange={e=>{setFile(e.target.files?.[0]??null);request.current=null;setError(null)}}/></label><label className="block text-sm">Clase de documento<select className={control} value={documentKind} onChange={e=>setDocumentKind(e.target.value as typeof documentKind)}>{['general','identity','contract','service','incident','billing','other'].map(k=><option key={k} value={k}>{{general:'General',identity:'Identidad',contract:'Contrato',service:'Servicio',incident:'Incidencia',billing:'Facturación',other:'Otro'}[k]}</option>)}</select></label></fieldset>{file&&<p className="text-xs text-slate-500">{file.size} bytes · Máximo 10 MiB. PDF, PNG o JPEG.</p>}{receipt?.expires_at&&<p className="text-xs text-slate-500">Intención pendiente hasta {receipt.expires_at}.</p>}{step==='prepared'&&<p role="status">Intención preparada. El archivo todavía no se ha subido.</p>}{step==='uploaded'&&<p role="status">Archivo subido; pendiente de finalización.</p>}{step==='done'&&<p role="status">Documento finalizado y disponible.</p>}{!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}{step!=='done'&&<button className={primary} disabled={busy||!file||conflict} onClick={action}>{busy?'Procesando…':uncertain?'Reintentar el mismo paso':step==='select'?'Preparar subida':step==='prepared'?'Subir archivo pendiente':'Confirmar finalización'}</button>}<p className="text-xs text-slate-500">No hay análisis antivirus ni certificación de integridad. Los archivos se descargan como adjuntos; la vista previa no está disponible.</p></div></Drawer>
}
