'use client'
import {DocumentIntegrity,DocumentCleanup} from './DocumentMaintenance'
import {DocumentImagePreview} from './DocumentImagePreview'
import { DocumentUpload } from './DocumentUpload'
import { useDocumentMetadataSelection } from './useDocumentMetadataSelection'
import type { DocumentContentInputsV1, DocumentContentReceiptV1 } from '@/lib/contracts/document-content-v1'
import { useCallback, useEffect, useRef, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import { PreviewNotice, control, primary, Drawer, Status } from '@/features/product/ui'
import type { DocumentListV1, DocumentMetadataV1, DocumentReceiptV1, DocumentTargetKindV1 } from '@/lib/contracts/document-v1'
import type { GlobalSearchV1 } from '@/lib/contracts/product-dashboard-v2'
export function IntegratedDocuments({customerId:initialCustomerId,contentEnabled=false,maintenanceEnabled=false,initialTarget}:{customerId?:string;contentEnabled?:boolean;maintenanceEnabled?:boolean;initialTarget?:{kind:DocumentTargetKindV1;id:string;label:string}}){
  const {repository,role,actorId,workspaceId}=useProduct(),authorized=role==='owner'||role==='admin'
  const [customerId,setCustomerId]=useState(initialCustomerId??''),[target,setTarget]=useState<{kind:DocumentTargetKindV1;id:string;label:string}|null>(initialTarget??(initialCustomerId?{kind:'customer',id:initialCustomerId,label:'Empresa seleccionada'}:null)),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<GlobalSearchV1|null>(null),[data,setData]=useState<DocumentListV1|null>(null),[status,setStatus]=useState<'active'|'archived'>('active')
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<DocumentMetadataV1|null>(null)
  const metadataScope=JSON.stringify([actorId,workspaceId,role,target?.kind,target?.id])
  const metadata=useDocumentMetadataSelection(repository,metadataScope,authorized),selected=metadata.selected
  const visibleError=metadata.error||error
  const [cleanup,setCleanup]=useState(false)
  const [preview,setPreview]=useState<DocumentMetadataV1|null>(null)
  const [upload,setUpload]=useState(false),[download,setDownload]=useState<DocumentMetadataV1|null>(null)
  const downloadIntent=useRef<DocumentContentInputsV1['document.request_download']|null>(null),ticket=useRef<DocumentContentReceiptV1|null>(null)
  async function downloadFile(){if(!download||busy)return;setBusy(true);setError('');try{if(!downloadIntent.current)downloadIntent.current=Object.freeze({command_id:crypto.randomUUID(),id:download.id,expected_version:download.version});if(!ticket.current)ticket.current=await repository.contentCommand('document.request_download',downloadIntent.current);if(!ticket.current.ticket_id)throw new ProductUiError('internal_safe');const blob=await repository.downloadDocument(download.id,ticket.current.ticket_id);const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=blob.type==='application/pdf'?'document.pdf':blob.type==='image/png'?'document.png':'document.jpg';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);downloadIntent.current=null;ticket.current=null;setDownload(null)}catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')){downloadIntent.current=null;ticket.current=null}}finally{setBusy(false)}}
  const pending=useRef<{execute:()=>Promise<DocumentReceiptV1>}|null>(null)
  const load=useCallback(async()=>{setData(null);setCursors([]);setRevision(v=>v+1)},[])
  useEffect(()=>{if(!target||!authorized)return;let current=true;const timer=setTimeout(()=>{if(current)setLoading(true)},0);void repository.documents({target_kind:target.kind,target_id:target.id,status,limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(current){setData(v);setError('')}}).catch(e=>{if(current){setData(null);setError(safeMessage(e))}}).finally(()=>{if(current)setLoading(false)});return()=>{current=false;clearTimeout(timer)}},[target,status,repository,authorized,cursors,revision])
  async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setResults(await repository.search(query))}catch(e){setResults(null);setError(safeMessage(e))}finally{setBusy(false)}}
  async function mutate(){if(!confirm||busy)return;setBusy(true);setError('');if(!pending.current){const operation=confirm.status==='active'?'document.archive':'document.restore';const input={command_id:crypto.randomUUID(),id:confirm.id,expected_version:confirm.version};pending.current={execute:()=>repository.documentCommand(operation,input)}}
    try{await pending.current.execute();pending.current=null;setConfirm(null);metadata.close();setMessage('Metadatos actualizados.');await load()}catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  return <div className="space-y-4"><PageHeader title="Documentos" description="Metadatos autorizados del cliente seleccionado"/><PreviewNotice/>{!authorized?<p className="text-sm text-slate-500">Documentos disponibles para administradores del espacio.</p>:<>
    {maintenanceEnabled&&<button className={control} onClick={()=>setCleanup(true)}>Revisar subidas caducadas</button>}
    <form onSubmit={search} className="flex flex-wrap gap-2"><input className={control} aria-label="Buscar cliente para documentos" placeholder="Empresa, contrato, servicio, línea u oportunidad" required minLength={2} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><button className={primary} disabled={busy}>Buscar registro</button></form>
    {results&&<div className="flex flex-wrap gap-2">{results.items.filter(r=>['customer','contract','service','line','opportunity'].includes(r.kind)).map(r=><button key={r.id} className={control} onClick={()=>{setCustomerId(r.customer_id??r.id);setTarget({kind:r.kind as DocumentTargetKindV1,id:r.id,label:r.label});setCursors([]);setData(null);setResults(null);metadata.close();setMessage('')}}>{{customer:'Empresa',contract:'Contrato',service:'Servicio',line:'Línea',opportunity:'Oportunidad',contact:'Contacto',invoice:'Factura'}[r.kind]} · {r.label}</button>)}{!results.items.some(r=>['customer','contract','service','line','opportunity'].includes(r.kind))&&<p className="text-sm text-slate-500">Sin registros compatibles en esta consulta.</p>}</div>}
    {visibleError&&!download&&!confirm&&<p role="alert" className="text-red-700">{visibleError}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}
    {target&&<section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">{target.label}</h2><div className="mb-4 flex flex-wrap gap-2"><select aria-label="Estado de documentos" className={control} value={status} onChange={e=>{setStatus(e.target.value as typeof status);setCursors([]);setData(null)}}><option value="active">Activos</option><option value="archived">Archivados</option></select><button className={control} onClick={()=>load()}>Actualizar documentos</button>{contentEnabled&&<button className={primary} onClick={()=>setUpload(true)}>Subir documento local</button>}</div>
    {loading&&<p role="status" className="py-4 text-sm text-slate-500">Cargando documentos…</p>}{data?.items.map(d=><article data-document-id={d.id} data-document-version={d.version} key={d.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div><h2 className="font-medium">Documento · {{general:'General',identity:'Identidad',contract:'Contrato',service:'Servicio',incident:'Incidencia',billing:'Facturación',other:'Otro'}[d.document_kind]}</h2><p className="text-xs text-slate-500">{d.media_type??'Tipo no disponible'} · {d.size_bytes===null?'Tamaño no disponible':`${d.size_bytes} bytes`}</p><Status value={d.status}/></div><div className="flex flex-wrap gap-2"><button className={control} onClick={()=>{setError('');void metadata.open(d.id)}}>Ver metadatos</button>{contentEnabled&&d.status==='active'&&['image/png','image/jpeg'].includes(d.media_type??'')&&<button className={control} onClick={()=>setPreview(d)}>Vista previa de imagen</button>}{contentEnabled&&d.status==='active'&&<button className={control} onClick={()=>{downloadIntent.current=null;ticket.current=null;setError('');setDownload(d)}}>Descargar archivo privado</button>}<button className={control} onClick={()=>{pending.current=null;setConfirm(d);setError('')}}>{d.status==='active'?'Archivar documento':'Restaurar documento'}</button></div></article>)}{data&&!data.items.length&&<p className="text-sm text-slate-500">Sin documentos en esta página.</p>}<div className="mt-4 flex flex-wrap items-center gap-3 border-t pt-4"><button className={control} disabled={loading||!cursors.length} onClick={()=>{setData(null);setCursors(v=>v.slice(0,-1))}}>Página anterior de documentos</button><span className="text-xs text-slate-500">Página {cursors.length+1} · Hasta 20 documentos</span><button className={control} disabled={loading||!data?.next_id} onClick={()=>{if(data?.next_id){setCursors(v=>[...v,data.next_id!]);setData(null)}}}>Siguiente página de documentos</button></div></section>}
    {!target&&<p className="text-sm text-slate-500">Selecciona una empresa o registro para consultar sus documentos. Hasta cinco resultados por tipo en cada búsqueda; las incidencias requieren una lectura de selección aún no publicada.</p>}
    <p className="text-sm text-slate-500">{contentEnabled?'Vista previa privada para PNG y JPEG. Los PDF se descargan como adjuntos. El análisis antivirus no está disponible.':'Subida y descarga pendientes de habilitación local explícita; vista previa no disponible.'}</p>
    {cleanup&&<DocumentCleanup onClose={()=>setCleanup(false)}/>}
    {preview&&<DocumentImagePreview key={preview.id} document={preview} onClose={()=>setPreview(null)}/>}
    {upload&&<DocumentUpload key={target?.id} customerId={customerId} targetKind={target?.kind} targetId={target?.id} onClose={()=>setUpload(false)} onSaved={async()=>{await load()}}/>}
    <ConfirmDialog open={!!download} title="Descargar archivo privado" description="Se solicitará un acceso de 30 segundos que revalida tus permisos. Archivo sin análisis antivirus." loading={busy} error={error} onConfirm={downloadFile} onCancel={()=>{if(!busy){setDownload(null);downloadIntent.current=null;ticket.current=null}}}/>
    {selected&&<Drawer title="Metadatos del documento" onClose={()=>metadata.close()}><dl className="space-y-3 text-sm"><div><dt>Tipo</dt><dd>{selected.document_kind}</dd></div><div><dt>Formato</dt><dd>{selected.media_type??'No disponible'}</dd></div><div><dt>Tamaño</dt><dd>{selected.size_bytes===null?'No disponible':`${selected.size_bytes} bytes`}</dd></div></dl><p className="text-xs text-slate-500">No incluye nombre, contenido, ruta ni enlace de descarga.</p>{contentEnabled&&maintenanceEnabled&&selected.status==='active'&&<DocumentIntegrity key={selected.id} document={selected} onVerified={async()=>{await metadata.refresh(selected.id);await load()}}/>}</Drawer>}
    <ConfirmDialog open={!!confirm} title={confirm?.status==='active'?'Archivar documento':'Restaurar documento'} description="Confirma el cambio de estado de los metadatos locales." loading={busy} error={error} onConfirm={mutate} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</div>
}
