'use client'
import { DocumentUpload } from './DocumentUpload'
import type { DocumentContentInputsV1, DocumentContentReceiptV1 } from '@/lib/contracts/document-content-v1'
import { useCallback, useEffect, useRef, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import { PreviewNotice, control, primary, Drawer, Status } from '@/features/product/ui'
import type { DocumentListV1, DocumentMetadataV1, DocumentReceiptV1 } from '@/lib/contracts/document-v1'
import type { GlobalSearchV1 } from '@/lib/contracts/product-dashboard-v2'
export function IntegratedDocuments({customerId:initialCustomerId,contentEnabled=false}:{customerId?:string;contentEnabled?:boolean}){
  const {repository,role}=useProduct(),authorized=role==='owner'||role==='admin'
  const [customerId,setCustomerId]=useState(initialCustomerId??''),[query,setQuery]=useState(''),[results,setResults]=useState<GlobalSearchV1|null>(null),[data,setData]=useState<DocumentListV1|null>(null),[status,setStatus]=useState<'active'|'archived'>('active')
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<DocumentMetadataV1|null>(null),[confirm,setConfirm]=useState<DocumentMetadataV1|null>(null)
  const [upload,setUpload]=useState(false),[download,setDownload]=useState<DocumentMetadataV1|null>(null)
  const downloadIntent=useRef<DocumentContentInputsV1['document.request_download']|null>(null),ticket=useRef<DocumentContentReceiptV1|null>(null)
  async function downloadFile(){if(!download||busy)return;setBusy(true);setError('');try{if(!downloadIntent.current)downloadIntent.current=Object.freeze({command_id:crypto.randomUUID(),id:download.id,expected_version:download.version});if(!ticket.current)ticket.current=await repository.contentCommand('document.request_download',downloadIntent.current);if(!ticket.current.ticket_id)throw new ProductUiError('internal_safe');const blob=await repository.downloadDocument(download.id,ticket.current.ticket_id);const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=blob.type==='application/pdf'?'document.pdf':blob.type==='image/png'?'document.png':'document.jpg';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);downloadIntent.current=null;ticket.current=null;setDownload(null)}catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')){downloadIntent.current=null;ticket.current=null}}finally{setBusy(false)}}
  const pending=useRef<{execute:()=>Promise<DocumentReceiptV1>}|null>(null)
  const load=useCallback(async(afterId?:string)=>{if(!customerId||!authorized)return;try{setData(await repository.documents({target_kind:'customer',target_id:customerId,status,limit:20,...(afterId?{after_id:afterId}:{})}));setError('')}catch(e){setData(null);setError(safeMessage(e))}},[customerId,status,repository,authorized])
  useEffect(()=>{if(!customerId||!authorized)return;let current=true;void repository.documents({target_kind:'customer',target_id:customerId,status,limit:20}).then(v=>{if(current){setData(v);setError('')}}).catch(e=>{if(current){setData(null);setError(safeMessage(e))}});return()=>{current=false}},[customerId,status,repository,authorized])
  async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{setResults(await repository.search(query))}catch(e){setResults(null);setError(safeMessage(e))}finally{setBusy(false)}}
  async function mutate(){if(!confirm||busy)return;setBusy(true);setError('');if(!pending.current){const operation=confirm.status==='active'?'document.archive':'document.restore';const input={command_id:crypto.randomUUID(),id:confirm.id,expected_version:confirm.version};pending.current={execute:()=>repository.documentCommand(operation,input)}}
    try{await pending.current.execute();pending.current=null;setConfirm(null);setSelected(null);setMessage('Metadatos actualizados.');await load()}catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  return <div className="space-y-4"><PageHeader title="Documentos" description="Metadatos autorizados del cliente seleccionado"/><PreviewNotice/>{!authorized?<p className="text-sm text-slate-500">Documentos disponibles para administradores del espacio.</p>:<>
    <form onSubmit={search} className="flex flex-wrap gap-2"><input className={control} aria-label="Buscar cliente para documentos" placeholder="Buscar empresa" required minLength={2} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><button className={primary} disabled={busy}>Buscar empresa</button></form>
    {results&&<div className="flex flex-wrap gap-2">{results.items.filter(r=>r.kind==='customer').map(r=><button key={r.id} className={control} onClick={()=>{setCustomerId(r.id);setData(null);setResults(null);setSelected(null);setMessage('')}}>{r.label}</button>)}{!results.items.some(r=>r.kind==='customer')&&<p className="text-sm text-slate-500">Sin empresas en esta consulta.</p>}</div>}
    {error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}
    {customerId&&<section className="rounded-xl border bg-white p-5"><div className="mb-4 flex flex-wrap gap-2"><select aria-label="Estado de documentos" className={control} value={status} onChange={e=>{setStatus(e.target.value as typeof status);setData(null)}}><option value="active">Activos</option><option value="archived">Archivados</option></select><button className={control} onClick={()=>load()}>Actualizar documentos</button>{contentEnabled&&<button className={primary} onClick={()=>setUpload(true)}>Subir documento local</button>}</div>
    {data?.items.map(d=><article key={d.id} className="flex flex-wrap items-center justify-between gap-3 border-t py-3"><div><h2 className="font-medium">Documento · {d.document_kind}</h2><p className="text-xs text-slate-500">{d.media_type??'Tipo no disponible'} · {d.size_bytes===null?'Tamaño no disponible':`${d.size_bytes} bytes`}</p><Status value={d.status}/></div><div className="flex flex-wrap gap-2"><button className={control} onClick={async()=>{try{setSelected((await repository.document(d.id)).record)}catch(e){setError(safeMessage(e))}}}>Ver metadatos</button>{contentEnabled&&d.status==='active'&&<button className={control} onClick={()=>{downloadIntent.current=null;ticket.current=null;setError('');setDownload(d)}}>Descargar archivo privado</button>}<button className={control} onClick={()=>{pending.current=null;setConfirm(d);setError('')}}>{d.status==='active'?'Archivar documento':'Restaurar documento'}</button></div></article>)}{data&&!data.items.length&&<p className="text-sm text-slate-500">Sin documentos en esta página.</p>}{data?.next_id&&<button className={control} onClick={()=>load(data.next_id!)}>Siguiente página</button>}</section>}
    {!customerId&&<p className="text-sm text-slate-500">Selecciona una empresa para consultar sus documentos.</p>}
    <p className="text-sm text-slate-500">{contentEnabled?'Archivos privados como adjuntos. La vista previa y el análisis antivirus no están disponibles.':'Subida y descarga pendientes de habilitación local explícita; vista previa no disponible.'}</p>
    {upload&&<DocumentUpload key={customerId} customerId={customerId} onClose={()=>setUpload(false)} onSaved={async()=>{await load()}}/>}
    <ConfirmDialog open={!!download} title="Descargar archivo privado" description="Se solicitará un acceso de 30 segundos que revalida tus permisos. Archivo sin análisis antivirus." loading={busy} error={error} onConfirm={downloadFile} onCancel={()=>{if(!busy){setDownload(null);downloadIntent.current=null;ticket.current=null}}}/>
    {selected&&<Drawer title="Metadatos del documento" onClose={()=>setSelected(null)}><dl className="space-y-3 text-sm"><div><dt>Tipo</dt><dd>{selected.document_kind}</dd></div><div><dt>Formato</dt><dd>{selected.media_type??'No disponible'}</dd></div><div><dt>Tamaño</dt><dd>{selected.size_bytes===null?'No disponible':`${selected.size_bytes} bytes`}</dd></div></dl><p className="text-xs text-slate-500">No incluye nombre, contenido, ruta ni enlace de descarga.</p></Drawer>}
    <ConfirmDialog open={!!confirm} title={confirm?.status==='active'?'Archivar documento':'Restaurar documento'} description="Confirma el cambio de estado de los metadatos locales." loading={busy} error={error} onConfirm={mutate} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</div>
}
