'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import {control,primary,Drawer,Status,statusLabel} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
import {NamedCustomer} from '@/features/customers/CustomerDomainPages'
import type {EquipmentInputsV1,EquipmentOperationV1,EquipmentReceiptV1,EquipmentRowV1,EquipmentReadV1,EquipmentKindV1,EquipmentStatusV1} from '@/lib/contracts/equipment-v1'
type Page=Extract<EquipmentReadV1,{operation:'equipment.list'}>
type History=Extract<EquipmentReadV1,{operation:'equipment.history'}>
const kinds:Record<EquipmentKindV1,string>={router:'Router',ont:'ONT',mobile_terminal:'Terminal móvil',other:'Otro equipo'}
const states:EquipmentStatusV1[]=['prepared','assigned','returned','replaced','cancelled']
const sources={manual:'Manual',import:'Importado',integration:'Integración'}
const actions={'equipment.assign':'Asignar','equipment.return':'Registrar devolución','equipment.replace':'Sustituir','equipment.cancel':'Cancelar equipo'} as const
type Action=keyof typeof actions
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function EquipmentInventory({customerId,initialId,createAllowed=false}:{customerId?:string;initialId?:string;createAllowed?:boolean}){
 const {repository,role}=useProduct(),[status,setStatus]=useState(''),[kind,setKind]=useState(''),[source,setSource]=useState(''),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[state,setState]=useState<{key:string;page?:Page;error?:string}|null>(null),[selected,setSelected]=useState(initialId??null),[creating,setCreating]=useState(false)
 const key=JSON.stringify([customerId,status,kind,source,cursors,revision]),current=state?.key===key?state:null,page=current?.page
 useEffect(()=>{let active=true;void repository.telecom('equipment.list',{...(customerId?{customer_id:customerId}:{}),...(status?{status:status as EquipmentStatusV1}:{}),...(kind?{kind:kind as EquipmentKindV1}:{}),...(source?{source:source as 'manual'|'import'|'integration'}:{}),limit:20,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})}).then(page=>{if(active)setState({key,page})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,customerId,status,kind,source,cursors,key])
 const refresh=()=>setRevision(v=>v+1),filter=(setter:(s:string)=>void,v:string)=>{setCursors([]);setter(v)}
 return <section className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Equipos</h2><p className="mt-1 text-xs text-slate-500">Equipos preparados o asignados a clientes · páginas de hasta 20 registros.</p></div><div className="flex gap-2"><button className={control} onClick={refresh}>Actualizar equipos</button>{customerId&&createAllowed&&role&&role!=='viewer'&&<button className={primary} onClick={()=>setCreating(true)}>Nuevo equipo</button>}</div></div>
 <div className="flex flex-wrap gap-2"><select aria-label="Estado de Equipos" className={control} value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">Todos los estados</option>{states.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select><select aria-label="Tipo de equipo" className={control} value={kind} onChange={e=>filter(setKind,e.target.value)}><option value="">Todos los tipos</option>{Object.entries(kinds).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select><select aria-label="Origen de equipos" className={control} value={source} onChange={e=>filter(setSource,e.target.value)}><option value="">Todos los orígenes</option>{Object.entries(sources).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select>{(status||kind||source)&&<button className={control} onClick={()=>{setStatus('');setKind('');setSource('');setCursors([])}}>Limpiar filtros</button>}</div>
 {current?.error?<div className="rounded-xl border border-red-100 bg-red-50 p-4"><p role="alert" className="text-sm text-red-700">{current.error}</p><button className={control+' mt-3'} onClick={refresh}>Reintentar equipos</button></div>:!page?<p role="status" className="p-4 text-sm text-slate-500">Cargando equipos…</p>:!page.items.length?<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">No hay equipos con estos filtros en esta página.</p>:<div className="overflow-hidden rounded-xl border bg-white"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Equipo',...(!customerId?['Cliente']:[]),'Tipo','Estado','Compra','Asignación','Origen','Detalle'].map(h=><th className="whitespace-nowrap p-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{page.items.map(r=><tr key={r.id} data-equipment-id={r.id}><td className="min-w-44 p-3"><p className="font-semibold">{r.manufacturer} · {r.model}</p>{r.commercial_description&&<p className="mt-1 text-slate-500">{r.commercial_description}</p>}</td>{!customerId&&<td className="p-3"><NamedCustomer id={r.customer_id}/></td>}<td className="p-3">{kinds[r.kind]}</td><td className="p-3"><Status value={r.status}/></td><td className="p-3 whitespace-nowrap">{productDate(r.purchased_on)}</td><td className="p-3 whitespace-nowrap">{productDate(r.assigned_on)}</td><td className="p-3">{sources[r.source]}</td><td className="p-3"><button className={control} onClick={()=>setSelected(r.id)}>Ver equipo</button></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{page.items.map(r=><article key={r.id} data-equipment-id={r.id} className="p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{r.manufacturer} · {r.model}</h3><Status value={r.status}/></div>{!customerId&&<p className="my-2 text-sm"><NamedCustomer id={r.customer_id}/></p>}<dl className="my-3 grid grid-cols-2 gap-3 text-xs">{[['Tipo',kinds[r.kind]],['Origen',sources[r.source]],['Compra',productDate(r.purchased_on)],['Asignación',productDate(r.assigned_on)]].map(([n,v])=><div key={n}><dt className="text-slate-500">{n}</dt><dd className="mt-1">{v}</dd></div>)}</dl>{r.commercial_description&&<p className="mb-3 text-sm text-slate-500">{r.commercial_description}</p>}<button className={control} onClick={()=>setSelected(r.id)}>Ver equipo</button></article>)}</div></div>}
 <footer className="flex flex-wrap justify-between gap-2"><button className={control} disabled={!page||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Página anterior de Equipos</button><span className="self-center text-xs text-slate-500">Página {cursors.length+1}{page?' · '+page.items.length+' registros':''}</span><button className={control} disabled={!page?.next_id} onClick={()=>{if(page?.next_id)setCursors(v=>[...v,page.next_id!])}}>Siguiente página de Equipos</button></footer>
 {selected&&<EquipmentDetail key={selected} id={selected} onClose={()=>setSelected(null)} onChanged={refresh}/>}{creating&&customerId&&<EquipmentCreate customerId={customerId} onClose={()=>setCreating(false)} onCreated={id=>{setCreating(false);setSelected(id);refresh()}}/>}
 </section>
}
function EquipmentDetail({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged:()=>void}){
 const {repository,role}=useProduct(),[record,setRecord]=useState<EquipmentRowV1|null>(null),[history,setHistory]=useState<History|null>(null),[historyCursors,setHistoryCursors]=useState<number[]>([]),[historyError,setHistoryError]=useState(''),[revision,setRevision]=useState(0),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[action,setAction]=useState<Action|null>(null),[eventOn,setEventOn]=useState(today),[manufacturer,setManufacturer]=useState(''),[model,setModel]=useState(''),[description,setDescription]=useState(''),[purchasedOn,setPurchasedOn]=useState(''),[review,setReview]=useState(false),[receipt,setReceipt]=useState<EquipmentReceiptV1|null>(null)
 const pending=useRef<{op:EquipmentOperationV1;input:EquipmentInputsV1[EquipmentOperationV1]}|null>(null),inFlight=useRef(false),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
 useEffect(()=>{let active=true;void repository.telecom('equipment.get',{id}).then(r=>{if(active){setRecord(r.record);setError(null)}}).catch(e=>{if(active){setRecord(null);setError(e)}});return()=>{active=false}},[repository,id,revision])
 useEffect(()=>{let active=true;void repository.telecom('equipment.history',{id,limit:20,...(historyCursors.at(-1)?{after_version:historyCursors.at(-1)}:{})}).then(h=>{if(active){setHistory(h);setHistoryError('')}}).catch(e=>{if(active){setHistory(null);setHistoryError(safeMessage(e))}});return()=>{active=false}},[repository,id,historyCursors,revision])
 const permitted:Action[]=record&&role&&role!=='viewer'&&record.source==='manual'?(record.status==='prepared'?['equipment.assign','equipment.cancel']:record.status==='assigned'?['equipment.return','equipment.replace']:[]):[]
 async function execute(){if(inFlight.current||!record||!action||receipt||conflict)return;inFlight.current=true;setBusy(true);setError(null);try{
  if(!pending.current){const base={command_id:crypto.randomUUID(),id:record.id,expected_version:record.version,event_on:eventOn};pending.current={op:action,input:Object.freeze(action==='equipment.replace'?{...base,manufacturer:manufacturer.trim(),model:model.trim(),commercial_description:description.trim()||null,purchased_on:purchasedOn||null,commitment_id:null}:base)}}
  const result=await repository.telecom(pending.current.op,pending.current.input) as EquipmentReceiptV1;setReceipt(result);pending.current=null;setReview(false);setAction(null);setHistory(null);setHistoryCursors([]);setRecord(null);setRevision(v=>v+1);onChanged()
 }catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{inFlight.current=false;setBusy(false)}}
 const minDate=record?.assigned_on??record?.purchased_on??'2000-01-01'
 return <Drawer title={record?record.manufacturer+' · '+record.model:'Detalle de equipo'} onClose={()=>{if(!busy&&!uncertain)onClose()}}><div className="space-y-4">
 {receipt&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">Cambio registrado: {statusLabel(receipt.status)}.{receipt.replacement_id&&' El equipo anterior conserva su historial; el nuevo equipo está asignado.'}</p>}
 {error!==null&&<div><p role="alert" className="text-sm text-red-700">{safeMessage(error)}</p>{uncertain?<button className={primary+' mt-3'} disabled={busy} onClick={()=>void execute()}>Comprobar la misma operación</button>:<button className={control+' mt-3'} disabled={busy} onClick={()=>{setRecord(null);setRevision(v=>v+1);setAction(null);setReview(false)}}>Volver a consultar el equipo</button>}</div>}
 {!record&&error===null&&<p role="status" className="text-sm text-slate-500">Consultando equipo…</p>}{record&&<><Status value={record.status}/><p className="text-sm"><NamedCustomer id={record.customer_id}/></p><dl className="grid grid-cols-2 gap-3 text-sm">{[['Tipo',kinds[record.kind]],['Origen',sources[record.source]],['Compra',productDate(record.purchased_on)],['Asignación',productDate(record.assigned_on)],['Devolución',productDate(record.returned_on)],['Sustitución',productDate(record.replaced_on)],['Cancelación',productDate(record.cancelled_on)]].map(([n,v])=><div key={n}><dt className="text-xs text-slate-500">{n}</dt><dd className="mt-1">{v}</dd></div>)}</dl>{record.commercial_description&&<p className="text-sm">{record.commercial_description}</p>}<div className="flex flex-wrap gap-2">{(['contract','service','line'] as const).map(k=>record[`${k}_id`]&&<Link key={k} className={control} href={`/portfolio?kind=${k}&id=${record[`${k}_id`]}`}>Ver {{contract:'contrato',service:'servicio',line:'línea'}[k]}</Link>)}{record.replaced_by_id&&<Link className={control} href={`/equipment?id=${record.replaced_by_id}`}>Ver equipo sustituto</Link>}{record.replaces_equipment_id&&<Link className={control} href={`/equipment?id=${record.replaces_equipment_id}`}>Ver equipo anterior</Link>}</div>
 {!permitted.length&&<p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-500">{record.source!=='manual'?'Los hechos importados o integrados se conservan en modo consulta.':role==='viewer'?'Consulta de solo lectura para tu rol.':'Este equipo está cerrado; su historial se conserva.'}</p>}
 {!receipt&&<div className="flex flex-wrap gap-2">{permitted.map(op=><button key={op} className={control} disabled={busy||uncertain||conflict} onClick={()=>{setAction(op);setReview(false);setError(null)}}>{actions[op]}</button>)}</div>}
 {action&&!receipt&&<form className="space-y-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();setReview(true)}}><h3 className="font-semibold">{actions[action]}</h3><fieldset disabled={busy||uncertain||review||conflict} className="space-y-3"><label className="block text-sm">Fecha del movimiento<input className={control+' mt-1 block w-full'} aria-label="Fecha del movimiento" type="date" required min={minDate} max={today()} value={eventOn} onChange={e=>setEventOn(e.target.value)}/></label>{action==='equipment.replace'&&<><p className="text-xs text-slate-500">El equipo anterior quedará sustituido. El nuevo conservará sus vínculos con cliente, contrato, servicio y línea. No se copiará una permanencia al equipo nuevo.</p><EquipmentFacts manufacturer={manufacturer} model={model} description={description} purchasedOn={purchasedOn} setManufacturer={setManufacturer} setModel={setModel} setDescription={setDescription} setPurchasedOn={setPurchasedOn} maxDate={eventOn}/></>}</fieldset>{!review&&!uncertain&&<button className={primary} disabled={busy||conflict}>Revisar movimiento</button>}{review&&<div className="space-y-3 rounded-lg bg-amber-50 p-3"><p className="text-sm">Confirmar: {actions[action]} · {productDate(eventOn)}{action==='equipment.replace'?' · '+manufacturer.trim()+' '+model.trim():''}. El cambio quedará en el historial del equipo.</p><div className="flex flex-wrap gap-2"><button type="button" className={primary} disabled={busy} onClick={()=>void execute()}>{busy?'Guardando…':'Confirmar movimiento'}</button><button type="button" className={control} disabled={busy} onClick={()=>setReview(false)}>Volver a editar</button></div></div>}</form>}
 </>}
 <section className="space-y-3 border-t pt-4"><h3 className="font-semibold">Historial de movimientos</h3>{historyError?<p role="alert" className="text-sm text-red-700">{historyError}</p>:!history?<p role="status" className="text-sm text-slate-500">Consultando historial…</p>:!history.items.length?<p className="text-sm text-slate-500">No hay movimientos en esta página.</p>:<ol className="space-y-3">{history.items.map(e=><li key={e.version} data-equipment-event={e.version} className="border-l-2 border-indigo-100 pl-3"><p className="text-sm font-semibold">{e.operation==='equipment.create'?'Alta de equipo':actions[e.operation]}</p><p className="mt-1 text-xs text-slate-500">{productDate(e.event_on??e.created_at)} · {statusLabel(e.status)}</p>{e.related_equipment_id&&<Link className="text-xs text-indigo-700" href={`/equipment?id=${e.related_equipment_id}`}>Consultar equipo relacionado</Link>}</li>)}</ol>}<div className="flex justify-between gap-2"><button className={control} disabled={!history||!historyCursors.length} onClick={()=>{setHistory(null);setHistoryCursors(v=>v.slice(0,-1))}}>Movimientos anteriores</button><button className={control} disabled={!history?.next_version} onClick={()=>{if(history?.next_version){setHistory(null);setHistoryCursors(v=>[...v,history.next_version!])}}}>Más movimientos</button></div></section>
 </div></Drawer>
}
function EquipmentFacts({manufacturer,model,description,purchasedOn,setManufacturer,setModel,setDescription,setPurchasedOn,maxDate}:{manufacturer:string;model:string;description:string;purchasedOn:string;setManufacturer:(v:string)=>void;setModel:(v:string)=>void;setDescription:(v:string)=>void;setPurchasedOn:(v:string)=>void;maxDate:string}){return <>{[['Fabricante',manufacturer,setManufacturer],['Modelo',model,setModel],['Descripción comercial',description,setDescription]].map(([name,value,set])=><label key={name as string} className="block text-sm">{name as string}<input className={control+' mt-1 block w-full'} aria-label={name as string} required={name!=='Descripción comercial'} maxLength={name==='Descripción comercial'?200:100} value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}<label className="block text-sm">Fecha de compra<input className={control+' mt-1 block w-full'} aria-label="Fecha de compra" type="date" min="2000-01-01" max={maxDate} value={purchasedOn} onChange={e=>setPurchasedOn(e.target.value)}/></label></>}
function EquipmentCreate({customerId,onClose,onCreated}:{customerId:string;onClose:()=>void;onCreated:(id:string)=>void}){
 const {repository}=useProduct(),[kind,setKind]=useState<EquipmentKindV1>('router'),[manufacturer,setManufacturer]=useState(''),[model,setModel]=useState(''),[description,setDescription]=useState(''),[purchasedOn,setPurchasedOn]=useState(''),[assignedOn,setAssignedOn]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null)
 const pending=useRef<EquipmentInputsV1['equipment.create']|null>(null),inFlight=useRef(false),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain'
 async function execute(){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError(null);try{pending.current??=Object.freeze({command_id:crypto.randomUUID(),customer_id:customerId,contract_id:null,service_id:null,line_id:null,commitment_id:null,kind,manufacturer:manufacturer.trim(),model:model.trim(),commercial_description:description.trim()||null,purchased_on:purchasedOn||null,assigned_on:assignedOn||null});const r=await repository.telecom('equipment.create',pending.current);pending.current=null;onCreated(r.id)}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{inFlight.current=false;setBusy(false)}}
 return <Drawer title="Nuevo equipo del cliente" onClose={()=>{if(!busy&&!uncertain)onClose()}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();setReview(true)}}><p className="text-sm"><NamedCustomer id={customerId}/></p><p className="text-xs text-slate-500">Alta comercial del equipo para este cliente. La asociación a un servicio o línea requiere su contexto autorizado.</p>{error!==null&&<p role="alert" className="text-sm text-red-700">{safeMessage(error)}</p>}<fieldset disabled={busy||review||uncertain} className="space-y-3"><label className="block text-sm">Tipo de equipo<select aria-label="Tipo de equipo nuevo" className={control+' mt-1 block w-full'} value={kind} onChange={e=>setKind(e.target.value as EquipmentKindV1)}>{Object.entries(kinds).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><EquipmentFacts manufacturer={manufacturer} model={model} description={description} purchasedOn={purchasedOn} setManufacturer={setManufacturer} setModel={setModel} setDescription={setDescription} setPurchasedOn={setPurchasedOn} maxDate={assignedOn||today()}/><label className="block text-sm">Asignado desde (opcional)<input aria-label="Asignado desde" className={control+' mt-1 block w-full'} type="date" min={purchasedOn||'2000-01-01'} max={today()} value={assignedOn} onChange={e=>setAssignedOn(e.target.value)}/></label></fieldset>{uncertain?<button type="button" className={primary} disabled={busy} onClick={()=>void execute()}>Comprobar la misma alta</button>:review?<div className="space-y-3 rounded-lg bg-indigo-50 p-3"><p className="text-sm">{manufacturer.trim()} · {model.trim()} · {assignedOn?'Asignado desde '+productDate(assignedOn):'Preparado, pendiente de asignar'}.</p><div className="flex flex-wrap gap-2"><button type="button" className={primary} disabled={busy} onClick={()=>void execute()}>{busy?'Guardando…':'Confirmar alta de equipo'}</button><button type="button" className={control} disabled={busy} onClick={()=>setReview(false)}>Volver a editar</button></div></div>:<button className={primary}>Revisar alta</button>}</form></Drawer>
}
