'use client'
import {PortfolioCreate} from './PortfolioCreate'
import {SimHistory} from '@/features/sims/Sims'
import {customerCollectionIdentity,customerName} from '@/features/customers/customer-identity'
import {productDate} from '@/features/product/presentation'
import {OriginProof} from '@/features/product/integration/OriginProof'
import { useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import {AssigneeSelect}from '@/features/product/integration/AssigneeSelect'
import {TelecomPortfolioInventory} from './TelecomPortfolioInventory'
import {ImportJobs}from './ImportJobs'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { Drawer, control, primary, Status, PreviewNotice } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import type { PortfolioGetV1, PortfolioInputsV1, PortfolioOperationV1, PortfolioReceiptV1, PortfolioKindV1 } from '@/lib/contracts/portfolio-v1'
const labels={contract:'Contrato',service:'Servicio',line:'Línea',renewal:'Renovación',permanence:'Permanencia'}
type Item={value:PortfolioGetV1;label:string}
export function IntegratedPortfolio({initialReference}:{initialReference?:{kind:PortfolioKindV1;id:string}}){
 const {repository,role}=useProduct(),[query,setQuery]=useState(''),[items,setItems]=useState<Item[]>([]),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Item|null>(null),[creating,setCreating]=useState<Item|null>(null)
 useEffect(()=>{if(!initialReference)return;let active=true;void repository.portfolio(initialReference.kind,initialReference.id).then(value=>{if(active){const item={value,label:labels[value.kind]};setItems([item]);setSelected(item)}}).catch(e=>{if(active)setError(safeMessage(e))});return()=>{active=false}},[repository,initialReference])
 const canWrite=role!==null&&role!=='viewer'
 const searchEpoch=useRef(0),[readingItems,setReadingItems]=useState(false)
 useEffect(()=>()=>{searchEpoch.current++},[])
 const search=useCallback(async()=>{const epoch=++searchEpoch.current;setBusy(true);setReadingItems(false);setError('');setItems([]);setCustomers([]);try{const result=await repository.search(query);if(epoch!==searchEpoch.current)return;setCustomers(result.items.filter(i=>i.kind==='customer').map(i=>({id:i.id,name:i.label})));const refs=result.items.filter(i=>i.kind==='contract'||i.kind==='service'||i.kind==='line');setReadingItems(refs.length>0);setBusy(false);const found=await Promise.all(refs.map(async i=>({label:i.label,value:await repository.portfolio(i.kind as 'contract'|'service'|'line',i.id)})));if(epoch===searchEpoch.current)setItems(found)}catch(e){if(epoch===searchEpoch.current){setItems([]);setError(safeMessage(e))}}finally{if(epoch===searchEpoch.current){setBusy(false);setReadingItems(false)}}},[repository,query])
 async function saved(receipt:PortfolioReceiptV1){const kind=receipt.operation.startsWith('renewal.')||receipt.operation==='contract.record_renewal'?'renewal':receipt.operation.startsWith('permanence.')?'permanence':receipt.operation.startsWith('line.')?'line':receipt.operation.startsWith('service.')?'service':'contract';const value=await repository.portfolio(kind,receipt.id);setItems(current=>[...current.filter(i=>i.value.record.id!==receipt.id),{value,label:'display_name'in value.record?value.record.display_name??current.find(i=>i.value.record.id===receipt.id)?.label??labels[kind]:current.find(i=>i.value.record.id===receipt.id)?.label??labels[kind]}]);setSelected(null);setCreating(null)}
 return <div className="space-y-4"><PageHeader title="Cartera Telecom" description="Activos autorizados y plazos registrados"/><PreviewNotice/><TelecomPortfolioInventory/><section className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Consulta rápida y edición de activos</h2><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void search()}}><input aria-label="Consultar cartera local" required minLength={2} maxLength={100} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa o activo" className={control}/><button className={primary} disabled={busy}>Consultar cartera</button></form><p className="text-xs text-slate-500">Hasta cinco resultados por familia en cada búsqueda. No es el inventario completo. Operadores y tarifas requieren un catálogo de selección autorizado.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(i=><article data-portfolio-id={i.value.record.id} key={i.value.record.id} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{labels[i.value.kind]} · Origen: {{manual:'Manual',import:'Importado',integration:'Integración'}[i.value.record.source]}</p><h2 className="my-2 font-semibold">{i.label}</h2><Status value={i.value.record.status}/><div className="mt-3 flex flex-wrap gap-2"><button className={control} onClick={async()=>{try{setSelected({...i,value:await repository.portfolio(i.value.kind,i.value.record.id)})}catch(e){setError(safeMessage(e))}}}>Ver activo</button>{canWrite&&i.value.record.source==='manual'&&i.value.kind==='contract'&&['draft','active'].includes(i.value.record.status)&&<button className={control} onClick={()=>setCreating(i)}>Añadir servicio o plazo</button>}{canWrite&&i.value.record.source==='manual'&&i.value.kind==='service'&&['pending','active','suspended'].includes(i.value.record.status)&&<button className={control} onClick={()=>setCreating(i)}>Añadir línea</button>}</div></article>)}</div>{readingItems&&<p role="status" className="text-sm text-slate-500">Consultando los activos de esta búsqueda…</p>}{!items.length&&!busy&&!readingItems&&<p className="rounded-xl border bg-white p-5 text-sm text-slate-500">Consulta un cliente o activo para ver sus resultados.</p>}{canWrite&&customers.length>0&&items.some(i=>i.value.kind==='contract')&&<button className={control} onClick={()=>setCreating(items.find(i=>i.value.kind==='contract')!)}>Nuevo contrato manual</button>}</section>
 <ImportJobs/>
 {selected&&<PortfolioEditor item={selected} canWrite={canWrite} onClose={()=>setSelected(null)} onSaved={saved}/>} {creating&&<PortfolioCreate parent={creating} customers={customers} onClose={()=>setCreating(null)} onSaved={saved}/>}</div>
}
export function PortfolioEditor({item,canWrite,onClose,onSaved}:{item:Item;canWrite:boolean;onClose:()=>void;onSaved:(r:PortfolioReceiptV1)=>Promise<void>}){
 const {repository}=useProduct(),v=item.value,r=v.record,[name,setName]=useState('display_name'in r?r.display_name??'':''),[date,setDate]=useState('target_on'in r?r.target_on:'starts_on'in r?r.starts_on:'signed_date'in r?r.signed_date??'':''),[end,setEnd]=useState('ends_on'in r?r.ends_on:''),[targetStatus,setTargetStatus]=useState<'active'|'suspended'|'ended'|'cancelled'>(r.status==='active'?'suspended':'active'),[reason,setReason]=useState('customer_request'),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState<'save'|'cancel'|'resolve'|'dismiss'|null>(null)
 const [assignee,setAssignee]=useState(v.kind==='contract'?v.record.assigned_user_id??'':'')
 const [parentActive,setParentActive]=useState<boolean|null>(v.kind==='service'||v.kind==='line'?null:true)
 useEffect(()=>{if(v.kind!=='service'&&v.kind!=='line')return;let active=true;void(async()=>{try{let contractId:string,serviceActive=true;if(v.kind==='service')contractId=v.record.contract_id;else{const service=await repository.portfolio('service',v.record.service_id);if(service.kind!=='service')throw new ProductUiError('internal_safe');contractId=service.record.contract_id;serviceActive=service.record.status==='active'}const contract=await repository.portfolio('contract',contractId);if(contract.kind!=='contract')throw new ProductUiError('internal_safe');if(active)setParentActive(contract.record.status==='active'&&serviceActive)}catch(e){if(active){setParentActive(false);setError(e)}}})();return()=>{active=false}},[repository,v])

 const [receiptConfirmed,setReceiptConfirmed]=useState(false)
 const confirmed=useRef<PortfolioReceiptV1|null>(null),pending=useRef<{op:PortfolioOperationV1;input:PortfolioInputsV1[PortfolioOperationV1]}|null>(null),conflict=error instanceof ProductUiError&&error.code==='conflict',uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',editable=canWrite&&r.source==='manual'&&!['ended','cancelled','completed','dismissed'].includes(r.status)
 async function execute(action:'save'|'cancel'|'resolve'|'dismiss'){
  if(busy||conflict||!editable)return;setBusy(true);setError(null)
  try{if(!pending.current&&!confirmed.current){const b={command_id:crypto.randomUUID(),id:r.id,expected_version:r.version};let op:PortfolioOperationV1,input:PortfolioInputsV1[PortfolioOperationV1]
   if(v.kind==='contract'){op=action==='cancel'?'contract.cancel':'contract.activate';input=action==='cancel'?b:{...b,signed_date:date}}
   else if(v.kind==='service'||v.kind==='line'){op=v.kind==='service'?'service.transition':'line.transition';input={...b,status:action==='cancel'?'cancelled':targetStatus,effective_on:date}}
   else if(v.kind==='renewal'){op=action==='resolve'?'renewal.resolve':action==='dismiss'?'renewal.dismiss':'renewal.update';input=action==='save'?{...b,target_on:date,opens_on:v.record.opens_on,closes_on:v.record.closes_on}:{...b,reason_code:reason}}
   else{op=action==='cancel'?'permanence.cancel':'permanence.update';input=action==='cancel'?{...b,reason_code:reason}:{...b,starts_on:date,ends_on:end,reason_code:reason}}
   pending.current={op,input:Object.freeze(input)}
  }const receipt=confirmed.current??await repository.portfolioCommand(pending.current!.op,pending.current!.input);confirmed.current=receipt;setReceiptConfirmed(true);pending.current=null;await onSaved(receipt);confirmed.current=null;setReceiptConfirmed(false)}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
 }
 async function saveLabel(){if(busy||conflict||!editable)return;setBusy(true);setError(null);try{if(!pending.current&&!confirmed.current){const op=v.kind==='service'?'service.update_label':'line.update_label';pending.current={op,input:Object.freeze({command_id:crypto.randomUUID(),id:r.id,expected_version:r.version,display_name:name})}}const result=confirmed.current??await repository.portfolioCommand(pending.current!.op,pending.current!.input);confirmed.current=result;setReceiptConfirmed(true);pending.current=null;await onSaved(result);confirmed.current=null;setReceiptConfirmed(false)}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}}
 async function saveAssignment(){if(busy||conflict||!editable||v.kind!=='contract')return;setBusy(true);setError(null);try{if(!confirmed.current)pending.current??={op:'contract.update_allowed_metadata',input:Object.freeze({command_id:crypto.randomUUID(),id:r.id,expected_version:r.version,assigned_user_id:assignee||null})};const receipt=confirmed.current??await repository.portfolioCommand(pending.current!.op,pending.current!.input);confirmed.current=receipt;setReceiptConfirmed(true);pending.current=null;await onSaved(receipt);confirmed.current=null;setReceiptConfirmed(false)}catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}}
 const locked=busy||uncertain||conflict||receiptConfirmed||!editable
 return <Drawer title={`${labels[v.kind]}: ${item.label}`} onClose={()=>{if(!busy&&!uncertain)onClose()}}><div className="space-y-4"><Status value={r.status}/>{v.kind==='service'&&<Link className="text-sm font-semibold text-indigo-700" href={'/services/'+r.id}>Instalación y componentes del servicio</Link>}<p className="text-sm">Origen: {{manual:'Manual',import:'Importado',integration:'Integración'}[r.source]}</p><OriginProof kind={v.kind} id={r.id}/>{v.kind==='line'&&<SimHistory key={r.id} lineId={r.id}/>}{'customer_id'in r&&<Link className={control} href={`/clients/${r.customer_id}`}>Ver cliente</Link>}{'start_date'in r&&<p className="text-sm">Inicio: {productDate(r.start_date)} · Firma: {r.signed_date?productDate(r.signed_date):'Pendiente'}</p>}{'target_on'in r&&<p className="text-sm">Ventana: {r.opens_on?productDate(r.opens_on):'Sin apertura'} — {r.closes_on?productDate(r.closes_on):'Sin cierre'}</p>}{'contract_id'in r&&<p className="text-xs text-slate-500">Vinculado al contrato autorizado; la relación no se puede sustituir.</p>}{'commitment_kind'in r&&<p className="text-sm">Compromiso: {({minimum_term:'Plazo mínimo',device:'Dispositivo',subsidy:'Subvención',discount:'Descuento'} as Record<string,string>)[r.commitment_kind]??'Otro compromiso'}</p>}
 {!editable&&<p className="rounded-lg bg-amber-50 p-3 text-sm">{r.source==='manual'?(canWrite?'Activo cerrado. Consulta de solo lectura.':'Consulta de solo lectura para tu rol.'):'Consulta de solo lectura. Los hechos importados o integrados conservan su procedencia.'}</p>}
 <PortfolioAncestry value={v}/><fieldset disabled={locked} className="space-y-3">{(v.kind==='service'||v.kind==='line')&&<><label className="block text-sm">Nombre del activo<input className={`${control} w-full`} value={name} maxLength={160} onChange={e=>setName(e.target.value)}/></label><button className={control} disabled={locked} onClick={saveLabel}>Guardar nombre</button><label className="block text-sm">Estado del activo<select aria-label="Estado del activo" className={control} value={targetStatus} onChange={e=>setTargetStatus(e.target.value as typeof targetStatus)}>{(r.status==='pending'?['active','cancelled']:r.status==='active'?['suspended','ended']:r.status==='suspended'?['active','ended']:[]).map(s=><option key={s} value={s} disabled={s==='active'&&parentActive!==true}>{{active:'Activo',suspended:'Suspendido',ended:'Finalizado',cancelled:'Cancelado'}[s]}</option>)}</select></label></>}
 {v.kind==='contract'&&<div className="space-y-2"><AssigneeSelect allowClear value={assignee} onChange={setAssignee} disabled={locked}/><button className={control} disabled={locked} onClick={()=>void saveAssignment()}>Guardar responsable del contrato</button></div>}
 <label className="block text-sm">{v.kind==='contract'?'Fecha de firma':v.kind==='renewal'?'Fecha objetivo':v.kind==='permanence'?'Inicio del compromiso':'Fecha efectiva'}<input className={`${control} w-full`} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{v.kind==='permanence'&&<label className="block text-sm">Fin del compromiso<input type="date" className={`${control} w-full`} value={end} onChange={e=>setEnd(e.target.value)}/></label>}{(v.kind==='renewal'||v.kind==='permanence')&&<label className="block text-sm">Motivo del cambio<select className={control} value={reason} onChange={e=>setReason(e.target.value)}><option value="customer_request">Solicitud del cliente</option><option value="completed">Gestión completada</option><option value="correction">Corrección</option></select></label>}</fieldset>
 {(v.kind==='service'||v.kind==='line')&&parentActive!==true&&<p className="text-sm text-amber-800">{parentActive===null?'Consultando los activos vinculados…':v.kind==='service'?'Activa el contrato vinculado antes de activar este servicio.':'Activa el servicio y el contrato vinculados antes de activar esta línea.'}</p>}
 {!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}{conflict&&<button className={control} onClick={onClose}>Cerrar y recargar el activo</button>}{(uncertain||receiptConfirmed)&&<button className={primary} disabled={busy} onClick={()=>execute('save')}>{receiptConfirmed?'Consultar el cambio registrado':'Reintentar la misma acción'}</button>}{editable&&!uncertain&&<div className="flex flex-wrap gap-2">{(v.kind!=='contract'||r.status==='draft')&&<button className={primary} disabled={locked||!date||(v.kind==='service'||v.kind==='line')&&targetStatus==='active'&&parentActive!==true} onClick={()=>setConfirm('save')}>{v.kind==='contract'?'Activar contrato':'Guardar cambio'}</button>}{v.kind==='renewal'?<><button className={control} disabled={locked} onClick={()=>setConfirm('resolve')}>Resolver renovación</button><button className={control} disabled={locked} onClick={()=>setConfirm('dismiss')}>Descartar renovación</button></>:(v.kind==='contract'||v.kind==='permanence')&&<button className={control} disabled={locked} onClick={()=>setConfirm('cancel')}>Cancelar activo</button>}</div>}<p className="text-xs text-slate-500">Selección completa de responsables y tarifas pendiente del catálogo. Las fechas se conservan como fechas civiles.</p><ConfirmDialog open={confirm!==null} title="Confirmar cambio de cartera" description="Se guardará la acción elegida sobre la versión consultada." loading={busy} error={error?safeMessage(error):undefined} onConfirm={()=>execute(confirm??'save')} onCancel={()=>{if(!busy)setConfirm(null)}}/></div></Drawer>
}

function PortfolioAncestry({value}:{value:PortfolioGetV1}){
 const {repository}=useProduct(),[state,setState]=useState<{key:string;refs:{kind:'customer'|'contract'|'service';id:string;label:string}[];error:string}|null>(null),key=value.kind+':'+value.record.id
 useEffect(()=>{let active=true;void(async()=>{const refs:{kind:'customer'|'contract'|'service';id:string;label:string}[]=[];let item=value
  if(item.kind==='line'){const parent=await repository.portfolio('service',item.record.service_id);if(parent.kind!=='service')throw new ProductUiError('internal_safe');refs.unshift({kind:'service',id:parent.record.id,label:parent.record.display_name});item=parent}
  if(item.kind==='service'||item.kind==='renewal'||item.kind==='permanence'){const parent=await repository.portfolio('contract',item.record.contract_id);if(parent.kind!=='contract')throw new ProductUiError('internal_safe');refs.unshift({kind:'contract',id:parent.record.id,label:'Contrato vinculado'});item=parent}
  if(item.kind==='contract'){const customer=await customerCollectionIdentity(repository,item.record.customer_id);refs.unshift({kind:'customer',id:customer.id,label:customerName(customer)})}
  if(active)setState({key,refs,error:''})
 })().catch(e=>{if(active)setState({key,refs:[],error:safeMessage(e)})});return()=>{active=false}},[repository,value,key])
 return <section className="space-y-2 rounded-lg bg-slate-50 p-3"><h3 className="text-sm font-semibold">Relaciones del activo</h3>{state?.key!==key?<p role="status" className="text-xs text-slate-500">Consultando vínculos autorizados…</p>:state.error?<p role="alert" className="text-xs text-red-700">{state.error}</p>:<nav aria-label="Relaciones del activo" className="flex flex-col gap-2">{state.refs.map(r=><Link key={r.kind+':'+r.id} href={r.kind==='customer'?'/clients/'+r.id:'/portfolio?kind='+r.kind+'&id='+r.id} className="text-sm font-medium text-indigo-700">{r.label}</Link>)}</nav>}</section>
}
