'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {Plus,Play,Pause,Zap} from 'lucide-react'
import {PageHeader} from '@/components/PageHeader'
import {ConfirmDialog} from '@/components/ConfirmDialog'
import {useProduct} from '@/features/product/integration/Provider'
import {AssigneeSelect} from '@/features/product/integration/AssigneeSelect'
import {ProductUiError,safeMessage,type AutomationRecord,type AutomationRead,type AutomationReceipt} from '@/features/product/integration/repository'
import type {AutomationDefinitionV1,AutomationInputV1,AutomationOperationV1} from '@/lib/contracts/automations-v1'
import {PreviewNotice,Drawer,control,primary,Empty,Unavailable} from '@/features/product/ui'
type Page=Extract<AutomationRead,{operation:'automation.list'}>
type History=Extract<AutomationRead,{operation:'automation.run_history'}>
type Intent={operation:AutomationOperationV1;input:AutomationInputV1;receipt?:AutomationReceipt}
const actions={'notification.create':'Crear aviso interno','task.create':'Crear tarea de seguimiento'}
const failures={action_denied:'Acción no autorizada',action_conflict:'El registro cambió',action_invalid:'Datos no válidos',action_unavailable:'Acción no disponible',target_unavailable:'Registro no disponible'}
export function IntegratedAutomations(){
 const {repository,role,actorId}=useProduct(),allowed=role==='owner'||role==='admin'
 const [cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[state,setState]=useState<{key:string;data?:Page;error?:string}|null>(null),[selected,setSelected]=useState<string|null>(null),[historyCursors,setHistoryCursors]=useState<string[]>([]),[detail,setDetail]=useState<{key:string;record?:AutomationRecord;history?:History;error?:string}|null>(null)
 const [editor,setEditor]=useState<{record?:AutomationRecord}|null>(null),[confirm,setConfirm]=useState<Intent|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[processResult,setProcessResult]=useState<Extract<AutomationReceipt,{operation:'automation.process_pending'}>|null>(null),intent=useRef<Intent|null>(null)
 const key=JSON.stringify([cursors.at(-1)??null,revision]),detailKey=JSON.stringify([selected,historyCursors.at(-1)??null,revision]),page=state?.key===key?state.data:undefined,current=detail?.key===detailKey?detail:undefined,locked=busy||uncertain
 useEffect(()=>{if(!allowed)return;let active=true;void repository.automation('automation.list',{limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(data=>{if(active)setState({key,data})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,allowed,cursors,key])
 useEffect(()=>{if(!allowed||!selected)return;let active=true;void Promise.all([repository.automation('automation.get',{id:selected}),repository.automation('automation.run_history',{id:selected,limit:20,...(historyCursors.length?{after_id:historyCursors.at(-1)}:{})})]).then(([v,history])=>{if(active)setDetail({key:detailKey,record:v.record,history})}).catch(e=>{if(active)setDetail({key:detailKey,error:safeMessage(e)})});return()=>{active=false}},[repository,allowed,selected,historyCursors,detailKey])
 async function run(next:Intent){if(busy)return;intent.current=next;setBusy(true);setError('');setNotice('');try{const receipt=next.receipt??await repository.automationCommand(next.operation,next.input);next.receipt=receipt
  if(receipt.operation==='automation.process_pending'){await repository.automation('automation.list',{limit:20});setProcessResult(receipt);setNotice('Procesamiento terminado.');window.dispatchEvent(new Event('crm-notifications-changed'))}
  else{const fresh=await repository.automation('automation.get',{id:receipt.id});if(fresh.record.version<receipt.version)throw new ProductUiError('internal_safe');setSelected(receipt.id);setNotice('Regla guardada y comprobada.')}
  intent.current=null;setUncertain(false);setEditor(null);setConfirm(null);setCursors([]);setHistoryCursors([]);setState(null);setDetail(null);setRevision(v=>v+1)
 }catch(e){setError(next.receipt?'Cambio guardado. Falta consultar el resultado actualizado.':safeMessage(e));const retry=!!next.receipt||e instanceof ProductUiError&&e.code==='transport_uncertain';setUncertain(retry);if(!retry){intent.current=null;if(e instanceof ProductUiError&&['conflict','access_denied','not_found'].includes(e.code)){setDetail(null);setState(null);setRevision(v=>v+1)}}}finally{setBusy(false)}}
 function prepare(operation:AutomationOperationV1,fields:Record<string,unknown>={}){if(locked)return;setError('');setConfirm({operation,input:Object.freeze({command_id:crypto.randomUUID(),...fields})})}
 const retry=<button type="button" className={control} disabled={busy} onClick={()=>{if(intent.current)void run(intent.current)}}>Comprobar la misma acción</button>
 if(!allowed)return <div className="space-y-4"><PageHeader title="Automatizaciones internas" description="Reglas y seguimiento del equipo."/><Unavailable title="Acceso restringido">La gestión de reglas requiere un responsable del espacio.</Unavailable></div>
 return <div className="space-y-4"><PageHeader title="Automatizaciones internas" description="Reglas registradas para nuevos clientes; acciones internas con resultados verificables." action={<button className={primary} disabled={locked} onClick={()=>{setEditor({});setError('')}}><Plus size={16}/>Nueva regla</button>}/><PreviewNotice/>
 <section className="flex flex-wrap items-start justify-between gap-3 rounded-xl border bg-white p-4"><div className="max-w-2xl"><h2 className="flex items-center gap-2 text-sm font-semibold"><Zap size={16}/>Procesamiento explícito</h2><p className="mt-2 text-sm text-slate-500">Las reglas activas se aplican a los nuevos clientes cuando procesas sus eventos pendientes. No hay un programador periódico ni conexiones externas.</p></div><div className="flex flex-wrap gap-2"><button className={control} disabled={locked} onClick={()=>{setState(null);setDetail(null);setRevision(v=>v+1)}}>Actualizar reglas</button><button className={primary} disabled={locked||!page} onClick={()=>prepare('automation.process_pending')}><Play size={14}/>Procesar eventos pendientes</button></div></section>
 {error&&!editor&&!confirm&&<p role="alert" className="text-sm text-red-700">{error}</p>}{uncertain&&!editor&&!confirm&&retry}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}
 {processResult&&<section aria-label="Resultado del procesamiento" className="rounded-xl border border-indigo-100 bg-indigo-50 p-4"><h2 className="font-semibold">Resultado comprobado</h2><dl className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Procesadas',processResult.processed],['Correctas',processResult.succeeded],['Fallidas',processResult.failed],['Omitidas',processResult.skipped]].map(([label,n])=><div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-lg font-semibold">{n}</dd></div>)}</dl><p className="mt-3 text-xs text-slate-600">{processResult.has_more?'Hay más eventos pendientes. Puedes procesar el siguiente lote.':'No quedan eventos pendientes en la revisión comprobada.'} Las ejecuciones fallidas son terminales; no se reintentan automáticamente.</p></section>}
 <div className="grid min-w-0 gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><section aria-label="Reglas internas" className="space-y-3">{state?.key===key&&state.error?<p role="alert" className="text-sm text-red-700">{state.error}</p>:!page?<p role="status" className="text-sm text-slate-500">Cargando reglas…</p>:!page.items.length?<Empty text="No hay reglas en esta página."/>:page.items.map(r=><article data-automation-id={r.id} key={r.id} className="space-y-3 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="break-words font-semibold">{r.name}</h2><span className={`rounded-full px-2 py-1 text-xs ${r.enabled?'bg-emerald-50 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{r.enabled?'Activa':'Pausada'}</span></div><p className="text-sm text-slate-500">Nuevo cliente → {actions[r.action.action_id]}</p><p className="text-xs text-slate-500">{r.condition.account_kind===null?'Todas las empresas':r.condition.account_kind==='legal_entity'?'Solo personas jurídicas':'Solo autónomos'} · Responsable {r.action.recipient_user_id===actorId?'tú':r.action.recipient_user_id.slice(0,8)}</p><div className="flex flex-wrap gap-2"><button className={control} disabled={locked} onClick={()=>{setSelected(r.id);setHistoryCursors([]);setDetail(null)}}>Ver regla e historial</button><button className={control} disabled={locked||r.enabled} title={r.enabled?'Pausa la regla antes de editarla':undefined} onClick={()=>{setEditor({record:r});setError('')}}>Editar regla</button><button className={control} disabled={locked} onClick={()=>prepare(r.enabled?'automation.disable':'automation.enable',{id:r.id,expected_version:r.version})}>{r.enabled?<Pause size={14} className="inline mr-1"/>:<Play size={14} className="inline mr-1"/>}{r.enabled?'Pausar regla':'Activar regla'}</button></div></article>)}<div className="flex flex-wrap items-center gap-2"><button className={control} disabled={locked||!page||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Reglas anteriores</button><span className="text-xs text-slate-500">Página {cursors.length+1} · Hasta 20 reglas</span><button className={control} disabled={locked||!page?.next_id} onClick={()=>{if(page?.next_id)setCursors(v=>[...v,page.next_id!])}}>Más reglas</button></div></section>
 <section aria-label="Detalle e historial de regla" className="space-y-3 rounded-xl border bg-white p-4">{!selected?<Empty text="Selecciona una regla para consultar sus resultados."/>:current?.error?<p role="alert" className="text-sm text-red-700">{current.error}</p>:!current?.record?<p role="status" className="text-sm text-slate-500">Consultando regla e historial autorizado…</p>:<><h2 className="font-semibold">{current.record.name}</h2><p className="text-sm text-slate-500">{actions[current.record.action.action_id]} · {current.record.enabled?'Activa para eventos futuros':'Pausada'}</p><h3 className="border-t pt-3 text-sm font-semibold">Historial de ejecuciones</h3>{!current.history?.items.length?<p className="text-sm text-slate-500">No hay ejecuciones en esta página.</p>:<ul className="space-y-3">{current.history.items.map(r=><li data-automation-run-id={r.id} key={r.id} className="space-y-2 rounded-lg border p-3"><p className="text-sm font-medium">{r.status==='succeeded'?'Acción completada':r.status==='failed'?'Acción fallida':'Acción omitida'}</p><p className="text-xs text-slate-500">{actions[r.action_id]} · {new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Madrid'}).format(new Date(r.created_at))}</p>{r.failure_code&&<p className="text-xs text-red-700">{failures[r.failure_code as keyof typeof failures]??'No disponible'}</p>}{r.status==='succeeded'&&r.effect_id&&(r.action_id==='task.create'?<Link className="text-sm font-semibold text-indigo-700" href={'/calendar?task='+r.effect_id}>Abrir tarea creada</Link>:<button className="text-sm font-semibold text-indigo-700" onClick={()=>window.dispatchEvent(new Event('crm-notifications-open'))}>Abrir tus notificaciones</button>)}</li>)}</ul>}<div className="flex flex-wrap items-center gap-2"><button className={control} disabled={locked||!current.history||!historyCursors.length} onClick={()=>setHistoryCursors(v=>v.slice(0,-1))}>Ejecuciones anteriores</button><span className="text-xs text-slate-500">Hasta 20 por página</span><button className={control} disabled={locked||!current.history?.next_id} onClick={()=>{if(current.history?.next_id)setHistoryCursors(v=>[...v,current.history!.next_id!])}}>Más ejecuciones</button></div></>}
 </section></div>
 <ConfirmDialog open={!!confirm} title={confirm?.operation==='automation.process_pending'?'Procesar eventos internos':confirm?.operation==='automation.enable'?'Activar regla':'Pausar regla'} description={confirm?.operation==='automation.process_pending'?'Aplicará las reglas activas y podrá crear tareas y avisos internos. Hasta 100 acciones por lote; no ejecuta proveedores externos.':confirm?.operation==='automation.enable'?'Se aplicará solo a nuevos eventos desde su activación. No reejecuta el historial.':'La regla dejará de procesar nuevos eventos.'} loading={busy} error={error} onConfirm={()=>{if(confirm)void run(intent.current??confirm)}} onCancel={()=>{if(!locked){setConfirm(null);setError('')}}}/>
 {editor&&<AutomationEditor record={editor.record} busy={locked} error={error} retry={uncertain?retry:null} onClose={()=>{if(!locked){setEditor(null);setError('')}}} onSave={definition=>void run({operation:editor.record?'automation.update':'automation.create',input:Object.freeze({command_id:crypto.randomUUID(),...(editor.record?{id:editor.record.id,expected_version:editor.record.version}:{}),...definition})})}/>}
 </div>
}
function AutomationEditor({record,busy,error,retry,onClose,onSave}:{record?:AutomationRecord;busy:boolean;error:string;retry:React.ReactNode;onClose:()=>void;onSave:(definition:AutomationDefinitionV1)=>void}){
 const {actorId}=useProduct(),[name,setName]=useState(record?.name??''),[kind,setKind]=useState<''|'legal_entity'|'sole_trader'>(record?.condition.account_kind??''),[action,setAction]=useState(record?.action.action_id??'notification.create'),[recipient,setRecipient]=useState(record?.action.recipient_user_id??actorId??'')
 return <Drawer title={record?'Editar regla interna':'Nueva regla interna'} onClose={onClose}><form className="space-y-4" onSubmit={e=>{e.preventDefault();onSave({name:name.trim(),trigger_id:'customer.created',condition:{account_kind:kind||null},action:{action_id:action,recipient_user_id:recipient}})}}><p className="text-sm text-slate-500">Las reglas se guardan pausadas. Actívalas después de revisar la condición, acción y responsable.</p><fieldset className="space-y-4" disabled={busy}><label className="block text-sm">Nombre de regla<input aria-label="Nombre de regla" className={`${control} mt-1 w-full`} maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/></label><div className="rounded-lg bg-slate-50 p-3 text-sm">Cuando: Se crea un nuevo cliente</div><label className="block text-sm">Tipo de cliente<select aria-label="Tipo de cliente para regla" className={`${control} mt-1 w-full`} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="">Cualquier tipo</option><option value="legal_entity">Persona jurídica</option><option value="sole_trader">Autónomo</option></select></label><label className="block text-sm">Acción interna<select aria-label="Acción interna" className={`${control} mt-1 w-full`} value={action} onChange={e=>setAction(e.target.value as typeof action)}>{Object.entries(actions).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><AssigneeSelect value={recipient} onChange={setRecipient} disabled={busy}/></fieldset>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{retry}<button className={primary} disabled={busy||!recipient||!name.trim()}>Guardar regla pausada</button></form></Drawer>
}
