'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, CalendarDays, Clock, RefreshCw } from 'lucide-react'
import { PageHeader } from '@/components/PageHeader'
import { SectionCard } from '@/components/SectionCard'
import { Kpis, PreviewNotice, PeriodSelect, control, primary, Status } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { safeMessage } from '@/features/product/integration/repository'
import { addDays, calendarDate, periods, type Period } from '@/features/product/model'
import type { DashboardV2 } from '@/lib/contracts/product-dashboard-v2'
import type { CalendarPageV1, CalendarEntryV1 } from '@/lib/contracts/product-queries-v1'
const periodLabels = {customers_created:'Clientes creados',tasks_due:'Tareas con vencimiento',meetings_scheduled:'Reuniones programadas',renewals_due:'Renovaciones previstas',permanences_due:'Permanencias que terminan',opportunities_closed:'Oportunidades cerradas'}
const kindLabels={task:'Tarea',meeting:'Reunión',renewal:'Renovación',permanence:'Permanencia'}
const financialLabels={issued_minor:'Emitido',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'}
const financialKeys=['issued_minor','paid_minor','outstanding_minor','overdue_minor'] as const
const money=(n:number,currency:string)=>new Intl.NumberFormat('es-ES',{style:'currency',currency}).format(n/100)
const date=(day:string)=>new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeZone:'Europe/Madrid'}).format(new Date(`${day}T12:00:00Z`))
export function IntegratedDashboard() {
 const {repository,role,actorId}=useProduct()
 const [audience,setAudience]=useState<'my'|'workspace'>('my'),[period,setPeriod]=useState<Period>('month'),[reload,setReload]=useState(0)
 const [today]=useState(()=>calendarDate(new Date().toISOString()))
 const [state,setState]=useState<{data:DashboardV2|null;error:string;loading:boolean}>({data:null,error:'',loading:true})
 const [agenda,setAgenda]=useState<{data:CalendarPageV1|null;error:string;loading:boolean}>({data:null,error:'',loading:true})
 useEffect(()=>{const query=new URLSearchParams(window.location.search),p=query.get('period');if(periods.some(v=>v.value===p))queueMicrotask(()=>setPeriod(p as Period))},[])
 useEffect(()=>{let current=true;queueMicrotask(()=>{if(current)setState({data:null,error:'',loading:true})});void repository.dashboard({audience,period}).then(data=>{if(current)setState({data,error:'',loading:false})}).catch(e=>{if(current)setState({data:null,error:safeMessage(e),loading:false})});return()=>{current=false}},[repository,audience,period,reload])
 useEffect(()=>{let current=true;queueMicrotask(()=>{if(current)setAgenda({data:null,error:'',loading:true})});if(audience==='my'&&!actorId)return
  void repository.calendar({range_start:`${addDays(today,-7)}T00:00:00Z`,range_end:`${addDays(today,32)}T00:00:00Z`,limit:100,...(audience==='my'?{assigned_user_id:actorId!}:{})}).then(data=>{if(current)setAgenda({data,error:'',loading:false})}).catch(e=>{if(current)setAgenda({data:null,error:safeMessage(e),loading:false})});return()=>{current=false}
 },[repository,audience,actorId,today,reload])
 function changePeriod(value:Period){setPeriod(value);const url=new URL(window.location.href);url.searchParams.set('period',value);window.history.replaceState(null,'',url.pathname+url.search)}
 const data=state.data,entries=agenda.data?.items??[],active=entries.filter(e=>['pending','in_progress','scheduled','open'].includes(e.status))
 const dayOf=(e:CalendarEntryV1)=>e.date??calendarDate(e.at)
 const meetings=active.filter(e=>e.kind==='meeting'&&dayOf(e)===today),tasks=active.filter(e=>e.kind==='task'),deadlines=active.filter(e=>e.kind==='renewal'||e.kind==='permanence')
 function rows(items:readonly CalendarEntryV1[],empty:string){return <div className="space-y-2">{items.slice(0,6).map(e=><Link key={`${e.kind}:${e.id}`} href={e.customer_id?`/clients/${e.customer_id}`:'/calendar'} className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 p-3 hover:border-indigo-200 hover:bg-indigo-50/40"><div className="min-w-0"><p className="break-words text-sm font-medium text-slate-800">{e.title}</p><p className="mt-1 text-xs text-slate-500">{kindLabels[e.kind]} · {date(dayOf(e))}{!e.all_day&&` · ${new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Madrid'}).format(new Date(e.at))}`}</p></div><Status value={e.status}/></Link>)}{!items.length&&<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">{empty}</p>}{items.length>6&&<Link href="/calendar" className="inline-flex text-xs font-semibold text-indigo-600">Ver agenda completa <ArrowRight className="ml-1 h-3 w-3"/></Link>}</div>}
 return <div className="space-y-5"><PageHeader title="Dashboard telecom" description="Tu cartera, la actividad comercial y el siguiente paso" action={<Link className={primary} href="/assistant">Consultar al asistente <ArrowRight className="h-4 w-4"/></Link>}/><PreviewNotice/>
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3"><div className="flex flex-wrap items-center gap-3"><select className={control} aria-label="Ámbito del dashboard" value={audience} onChange={e=>setAudience(e.target.value as typeof audience)}><option value="my">Mi actividad</option>{['owner','admin'].includes(role??'')&&<option value="workspace">Todo el espacio</option>}</select><PeriodSelect value={period} onChange={changePeriod}/></div><button className={`${control} inline-flex items-center gap-2`} disabled={state.loading} onClick={()=>setReload(v=>v+1)}><RefreshCw className="h-4 w-4"/>Actualizar</button></div>
  {state.error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{state.error}</p>}{state.loading&&<p role="status" className="rounded-lg bg-slate-100 p-4">Cargando métricas…</p>}
  {data&&<><Kpis items={[{label:'Clientes',value:data.snapshot_counts.customers},{label:'Contratos',value:data.snapshot_counts.contracts},{label:'Servicios',value:data.snapshot_counts.services},{label:'Líneas',value:data.snapshot_counts.lines},{label:'Oportunidades',value:data.snapshot_counts.opportunities},{label:'Tareas',value:data.snapshot_counts.tasks},{label:'Renovaciones',value:data.snapshot_counts.renewals},{label:'Permanencias',value:data.snapshot_counts.permanences,tone:'text-amber-700'}].map(v=>({...v,note:'Cartera actual · ámbito seleccionado'}))}/>
   <SectionCard title="Rendimiento del periodo" description={`${data.audience==='my'?'Mi actividad':'Todo el espacio'} · ${data.period.start?`${date(data.period.start)} — ${date(addDays(data.period.end_exclusive!,-1))}`:'Todo el histórico'}`}><Kpis items={Object.entries(data.period_counts).map(([key,value])=>({label:periodLabels[key as keyof typeof periodLabels],value}))}/></SectionCard>
   <SectionCard title="Facturación" description={`${data.audience==='my'?'Facturas creadas por ti':'Facturas del espacio'} · mismo periodo seleccionado · cada moneda por separado`}>{data.financial_status==='unavailable'?<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Información financiera no disponible para tu rol.</p>:<div className="grid gap-4 xl:grid-cols-2">{data.financial?.currencies.map(c=><section key={c.currency} aria-label={`Facturación ${c.currency}`} className="rounded-lg border border-slate-100 p-4"><h3 className="mb-3 font-semibold text-slate-700">{c.currency}</h3><Kpis items={financialKeys.map(key=>({label:financialLabels[key],value:money(c[key],c.currency)}))}/><div className="mt-4 space-y-2">{financialKeys.map(key=><div key={key}><div className="mb-1 flex justify-between gap-3 text-xs"><span>{financialLabels[key]}</span><span>{money(c[key],c.currency)}</span></div><div aria-hidden="true" className="h-2 overflow-hidden rounded bg-slate-100"><div className={`h-full rounded ${key==='overdue_minor'?'bg-amber-500':'bg-indigo-500'}`} style={{width:`${100*c[key]/Math.max(1,c.issued_minor,c.paid_minor,c.outstanding_minor,c.overdue_minor)}%`}}/></div></div>)}</div><p className="mt-3 text-xs text-slate-500">Vencido está incluido en Pendiente. Las categorías no se suman.</p></section>)}{!data.financial?.currencies.length&&<p className="text-sm text-slate-500">No hay facturas emitidas en este ámbito y periodo.</p>}</div>}</SectionCard>
  </>}
  <section aria-label="Acciones rápidas" className="flex flex-wrap items-center gap-2 rounded-xl bg-indigo-950 p-4"><span className="mr-2 text-sm font-semibold text-white">Tu siguiente paso</span>{[['/clients','Clientes'],['/calendar','Agenda y tareas'],['/opportunities','Pipeline'],['/portfolio','Cartera'],...(role==='owner'||role==='admin'?[['/facturacion','Facturación']]:[])].map(([href,label])=><Link key={href} href={href} className="rounded-lg border border-indigo-700 bg-indigo-900 px-3 py-2 text-sm text-white hover:bg-indigo-800">{label}</Link>)}</section>
  <div><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="flex items-center gap-2 font-semibold text-slate-900"><CalendarDays className="h-5 w-5 text-indigo-600"/>Agenda operativa</h2><span className="text-xs text-slate-500">{audience==='my'?'Asignada a ti':'Todo el espacio'} · Europe/Madrid · ventana de 39 días</span></div>{agenda.loading&&<p role="status">Consultando agenda…</p>}{agenda.error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{agenda.error}</p>}{agenda.data&&<><div className="grid gap-4 xl:grid-cols-3"><SectionCard title="Reuniones de hoy" description={date(today)}>{rows(meetings,'No hay reuniones programadas hoy en esta consulta.')}</SectionCard><SectionCard title="Tareas y seguimiento" description="Pendientes y en curso · ordenadas por vencimiento">{rows(tasks,'No hay tareas abiertas con fecha en esta consulta.')}</SectionCard><SectionCard title="Renovaciones y permanencias" description="Plazos próximos y pendientes de la ventana">{rows(deadlines,'No hay plazos abiertos en esta consulta.')}</SectionCard></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-7">{Array.from({length:7},(_,i)=>addDays(today,i)).map(day=><Link key={day} href="/calendar" className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold text-slate-700">{day===today?'Hoy':new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',timeZone:'Europe/Madrid'}).format(new Date(`${day}T12:00:00Z`))}</p><p className="mt-2 text-sm text-slate-500">{active.filter(e=>dayOf(e)===day&&e.kind==='meeting').length} reuniones</p><p className="text-sm text-slate-500">{active.filter(e=>dayOf(e)===day&&e.kind==='task').length} tareas</p></Link>)}</div><p className="mt-2 text-xs text-slate-500">{agenda.data.next?'Vista parcial: primeros 100 registros. Consulta las siguientes páginas en Agenda.':'Registros con fecha de la ventana consultada. Las tareas sin fecha no forman parte de esta agenda.'}</p></>}</div>
  {data&&<SectionCard title="Actividad reciente" description="Últimos 20 eventos del ámbito · independiente del periodo"><div className="grid gap-x-6 md:grid-cols-2">{data.recent_activity.map(a=><div key={a.id} className="flex items-start gap-3 border-b border-slate-100 py-3"><Clock className="mt-1 h-4 w-4 shrink-0 text-slate-400"/><div><p className="text-sm font-medium text-slate-700">{{'entity.created':'Registro creado','entity.updated':'Registro actualizado','entity.contacted':'Contacto registrado','entity.status_changed':'Estado modificado','system.imported':'Importación registrada','system.synchronized':'Sincronización registrada'}[a.summary_code]??'Actividad registrada'}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Madrid'}).format(new Date(a.occurred_at))}</p>{a.customer_id&&<Link href={`/clients/${a.customer_id}`} className="mt-1 inline-block text-xs font-semibold text-indigo-600">Abrir cliente</Link>}</div></div>)}</div>{!data.recent_activity.length&&<p className="text-sm text-slate-500">Sin eventos en esta consulta.</p>}</SectionCard>}
 </div>
}
