import {isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import {snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import {exact,natural,instant}from './notifications-runtime-v1.ts'
import type {AutomationOperationV1,AutomationInputV1,AutomationReadInputV1}from '../contracts/automations-v1'
export const AUTOMATIONS_RPC_V1={'automation.create':'automation_v1_create','automation.update':'automation_v1_update','automation.enable':'automation_v1_enable','automation.disable':'automation_v1_disable','automation.process_pending':'automation_v1_process_pending'}as const
export function isAutomationOperationV1(v:unknown):v is AutomationOperationV1{return typeof v==='string'&&Object.hasOwn(AUTOMATIONS_RPC_V1,v)}
const definition=(v:Record<string,unknown>)=>typeof v.name==='string'&&[...v.name].length>=1&&[...v.name].length<=100&&v.name===v.name.trim()&&!/[\x00-\x1f\x7f]/.test(v.name)&&v.trigger_id==='customer.created'&&plain(v.condition)&&exact(v.condition,'account_kind')&&(v.condition.account_kind===null||['legal_entity','sole_trader'].includes(v.condition.account_kind as string))&&plain(v.action)&&exact(v.action,'action_id,recipient_user_id')&&['notification.create','task.create'].includes(v.action.action_id as string)&&uuid(v.action.recipient_user_id)
export function parseAutomationInputV1(op:AutomationOperationV1,value:unknown):AutomationInputV1|null{try{const v=snapshotProductJsonV1(value);if(!isAutomationOperationV1(op)||!plain(v)||!uuid(v.command_id))return null;const expected=op==='automation.create'?'command_id,name,trigger_id,condition,action':op==='automation.update'?'command_id,id,expected_version,name,trigger_id,condition,action':op==='automation.process_pending'?'command_id':'command_id,id,expected_version';if(!exact(v,expected)||['automation.create','automation.update'].includes(op)&&!definition(v)||!['automation.create','automation.process_pending'].includes(op)&&(!uuid(v.id)||!natural(v.expected_version)||v.expected_version===0))return null;return {...v,command_id:v.command_id.toLowerCase(),...('id'in v?{id:(v.id as string).toLowerCase()}:{}),...(plain(v.action)?{action:{...v.action,recipient_user_id:(v.action.recipient_user_id as string).toLowerCase()}}:{})}as AutomationInputV1}catch{return null}}
export function parseAutomationReceiptV1(op:AutomationOperationV1,i:AutomationInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||v.contract_version!=='automations.v1'||v.operation!==op||v.command_id!==i.command_id)return null;if(op==='automation.process_pending')return exact(v,'contract_version,operation,command_id,processed,succeeded,failed,skipped,has_more')&&[v.processed,v.succeeded,v.failed,v.skipped].every(natural)&&(v.processed as number)<=100&&v.processed===(v.succeeded as number)+(v.failed as number)+(v.skipped as number)&&typeof v.has_more==='boolean'?v:null;return exact(v,'contract_version,operation,command_id,id,version,enabled')&&uuid(v.id)&&(op==='automation.create'||v.id===i.id)&&v.version===(op==='automation.create'?1:(i.expected_version??0)+1)&&v.enabled===(op==='automation.enable')?v:null}catch{return null}}
export function parseAutomationReadInputV1(op:string,v:unknown):AutomationReadInputV1|null{try{if(!plain(v)||!['automation.get','automation.list','automation.run_history'].includes(op)||Object.keys(v).some(k=>!(op==='automation.list'?['limit','after_id']:op==='automation.get'?['id']:['id','limit','after_id']).includes(k))||op!=='automation.list'&&!uuid(v.id)||'limit'in v&&(!natural(v.limit)||(v.limit as number)<1||(v.limit as number)>100)||'after_id'in v&&!uuid(v.after_id))return null;return {...v,...('id'in v?{id:(v.id as string).toLowerCase()}:{}),...('after_id'in v?{after_id:(v.after_id as string).toLowerCase()}:{})}as AutomationReadInputV1}catch{return null}}
function record(v:unknown){return plain(v)&&exact(v,'id,version,name,trigger_id,condition,action,enabled,created_at,updated_at')&&uuid(v.id)&&natural(v.version)&&v.version!==0&&definition(v)&&typeof v.enabled==='boolean'&&instant(v.created_at)&&instant(v.updated_at)}
export function parseAutomationReadV1(op:string,i:AutomationReadInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||v.contract_version!=='automations.v1'||v.operation!==op)return null;if(op==='automation.get')return exact(v,'contract_version,operation,record')&&record(v.record)&&(v.record as Record<string,unknown>).id===i.id?v:null;if(!exact(v,'contract_version,operation,items,next_id')||!Array.isArray(v.items)||v.items.length>(i.limit??20))return null;let last=i.after_id??'';for(const r of v.items){if(!plain(r)||!uuid(r.id)||r.id<=last)return null;if(op==='automation.list'){if(!record(r))return null}else if(!exact(r,'id,automation_id,event_id,action_id,definition_version,status,effect_id,failure_code,created_at')||r.automation_id!==i.id||!uuid(r.event_id)||!['notification.create','task.create'].includes(r.action_id as string)||!natural(r.definition_version)||r.definition_version===0||!['succeeded','failed','skipped'].includes(r.status as string)||!instant(r.created_at)||(r.status==='succeeded'?!uuid(r.effect_id)||r.failure_code!==null:r.effect_id!==null|| (r.status==='failed'?!['action_denied','action_conflict','action_invalid','action_unavailable','target_unavailable'].includes(r.failure_code as string):r.failure_code!==null)))return null;last=r.id}if(v.next_id!==null&&(v.next_id!==last||v.items.length!==(i.limit??20)))return null;return v}catch{return null}}
