import type{EquipmentInputsV1,EquipmentOperationV1,EquipmentReceiptV1,EquipmentReadV1}from '../contracts/equipment-v1'
import{snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import{isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import{isStrictCalendarDateV1}from './telecom-runtime-v1.ts'
export const EQUIPMENT_RPC_V1={'equipment.create':'equipment_v1_command','equipment.assign':'equipment_v1_command','equipment.return':'equipment_v1_command','equipment.replace':'equipment_v1_command','equipment.cancel':'equipment_v1_command','equipment.get':'equipment_v1_query','equipment.list':'equipment_v1_query','equipment.history':'equipment_v1_query'}as const
const req={'equipment.create':['command_id','customer_id','contract_id','service_id','line_id','commitment_id','kind','manufacturer','model','commercial_description','purchased_on','assigned_on'],'equipment.assign':['command_id','id','expected_version','event_on'],'equipment.return':['command_id','id','expected_version','event_on'],'equipment.cancel':['command_id','id','expected_version','event_on'],'equipment.replace':['command_id','id','expected_version','event_on','manufacturer','model','commercial_description','purchased_on','commitment_id'],'equipment.get':['id'],'equipment.list':[],'equipment.history':['id']}as const
const kinds=['router','ont','mobile_terminal','other'],states=['prepared','assigned','returned','replaced','cancelled'],sources=['manual','import','integration']
const exact=(v:Record<string,unknown>,keys:readonly string[])=>Object.keys(v).sort().join(',')===[...keys].sort().join(',')
const int=(v:unknown,max=999999999999999):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=1&&v<=max
const text=(v:unknown,max:number)=>typeof v==='string'&&v.trim().length>0&&[...v].length<=max&&!/[\u0000-\u001f\u007f-\u009f]/.test(v)
const date=(v:unknown):v is string=>isStrictCalendarDateV1(v)&&v>='2000-01-01'&&v<='2100-12-31'
const today=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return p.year+'-'+p.month+'-'+p.day}
export function isEquipmentOperationV1(v:unknown):v is EquipmentOperationV1{return typeof v==='string'&&Object.hasOwn(req,v)}
export function parseEquipmentInputV1<O extends EquipmentOperationV1>(op:O,value:unknown):EquipmentInputsV1[O]|null{try{
 if(!isEquipmentOperationV1(op))return null;const v=snapshotProductJsonV1(value),required:readonly string[]=req[op],optional=op==='equipment.list'?['customer_id','contract_id','service_id','line_id','kind','status','source','limit','after_id']:op==='equipment.history'?['limit','after_version']:[]
 if(!plain(v)||required.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>![...required,...optional].includes(k)))return null
 for(const[k,x]of Object.entries(v)){if(x===null&&['equipment.create','equipment.replace'].includes(op)&&['contract_id','service_id','line_id','commitment_id','commercial_description','purchased_on','assigned_on'].includes(k))continue
 if(k==='id'||k.endsWith('_id')){if(!uuid(x))return null}else if(['expected_version','after_version','limit'].includes(k)){if(!int(x,k==='limit'?100:999999999999999))return null}else if(['purchased_on','assigned_on','event_on'].includes(k)){if(!date(x)||x>today())return null}else if(k==='kind'){if(!kinds.includes(x as string))return null}else if(k==='status'){if(!states.includes(x as string))return null}else if(k==='source'){if(!sources.includes(x as string))return null}else if(!text(x,k==='commercial_description'?200:100))return null}
 if(op==='equipment.create'&&(v.service_id!==null&&v.contract_id===null||v.line_id!==null&&v.service_id===null||v.commitment_id!==null&&v.contract_id===null))return null
 if(v.purchased_on!==undefined&&v.purchased_on!==null){const end=v.assigned_on??v.event_on;if(end!==undefined&&end!==null&&(v.purchased_on as string)>(end as string))return null}
 return v as EquipmentInputsV1[O]}catch{return null}}
export function parseEquipmentReceiptV1(op:EquipmentOperationV1,i:EquipmentInputsV1[EquipmentOperationV1],value:unknown):EquipmentReceiptV1|null{try{
 const v=snapshotProductJsonV1(value),input=i as unknown as Record<string,unknown>;if(!plain(v)||!exact(v,['contract_version','operation','command_id','id','version','status','source','replacement_id','replacement_version'])||v.contract_version!=='equipment.v1'||v.operation!==op||v.command_id!==input.command_id||!uuid(v.id)||!int(v.version)||v.source!=='manual')return null
 if(op==='equipment.create'){if(v.version!==1||v.status!==(input.assigned_on===null?'prepared':'assigned'))return null}else{if(v.id!==input.id||v.version!==(input.expected_version as number)+1||v.status!==({'equipment.assign':'assigned','equipment.return':'returned','equipment.replace':'replaced','equipment.cancel':'cancelled'}as Record<string,string>)[op])return null}
 if(op==='equipment.replace'){if(!uuid(v.replacement_id)||v.replacement_id===v.id||v.replacement_version!==1)return null}else if(v.replacement_id!==null||v.replacement_version!==null)return null;return v as EquipmentReceiptV1}catch{return null}}
export function validEquipmentRowV1(x:unknown):boolean{if(!plain(x)||!exact(x,['id','version','customer_id','contract_id','service_id','line_id','commitment_id','kind','manufacturer','model','commercial_description','status','purchased_on','assigned_on','returned_on','replaced_on','cancelled_on','replaces_equipment_id','replaced_by_id','source'])||!uuid(x.id)||!uuid(x.customer_id)||!int(x.version)||!kinds.includes(x.kind as string)||!states.includes(x.status as string)||!sources.includes(x.source as string)||!text(x.manufacturer,100)||!text(x.model,100)||x.commercial_description!==null&&!text(x.commercial_description,200))return false
 for(const k of['contract_id','service_id','line_id','commitment_id','replaces_equipment_id','replaced_by_id'])if(x[k]!==null&&!uuid(x[k]))return false
 for(const k of['purchased_on','assigned_on','returned_on','replaced_on','cancelled_on'])if(x[k]!==null&&!date(x[k]))return false
 if(x.service_id!==null&&x.contract_id===null||x.line_id!==null&&x.service_id===null||x.commitment_id!==null&&x.contract_id===null||x.replaced_by_id===x.id||x.replaces_equipment_id===x.id)return false
 if(x.assigned_on!==null&&x.purchased_on!==null&&(x.assigned_on as string)<(x.purchased_on as string))return false
 if(x.status==='prepared'||x.status==='cancelled'){if(x.assigned_on!==null||x.returned_on!==null||x.replaced_on!==null||x.replaced_by_id!==null||x.status==='prepared'&&x.cancelled_on!==null||x.status==='cancelled'&&!date(x.cancelled_on))return false}
 else if(!date(x.assigned_on)||x.cancelled_on!==null)return false
 if(x.status==='assigned'&&(x.returned_on!==null||x.replaced_on!==null||x.replaced_by_id!==null))return false
 if(x.status==='returned'&&(!date(x.returned_on)||(x.returned_on as string)<(x.assigned_on as string)||x.replaced_on!==null||x.replaced_by_id!==null))return false
 if(x.status==='replaced'&&(!date(x.replaced_on)||(x.replaced_on as string)<(x.assigned_on as string)||x.returned_on!==null||!uuid(x.replaced_by_id)))return false
 return true}
export function parseEquipmentReadV1(op:EquipmentOperationV1,i:EquipmentInputsV1[EquipmentOperationV1],value:unknown):EquipmentReadV1|null{try{
 const v=snapshotProductJsonV1(value),input=i as unknown as Record<string,unknown>,lim=(input.limit as number)??50;if(!plain(v)||v.contract_version!=='equipment.v1'||v.operation!==op)return null
 if(op==='equipment.get'){if(!exact(v,['contract_version','operation','record'])||!validEquipmentRowV1(v.record)||(v.record as Record<string,unknown>).id!==input.id)return null}
 else if(op==='equipment.list'){if(!exact(v,['contract_version','operation','items','next_id'])||!Array.isArray(v.items)||v.items.length>lim)return null;let previous=(input.after_id as string)??'';for(const x of v.items){if(!validEquipmentRowV1(x)||x.id<=previous||['customer_id','contract_id','service_id','line_id','kind','status','source'].some(k=>input[k]!==undefined&&x[k]!==input[k]))return null;previous=x.id}if(v.next_id!==null&&(!uuid(v.next_id)||v.items.length!==lim||v.next_id!==previous))return null}
 else if(op==='equipment.history'){if(!exact(v,['contract_version','operation','id','items','next_version'])||v.id!==input.id||!Array.isArray(v.items)||v.items.length>lim)return null;let previous=(input.after_version as number)??0;for(const x of v.items){if(!plain(x)||!exact(x,['version','operation','status','event_on','related_equipment_id','actor_user_id','created_at'])||!int(x.version)||x.version<=previous||!['equipment.create','equipment.assign','equipment.return','equipment.replace','equipment.cancel'].includes(x.operation as string)||!states.includes(x.status as string)||x.event_on!==null&&!date(x.event_on)||x.related_equipment_id!==null&&!uuid(x.related_equipment_id)||!uuid(x.actor_user_id)||typeof x.created_at!=='string'||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,6})?(?:Z|\+00:00)$/.test(x.created_at)||!Number.isFinite(Date.parse(x.created_at)))return null;if(x.operation==='equipment.create'&&!['prepared','assigned'].includes(x.status as string)||x.operation!=='equipment.create'&&(x.status!==({'equipment.assign':'assigned','equipment.return':'returned','equipment.replace':'replaced','equipment.cancel':'cancelled'}as Record<string,string>)[x.operation as string]||x.event_on===null)||x.operation==='equipment.replace'&&x.related_equipment_id===null||!['equipment.create','equipment.replace'].includes(x.operation as string)&&x.related_equipment_id!==null)return null;previous=x.version}if(v.next_version!==null&&(!int(v.next_version)||v.items.length!==lim||v.next_version!==previous))return null}
 else return null;return v as EquipmentReadV1}catch{return null}}
