import {isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import {snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import type {ImportJobCancelInputV1,ImportJobListInputV1,ImportJobRecordV1,ImportJobReceiptV1}from '../contracts/importjob-v1'
export const IMPORTJOB_RPC_V1={'importjob.cancel':'importjob_v1_cancel'}as const
const states=['uploaded','mapping','validating','ready','applying','completed','failed','cancelled']
const keys=(v:Record<string,unknown>,s:string)=>Object.keys(v).sort().join(',')===s.split(',').sort().join(',')
const count=(n:unknown)=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=0
const version=(n:unknown)=>count(n)&&(n as number)>0&&(n as number)<1e15
export function parseImportJobCancelV1(v:unknown):ImportJobCancelInputV1|null{try{return plain(v)&&keys(v,'command_id,id,expected_version')&&uuid(v.command_id)&&uuid(v.id)&&version(v.expected_version)?Object.freeze({...v,command_id:v.command_id.toLowerCase(),id:v.id.toLowerCase()})as ImportJobCancelInputV1:null}catch{return null}}
export function parseImportJobIdV1(v:unknown){return plain(v)&&keys(v,'id')&&uuid(v.id)?Object.freeze({id:v.id.toLowerCase()}):null}
export function parseImportJobListV1(v:unknown):ImportJobListInputV1|null{try{if(!plain(v)||Object.keys(v).some(k=>!['limit','after_id','status'].includes(k))||'limit'in v&&(!Number.isInteger(v.limit)||(v.limit as number)<1||(v.limit as number)>100)||'after_id'in v&&!uuid(v.after_id)||'status'in v&&!states.includes(v.status as string))return null;return Object.freeze({...v,...('after_id'in v?{after_id:(v.after_id as string).toLowerCase()}:{})})as ImportJobListInputV1}catch{return null}}
function record(v:unknown):v is ImportJobRecordV1{
 if(!plain(v)||!keys(v,'id,version,kind,status,total_rows,valid_rows,invalid_rows,applied_rows,failed_rows,checkpoint,failure_code,can_cancel,processing_status')||!uuid(v.id)||!version(v.version)||!['customers','contacts','operators','plans','plan_versions','contracts','services','lines','entitlements','bundle_components','renewals','permanences','sims','portabilities','cases','service_locations','equipment','protected_identifiers'].includes(v.kind as string)||!states.includes(v.status as string)||v.processing_status!=='blocked_encrypted_staging_adapter'||v.can_cancel!==['uploaded','mapping','validating','ready'].includes(v.status as string))return false
 for(const k of ['total_rows','valid_rows','invalid_rows','applied_rows','failed_rows'])if(!count(v[k]))return false
 return(v.checkpoint===null||count(v.checkpoint)&&(v.checkpoint as number)<=(v.total_rows as number))&&(v.valid_rows as number)+(v.invalid_rows as number)<=(v.total_rows as number)&&(v.applied_rows as number)+(v.failed_rows as number)<=(v.valid_rows as number)&&(v.failure_code===null||['source_unavailable','integrity_mismatch','mapping_invalid','validation_failed','application_failed','cancelled_by_policy','system_failure'].includes(v.failure_code as string))&&(v.status==='failed')===(v.failure_code!==null)
}
export function parseImportJobGetResultV1(id:string,value:unknown){try{const v=snapshotProductJsonV1(value);return plain(v)&&keys(v,'contract_version,operation,record')&&v.contract_version==='importjob.v1'&&v.operation==='importjob.get'&&record(v.record)&&v.record.id===id?v as {contract_version:'importjob.v1';operation:'importjob.get';record:ImportJobRecordV1}:null}catch{return null}}
export function parseImportJobListResultV1(input:ImportJobListInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||!keys(v,'contract_version,operation,items,next_id')||v.contract_version!=='importjob.v1'||v.operation!=='importjob.list'||!Array.isArray(v.items)||v.items.length>(input.limit??20))return null;let last=input.after_id??'';for(const r of v.items){if(!record(r)||r.id<=last||input.status!==undefined&&r.status!==input.status)return null;last=r.id}if(v.next_id!==null&&(v.items.length!==(input.limit??20)||v.next_id!==last))return null;return v as {contract_version:'importjob.v1';operation:'importjob.list';items:ImportJobRecordV1[];next_id:string|null}}catch{return null}}
export function parseImportJobReceiptV1(i:ImportJobCancelInputV1,v:unknown):ImportJobReceiptV1|null{try{return plain(v)&&keys(v,'contract_version,operation,command_id,id,version,status')&&v.contract_version==='importjob.v1'&&v.operation==='importjob.cancel'&&v.command_id===i.command_id&&v.id===i.id&&v.version===i.expected_version+1&&v.status==='cancelled'?Object.freeze({...v})as ImportJobReceiptV1:null}catch{return null}}
