import {isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import {snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import type {InboxInputV1,InboxOperationV1,InboxReceiptV1,InboxRecordV1,InboxMessageV1,InboxListInputV1,InboxThreadInputV1}from '../contracts/inbox-v1'
export const INBOX_RPC_V1={'conversation.create_internal':'inbox_v1_conversation_create_internal','message.add_internal_note':'inbox_v1_message_add_internal_note','conversation.assign':'inbox_v1_conversation_assign','conversation.link_customer':'inbox_v1_conversation_link_customer','conversation.close':'inbox_v1_conversation_close','conversation.reopen':'inbox_v1_conversation_reopen','conversation.archive':'inbox_v1_conversation_archive','conversation.restore':'inbox_v1_conversation_restore','conversation.mark_read':'inbox_v1_conversation_mark_read','conversation.mark_unread':'inbox_v1_conversation_mark_unread'}as const
export function isInboxOperationV1(v:unknown):v is InboxOperationV1{return typeof v==='string'&&Object.hasOwn(INBOX_RPC_V1,v)}
const keys=(v:Record<string,unknown>,s:string)=>Object.keys(v).sort().join(',')===s.split(',').sort().join(',')
const integer=(v:unknown,min=0)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<1e15
const body=(v:unknown)=>typeof v==='string'&&v.length>0&&[...v].length<=2000&&v===v.trim()&&!/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(v)
const timestamp=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v))
const readOp=(op:string)=>['conversation.mark_read','conversation.mark_unread'].includes(op)
export function parseInboxInputV1(op:InboxOperationV1,v:unknown):InboxInputV1|null{
 try{if(!isInboxOperationV1(op)||!plain(v))return null
 const expected=op==='conversation.create_internal'?'command_id,assigned_user_id,customer_id,body':op==='conversation.assign'?'command_id,id,expected_version,assigned_user_id':op==='conversation.link_customer'?'command_id,id,expected_version,customer_id,contact_id':op==='message.add_internal_note'?'command_id,id,expected_version,body':'command_id,id,expected_version'
 if(!keys(v,expected)||!uuid(v.command_id)||op!=='conversation.create_internal'&&(!uuid(v.id)||!integer(v.expected_version,readOp(op)?0:1)))return null
 for(const k of ['assigned_user_id','customer_id','contact_id'])if(k in v&&v[k]!==null&&!uuid(v[k]))return null
 if('body'in v&&!body(v.body)||v.contact_id!==undefined&&v.contact_id!==null&&v.customer_id===null)return null
 const out={...v};for(const k of ['id','command_id','assigned_user_id','customer_id','contact_id'])if(typeof out[k]==='string')out[k]=(out[k]as string).toLowerCase()
 return Object.freeze(out)as InboxInputV1}catch{return null}
}
export function parseInboxReceiptV1(op:InboxOperationV1,i:InboxInputV1,v:unknown):InboxReceiptV1|null{try{
 const status=op==='conversation.mark_read'?'read':op==='conversation.mark_unread'?'unread':op==='conversation.close'?'closed':op==='conversation.archive'?'archived':['conversation.create_internal','conversation.reopen','message.add_internal_note'].includes(op)?'open':null
 return plain(v)&&keys(v,'contract_version,operation,command_id,id,version,status')&&v.contract_version==='inbox.v1'&&v.operation===op&&v.command_id===i.command_id&&uuid(v.id)&&(op==='conversation.create_internal'||v.id===i.id)&&integer(v.version,1)&&v.version===(op==='conversation.create_internal'?1:(i.expected_version??0)+1)&&(status===null?['open','closed'].includes(v.status as string):v.status===status)?Object.freeze({...v})as InboxReceiptV1:null}catch{return null}}
export function parseInboxListInputV1(v:unknown):InboxListInputV1|null{try{return plain(v)&&!Object.keys(v).some(k=>!['limit','after_id','status'].includes(k))&&(!('limit'in v)||integer(v.limit,1)&&(v.limit as number)<=100)&&(!('after_id'in v)||uuid(v.after_id))&&(!('status'in v)||['open','closed','archived'].includes(v.status as string))?Object.freeze({...v,...('after_id'in v?{after_id:(v.after_id as string).toLowerCase()}:{})})as InboxListInputV1:null}catch{return null}}
export function parseInboxThreadInputV1(v:unknown):InboxThreadInputV1|null{try{return plain(v)&&uuid(v.id)&&!Object.keys(v).some(k=>!['id','limit','after_seq'].includes(k))&&(!('limit'in v)||integer(v.limit,1)&&(v.limit as number)<=50)&&(!('after_seq'in v)||integer(v.after_seq))?Object.freeze({...v,id:v.id.toLowerCase()})as InboxThreadInputV1:null}catch{return null}}
function record(v:unknown):v is InboxRecordV1{return plain(v)&&keys(v,'id,version,status,channel,source,assigned_user_id,customer_id,contact_id,last_seq,created_at,updated_at,read_version,unread')&&uuid(v.id)&&integer(v.version,1)&&['open','closed','archived'].includes(v.status as string)&&v.channel==='internal'&&v.source==='manual_internal'&&[v.assigned_user_id,v.customer_id,v.contact_id].every(x=>x===null||uuid(x))&&(v.contact_id===null||v.customer_id!==null)&&integer(v.last_seq)&&timestamp(v.created_at)&&timestamp(v.updated_at)&&Date.parse(v.updated_at as string)>=Date.parse(v.created_at as string)&&integer(v.read_version)&&typeof v.unread==='boolean'}
export function parseInboxListResultV1(i:InboxListInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||!keys(v,'contract_version,operation,items,next_id')||v.contract_version!=='inbox.v1'||v.operation!=='inbox.list'||!Array.isArray(v.items)||v.items.length>(i.limit??20))return null;let last=i.after_id??'';for(const r of v.items){if(!record(r)||r.id<=last||r.status!==(i.status??'open'))return null;last=r.id}if(v.next_id!==null&&(v.next_id!==last||v.items.length!==(i.limit??20)))return null;return v as {contract_version:'inbox.v1';operation:'inbox.list';items:InboxRecordV1[];next_id:string|null}}catch{return null}}
export function parseInboxThreadResultV1(i:InboxThreadInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||!keys(v,'contract_version,operation,conversation,messages,next_seq,provider_status')||v.contract_version!=='inbox.v1'||v.operation!=='inbox.get_thread'||!record(v.conversation)||v.conversation.id!==i.id||v.provider_status!=='not_configured'||!Array.isArray(v.messages)||v.messages.length>(i.limit??20))return null;let seq=i.after_seq??0;for(const m of v.messages){if(!plain(m)||!keys(m,'id,seq,kind,body,actor_user_id,created_at')||!uuid(m.id)||!uuid(m.actor_user_id)||!timestamp(m.created_at)||m.kind!=='internal_note'||!body(m.body)||!integer(m.seq,1)||(m.seq as number)<=seq||(m.seq as number)>v.conversation.last_seq)return null;seq=m.seq as number}if(v.next_seq!==null&&(v.next_seq!==seq||v.messages.length!==(i.limit??20)))return null;return v as {contract_version:'inbox.v1';operation:'inbox.get_thread';conversation:InboxRecordV1;messages:InboxMessageV1[];next_seq:number|null;provider_status:'not_configured'}}catch{return null}}
export function parseInboxUnreadV1(value:unknown){try{const v=snapshotProductJsonV1(value);return plain(v)&&keys(v,'contract_version,operation,unread_count')&&v.contract_version==='inbox.v1'&&v.operation==='inbox.unread_summary'&&integer(v.unread_count)?v as {contract_version:'inbox.v1';operation:'inbox.unread_summary';unread_count:number}:null}catch{return null}}
