import {isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import {snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import type {NotificationOperationV1,NotificationInputV1,NotificationListInputV1,NotificationRecordV1}from '../contracts/notifications-v1'
export const NOTIFICATIONS_RPC_V1={'notification.refresh':'notification_v1_refresh','notification.mark_read':'notification_v1_mark_read','notification.mark_all_read':'notification_v1_mark_all_read'}as const
export const exact=(v:Record<string,unknown>,s:string)=>Object.keys(v).sort().join(',')===s.split(',').filter(Boolean).sort().join(',')
export const natural=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0&&v<1e15
export const instant=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v))
export function isNotificationOperationV1(v:unknown):v is NotificationOperationV1{return typeof v==='string'&&Object.hasOwn(NOTIFICATIONS_RPC_V1,v)}
export function parseNotificationInputV1(op:NotificationOperationV1,v:unknown):NotificationInputV1|null{try{return isNotificationOperationV1(op)&&plain(v)&&exact(v,op==='notification.mark_read'?'command_id,expected_version,id':'command_id,expected_version')&&uuid(v.command_id)&&natural(v.expected_version)&&(op!=='notification.mark_read'||uuid(v.id))?Object.freeze({...v,command_id:v.command_id.toLowerCase(),...('id'in v?{id:(v.id as string).toLowerCase()}:{})})as NotificationInputV1:null}catch{return null}}
export function parseNotificationReceiptV1(op:NotificationOperationV1,i:NotificationInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);return plain(v)&&exact(v,'contract_version,operation,command_id,version,affected,has_more')&&v.contract_version==='notifications.v1'&&v.operation===op&&v.command_id===i.command_id&&natural(v.version)&&v.version===(op==='notification.refresh'?i.expected_version+1+(v.affected as number):i.expected_version+1)&&typeof v.has_more==='boolean'&&(op!=='notification.mark_read'||v.has_more===false)&&natural(v.affected)&&(v.affected as number)<=100&&(op!=='notification.mark_read'||v.affected===1)?v:null}catch{return null}}
export function parseNotificationListInputV1(v:unknown):NotificationListInputV1|null{try{return plain(v)&&!Object.keys(v).some(k=>!['limit','after_id'].includes(k))&&(!('limit'in v)||natural(v.limit)&&(v.limit as number)>=1&&(v.limit as number)<=100)&&(!('after_id'in v)||uuid(v.after_id))?Object.freeze({...v,...('after_id'in v?{after_id:(v.after_id as string).toLowerCase()}:{})})as NotificationListInputV1:null}catch{return null}}
export function parseNotificationListV1(i:NotificationListInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||!exact(v,'contract_version,operation,version,items,next_id')||v.contract_version!=='notifications.v1'||v.operation!=='notification.list'||!natural(v.version)||!Array.isArray(v.items)||v.items.length>(i.limit??20))return null;let last=i.after_id??'';for(const n of v.items){if(!plain(n)||!exact(n,'id,kind,title,summary,target,created_at,read_at')||!uuid(n.id)||n.id<=last||!['task_overdue','customer_created'].includes(n.kind as string)||n.title!==(n.kind==='task_overdue'?'Tarea vencida':'Nuevo cliente')||n.summary!=='Revise el registro autorizado.'||!plain(n.target)||!exact(n.target,'kind,id')||n.target.kind!==(n.kind==='task_overdue'?'task':'customer')||!uuid(n.target.id)||!instant(n.created_at)||n.read_at!==null&&!instant(n.read_at))return null;last=n.id}if(v.next_id!==null&&(v.next_id!==last||v.items.length!==(i.limit??20)))return null;return v as {contract_version:'notifications.v1';operation:'notification.list';version:number;items:NotificationRecordV1[];next_id:string|null}}catch{return null}}
export function parseNotificationCountV1(value:unknown){try{const v=snapshotProductJsonV1(value);return plain(v)&&exact(v,'contract_version,operation,version,unread_count')&&v.contract_version==='notifications.v1'&&v.operation==='notification.unread_count'&&natural(v.version)&&natural(v.unread_count)?v:null}catch{return null}}
