import type{ServiceLocationInputsV1,ServiceLocationOperationV1,ServiceLocationReceiptV1,ServiceLocationReadV1}from '../contracts/service-location-v1'
import{snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import{isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
export const SERVICE_LOCATION_RPC_V1={'service_location.create':'service_location_v1_command','service_location.assign':'service_location_v1_command','service_location.get':'service_location_v1_query','service_location.list':'service_location_v1_query'}as const
const req={'service_location.create':['command_id','customer_id','label','address_line1','address_line2','postal_code','city','region','country'],'service_location.assign':['command_id','service_id','location_id','expected_service_version','expected_details_version'],'service_location.get':['id'],'service_location.list':['customer_id']}as const
const exact=(v:Record<string,unknown>,keys:readonly string[])=>Object.keys(v).sort().join(',')===[...keys].sort().join(',')
const int=(v:unknown,min=1,max=999999999999999)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max
const text=(v:unknown,max:number)=>typeof v==='string'&&v.trim().length>0&&[...v].length<=max&&!/[\u0000-\u001f\u007f-\u009f]/.test(v)
export function isServiceLocationOperationV1(v:unknown):v is ServiceLocationOperationV1{return typeof v==='string'&&Object.hasOwn(req,v)}
export function parseServiceLocationInputV1<O extends ServiceLocationOperationV1>(op:O,value:unknown):ServiceLocationInputsV1[O]|null{try{if(!isServiceLocationOperationV1(op))return null;const v=snapshotProductJsonV1(value),required:readonly string[]=req[op],optional=op==='service_location.list'?['limit','after_id']:[];if(!plain(v)||required.some(k=>!Object.hasOwn(v,k))||Object.keys(v).some(k=>![...required,...optional].includes(k)))return null
 for(const[k,x]of Object.entries(v)){if(x===null&&['location_id','address_line2','region'].includes(k))continue;if(k==='id'||k.endsWith('_id')){if(!uuid(x))return null}else if(k.startsWith('expected_')||k==='limit'){if(!int(x,k==='expected_details_version'?0:1,k==='limit'?100:999999999999999))return null}else if(k==='country'){if(typeof x!=='string'||! /^[A-Z]{2}$/.test(x))return null}else if(!text(x,k==='address_line1'?300:k==='address_line2'?150:k==='postal_code'?20:100))return null}
 return v as ServiceLocationInputsV1[O]}catch{return null}}
export function parseServiceLocationReceiptV1(op:ServiceLocationOperationV1,i:ServiceLocationInputsV1[ServiceLocationOperationV1],value:unknown):ServiceLocationReceiptV1|null{try{const v=snapshotProductJsonV1(value),input=i as unknown as Record<string,unknown>;if(!plain(v)||!exact(v,['contract_version','operation','command_id','id','customer_id','service_id','service_version','version','status'])||v.contract_version!=='service_location.v1'||v.operation!==op||v.command_id!==input.command_id||!uuid(v.id)||!uuid(v.customer_id)||!int(v.version))return null
 if(op==='service_location.create'){if(v.customer_id!==input.customer_id||v.version!==1||v.service_id!==null||v.service_version!==null||v.status!=='created')return null}else if(op==='service_location.assign'){if(v.id!==input.service_id||v.service_id!==input.service_id||v.service_version!==(input.expected_service_version as number)+1||v.version!==(input.expected_details_version as number)+1||v.status!=='assigned')return null}else return null;return v as ServiceLocationReceiptV1}catch{return null}}
export function parseServiceLocationReadV1(op:ServiceLocationOperationV1,i:ServiceLocationInputsV1[ServiceLocationOperationV1],value:unknown):ServiceLocationReadV1|null{try{const v=snapshotProductJsonV1(value),input=i as unknown as Record<string,unknown>;if(!plain(v)||v.contract_version!=='service_location.v1'||v.operation!==op)return null
 const row=(x:unknown)=>plain(x)&&exact(x,['id','customer_id','version','label','country','source'])&&uuid(x.id)&&uuid(x.customer_id)&&x.version===1&&text(x.label,100)&&typeof x.country==='string'&&/^[A-Z]{2}$/.test(x.country)&&['manual','import','integration'].includes(x.source as string)
 if(op==='service_location.get'){if(!exact(v,['contract_version','operation','record'])||!row(v.record)||(v.record as Record<string,unknown>).id!==input.id)return null}else if(op==='service_location.list'){if(!exact(v,['contract_version','operation','items','next_id'])||!Array.isArray(v.items)||v.items.length>((input.limit as number)??50))return null;let previous=(input.after_id as string)??'';for(const x of v.items){if(!row(x)||x.customer_id!==input.customer_id||x.id<=previous)return null;previous=x.id}if(v.next_id!==null&&(!uuid(v.next_id)||v.items.length!==((input.limit as number)??50)||v.next_id!==previous))return null}else return null;return v as ServiceLocationReadV1}catch{return null}}
