import {isClosedObjectV1 as plain,isUuidV1 as uuid}from './product-work-runtime-v1.ts'
import {snapshotProductJsonV1}from './product-query-runtime-v1.ts'
import {exact,natural}from './notifications-runtime-v1.ts'
import type {SettingsOperationV1,SettingsInputV1,ProductPreferencesV1,CompanyProfileV1}from '../contracts/settings-v1'
export const SETTINGS_RPC_V1={'settings.profile_update':'settings_v1_profile_update','settings.company_update':'settings_v1_company_update'}as const
export function isSettingsOperationV1(v:unknown):v is SettingsOperationV1{return typeof v==='string'&&Object.hasOwn(SETTINGS_RPC_V1,v)}
const text=(v:unknown,max:number)=>v===null||typeof v==='string'&&[...v].length>=1&&[...v].length<=max&&v===v.trim()&&!/[\x00-\x1f\x7f]/.test(v)
const zone=(v:unknown)=>{try{if(typeof v!=='string'||v.length>100)return false;new Intl.DateTimeFormat('en',{timeZone:v});return true}catch{return false}}
const locale=(v:unknown)=>['es-ES','en-GB','en-US'].includes(v as string)
const website=(v:unknown)=>{try{if(v===null)return true;if(!text(v,500)||typeof v!=='string')return false;const u=new URL(v);return u.protocol==='https:'&&!!u.hostname&&!u.username&&!u.password&&!/\s/.test(v)}catch{return false}}
export function validPreferenceV1(v:unknown):v is ProductPreferencesV1{return plain(v)&&exact(v,'display_name,timezone,locale,notification_preferences')&&text(v.display_name,100)&&zone(v.timezone)&&locale(v.locale)&&plain(v.notification_preferences)&&exact(v.notification_preferences,'in_app')&&typeof v.notification_preferences.in_app==='boolean'}
export function validCompanyProfileV1(v:unknown):v is CompanyProfileV1{return plain(v)&&exact(v,'trade_name,business_name,business_email,phone,website,address,timezone,locale,description,logo_document_id')&&text(v.trade_name,200)&&text(v.business_name,200)&&text(v.business_email,320)&&(v.business_email===null||/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v.business_email as string))&&text(v.phone,40)&&website(v.website)&&text(v.address,500)&&zone(v.timezone)&&locale(v.locale)&&text(v.description,1000)&&(v.logo_document_id===null||uuid(v.logo_document_id))}
export function parseSettingsInputV1(op:SettingsOperationV1,value:unknown):SettingsInputV1|null{try{const v=snapshotProductJsonV1(value);return isSettingsOperationV1(op)&&plain(v)&&exact(v,'command_id,expected_version,profile')&&uuid(v.command_id)&&natural(v.expected_version)&&(op==='settings.profile_update'?validPreferenceV1(v.profile):validCompanyProfileV1(v.profile))?{...v,command_id:v.command_id.toLowerCase()}as SettingsInputV1:null}catch{return null}}
export function parseSettingsReceiptV1(op:SettingsOperationV1,i:SettingsInputV1,value:unknown){try{const v=snapshotProductJsonV1(value);return plain(v)&&exact(v,'contract_version,operation,command_id,version')&&v.contract_version==='settings.v1'&&v.operation===op&&v.command_id===i.command_id&&v.version===i.expected_version+1?v:null}catch{return null}}
export function parseSettingsReadV1(op:string,value:unknown){try{const v=snapshotProductJsonV1(value);if(!plain(v)||v.contract_version!=='settings.v1'||v.operation!==op)return null;if(op==='settings.integrations'){const classes=['google_calendar','auth_mail','crm_mail','whatsapp','n8n','ai_provider','storage'];if(!exact(v,'contract_version,operation,integrations')||!Array.isArray(v.integrations)||v.integrations.length!==classes.length)return null;for(let i=0;i<classes.length;i++){const r=v.integrations[i];if(!plain(r)||!exact(r,'class,status')||r.class!==classes[i]||!(classes[i]==='storage'?['configured','unavailable']:['not_configured']).includes(r.status as string))return null}return v}return exact(v,'contract_version,operation,version,profile')&&natural(v.version)&&(op==='settings.profile_get'?validPreferenceV1(v.profile):op==='settings.company_get'&&validCompanyProfileV1(v.profile))?v:null}catch{return null}}
