'use client'
import {ScopedCollectionLabels} from '@/features/product/integration/ScopedCollectionLabels'
import {useEffect,useState,useMemo} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {control} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
import {NamedCustomer} from '@/features/customers/CustomerDomainPages'
import {minorAmount,amountBarPercent,analyticsMonth} from './analytics-presentation'
import type {BillingAnalyticsResultV1,BillingAnalyticsInputV1,BillingAnalyticsOperationV1} from '@/lib/contracts/billing-analytics-v1'
const columns={issued_minor:'Emitido',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'} as const
const keys=Object.keys(columns) as (keyof typeof columns)[]
function month(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit'}).format(new Date())}
function startMonth(){const d=new Date(month()+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-5);return d.toISOString().slice(0,7)}
export function BillingAnalytics({customerId}:{customerId?:string}){
 const {role}=useProduct(),[from,setFrom]=useState(startMonth),[to,setTo]=useState(month),[currency,setCurrency]=useState<BillingAnalyticsInputV1['currency']>('EUR'),[revision,setRevision]=useState(0)
 const span=(Number(to.slice(0,4))-Number(from.slice(0,4)))*12+Number(to.slice(5,7))-Number(from.slice(5,7)),valid=/^\d{4}-\d{2}$/.test(from)&&/^\d{4}-\d{2}$/.test(to)&&span>=0&&span<24,input=useMemo(()=>({currency,from_month:from+'-01',to_month:to+'-01',...(customerId?{customer_id:customerId}:{})}),[currency,from,to,customerId])
 if(role!=='owner'&&role!=='admin')return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Analítica financiera</h2><p className="mt-2 text-sm text-slate-500">Disponible para los responsables del espacio.</p></section>
 return <section className="space-y-4"><div><h2 className="text-lg font-semibold">Analítica financiera</h2><p className="mt-1 text-sm text-slate-500">Estado actual de las facturas agrupado por mes de emisión. Las monedas se consultan por separado.</p></div><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="text-sm">Mes inicial<input type="month" aria-label="Mes inicial de analítica" className={control+' ml-2'} min="2000-01" max="2100-12" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Mes final<input type="month" aria-label="Mes final de analítica" className={control+' ml-2'} min="2000-01" max="2100-12" value={to} onChange={e=>setTo(e.target.value)}/></label><select aria-label="Moneda de analítica" className={control} value={currency} onChange={e=>setCurrency(e.target.value as typeof currency)}>{['EUR','USD','GBP'].map(c=><option key={c}>{c}</option>)}</select><button className={control} onClick={()=>setRevision(v=>v+1)}>Actualizar analítica</button></div>{!valid?<p role="alert" className="text-sm text-red-700">Selecciona un intervalo de entre 1 y 24 meses.</p>:<div className="space-y-4"><AnalyticsPanel key={'months'+JSON.stringify(input)} operation="billing.monthly_series" input={input} revision={revision}/><AnalyticsPanel key={'customers'+JSON.stringify(input)} operation="billing.top_customers" input={input} revision={revision}/></div>}</section>
}
function AnalyticsPanel({operation,input,revision}:{operation:BillingAnalyticsOperationV1;input:BillingAnalyticsInputV1;revision:number}){
 const {repository}=useProduct(),[retry,setRetry]=useState(0),key=JSON.stringify([input,revision,retry]),[state,setState]=useState<{key:string;data?:BillingAnalyticsResultV1;error?:string}|null>(null),current=state?.key===key?state:null,data=current?.data,monthly=operation==='billing.monthly_series',title=monthly?'Evolución por mes de emisión':'Clientes por importe emitido'
 useEffect(()=>{let active=true;void repository.telecom(operation,{...input,...(!monthly?{limit:10}:{})}).then(data=>{if(active)setState({key,data})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,operation,input,monthly,key])
 let max=BigInt(0);data?.items.forEach(r=>{if(BigInt(r.issued_minor)>max)max=BigInt(r.issued_minor)})
 return <section className="overflow-hidden rounded-xl border bg-white" aria-label={title}><div className="border-b p-4"><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-slate-500">{monthly?'Todos los meses del intervalo, incluidos los meses sin emisión.':'Hasta 10 clientes ordenados por el importe emitido de esta moneda e intervalo.'} Vencido forma parte de Pendiente.</p></div>{current?.error?<div className="p-4"><p role="alert" className="text-sm text-red-700">{current.error}</p><button className={control+' mt-3'} onClick={()=>setRetry(v=>v+1)}>Reintentar {monthly?'evolución mensual':'clientes por emisión'}</button></div>:!data?<p role="status" className="p-4 text-sm text-slate-500">Consultando {title.toLowerCase()}…</p>:!data.items.length?<p className="p-5 text-sm text-slate-500">No hay facturas emitidas en esta moneda e intervalo.</p>:<ScopedCollectionLabels rows={data.items}><div className="space-y-3 p-4" aria-label={'Gráfico de '+title.toLowerCase()}>{data.items.map(r=><div key={'month'in r?r.month:r.customer_id} className="grid items-center gap-2 sm:grid-cols-[12rem_1fr]"><p className="text-sm font-medium">{'month'in r?analyticsMonth(r.month):<NamedCustomer id={r.customer_id}/>}</p><div><div aria-hidden="true" className="h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{width:amountBarPercent(r.issued_minor,max.toString())+'%'}}/></div><p className="mt-1 break-words text-xs text-slate-500">Emitido: {minorAmount(r.issued_minor,data.currency)}</p></div></div>)}</div><div className="overflow-x-auto border-t"><table className="w-full text-left text-xs"><caption className="sr-only">{title}: importes exactos en {data.currency}. Estado actual de las facturas por mes de emisión.</caption><thead className="bg-slate-50 text-slate-500"><tr><th scope="col" className="p-3">{monthly?'Mes de emisión':'Cliente'}</th>{keys.map(k=><th scope="col" key={k} className="p-3">{columns[k]}</th>)}</tr></thead><tbody className="divide-y">{data.items.map(r=><tr key={'month'in r?r.month:r.customer_id} data-analytics-row={'month'in r?r.month:r.customer_id}><th scope="row" className="whitespace-nowrap p-3 font-medium">{'month'in r?analyticsMonth(r.month):<NamedCustomer id={r.customer_id}/>}</th>{keys.map(k=><td key={k} className="whitespace-nowrap p-3">{minorAmount(r[k],data.currency)}</td>)}</tr>)}</tbody></table></div><p className="p-4 text-xs text-slate-500">Estado consultado el {productDate(data.as_of)}. Cobrado indica el estado actual de las facturas emitidas en ese mes; no representa una serie histórica de cobros.</p></ScopedCollectionLabels>}</section>
}
