'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import { PreviewNotice, control, primary, Drawer, Status, Kpis, PeriodSelect } from '@/features/product/ui'
import type { Period } from '@/features/product/model'
import type { BillingReadDataV1, BillingInvoiceV1, BillingReceiptV1, BillingOperationV1, BillingInputsV1, BillingProfileV1 } from '@/lib/contracts/billing-v1'
import { PrivateInvoicePdf } from './PrivateInvoicePdf'
import { InvoiceEditor } from './Editor'
import { PromptBuilder } from './PromptBuilder'
import { blankForm, type InvoiceFormData, type InvoiceLink } from './model'
import { invoiceForm, normalizedInvoice } from './integration'
import { initialCompany } from '@/features/settings/LocalCompany'
type Configuration=Extract<BillingReadDataV1,{operation:'configuration.get'}>
type InvoicePage=Extract<BillingReadDataV1,{operation:'invoice.list'}>
type Financial=Extract<BillingReadDataV1,{operation:'invoice.financial_summary'}>
const money=(minor:number,currency:string)=>new Intl.NumberFormat('es-ES',{style:'currency',currency}).format(minor/100)
export function IntegratedBilling({initialInvoiceId,initialCustomerId,contentEnabled=false}:{initialInvoiceId?:string;initialCustomerId?:string;contentEnabled?:boolean}){
  const {repository,role}=useProduct(),authorized=role==='owner'||role==='admin'
  const [query,setQuery]=useState(''),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[customerId,setCustomerId]=useState(initialCustomerId??''),[status,setStatus]=useState(''),[period,setPeriod]=useState<Period>('month')
  const [page,setPage]=useState<InvoicePage|null>(null),[financial,setFinancial]=useState<Financial|null>(null),[configuration,setConfiguration]=useState<Configuration|null>(null),[invoice,setInvoice]=useState<BillingInvoiceV1|null>(null),[edit,setEdit]=useState<InvoiceFormData|null>(null),[fiscal,setFiscal]=useState<'issuer'|'customer'|null>(null)
  const [error,setError]=useState<unknown>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[confirm,setConfirm]=useState<{operation:BillingOperationV1;input:BillingInputsV1[BillingOperationV1];label:string}|null>(null)
  const pending=useRef<{execute:()=>Promise<BillingReceiptV1>}|null>(null)
  const uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
  const loadInvoice=useCallback(async(id:string)=>{try{setInvoice((await repository.billing('invoice.get',{id})).invoice);setError(null)}catch(e){setInvoice(null);setError(e)}},[repository])
  useEffect(()=>{if(!authorized)return;let active=true;void Promise.all([repository.billing('invoice.list',{limit:50,...(status?{status:status as 'draft'|'issued'|'paid'|'trashed'|'overdue'}:{}),...(customerId?{customer_id:customerId}:{})}),repository.billing('invoice.financial_summary',{period}),repository.billing('configuration.get',customerId?{customer_id:customerId}:{})]).then(([p,f,c])=>{if(active){setPage(p);setFinancial(f);setConfiguration(c)}}).catch(e=>{if(active){setPage(null);setFinancial(null);setConfiguration(null);setError(e)}});return()=>{active=false}},[repository,authorized,customerId,status,period,reload])
  useEffect(()=>{if(!authorized||!initialInvoiceId)return;let current=true;void repository.billing('invoice.get',{id:initialInvoiceId}).then(v=>{if(current){setInvoice(v.invoice);setError(null)}}).catch(e=>{if(current){setInvoice(null);setError(e)}});return()=>{current=false}},[authorized,initialInvoiceId,repository])
  useEffect(()=>{if(!authorized||!initialCustomerId)return;let current=true;void repository.customer(initialCustomerId).then(c=>{if(current)setCustomers([{id:c.id,name:c.trade_name??c.legal_name}])}).catch(e=>{if(current){setCustomerId('');setError(e)}});return()=>{current=false}},[authorized,initialCustomerId,repository])
  async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{const result=await repository.search(query);setCustomers(result.items.filter(i=>i.kind==='customer').map(i=>({id:i.id,name:i.label})))}catch(e){setCustomers([]);setError(e)}finally{setBusy(false)}}
  async function execute(operation:BillingOperationV1,input:BillingInputsV1[BillingOperationV1]){
    if(busy)return;pending.current??={execute:()=>repository.billingCommand(operation,input)};return runPending()
  }
  async function runPending(){
    if(busy||!pending.current)return;setBusy(true);setError(null)
    try{const receipt=await pending.current.execute();pending.current=null;setEdit(null);setFiscal(null);setConfirm(null);setMessage(receipt.operation==='invoice.issue'?'Factura emitida con numeración del servidor.':receipt.operation==='invoice.mark_paid'?'Cobro registrado.':receipt.operation==='invoice.reverse_payment'?'Cobro revertido.':'Cambio guardado en la base local.');setReload(v=>v+1);if(receipt.operation.startsWith('invoice.'))await loadInvoice(receipt.id)}
    catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  function save(form:InvoiceFormData){try{const draft=normalizedInvoice(form);if(invoice&&invoice.status==='draft'){const {customer_id:discarded,...fields}=draft;void discarded;void execute('invoice.update_draft',{...fields,command_id:crypto.randomUUID(),id:invoice.id,expected_version:invoice.version})}else void execute('invoice.create_draft',{...draft,command_id:crypto.randomUUID()})}catch(e){setError(e)}}
  function prepare(operation:'invoice.issue'|'invoice.mark_paid'|'invoice.reverse_payment'|'invoice.trash'|'invoice.restore',label:string){if(!invoice)return;setError(null);pending.current=null;setConfirm({operation,label,input:{command_id:crypto.randomUUID(),id:invoice.id,expected_version:invoice.version}})}
  async function pdf(){if(!invoice)return;setBusy(true);setError(null);try{const blob=await repository.invoicePdf(invoice.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Factura_local_autorizada.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e)}finally{setBusy(false)}}
  const links:InvoiceLink[]=invoice?(['contractId','serviceId','opportunityId'] as const).flatMap(kind=>{const id={contractId:invoice.contract_id,serviceId:invoice.service_id,opportunityId:invoice.opportunity_id}[kind];return id?[{kind,id,customerId:invoice.customer_id,label:'Vínculo autorizado',...(kind==='serviceId'?{contractId:invoice.contract_id}:{})}]:[]}):[]
  const editorCustomers=invoice&&!customers.some(c=>c.id===invoice.customer_id)?[...customers,{id:invoice.customer_id,name:'Cliente de la factura'}]:customers
  return <div className="space-y-4"><PageHeader title="Facturación PRO" description="Facturas sintéticas guardadas, numeradas y calculadas por el servidor local"/><PreviewNotice/>{!authorized?<p className="text-sm text-slate-500">Facturación disponible para administradores del espacio.</p>:<>
    {!!error&&!edit&&!fiscal&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}
    <div className="flex flex-wrap gap-3"><PeriodSelect value={period} onChange={setPeriod}/><select aria-label="Estado de facturas" className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{[['draft','Borradores'],['issued','Emitidas'],['paid','Cobradas'],['overdue','Vencidas'],['trashed','Papelera']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className={control} onClick={()=>setReload(v=>v+1)}>Actualizar facturas</button></div>
    {financial?.currencies.map(c=><section key={c.currency} className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">{c.currency}</h2><Kpis items={(['issued_minor','paid_minor','outstanding_minor','overdue_minor'] as const).map(k=>({label:{issued_minor:'Facturado',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'}[k],value:money(c[k],c.currency)}))}/></section>)}
    <section className="rounded-xl border bg-white p-4"><form onSubmit={search} className="flex flex-wrap gap-2"><input aria-label="Buscar cliente de factura" placeholder="Buscar empresa" required minLength={2} maxLength={100} className={control} value={query} onChange={e=>setQuery(e.target.value)}/><button className={control} disabled={busy}>Buscar cliente</button></form><div className="mt-3 flex flex-wrap gap-2"><select aria-label="Cliente para facturación" className={control} value={customerId} onChange={e=>{setCustomerId(e.target.value);setInvoice(null);setConfiguration(null)}}><option value="">Todo el espacio</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className={primary} disabled={!customerId||busy} onClick={()=>{setError(null);setInvoice(null);pending.current=null;setEdit({...blankForm(),clientId:customerId,issueDate:new Date().toISOString().slice(0,10),series:configuration?.issuer?.default_series??'A'})}}>Nuevo borrador local</button><button className={control} disabled={busy||!configuration} onClick={()=>{setError(null);pending.current=null;setFiscal('issuer')}}>Configurar emisor</button><button className={control} disabled={!customerId||busy||!configuration} onClick={()=>{setError(null);pending.current=null;setFiscal('customer')}}>Datos fiscales del cliente</button></div><p className="mt-2 text-xs text-slate-500">Búsqueda limitada a cinco empresas. Nuevos vínculos de cartera pendientes de conectar.</p>
    {customerId&&<PromptBuilder customers={customers.filter(c=>c.id===customerId)} onGenerate={async (result,source)=>{setError(null);try{const proposal=await repository.billing('invoice.propose',{source,draft:normalizedInvoice(result.draft)});if(!proposal.requires_review||proposal.saved)throw new ProductUiError('internal_safe');setInvoice(null);setEdit(result.draft);setMessage('Propuesta validada: requiere revisión. No se ha guardado ninguna factura.')}catch(e){setError(e)}}}/>}</section>
    <section className="overflow-x-auto rounded-xl border bg-white p-4"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Factura</th><th className="p-2">Estado</th><th className="p-2">Vencimiento</th><th className="p-2">Total</th><th className="p-2">Acciones</th></tr></thead><tbody>{page?.items.map(i=><tr key={i.id} className="border-t"><td className="p-2">{i.number?`${i.number.series}/${i.number.year}/${String(i.number.sequence).padStart(6,'0')}`:`Borrador ${i.series} · ${i.issue_on}`}</td><td className="p-2"><Status value={i.status}/>{i.overdue&&<span className="ml-2 text-amber-700">Vencida</span>}</td><td className="p-2">{i.due_on??'Sin vencimiento'}</td><td className="p-2">{money(i.totals.total_minor,i.currency)}</td><td className="p-2"><button className={control} onClick={()=>loadInvoice(i.id)}>Abrir factura</button></td></tr>)}</tbody></table>{page?.next_id&&<button className={control} onClick={async()=>{try{setPage(await repository.billing('invoice.list',{limit:50,after_id:page.next_id!,...(status?{status:status as 'draft'|'issued'|'paid'|'trashed'|'overdue'}:{}),...(customerId?{customer_id:customerId}:{})}))}catch(e){setError(e)}}}>Siguiente página</button>}</section>
    {invoice&&!edit&&<section className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{invoice.number?`Factura ${invoice.number.series}/${invoice.number.year}/${String(invoice.number.sequence).padStart(6,'0')}`:'Borrador guardado'}</h2><Status value={invoice.status}/></div><p className="mt-2 text-sm">Total confirmado por el servidor: {money(invoice.totals.total_minor,invoice.currency)}</p><p className="mt-2 text-sm text-slate-500">{invoice.issuer?.legal_name??'Emisor pendiente'} · {invoice.customer_fiscal?.legal_name??'Datos fiscales pendientes'}</p><div className="mt-4 flex flex-wrap gap-2">{invoice.status==='draft'&&<><button className={control} disabled={busy} onClick={()=>{setError(null);pending.current=null;setEdit(invoiceForm(invoice))}}>Editar borrador</button><button className={primary} disabled={busy} onClick={()=>prepare('invoice.issue','Emitir factura')}>Emitir factura</button><button className={control} disabled={busy} onClick={()=>prepare('invoice.trash','Mover borrador a papelera')}>Mover a papelera</button></>}{invoice.status==='trashed'&&<button className={control} onClick={()=>prepare('invoice.restore','Restaurar borrador')}>Restaurar borrador</button>}{invoice.status==='issued'&&<button className={primary} onClick={()=>prepare('invoice.mark_paid','Registrar cobro')}>Marcar como cobrada</button>}{invoice.status==='paid'&&<button className={control} onClick={()=>prepare('invoice.reverse_payment','Revertir cobro')}>Revertir cobro</button>}<button className={control} disabled={busy} onClick={pdf}>Descargar PDF autorizado</button></div>{contentEnabled&&['issued','paid'].includes(invoice.status)&&<PrivateInvoicePdf key={invoice.id} invoice={invoice} onReload={()=>loadInvoice(invoice.id)}/>}</section>}
    {edit&&<InvoiceEditor initial={edit} customers={editorCustomers} links={links} issuer={initialCompany} integrated immutableCustomer={!!invoice} locked={busy||uncertain||conflict} serverError={error?safeMessage(error):undefined} onRetry={uncertain?()=>void runPending():undefined} onReload={conflict?async()=>{setEdit(null);pending.current=null;if(invoice)await loadInvoice(invoice.id);setMessage('Versión actual recargada. Revisa antes de volver a editar.')}:undefined} onSave={save} onClose={()=>{if(!busy){setEdit(null);pending.current=null;setError(null)}}}/>}
    {fiscal&&configuration&&<FiscalEditor kind={fiscal} configuration={configuration} customerId={customerId} busy={busy} error={error} onClose={()=>{if(!busy){setFiscal(null);pending.current=null}}} onSave={(profile)=>{if(fiscal==='issuer')void execute('issuer.set',{command_id:crypto.randomUUID(),expected_version:configuration.issuer?.version??0,profile,currency:configuration.issuer?.currency??'EUR',default_series:configuration.issuer?.default_series??'A'});else void execute('customer_fiscal.set',{command_id:crypto.randomUUID(),customer_id:customerId,expected_version:configuration.customer?.version??0,profile})}}/>}
    <ConfirmDialog open={!!confirm} title={confirm?.label??''} description={confirm?.operation==='invoice.issue'?'La emisión asignará un número oficial local y congelará los datos fiscales. Confirma únicamente tras revisar la factura.':'Confirma este cambio en la factura sintética local.'} loading={busy} error={error?safeMessage(error):null} onConfirm={()=>{if(confirm)void execute(confirm.operation,confirm.input)}} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</div>
}
function FiscalEditor({kind,configuration,customerId,busy,error,onSave,onClose}:{kind:'issuer'|'customer';configuration:Configuration;customerId:string;busy:boolean;error:unknown;onSave:(profile:BillingProfileV1)=>void;onClose:()=>void}){
  const [profile,setProfile]=useState<BillingProfileV1>(()=>(kind==='issuer'?configuration.issuer?.profile:configuration.customer?.profile)??{legal_name:'',tax_id:'',address:'',postal_code:'',city:'',region:'',country:'ES'})
  const uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
  void customerId
  return <Drawer title={kind==='issuer'?'Datos fiscales del emisor':'Datos fiscales del cliente'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(profile)}} className="space-y-4"><fieldset disabled={busy||uncertain||conflict} className="space-y-3">{(Object.keys(profile) as (keyof BillingProfileV1)[]).map(key=><label key={key} className="block text-sm">{{legal_name:'Razón social fiscal',tax_id:'Identificación fiscal',address:'Dirección fiscal',postal_code:'Código postal',city:'Ciudad',region:'Provincia',country:'País (ISO)'}[key]}<input className={`${control} mt-1 w-full`} required maxLength={key==='address'?300:key==='legal_name'?200:80} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}</fieldset>{!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}<button className={primary} disabled={busy||conflict}>{busy?'Guardando…':uncertain?'Reintentar la misma acción':'Guardar datos fiscales'}</button>{conflict&&<button type="button" className={control} onClick={onClose}>Cerrar y actualizar configuración</button>}</form></Drawer>
}
