'use client'
import { CustomerSelect } from '@/features/product/integration/CustomerSelect'
import { productDate } from '@/features/product/presentation'
import { useCallback, useEffect, useRef, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useProduct } from '@/features/product/integration/Provider'
import { ProductUiError, safeMessage } from '@/features/product/integration/repository'
import { PreviewNotice, control, primary, Drawer, Status, Kpis, PeriodSelect } from '@/features/product/ui'
import { calendarDate, type Period } from '@/features/product/model'
import type { BillingReadDataV1, BillingInvoiceV1, BillingReceiptV1, BillingOperationV1, BillingInputsV1, BillingProfileV1 } from '@/lib/contracts/billing-v1'
import { PrivateInvoicePdf } from './PrivateInvoicePdf'
import { InvoiceEditor } from './Editor'
import { InvoiceRows } from './InvoiceRows'
import { PromptBuilder } from './PromptBuilder'
import { blankForm, type InvoiceFormData, type InvoiceLink } from './model'
import { invoiceForm, normalizedInvoice, invoiceIssuerForm } from './integration'
type Configuration=Extract<BillingReadDataV1,{operation:'configuration.get'}>
type InvoicePage=Extract<BillingReadDataV1,{operation:'invoice.list'}>
type Summary=Extract<BillingReadDataV1,{operation:'invoice.summary'}>['invoice']
type Financial=Extract<BillingReadDataV1,{operation:'invoice.financial_summary'}>
type RegisteredInvoice={receipt:BillingReceiptV1;customerId:string}
const money=(minor:number,currency:string)=>new Intl.NumberFormat('es-ES',{style:'currency',currency}).format(minor/100)
export function IntegratedBilling({initialInvoiceId,initialCustomerId,contentEnabled=false,initialCreate=false}:{initialCreate?:boolean;initialInvoiceId?:string;initialCustomerId?:string;contentEnabled?:boolean}){
  const {repository,role}=useProduct(),authorized=role==='owner'||role==='admin'
  const [createCustomer,setCreateCustomer]=useState(initialCreate&&authorized),[newCustomer,setNewCustomer]=useState('')
  const [query,setQuery]=useState(''),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[customerId,setCustomerId]=useState(initialCustomerId??''),[status,setStatus]=useState(''),[period,setPeriod]=useState<Period>('month')
  const [pageState,setPageState]=useState<{key:string;data:InvoicePage}|null>(null),[financialState,setFinancial]=useState<Financial|null>(null),[configuration,setConfiguration]=useState<Configuration|null>(null),[invoice,setInvoice]=useState<BillingInvoiceV1|null>(null),[edit,setEdit]=useState<InvoiceFormData|null>(null),[fiscal,setFiscal]=useState<'issuer'|'customer'|null>(null)
  const [error,setError]=useState<unknown>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[confirm,setConfirm]=useState<{operation:BillingOperationV1;input:BillingInputsV1[BillingOperationV1];label:string}|null>(null)
  const [summary,setSummary]=useState<{id:string;data?:Summary;error?:string}|null>(null)
  const summaryRequest=useRef(0)
  async function readSummary(id:string){const request=++summaryRequest.current;setSummary({id});try{const result=await repository.billing('invoice.summary',{id});if(summaryRequest.current===request)setSummary({id,data:result.invoice})}catch(e){if(summaryRequest.current===request)setSummary({id,error:safeMessage(e)})}}
  const [paging,setPaging]=useState<{key:string;cursors:string[]}>({key:'',cursors:[]})
  const pageKey=JSON.stringify([customerId,status,reload]),cursors=paging.key===pageKey?paging.cursors:[],cursor=cursors.at(-1),pageQueryKey=JSON.stringify([pageKey,cursor??null]),page=pageState?.key===pageQueryKey?pageState.data:null,financial=financialState?.period===period?financialState:null
  const pending=useRef<{execute:()=>Promise<BillingReceiptV1>;customerId:string|null}|null>(null)
  const recorded=useRef<RegisteredInvoice|null>(null),[registered,setRegistered]=useState<RegisteredInvoice|null>(null)
  const [fiscalNeedsRefresh,setFiscalNeedsRefresh]=useState(false)
  const blocked=busy||!!registered
  const uncertain=!registered&&error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=!registered&&error instanceof ProductUiError&&error.code==='conflict'
  const selectedCustomerReady=customers.some(customer=>customer.id===customerId)
  const loadInvoice=useCallback(async(id:string)=>{if(recorded.current)return;try{setInvoice((await repository.billing('invoice.get',{id})).invoice);setError(null)}catch(e){setInvoice(null);setError(e)}},[repository])
  useEffect(()=>{if(!authorized)return;let active=true;void Promise.all([repository.billing('invoice.list',{limit:50,...(cursor?{after_id:cursor}:{}),...(status?{status:status as 'draft'|'issued'|'paid'|'trashed'|'overdue'}:{}),...(customerId?{customer_id:customerId}:{})}),repository.billing('invoice.financial_summary',{period}),repository.billing('configuration.get',customerId?{customer_id:customerId}:{})]).then(([p,f,c])=>{if(active){setPageState({key:pageQueryKey,data:p});setFinancial(f);setConfiguration(c)}}).catch(e=>{if(active){setPageState(null);setFinancial(null);setConfiguration(null);setError(e)}});return()=>{active=false}},[repository,authorized,customerId,status,period,reload,cursor,pageQueryKey])
  useEffect(()=>{if(!authorized||!initialInvoiceId)return;let current=true;void repository.billing('invoice.get',{id:initialInvoiceId}).then(v=>{if(current){setInvoice(v.invoice);setError(null)}}).catch(e=>{if(current){setInvoice(null);setError(e)}});return()=>{current=false}},[authorized,initialInvoiceId,repository])
  useEffect(()=>{if(!authorized||!initialCustomerId)return;let current=true;void repository.customer(initialCustomerId).then(c=>{if(current)setCustomers([{id:c.id,name:c.trade_name??c.legal_name}])}).catch(e=>{if(current){setCustomerId('');setError(e)}});return()=>{current=false}},[authorized,initialCustomerId,repository])
  async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{const result=await repository.search(query);setCustomers(result.items.filter(i=>i.kind==='customer').map(i=>({id:i.id,name:i.label})))}catch(e){setCustomers([]);setError(e)}finally{setBusy(false)}}
  async function execute(operation:BillingOperationV1,input:BillingInputsV1[BillingOperationV1]){
    if(busy||recorded.current||fiscalNeedsRefresh&&operation.endsWith('.set'))return;pending.current??={execute:()=>repository.billingCommand(operation,input),customerId:'customer_id'in input?input.customer_id:invoice?.customer_id??null};return runPending()
  }
  async function refreshFiscalConfiguration(){
    if(busy)return;setBusy(true);setError(null);pending.current=null
    try{const current=await repository.billing('configuration.get',customerId?{customer_id:customerId}:{});setConfiguration(current);setFiscalNeedsRefresh(false);setFiscal(null);setMessage('Configuración actual recargada. Revisa antes de volver a guardar.')}
    catch(e){setError(e)}finally{setBusy(false)}
  }
  async function readRegistered(){
    const saved=recorded.current;if(!saved)return
    const current=(await repository.billing('invoice.get',{id:saved.receipt.id})).invoice,receipt=saved.receipt
    const numberMatches=current.number?.series===receipt.number?.series&&current.number?.year===receipt.number?.year&&current.number?.sequence===receipt.number?.sequence
    if(current.id!==receipt.id||current.customer_id!==saved.customerId||current.version<receipt.version||current.version===receipt.version&&(current.status!==receipt.status||!numberMatches)||receipt.number!==null&&!numberMatches)throw new ProductUiError('internal_safe')
    setInvoice(current);setEdit(null);setFiscal(null);setConfirm(null);setError(null);recorded.current=null;setRegistered(null)
    setMessage(current.version>receipt.version?'Cambio registrado. Se muestra la versión actual de la factura.':receipt.operation==='invoice.issue'?'Factura emitida con numeración del servidor.':receipt.operation==='invoice.mark_paid'?'Cobro registrado.':receipt.operation==='invoice.reverse_payment'?'Cobro revertido.':'Cambio guardado en la base local.');setReload(v=>v+1)
  }
  async function refreshRegistered(){if(busy||!recorded.current)return;setBusy(true);setError(null);try{await readRegistered()}catch(e){setError(e)}finally{setBusy(false)}}
  async function runPending(){
    if(busy||recorded.current||!pending.current)return;setBusy(true);setError(null);setMessage('')
    try{const action=pending.current,receipt=await action.execute();pending.current=null;if(receipt.operation.startsWith('invoice.')){if(!action.customerId)throw new ProductUiError('internal_safe');const saved={receipt,customerId:action.customerId};recorded.current=saved;setRegistered(saved);setConfirm(null);if(!edit)setInvoice(null);await readRegistered()}else{setConfiguration(await repository.billing('configuration.get',customerId?{customer_id:customerId}:{}));setEdit(null);setFiscal(null);setConfirm(null);setMessage('Cambio guardado en la base local.');setReload(v=>v+1)}}
    catch(e){setError(e);if(fiscal&&e instanceof ProductUiError&&e.code==='conflict')setFiscalNeedsRefresh(true);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  function save(form:InvoiceFormData){try{const draft=normalizedInvoice(form);if(invoice&&invoice.status==='draft'){const {customer_id:discarded,...fields}=draft;void discarded;void execute('invoice.update_draft',{...fields,command_id:crypto.randomUUID(),id:invoice.id,expected_version:invoice.version})}else void execute('invoice.create_draft',{...draft,command_id:crypto.randomUUID()})}catch(e){setError(e)}}
  function prepare(operation:'invoice.issue'|'invoice.mark_paid'|'invoice.reverse_payment'|'invoice.trash'|'invoice.restore',label:string){if(!invoice||recorded.current)return;setError(null);pending.current=null;setConfirm({operation,label,input:{command_id:crypto.randomUUID(),id:invoice.id,expected_version:invoice.version}})}
  async function pdf(){if(!invoice)return;setBusy(true);setError(null);try{const blob=await repository.invoicePdf(invoice.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Factura_local_autorizada.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e)}finally{setBusy(false)}}
  const links:InvoiceLink[]=invoice?(['contractId','serviceId','opportunityId'] as const).flatMap(kind=>{const id={contractId:invoice.contract_id,serviceId:invoice.service_id,opportunityId:invoice.opportunity_id}[kind];return id?[{kind,id,customerId:invoice.customer_id,label:'Vínculo autorizado',...(kind==='serviceId'?{contractId:invoice.contract_id}:{})}]:[]}):[]
  const editorCustomers=invoice&&!customers.some(c=>c.id===invoice.customer_id)?[...customers,{id:invoice.customer_id,name:'Cliente de la factura'}]:customers
  return <div className="space-y-4"><PageHeader title="Facturación PRO" description="Facturas sintéticas guardadas, numeradas y calculadas por el servidor local"/><PreviewNotice/>{!authorized?<p className="text-sm text-slate-500">Facturación disponible para administradores del espacio.</p>:<>
    {createCustomer&&<Drawer title="Nueva factura" onClose={()=>setCreateCustomer(false)}><p className="text-sm text-slate-500">Selecciona la empresa para preparar un borrador. La factura se guardará únicamente tras tu revisión.</p><CustomerSelect value={newCustomer} onChange={setNewCustomer} inputLabel="Buscar empresa para factura"/><button className={primary} disabled={!newCustomer||blocked} onClick={async()=>{setBusy(true);setError(null);try{const [company,config]=await Promise.all([repository.customer(newCustomer),repository.billing('configuration.get',{customer_id:newCustomer})]);setCustomers(current=>[...current.filter(c=>c.id!==company.id),{id:company.id,name:company.trade_name??company.legal_name}]);setCustomerId(company.id);setConfiguration(config);setInvoice(null);setCreateCustomer(false);setEdit({...blankForm(),clientId:company.id,issueDate:calendarDate(new Date().toISOString()),series:config.issuer?.default_series??'A'})}catch(e){setError(e)}finally{setBusy(false)}}}>Preparar borrador</button>{!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}</Drawer>}
    {!!error&&!edit&&!fiscal&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}{message&&<p role="status" className="text-emerald-700">{message}</p>}{registered&&!edit&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p role="status" className="text-sm">El cambio está registrado. Consulta la factura para confirmar sus datos actuales.</p><button className={control} disabled={busy} onClick={()=>void refreshRegistered()}>Consultar factura registrada</button></div>}
    <div className="flex flex-wrap gap-3"><PeriodSelect value={period} onChange={setPeriod}/><select aria-label="Estado de facturas" className={control} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos los estados</option>{[['draft','Borradores'],['issued','Emitidas'],['paid','Cobradas'],['overdue','Vencidas'],['trashed','Papelera']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className={control} onClick={()=>setReload(v=>v+1)}>Actualizar facturas</button></div>
    {financial&&<p className="text-xs text-slate-500">Resumen del espacio · corte {productDate(financial.as_of)} · {financial.from?productDate(financial.from):'Desde el inicio'} — {financial.to?productDate(financial.to):'Sin límite'}. El filtro de cliente solo limita la lista de facturas.</p>}
    {financial?.currencies.map(c=><section key={c.currency} aria-label={`Importes financieros ${c.currency}`} className="rounded-xl border bg-white p-4"><h2 className="mb-3 font-semibold">{c.currency}</h2><Kpis items={(['issued_minor','paid_minor','outstanding_minor','overdue_minor'] as const).map(k=>({label:{issued_minor:'Facturado',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'}[k],value:money(c[k],c.currency)}))}/><div className="mt-4 space-y-3" role="list" aria-label={`Comparación de importes ${c.currency}`}>{(['issued_minor','paid_minor','outstanding_minor','overdue_minor'] as const).map(k=>{const label={issued_minor:'Facturado',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'}[k],maximum=Math.max(1,c.issued_minor,c.paid_minor,c.outstanding_minor,c.overdue_minor);return <div key={k} role="listitem"><div className="mb-1 flex justify-between gap-3 text-xs"><span>{label}</span><span className="font-medium">{money(c[k],c.currency)}</span></div><div className="h-2 overflow-hidden rounded bg-slate-100" aria-hidden="true"><div className="h-full rounded bg-indigo-500" style={{width:`${100*c[k]/maximum}%`}}/></div></div>})}</div><p className="mt-3 text-xs text-slate-500">Comparación dentro de {c.currency}. Vencido está incluido en Pendiente; las categorías no se suman. No se convierten divisas.</p></section>)}
    <section className="rounded-xl border bg-white p-4"><form onSubmit={search} className="flex flex-wrap gap-2"><input aria-label="Buscar cliente de factura" placeholder="Buscar empresa" required minLength={2} maxLength={100} className={control} value={query} onChange={e=>setQuery(e.target.value)}/><button className={control} disabled={busy}>Buscar cliente</button></form><div className="mt-3 flex flex-wrap gap-2"><select aria-label="Cliente para facturación" disabled={blocked} className={control} value={customerId} onChange={e=>{setCustomerId(e.target.value);setInvoice(null);setConfiguration(null)}}><option value="">Todo el espacio</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className={primary} disabled={!selectedCustomerReady||blocked} onClick={()=>{setError(null);setInvoice(null);pending.current=null;setEdit({...blankForm(),clientId:customerId,issueDate:calendarDate(new Date().toISOString()),series:configuration?.issuer?.default_series??'A'})}}>Nuevo borrador local</button><button className={control} disabled={blocked||!configuration} onClick={()=>{setError(null);pending.current=null;setFiscal('issuer')}}>Configurar emisor</button><button className={control} disabled={!customerId||blocked||!configuration} onClick={()=>{setError(null);pending.current=null;setFiscal('customer')}}>Datos fiscales del cliente</button></div><p className="mt-2 text-xs text-slate-500">Búsqueda limitada a cinco empresas. Los vínculos se consultan para el cliente seleccionado.</p>
    {customerId&&selectedCustomerReady&&!registered&&<PromptBuilder asOf={calendarDate(new Date().toISOString())} customers={customers.filter(c=>c.id===customerId)} onGenerate={async (result,source)=>{setError(null);try{const proposal=await repository.billing('invoice.propose',{source,draft:normalizedInvoice(result.draft)});if(!proposal.requires_review||proposal.saved)throw new ProductUiError('internal_safe');setInvoice(null);setEdit(result.draft);setMessage('Propuesta validada: requiere revisión. No se ha guardado ninguna factura.')}catch(e){setError(e)}}}/>}</section>
    <section className="overflow-x-auto rounded-xl border bg-white p-4"><InvoiceRows items={page?.items??[]} disabled={blocked} onSummary={id=>void readSummary(id)} onOpen={id=>void loadInvoice(id)}/>{!page&&!error&&<p role="status" className="py-4 text-sm text-slate-500">Cargando facturas…</p>}{page&&!page.items.length&&<p className="py-4 text-sm text-slate-500">No hay facturas en esta página con los filtros seleccionados.</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><button className={control} disabled={busy||!page||!cursors.length} onClick={()=>setPaging({key:pageKey,cursors:cursors.slice(0,-1)})}>Página anterior de facturas</button><span className="text-xs text-slate-500">Página {cursors.length+1} · Hasta 50 facturas</span><button className={control} disabled={busy||!page?.next_id} onClick={()=>{if(page?.next_id)setPaging({key:pageKey,cursors:[...cursors,page.next_id]})}}>Siguiente página de facturas</button></div></section>
    {summary&&<Drawer title="Resumen de factura" onClose={()=>{summaryRequest.current++;setSummary(null)}}>{summary.error?<><p role="alert" className="text-red-700">{summary.error}</p><button className={control} onClick={()=>void readSummary(summary.id)}>Reintentar resumen</button></>:!summary.data?<p role="status">Consultando resumen autorizado…</p>:<div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{summary.data.number?`${summary.data.number.series}/${summary.data.number.year}/${String(summary.data.number.sequence).padStart(6,'0')}`:'Borrador sin número'}</h2><Status value={summary.data.status}/></div><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">Fecha</dt><dd>{summary.data.issue_on}</dd></div><div><dt className="text-slate-500">Vencimiento</dt><dd>{summary.data.due_on??'Sin vencimiento'}</dd></div><div><dt className="text-slate-500">Total</dt><dd className="font-semibold">{money(summary.data.totals.total_minor,summary.data.currency)}</dd></div><div><dt className="text-slate-500">Situación</dt><dd>{summary.data.overdue?'Vencida':'Sin atraso publicado'}</dd></div></dl><p className="text-xs text-slate-500">Resumen actualizado sin datos fiscales ni conceptos completos.</p><button className={primary} onClick={()=>{const id=summary.id;summaryRequest.current++;setSummary(null);void loadInvoice(id)}}>Abrir detalle autorizado</button></div>}</Drawer>}
    {invoice&&!edit&&<section data-invoice-detail-id={invoice.id} data-invoice-detail-version={invoice.version} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{invoice.number?`Factura ${invoice.number.series}/${invoice.number.year}/${String(invoice.number.sequence).padStart(6,'0')}`:'Borrador guardado'}</h2><Status value={invoice.status}/></div><p className="mt-2 text-sm">Total confirmado por el servidor: {money(invoice.totals.total_minor,invoice.currency)}</p><p className="mt-2 text-sm text-slate-500">{invoice.issuer?.legal_name??'Emisor pendiente'} · {invoice.customer_fiscal?.legal_name??'Datos fiscales pendientes'}</p><div className="mt-4 flex flex-wrap gap-2">{invoice.status==='draft'&&<><button className={control} disabled={busy} onClick={()=>{setError(null);pending.current=null;setEdit(invoiceForm(invoice))}}>Editar borrador</button><button className={primary} disabled={busy} onClick={()=>prepare('invoice.issue','Emitir factura')}>Emitir factura</button><button className={control} disabled={busy} onClick={()=>prepare('invoice.trash','Mover borrador a papelera')}>Mover a papelera</button></>}{invoice.status==='trashed'&&<button className={control} onClick={()=>prepare('invoice.restore','Restaurar borrador')}>Restaurar borrador</button>}{invoice.status==='issued'&&<button className={primary} onClick={()=>prepare('invoice.mark_paid','Registrar cobro')}>Marcar como cobrada</button>}{invoice.status==='paid'&&<button className={control} onClick={()=>prepare('invoice.reverse_payment','Revertir cobro')}>Revertir cobro</button>}<button className={control} disabled={busy} onClick={pdf}>Descargar PDF autorizado</button></div>{contentEnabled&&['issued','paid'].includes(invoice.status)&&<PrivateInvoicePdf key={invoice.id} invoice={invoice} onReload={()=>loadInvoice(invoice.id)}/>}</section>}
    {edit&&<InvoiceEditor initial={edit} customers={editorCustomers} links={links} issuer={invoiceIssuerForm(invoice?.issuer??configuration?.issuer?.profile)} integrated authorizedRelations immutableCustomer={!!invoice} locked={blocked||uncertain||conflict} serverError={error?safeMessage(error):undefined} onReadRecorded={registered?()=>void refreshRegistered():undefined} readingRecorded={busy} onRetry={uncertain?()=>void runPending():undefined} onReload={conflict?async()=>{setEdit(null);pending.current=null;if(invoice)await loadInvoice(invoice.id);setMessage('Versión actual recargada. Revisa antes de volver a editar.')}:undefined} onSave={save} onClose={()=>{if(!blocked){setEdit(null);pending.current=null;setError(null)}}}/>}
    {fiscal&&configuration&&<FiscalEditor kind={fiscal} configuration={configuration} customerId={customerId} busy={busy} error={error} requiresReload={fiscalNeedsRefresh} onReload={()=>void refreshFiscalConfiguration()} onClose={()=>{if(!busy){setFiscal(null);pending.current=null}}} onSave={(profile)=>{if(fiscal==='issuer')void execute('issuer.set',{command_id:crypto.randomUUID(),expected_version:configuration.issuer?.version??0,profile,currency:configuration.issuer?.currency??'EUR',default_series:configuration.issuer?.default_series??'A'});else void execute('customer_fiscal.set',{command_id:crypto.randomUUID(),customer_id:customerId,expected_version:configuration.customer?.version??0,profile})}}/>}
    <ConfirmDialog open={!!confirm} title={confirm?.label??''} description={confirm?.operation==='invoice.issue'?'La emisión asignará un número del servidor local y congelará los datos fiscales. Confirma únicamente tras revisar la factura.':'Confirma este cambio en la factura sintética local.'} loading={busy} error={error?safeMessage(error):null} onConfirm={()=>{if(confirm)void execute(confirm.operation,confirm.input)}} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</div>
}
function FiscalEditor({kind,configuration,customerId,busy,error,requiresReload,onReload,onSave,onClose}:{kind:'issuer'|'customer';configuration:Configuration;customerId:string;busy:boolean;error:unknown;requiresReload:boolean;onReload:()=>void;onSave:(profile:BillingProfileV1)=>void;onClose:()=>void}){
  const [profile,setProfile]=useState<BillingProfileV1>(()=>(kind==='issuer'?configuration.issuer?.profile:configuration.customer?.profile)??{legal_name:'',tax_id:'',address:'',postal_code:'',city:'',region:'',country:'ES'})
  const uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
  void customerId
  return <Drawer title={kind==='issuer'?'Datos fiscales del emisor':'Datos fiscales del cliente'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(profile)}} className="space-y-4"><fieldset disabled={busy||uncertain||conflict||requiresReload} className="space-y-3">{(Object.keys(profile) as (keyof BillingProfileV1)[]).map(key=><label key={key} className="block text-sm">{{legal_name:'Razón social fiscal',tax_id:'Identificación fiscal',address:'Dirección fiscal',postal_code:'Código postal',city:'Ciudad',region:'Provincia',country:'País (ISO)'}[key]}<input className={`${control} mt-1 w-full`} required maxLength={key==='address'?300:key==='legal_name'?200:80} value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}</fieldset>{!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}<button className={primary} disabled={busy||conflict||requiresReload}>{busy?'Guardando…':uncertain?'Reintentar la misma acción':'Guardar datos fiscales'}</button>{(conflict||requiresReload)&&<button type="button" className={control} disabled={busy} onClick={onReload}>Cerrar y actualizar configuración</button>}</form></Drawer>
}
