'use client'
import {useEffect,useRef,useState}from 'react'
import {useProduct}from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage}from '@/features/product/integration/repository'
import {control}from '@/features/product/ui'
import type {BillingInvoiceV1}from '@/lib/contracts/billing-v1'
import type {BillingArtifactInputV1,BillingArtifactReferenceV1}from '@/lib/contracts/billing-artifact-v1'
export function PrivateInvoicePdf({invoice,onReload}:{invoice:BillingInvoiceV1;onReload:()=>Promise<void>}){
 const {repository}=useProduct(),[reference,setReference]=useState<BillingArtifactReferenceV1|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[retryPending,setRetryPending]=useState(false)
 const pending=useRef<BillingArtifactInputV1|null>(null)
 const uncertain=retryPending&&error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
 useEffect(()=>{let active=true
 void repository.privateInvoiceReference(invoice.id).then(r=>{if(active){setReference(r);setLoaded(true);setError(null)}}).catch(e=>{if(active){if(e instanceof ProductUiError&&e.code==='not_found'){setReference(null);setLoaded(true);setError(null)}else setError(e)}})
 return()=>{active=false}},[repository,invoice.id,invoice.version,revision])
 async function persist(){if(busy||!loaded)return;pending.current??=Object.freeze({command_id:crypto.randomUUID(),id:invoice.id,expected_version:invoice.version,expected_artifact_version:reference?.version??0});setBusy(true);setError(null);setRetryPending(false)
 try{await repository.persistPrivateInvoice(pending.current);pending.current=null;setLoaded(false);setRevision(v=>v+1)}catch(e){setError(e);setRetryPending(e instanceof ProductUiError&&e.code==='transport_uncertain');if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}}
 async function download(){if(busy||!reference)return;setBusy(true);setError(null);try{const blob=await repository.privateInvoicePdf(invoice.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Factura_fiscal_privada.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e)}finally{setBusy(false)}}
 return <section aria-label="PDF fiscal privado" className="mt-4 rounded-lg border bg-slate-50 p-4"><h3 className="font-semibold">PDF fiscal privado</h3><p className="mt-1 text-sm text-slate-600">La factura ya está emitida. Este archivo conserva sus datos fiscales congelados y se verifica al descargarlo.</p>{loaded&&<p role="status" className="mt-2 text-sm">{reference?reference.document_status==='archived'?'El documento está archivado. Revisa su estado en Documentos.':'Copia conservada; verificación de integridad requerida en cada descarga.':'Copia privada pendiente de conservar. La factura mantiene su número.'}</p>}{!!error&&<p role="alert" className="mt-2 text-red-700">{safeMessage(error)}</p>}<div className="mt-3 flex flex-wrap gap-2">{loaded&&!reference&&<button className={control} disabled={busy||conflict} onClick={()=>void persist()}>{uncertain?'Reintentar conservación':'Conservar PDF fiscal privado'}</button>}{reference?.document_status==='active'&&<button className={control} disabled={busy||uncertain||conflict} onClick={()=>void download()}>Descargar PDF fiscal privado</button>}<button className={control} disabled={busy||uncertain} onClick={()=>{pending.current=null;setRetryPending(false);setLoaded(false);void onReload();setRevision(v=>v+1)}}>Actualizar estado del PDF</button></div>{conflict&&<p className="mt-2 text-sm">Actualiza también la factura antes de reintentar; se conservará la versión vigente.</p>}</section>
}
