'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { PreviewNotice, control, primary, Status } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { safeMessage, ProductUiError } from '@/features/product/integration/repository'
import { canManageTarget } from '@/lib/workspace-roles'
import type { TeamListV1, TeamAssignableRoleV1, TeamInputsV1, TeamOperationV1, TeamReceiptV1 } from '@/lib/contracts/team-v1'
export function IntegratedSettings(){
  const {repository,role,actorId}=useProduct(),canManage=role==='owner'||role==='admin'
  const [data,setData]=useState<TeamListV1|null>(null),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState<TeamAssignableRoleV1>('member'),[roles,setRoles]=useState<Record<string,TeamAssignableRoleV1>>({})
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<TeamReceiptV1|null>(null),[confirm,setConfirm]=useState<{label:string;operation:TeamOperationV1;input:TeamInputsV1[TeamOperationV1]}|null>(null)
  const pending=useRef<{execute:()=>Promise<TeamReceiptV1>}|null>(null)
  const load=useCallback(async()=>{if(!canManage)return;try{setData(await repository.team());setRoles({});setError('')}catch(e){setData(null);setError(safeMessage(e))}},[repository,canManage])
  useEffect(()=>{if(!canManage)return;let active=true;void repository.team().then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(safeMessage(e))});return()=>{active=false}},[repository,canManage])
  async function execute(){if(!confirm||busy)return;setBusy(true);setError('');pending.current??={execute:()=>repository.teamCommand(confirm.operation,confirm.input)}
    try{const result=await pending.current.execute();pending.current=null;setReceipt(result);setEmail('');await load();setConfirm(null)}
    catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  function prepare(label:string,operation:TeamOperationV1,input:Omit<TeamInputsV1[TeamOperationV1],'command_id'>){if(busy)return;pending.current=null;setError('');setConfirm({label,operation,input:{...input,command_id:crypto.randomUUID()} as TeamInputsV1[TeamOperationV1]})}
  return <div className="space-y-4"><PageHeader title="Configuración" description="Equipo y funciones disponibles en el entorno local"/><PreviewNotice/>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Equipo</h2>{!canManage?<p className="mt-2 text-sm text-slate-500">Gestión disponible para administradores del espacio.</p>:<><button className={`${control} mt-3`} onClick={load}>Actualizar equipo</button>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}
    <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Usuario</th><th className="p-2">Rol</th><th className="p-2">Estado</th><th className="p-2">Acciones</th></tr></thead><tbody>{data?.items.map(m=>{const manageable=m.role!=='owner'&&m.user_id!==actorId&&role&&canManageTarget(role,m.role);return <tr key={m.id} className="border-t"><td className="p-2">{m.user_id===actorId?'Tú':`Usuario ${m.user_id.slice(0,8)}`}</td><td className="p-2">{manageable&&m.status!=='removed'?<select disabled={busy} aria-label={`Rol de usuario ${m.user_id.slice(0,8)}`} className={control} value={roles[m.id]??m.role} onChange={e=>setRoles({...roles,[m.id]:e.target.value as TeamAssignableRoleV1})}>{role==='owner'&&<option value="admin">Administrador</option>}<option value="member">Miembro</option><option value="viewer">Lector</option></select>:m.role}</td><td className="p-2"><Status value={m.status}/></td><td className="p-2">{manageable&&m.status!=='removed'&&<div className="flex flex-wrap gap-2">{roles[m.id]&&roles[m.id]!==m.role&&<button disabled={busy} className={control} onClick={()=>prepare('Cambiar rol','member.role_change',{id:m.id,expected_version:m.version,role:roles[m.id]} as Omit<TeamInputsV1['member.role_change'],'command_id'>)}>Guardar rol</button>}<button disabled={busy} className={control} onClick={()=>prepare(m.status==='active'?'Suspender acceso':'Reactivar acceso',m.status==='active'?'member.suspend':'member.resume',{id:m.id,expected_version:m.version})}>{m.status==='active'?'Suspender':'Reactivar'}</button><button disabled={busy} className={control} onClick={()=>prepare('Retirar acceso','member.remove',{id:m.id,expected_version:m.version})}>Retirar</button></div>}</td></tr>})}</tbody></table></div>{data?.next_id&&<p className="mt-2 text-xs text-amber-800">Lista parcial: primeros 100 miembros. Paginación pendiente.</p>}
    <form className="mt-5 flex flex-wrap gap-2 border-t pt-4" onSubmit={e=>{e.preventDefault();prepare('Preparar invitación','member.invite_intent',{email:email.trim().toLowerCase(),role:inviteRole} as Omit<TeamInputsV1['member.invite_intent'],'command_id'>)}}><input disabled={busy} aria-label="Correo para invitación" type="email" required maxLength={320} className={control} value={email} onChange={e=>setEmail(e.target.value)}/><select disabled={busy} aria-label="Rol de invitación" className={control} value={inviteRole} onChange={e=>setInviteRole(e.target.value as TeamAssignableRoleV1)}>{role==='owner'&&<option value="admin">Administrador</option>}<option value="member">Miembro</option><option value="viewer">Lector</option></select><button disabled={busy} className={primary}>Preparar invitación</button></form><p className="mt-2 text-xs text-slate-500">Registra una intención interna. No envía correo ni concede acceso.</p>
    {receipt&&<div role="status" className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{receipt.operation==='member.invite_intent'?'Invitación preparada. No se ha enviado correo.':'Cambio de equipo guardado.'}{receipt.operation==='member.invite_intent'&&receipt.status==='pending'&&<button className={`${control} ml-2`} onClick={()=>prepare('Cancelar invitación preparada','member.cancel_invite',{id:receipt.id,expected_version:receipt.version})}>Cancelar invitación</button>}</div>}
    <ConfirmDialog open={!!confirm} title={confirm?.label??''} description="Confirma el cambio en el equipo sintético local." loading={busy} error={error} onConfirm={execute} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Empresa e integraciones</h2><p className="mt-2 text-sm text-slate-500">Configuración de empresa pendiente de conectar. Cambios desactivados.</p><p className="mt-2 text-sm text-slate-500">Proveedores de correo, WhatsApp, Instagram y automatizaciones: no conectados. No se realizan envíos ni pruebas externas.</p></section>
  </div>
}
