'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import {useWorkspaceIdentity} from '@/components/WorkspaceIdentityProvider'
import { PageHeader } from '@/components/PageHeader'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { PreviewNotice, Tabs, Unavailable, control, primary, Status } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { safeMessage, ProductUiError } from '@/features/product/integration/repository'
import { canManageTarget } from '@/lib/workspace-roles'
import type { TeamListV1, TeamAssignableRoleV1, TeamInputsV1, TeamOperationV1, TeamReceiptV1 } from '@/lib/contracts/team-v1'
export function IntegratedSettings(){
  const {repository,role,actorId}=useProduct(),canManage=role==='owner'||role==='admin'
  const {currentUser}=useWorkspaceIdentity(),[area,setArea]=useState('Equipo y roles'),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0)
  const [data,setData]=useState<TeamListV1|null>(null),[email,setEmail]=useState(''),[inviteRole,setInviteRole]=useState<TeamAssignableRoleV1>('member'),[roles,setRoles]=useState<Record<string,TeamAssignableRoleV1>>({})
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<TeamReceiptV1|null>(null),[confirm,setConfirm]=useState<{label:string;operation:TeamOperationV1;input:TeamInputsV1[TeamOperationV1]}|null>(null)
  const pending=useRef<{execute:()=>Promise<TeamReceiptV1>}|null>(null)
  const load=useCallback(async()=>{setData(null);setRoles({});setCursors([]);setRevision(v=>v+1)},[])
  useEffect(()=>{if(!canManage)return;let active=true;void repository.team({limit:100,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(active){setData(v);setError('')}}).catch(e=>{if(active){setData(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,canManage,cursors,revision])
  async function execute(){if(!confirm||busy)return;setBusy(true);setError('');pending.current??={execute:()=>repository.teamCommand(confirm.operation,confirm.input)}
    try{const result=await pending.current.execute();pending.current=null;setReceipt(result);setEmail('');await load();setConfirm(null)}
    catch(e){setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  function prepare(label:string,operation:TeamOperationV1,input:Omit<TeamInputsV1[TeamOperationV1],'command_id'>){if(busy)return;pending.current=null;setError('');setConfirm({label,operation,input:{...input,command_id:crypto.randomUUID()} as TeamInputsV1[TeamOperationV1]})}
  return <div className="space-y-4"><PageHeader title="Configuración" description="Identidad, equipo, datos fiscales y estado de las conexiones"/><PreviewNotice/><Tabs prefix="settings-" items={['Perfil','Empresa','Datos fiscales','Equipo y roles','Integraciones','Seguridad','Notificaciones','Facturación','Asistente IA']} value={area} onChange={setArea}/><section role="tabpanel" id={`settings-panel-${area}`} aria-labelledby={`settings-tab-${area}`}>
    {area==='Equipo y roles'?<section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Equipo</h2>{!canManage?<p className="mt-2 text-sm text-slate-500">Gestión disponible para administradores del espacio.</p>:<><button className={`${control} mt-3`} onClick={load}>Actualizar equipo</button>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}
    <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Usuario</th><th className="p-2">Rol</th><th className="p-2">Estado</th><th className="p-2">Acciones</th></tr></thead><tbody>{data?.items.map(m=>{const manageable=m.role!=='owner'&&m.user_id!==actorId&&role&&canManageTarget(role,m.role);return <tr key={m.id} className="border-t"><td className="p-2">{m.user_id===actorId?'Tú':`Usuario ${m.user_id.slice(0,8)}`}</td><td className="p-2">{manageable&&m.status!=='removed'?<select disabled={busy} aria-label={`Rol de usuario ${m.user_id.slice(0,8)}`} className={control} value={roles[m.id]??m.role} onChange={e=>setRoles({...roles,[m.id]:e.target.value as TeamAssignableRoleV1})}>{role==='owner'&&<option value="admin">Administrador</option>}<option value="member">Miembro</option><option value="viewer">Lector</option></select>:{owner:'Titular',admin:'Administrador',member:'Miembro',viewer:'Lector'}[m.role]}</td><td className="p-2"><Status value={m.status}/></td><td className="p-2">{manageable&&m.status!=='removed'&&<div className="flex flex-wrap gap-2">{roles[m.id]&&roles[m.id]!==m.role&&<button disabled={busy} className={control} onClick={()=>prepare('Cambiar rol','member.role_change',{id:m.id,expected_version:m.version,role:roles[m.id]} as Omit<TeamInputsV1['member.role_change'],'command_id'>)}>Guardar rol</button>}<button disabled={busy} className={control} onClick={()=>prepare(m.status==='active'?'Suspender acceso':'Reactivar acceso',m.status==='active'?'member.suspend':'member.resume',{id:m.id,expected_version:m.version})}>{m.status==='active'?'Suspender':'Reactivar'}</button><button disabled={busy} className={control} onClick={()=>prepare('Retirar acceso','member.remove',{id:m.id,expected_version:m.version})}>Retirar</button></div>}</td></tr>})}</tbody></table></div>{!data&&!error&&<p role="status" className="mt-3 text-sm text-slate-500">Cargando equipo…</p>}<div className="mt-4 flex flex-wrap items-center gap-3"><button className={control} disabled={busy||!cursors.length} onClick={()=>{setData(null);setCursors(v=>v.slice(0,-1))}}>Página anterior del equipo</button><span className="text-xs text-slate-500">Página {cursors.length+1} · Hasta 100 miembros</span><button className={control} disabled={busy||!data?.next_id} onClick={()=>{if(data?.next_id){setCursors(v=>[...v,data.next_id!]);setData(null)}}}>Siguiente página del equipo</button></div>
    <form className="mt-5 flex flex-wrap gap-2 border-t pt-4" onSubmit={e=>{e.preventDefault();prepare('Preparar invitación','member.invite_intent',{email:email.trim().toLowerCase(),role:inviteRole} as Omit<TeamInputsV1['member.invite_intent'],'command_id'>)}}><input disabled={busy} aria-label="Correo para invitación" type="email" required maxLength={320} className={control} value={email} onChange={e=>setEmail(e.target.value)}/><select disabled={busy} aria-label="Rol de invitación" className={control} value={inviteRole} onChange={e=>setInviteRole(e.target.value as TeamAssignableRoleV1)}>{role==='owner'&&<option value="admin">Administrador</option>}<option value="member">Miembro</option><option value="viewer">Lector</option></select><button disabled={busy} className={primary}>Preparar invitación</button></form><p className="mt-2 text-xs text-slate-500">Registra una intención interna. No envía correo ni concede acceso.</p>
    {receipt&&<div role="status" className="mt-3 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{receipt.operation==='member.invite_intent'?'Invitación preparada. No se ha enviado correo.':'Cambio de equipo guardado.'}{receipt.operation==='member.invite_intent'&&receipt.status==='pending'&&<button className={`${control} ml-2`} onClick={()=>prepare('Cancelar invitación preparada','member.cancel_invite',{id:receipt.id,expected_version:receipt.version})}>Cancelar invitación</button>}</div>}
    <ConfirmDialog open={!!confirm} title={confirm?.label??''} description="Confirma el cambio en el equipo sintético local." loading={busy} error={error} onConfirm={execute} onCancel={()=>{if(!busy){setConfirm(null);pending.current=null}}}/></>}</section>
    :area==='Perfil'?<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Tu perfil</h2><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Nombre de la sesión</dt><dd className="mt-1 text-sm">{currentUser.isAuthenticated&&!currentUser.isFallback?currentUser.name:'No disponible'}</dd></div><div><dt className="text-xs text-slate-500">Rol actual</dt><dd className="mt-1 text-sm">{role?{owner:'Titular',admin:'Administrador',member:'Miembro',viewer:'Lector'}[role]:'No disponible'}</dd></div></dl><Unavailable title="Edición de perfil pendiente">La actualización de datos personales todavía no está habilitada.</Unavailable></section>
    :area==='Empresa'?<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Empresa y espacio de trabajo</h2><p className="text-sm">{currentUser.isAuthenticated&&!currentUser.isFallback?currentUser.workspaceName:'Nombre no disponible'}</p><Unavailable title="Edición de empresa pendiente">Nombre comercial, logo y contacto general necesitan una configuración autorizada. No se guardan cambios temporales como si fueran definitivos.</Unavailable></section>
    :area==='Datos fiscales'||area==='Facturación'?<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">{area==='Datos fiscales'?'Identidad fiscal del emisor':'Facturación y series'}</h2><p className="text-sm text-slate-500">La configuración fiscal, numeración y datos del emisor se consultan y revisan en Facturación PRO. La emisión y el pago requieren confirmaciones separadas.</p>{canManage?<Link href="/facturacion" className={primary}>Abrir configuración de Facturación PRO</Link>:<Unavailable title="Acceso fiscal restringido">Disponible para los responsables del espacio.</Unavailable>}<p className="text-xs text-slate-500">Suscripción, cobros del plan y portal de pago del CRM no están conectados.</p></section>
    :area==='Integraciones'?<section className="grid gap-3 md:grid-cols-2">{[['Google Calendar','Selección y sincronización del calendario por usuario.','Pendiente de conexión'],['Correo y WhatsApp','Mensajería y notificaciones externas.','Pendiente de conexión'],['Automatizaciones internas','Reglas para nuevos clientes que crean tareas o avisos dentro del espacio.','Procesamiento manual autorizado'],['Inbox interno','Conversaciones, notas y lectura por el equipo autorizado.','Disponible en integración local'],['Documentos','Metadatos y archivos privados con permisos revisados en cada acceso.','Acceso autorizado por documento']].map(([name,description,state])=><article key={name} className="space-y-2 rounded-xl border bg-white p-4"><h2 className="font-semibold">{name}</h2><p className="text-xs font-medium text-indigo-700">{state}</p><p className="text-sm text-slate-500">{description}</p>{name==='Automatizaciones internas'?<Link href="/automations" className="inline-block text-sm font-semibold text-indigo-700">Ver reglas internas</Link>:name==='Inbox interno'?<Link href="/inbox" className="inline-block text-sm font-semibold text-indigo-700">Abrir Inbox interno</Link>:name==='Documentos'?<Link href="/documents" className="inline-block text-sm font-semibold text-indigo-700">Abrir documentos</Link>:<button className={control} disabled>Conectar</button>}</article>)}</section>
    :area==='Seguridad'?<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Acceso y seguridad</h2><p className="text-sm text-slate-500">Las acciones requieren sesión activa y permisos actuales del equipo. Suspender o retirar un miembro revoca su acceso a los datos protegidos.</p><Unavailable title="Gestión de seguridad pendiente">Cambio de contraseña, segundo factor y listado de dispositivos aún no están habilitados desde esta pantalla.</Unavailable></section>
    :area==='Notificaciones'?<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Notificaciones</h2><p className="text-sm text-slate-500">Los avisos personales muestran tareas vencidas y los resultados internos de reglas autorizadas. La revisión de tareas se ejecuta cuando la solicitas.</p>{role!=='viewer'?<button className={primary} onClick={()=>window.dispatchEvent(new Event('crm-notifications-open'))}>Abrir notificaciones personales</button>:<Unavailable title="Avisos restringidos">Disponible para miembros activos del equipo.</Unavailable>}<Unavailable title="Preferencias pendientes">La selección de canales, avisos y resumen por correo no está conectada.</Unavailable></section>
    :<section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Asistente IA</h2><p className="text-sm text-slate-500">El asistente integrado está en preparación. Las consultas, confirmaciones y cambios mediante IA permanecen desactivados.</p><Link href="/assistant" className={primary}>Abrir asistente</Link></section>}
    </section></div>
}
