'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage,type SettingsReceipt,type SettingsRead} from '@/features/product/integration/repository'
import type {ProductPreferencesV1,CompanyProfileV1,SettingsInputV1,SettingsOperationV1} from '@/lib/contracts/settings-v1'
import type {DocumentListV1,DocumentMetadataV1} from '@/lib/contracts/document-v1'
import {CustomerSelect} from '@/features/product/integration/CustomerSelect'
import {DocumentImagePreview} from '@/features/documents/DocumentImagePreview'
import {control,primary,Unavailable} from '@/features/product/ui'
type Profile=ProductPreferencesV1|CompanyProfileV1
type Record=Extract<SettingsRead,{operation:'settings.profile_get'|'settings.company_get'}>
type Pending={operation:SettingsOperationV1;input:SettingsInputV1;receipt?:SettingsReceipt}
const locales=[['es-ES','Español (España)'],['en-GB','Inglés (Reino Unido)'],['en-US','Inglés (Estados Unidos)']]
function FormatFields({timezone,locale,change}:{timezone:string;locale:string;change:(key:'timezone'|'locale',value:string)=>void}){return <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm">Zona horaria preferida<input aria-label="Zona horaria preferida" list="product-settings-zones" className={`${control} mt-1 w-full`} required maxLength={100} value={timezone} onChange={e=>change('timezone',e.target.value)}/><datalist id="product-settings-zones"><option value="Europe/Madrid"/><option value="UTC"/><option value="Europe/London"/></datalist></label><label className="block text-sm">Formato regional<select aria-label="Formato regional" className={`${control} mt-1 w-full`} value={locale} onChange={e=>change('locale',e.target.value)}>{locales.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div>}
export function ProductSettingsPanel({kind,notificationsOnly=false}:{kind:'profile'|'company';notificationsOnly?:boolean}){
 const {repository,role}=useProduct(),operation=kind==='profile'?'settings.profile_get':'settings.company_get',canWrite=kind==='profile'||role==='owner'||role==='admin'
 const [record,setRecord]=useState<Record|null>(null),[draft,setDraft]=useState<Profile|null>(null),[error,setError]=useState<unknown>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[conflict,setConflict]=useState(false),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),pending=useRef<Pending|null>(null),readAttempt=useRef(0)
 const [logoPreview,setLogoPreview]=useState<DocumentMetadataV1|null>(null)
 const load=useCallback(async()=>{const attempt=++readAttempt.current;setLoading(true);setError(null);setRecord(null);setDraft(null);try{const v=await repository.settings(operation);if(readAttempt.current===attempt){setRecord(v);setDraft(v.profile);pending.current=null;setUncertain(false);setConflict(false)}}catch(e){if(readAttempt.current===attempt)setError(e)}finally{if(readAttempt.current===attempt)setLoading(false)}},[repository,operation])
 useEffect(()=>{let active=true;const attempt=readAttempt;queueMicrotask(()=>{if(active)void load()});return()=>{active=false;attempt.current++}},[load])
 async function save(){if(busy||!record||!draft||!canWrite||conflict)return;setBusy(true);setError(null);setNotice('');try{
  if(!pending.current){const profile=Object.fromEntries(Object.entries(draft).map(([k,v])=>[k,typeof v==='string'&&k!=='timezone'&&k!=='locale'?v.trim()||null:v])) as Profile;pending.current={operation:kind==='profile'?'settings.profile_update':'settings.company_update',input:Object.freeze({command_id:crypto.randomUUID(),expected_version:record.version,profile:Object.freeze(profile)})}}
  const p=pending.current;p.receipt??=await repository.settingsCommand(p.operation,p.input);const fresh=await repository.settings(operation);if(fresh.version<p.receipt.version)throw new ProductUiError('internal_safe');setRecord(fresh);setDraft(fresh.profile);pending.current=null;setUncertain(false);setNotice(kind==='company'?'Datos de empresa guardados y comprobados.':'Preferencias guardadas y comprobadas.');window.dispatchEvent(new Event('crm-product-display-changed'));window.dispatchEvent(new Event('crm-notifications-changed'))
 }catch(e){setError(pending.current?.receipt?new ProductUiError('transport_uncertain'):e);setUncertain(!!pending.current?.receipt||e instanceof ProductUiError&&e.code==='transport_uncertain');if(!pending.current?.receipt&&!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null;if(e instanceof ProductUiError&&e.code==='conflict')setConflict(true);if(e instanceof ProductUiError&&['access_denied','not_found'].includes(e.code)){setRecord(null);setDraft(null)}}finally{setBusy(false)}}
 const locked=busy||uncertain||conflict,change=(key:string,value:unknown)=>setDraft(d=>d?{...d,[key]:value}:d)
 return <section className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">{kind==='company'?'Datos de empresa':notificationsOnly?'Avisos personales':'Preferencias personales'}</h2><p className="text-sm text-slate-500">{kind==='company'?'Perfil del espacio. La identidad fiscal se mantiene en Facturación PRO.':'Estas preferencias pertenecen a tu usuario. No cambian las credenciales ni la identidad de acceso.'}</p>{loading&&<p role="status" className="text-sm text-slate-500">Consultando configuración autorizada…</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{!!error&&<p role="alert" className="text-sm text-red-700">{safeMessage(error)}</p>}
 {draft&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={locked||!canWrite} className="space-y-4">{kind==='profile'?<>{!notificationsOnly&&<><label className="block text-sm">Nombre para mostrar<input aria-label="Nombre para mostrar" className={`${control} mt-1 w-full`} maxLength={100} value={(draft as ProductPreferencesV1).display_name??''} onChange={e=>change('display_name',e.target.value)}/></label><FormatFields timezone={draft.timezone} locale={draft.locale} change={change}/></>}<label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" aria-label="Recibir nuevos avisos internos" checked={(draft as ProductPreferencesV1).notification_preferences.in_app} onChange={e=>change('notification_preferences',{in_app:e.target.checked})}/><span>Recibir nuevos avisos internos<p className="mt-1 text-xs text-slate-500">Al desactivarlo se omiten nuevos avisos de tareas y reglas. Los avisos anteriores siguen disponibles. No activa correo ni mensajes externos.</p></span></label></>:<>{([['trade_name','Nombre comercial',200],['business_name','Razón social de empresa',200],['business_email','Correo empresarial',320],['phone','Teléfono empresarial',40],['website','Web empresarial HTTPS',500],['address','Dirección empresarial',500],['description','Descripción de empresa',1000]] as const).map(([key,label,max])=><label className="block text-sm" key={key}>{label}{key==='description'?<textarea aria-label={label} className={`${control} mt-1 w-full`} maxLength={max} value={(draft as CompanyProfileV1)[key]??''} onChange={e=>change(key,e.target.value)}/>:<input aria-label={label} type={key==='business_email'?'email':key==='website'?'url':'text'} className={`${control} mt-1 w-full`} maxLength={max} value={(draft as CompanyProfileV1)[key]??''} onChange={e=>change(key,e.target.value)}/>}</label>)}<FormatFields timezone={draft.timezone} locale={draft.locale} change={change}/>{canWrite&&<LogoSelector value={(draft as CompanyProfileV1).logo_document_id} onChange={id=>change('logo_document_id',id)} disabled={locked}/>}</>}</fieldset>
 {canWrite&&<button className={primary} disabled={busy||conflict} type="submit">{busy?'Guardando…':uncertain?'Comprobar el mismo cambio':kind==='company'?'Guardar empresa':'Guardar preferencias'}</button>}{!canWrite&&<p className="text-xs text-slate-500">Consulta autorizada. La edición requiere un responsable del espacio.</p>}
 </form>}{kind==='company'&&(draft as CompanyProfileV1|null)?.logo_document_id&&<div className="flex flex-wrap gap-2"><p className="text-xs text-slate-500">Logo asociado a un archivo privado. Sin certificación de contenido.</p>{canWrite&&<button type="button" className={control} disabled={locked} onClick={async()=>{try{setLogoPreview((await repository.document((draft as CompanyProfileV1).logo_document_id!)).record)}catch(e){setError(e)}}}>Consultar logo privado</button>}</div>}
 {(!draft&&!loading||conflict)&&<button className={control} disabled={busy||uncertain} onClick={()=>void load()}>{conflict?'Recargar versión actual y descartar cambios':'Reintentar configuración'}</button>}{logoPreview&&<DocumentImagePreview document={logoPreview} onClose={()=>setLogoPreview(null)}/>}</section>
}
function LogoSelector({value,onChange,disabled}:{value:string|null;onChange:(id:string|null)=>void;disabled:boolean}){
 const {repository}=useProduct(),[customer,setCustomer]=useState(''),[state,setState]=useState<{customer:string;data?:DocumentListV1;error?:string}|null>(null)
 useEffect(()=>{if(!customer)return;let active=true;void repository.documents({target_kind:'customer',target_id:customer,status:'active',limit:20}).then(data=>{if(active)setState({customer,data})}).catch(e=>{if(active)setState({customer,error:safeMessage(e)})});return()=>{active=false}},[repository,customer]);const current=state?.customer===customer?state:null
 return <div className="space-y-3 rounded-lg border border-slate-100 p-4"><h3 className="text-sm font-semibold">Logo privado</h3><p className="text-xs text-slate-500">Selecciona un PNG o JPEG activo ya subido a una empresa. Se consultan hasta20 documentos; los PDF quedan excluidos.</p><CustomerSelect value={customer} onChange={setCustomer} disabled={disabled}/>{current?.error&&<p role="alert" className="text-sm text-red-700">{current.error}</p>}{customer&&!current?.data&&!current?.error&&<p role="status" className="text-sm text-slate-500">Consultando imágenes privadas…</p>}{current?.data&&<label className="block text-sm">Imagen para logo<select aria-label="Imagen para logo" className={`${control} mt-1 w-full`} disabled={disabled} value={value??''} onChange={e=>onChange(e.target.value||null)}><option value="">Sin logo</option>{value&&!current.data.items.some(d=>d.id===value)&&<option value={value}>Logo actual</option>}{current.data.items.filter(d=>['image/png','image/jpeg'].includes(d.media_type??'')).map((d,i)=><option key={d.id} value={d.id}>Imagen {i+1} · {d.media_type==='image/png'?'PNG':'JPEG'} · {d.size_bytes??'Tamaño desconocido'} bytes</option>)}</select></label>}{value&&<button className={control} type="button" disabled={disabled} onClick={()=>onChange(null)}>Quitar asociación de logo</button>}{current?.data?.next_id&&<p className="text-xs text-amber-700">Hay más documentos; la selección de logo muestra la primera página.</p>}</div>
}
const providerLabels={google_calendar:'Google Calendar',auth_mail:'Correo de acceso',crm_mail:'Correo del CRM',whatsapp:'WhatsApp',n8n:'n8n',ai_provider:'Proveedor IA',storage:'Archivos privados'}
export function ProductIntegrationStatuses(){const {repository}=useProduct(),[data,setData]=useState<Extract<SettingsRead,{operation:'settings.integrations'}>|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{let active=true;void repository.settings('settings.integrations').then(v=>{if(active){setData(v);setError('')}}).catch(e=>{if(active){setData(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,revision]);return <section className="space-y-4"><button className={control} onClick={()=>{setData(null);setRevision(v=>v+1)}}>Actualizar estados de integración</button>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:!data?<p role="status" className="text-sm text-slate-500">Consultando estados autorizados…</p>:<div className="grid gap-3 sm:grid-cols-2">{data.integrations.map(p=><article key={p.class} className="space-y-2 rounded-xl border bg-white p-4"><h2 className="font-semibold">{providerLabels[p.class]}</h2><p className="text-sm font-medium text-indigo-700">{p.status==='configured'?'Configuración disponible':p.status==='unavailable'?'No disponible':'Sin configurar'}</p><p className="text-xs text-slate-500">{p.class==='storage'?'Configuración del transporte privado. Cada archivo comprueba de nuevo tus permisos.':'No hay un adaptador externo conectado. Las acciones externas están desactivadas.'}</p></article>)}</div>}<Unavailable title="Conexiones externas pendientes">La configuración no demuestra conexión ni salud del proveedor. OAuth, correo, WhatsApp, n8n y proveedor IA siguen pendientes.</Unavailable></section>}
