'use client'
import {useEffect,useRef,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import type {TeamInviteListV1,TeamInputsV1,TeamReceiptV1} from '@/lib/contracts/team-v1'
import {control,Status} from '@/features/product/ui'
import {ConfirmDialog} from '@/components/ConfirmDialog'
type Intent={operation:'member.reissue_invite'|'member.cancel_invite';input:TeamInputsV1['member.reissue_invite'];receipt?:TeamReceiptV1}
export function TeamInvitations({revision}:{revision:number}){
 const {repository,role}=useProduct(),[data,setData]=useState<TeamInviteListV1|null>(null),[cursors,setCursors]=useState<string[]>([]),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[intent,setIntent]=useState<Intent|null>(null),[notice,setNotice]=useState(''),pending=useRef<Intent|null>(null)
 useEffect(()=>{let alive=true;void repository.teamInvites({limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(alive){setData(v);setError('')}}).catch(e=>{if(alive){setData(null);setError(safeMessage(e))}});return()=>{alive=false}},[repository,cursors,refresh,revision])
 function reload(){setData(null);setCursors([]);setRefresh(v=>v+1);setError('')}
 function prepare(operation:Intent['operation'],row:TeamInviteListV1['items'][number]){if(busy||intent)return;pending.current=null;setError('');setIntent({operation,input:Object.freeze({command_id:crypto.randomUUID(),id:row.id,expected_version:row.version})})}
 async function execute(){if(!intent||busy)return;setBusy(true);setError('');pending.current??=intent;try{const p=pending.current;p.receipt??=await repository.teamCommand(p.operation,p.input);const fresh=await repository.teamInvites({limit:20});setData(fresh);setCursors([]);setNotice(p.operation==='member.reissue_invite'?'Intención renovada por siete días. No se ha enviado correo.':'Intención de invitación cancelada.');pending.current=null;setIntent(null)}catch(e){setData(null);setError(safeMessage(e));if(!(e instanceof ProductUiError&&e.code==='transport_uncertain')&&!pending.current?.receipt)pending.current=null}finally{setBusy(false)}}
 return <section aria-label="Invitaciones internas" className="mt-5 space-y-3 border-t pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Invitaciones internas</h3><button className={control} disabled={busy||!!intent} onClick={reload}>Actualizar invitaciones</button></div><p className="text-xs text-slate-500">Las intenciones caducan a los siete días. Renovarlas no envía correo ni concede acceso.</p>{error&&!intent&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-emerald-700">{notice}</p>}{!data&&!error&&<p role="status">Cargando invitaciones…</p>}{data&&!data.items.length&&<p className="text-sm text-slate-500">Sin invitaciones en esta página.</p>}{data?.items.map(r=><article data-invite-id={r.id} key={r.id} className="rounded-lg border p-3"><p className="break-all text-sm font-medium">{r.email}</p><div className="my-2 flex flex-wrap gap-2 text-xs"><Status value={r.status}/><span>{r.role}</span><span>Caduca: {new Date(r.expires_at).toLocaleString('es-ES')}</span></div>{r.status!=='cancelled'&&(r.role!=='admin'||role==='owner')&&<div className="flex flex-wrap gap-2">{r.status==='expired'&&<button className={control} disabled={busy||!!intent} onClick={()=>prepare('member.reissue_invite',r)}>Renovar intención caducada</button>}<button className={control} disabled={busy||!!intent} onClick={()=>prepare('member.cancel_invite',r)}>Cancelar intención</button></div>}</article>)}<div className="flex flex-wrap items-center gap-2"><button className={control} disabled={!cursors.length||busy||!!intent} onClick={()=>{setData(null);setCursors(v=>v.slice(0,-1))}}>Página anterior de invitaciones</button><span className="text-xs">Página {cursors.length+1} · Hasta 20 intenciones</span><button className={control} disabled={!data?.next_id||busy||!!intent} onClick={()=>{if(data?.next_id){setData(null);setCursors(v=>[...v,data.next_id!])}}}>Siguiente página de invitaciones</button></div><ConfirmDialog open={!!intent} title={intent?.operation==='member.reissue_invite'?'Renovar intención caducada':'Cancelar intención de invitación'} description="Revisa el cambio. No se enviará correo ni se concederá acceso." loading={busy} error={error} onConfirm={execute} onCancel={()=>{if(!busy){pending.current=null;setIntent(null);if(error)reload()}}}/></section>
}
