'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage,type InboxPage} from '@/features/product/integration/repository'
import {control,Status} from '@/features/product/ui'
export function CustomerCommunications({customerId}:{customerId:string}){const {role}=useProduct();return role==='viewer'?<p className="rounded-xl border bg-white p-4 text-sm text-slate-500">Acceso restringido. Las conversaciones internas requieren permisos comerciales.</p>:<LinkedConversations key={customerId} customerId={customerId}/>}
function LinkedConversations({customerId}:{customerId:string}){
 const {repository}=useProduct(),[page,setPage]=useState<InboxPage|null>(null),[cursors,setCursors]=useState<string[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{let active=true;void repository.inbox({limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(active){setPage(v);setError('')}}).catch(e=>{if(active){setPage(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,cursors,revision])
 const linked=page?.items.filter(r=>r.customer_id===customerId)??[]
 return <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Comunicaciones internas</h2><button className={control} onClick={()=>{setPage(null);setError('');setRevision(v=>v+1)}}>Actualizar comunicaciones</button></div><p className="text-xs text-slate-500">Conversaciones vinculadas a esta empresa en la página autorizada del Inbox. Hasta 20 conversaciones por página; las demás pueden aparecer en páginas posteriores. No se consultan los cuerpos de las notas.</p>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:!page?<p role="status" className="text-sm text-slate-500">Consultando conversaciones…</p>:linked.length?<ul className="divide-y divide-slate-100">{linked.map(r=><li key={r.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><Status value={r.status}/><p className="mt-1 text-xs text-slate-500">{r.unread?'Sin leer':'Leída'} · Última actualización: {new Date(r.updated_at).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}</p></div><Link className={control} href={'/inbox?id='+r.id}>Abrir conversación interna</Link></li>)}</ul>:<p className="text-sm text-slate-500">No hay conversaciones vinculadas en esta página.</p>}<div className="flex flex-wrap justify-between gap-2"><button className={control} disabled={!page||!cursors.length} onClick={()=>{setPage(null);setError('');setCursors(v=>v.slice(0,-1))}}>Conversaciones anteriores</button><span className="text-xs text-slate-500">Página {cursors.length+1}</span><button className={control} disabled={!page?.next_id} onClick={()=>{if(page?.next_id){setPage(null);setError('');setCursors(v=>[...v,page.next_id!])}}}>Más conversaciones</button></div><p className="text-xs text-slate-500">Correo empresarial y WhatsApp no están conectados; no se realizan envíos.</p></section>
}
