'use client'
import {useEffect,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {IntegratedDocuments} from '@/features/documents/IntegratedDocuments'
import {control} from '@/features/product/ui'
import type {DocumentTargetKindV1} from '@/lib/contracts/document-v1'
type Kind='customer'|'contract'|'service'|'line'|'opportunity'|'case'
type Page={items:{id:string;label:string}[];next_id:string|null}
export function CustomerDocuments({customerId}:{customerId:string}){const {role}=useProduct();return role==='owner'||role==='admin'?<DocumentTargets key={customerId} customerId={customerId}/>:<p className="rounded-xl border bg-white p-4 text-sm text-slate-500">Acceso restringido. Los documentos requieren permisos de administración.</p>}
function DocumentTargets({customerId}:{customerId:string}){
 const {repository}=useProduct(),[kind,setKind]=useState<Kind>('customer'),[target,setTarget]=useState(customerId),[page,setPage]=useState<Page|null>(null),[cursors,setCursors]=useState<string[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{if(kind==='customer')return;let active=true;void(async()=>{const input={customer_id:customerId,limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})},result=kind==='case'?await repository.telecom('case.list',input):await repository.collection((kind+'.list') as 'contract.list'|'service.list'|'line.list'|'opportunity.list',input);const items=result.items.map((r,i)=>({id:r.id,label:'display_name'in r?r.display_name:'title'in r?r.title:'Contrato · '+('start_date'in r?r.start_date:'registro '+(i+1))}));if(active){setPage({items,next_id:result.next_id});setError('')}})().catch(e=>{if(active){setPage(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,customerId,kind,cursors,revision])
 return <div className="space-y-4"><section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-semibold">Documentos de la empresa y sus registros</h2><p className="text-xs text-slate-500">Cada destino tiene su propia colección paginada. El resumen incluye documentos de descendientes; esta vista no mezcla destinos ni inventa una colección única.</p><div className="flex flex-wrap gap-2"><select aria-label="Destino de documentos del cliente" className={control} value={kind} onChange={e=>{const next=e.target.value as Kind;setKind(next);setTarget(next==='customer'?customerId:'');setPage(null);setError('');setCursors([])}}>{(['customer','contract','service','line','opportunity','case'] as const).map(k=><option key={k} value={k}>{{customer:'Empresa',contract:'Contratos',service:'Servicios',line:'Líneas',opportunity:'Oportunidades',case:'Incidencias'}[k]}</option>)}</select>{kind!=='customer'&&<select aria-label="Registro para documentos del cliente" className={control} value={target} disabled={!page} onChange={e=>setTarget(e.target.value)}><option value="">Seleccionar registro</option>{page?.items.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select>}</div>{kind!=='customer'&&<div className="flex flex-wrap gap-2"><button className={control} disabled={!page||!cursors.length} onClick={()=>{setTarget('');setPage(null);setCursors(v=>v.slice(0,-1))}}>Destinos anteriores</button><button className={control} disabled={!page?.next_id} onClick={()=>{if(page?.next_id){setTarget('');setPage(null);setCursors(v=>[...v,page.next_id!])}}}>Más destinos</button></div>}{error&&<div><p role="alert" className="text-sm text-red-700">{error}</p><button className={control} onClick={()=>{setError('');setRevision(v=>v+1)}}>Reintentar destinos</button></div>}{kind!=='customer'&&!page&&!error&&<p role="status" className="text-sm text-slate-500">Consultando destinos…</p>}{page&&!page.items.length&&<p className="text-sm text-slate-500">No hay destinos de este tipo en esta página.</p>}</section>{target&&<IntegratedDocuments key={kind+':'+target} customerId={customerId} initialTarget={{kind:kind==='case'?'service_case':kind as DocumentTargetKindV1,id:target,label:kind==='customer'?'Empresa seleccionada':page?.items.find(r=>r.id===target)?.label??'Registro seleccionado'}}/>}</div>
}
