'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {control,Kpis,Status} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
import {attentionReasons,attentionHref} from '@/features/attention/presentation'
import type {TelecomReadResultV1} from '@/lib/contracts/telecom-reads-v1'
import type {TelecomAttentionPageV1} from '@/lib/contracts/telecom-attention-v1'
const labels={renewal:'Renovación',permanence:'Permanencia',case:'Incidencia',task:'Tarea',meeting:'Reunión',opportunity:'Oportunidad',portability:'Portabilidad'}
const priorities={urgent:'Urgente',high:'Alta',normal:'Normal',low:'Baja'}
export function Customer360Overview({customerId}:{customerId:string}){
 const {repository}=useProduct(),[summary,setSummary]=useState<TelecomReadResultV1<'customer360.summary'>|null>(null),[attention,setAttention]=useState<TelecomAttentionPageV1|null>(null),[error,setError]=useState(''),[attentionError,setAttentionError]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{let active=true;void repository.telecom('customer360.summary',{customer_id:customerId}).then(v=>{if(active){setSummary(v);setError('')}}).catch(e=>{if(active){setSummary(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,customerId,revision])
 useEffect(()=>{let active=true;const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid'}).format(new Date()),shift=(days:number)=>new Date(Date.parse(today+'T12:00:00Z')+days*86400000).toISOString().slice(0,10);void repository.telecom('telecom.attention',{customer_id:customerId,window_from:shift(-30),window_to:shift(30),limit:5}).then(v=>{if(active){setAttention(v);setAttentionError('')}}).catch(e=>{if(active){setAttention(null);setAttentionError(safeMessage(e))}});return()=>{active=false}},[repository,customerId,revision])
 return <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm" aria-label="Resumen real del cliente"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Visión comercial</h2><button className={control} onClick={()=>{setSummary(null);setAttention(null);setError('');setAttentionError('');setRevision(v=>v+1)}}>Actualizar resumen</button></div>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:!summary?<p role="status" className="text-sm text-slate-500">Consultando el resumen del cliente…</p>:<><Kpis compact items={[{label:'Contratos',value:summary.record.contracts},{label:'Servicios',value:summary.record.services},{label:'Líneas',value:summary.record.lines},{label:'SIM/eSIM',value:summary.record.sims},{label:'Portabilidades',value:summary.record.portabilities},{label:'Oportunidades',value:summary.record.opportunities},{label:'Incidencias',value:summary.record.cases},{label:'Renovaciones / permanencias',value:summary.record.renewals+' / '+summary.record.permanences}]}/><p className="text-xs text-slate-500">Recuentos completos del cliente, incluidos los estados históricos. Comprobados a {productDate(summary.as_of)}. Documentos: {summary.record.documents??'Acceso restringido'} · Facturación: {summary.record.billing??'Acceso restringido'} · Tareas: {summary.record.tasks} · Reuniones: {summary.record.meetings}</p></>}<details className="border-t border-slate-100 pt-3"><summary className="cursor-pointer text-sm font-semibold">Prioridades del cliente{attention ? " · "+attention.items.length+" en esta página" : ""}</summary><p className="mb-3 text-xs text-slate-500">Página de hasta cinco asuntos; consulta completa en el centro de atención. Ventana: últimos y próximos 30 días; las reglas de prioridad las determina el servicio.</p>{attentionError?<p role="alert" className="text-sm text-red-700">{attentionError}</p>:!attention?<p role="status" className="text-sm text-slate-500">Consultando prioridades…</p>:attention.items.length?<ul className="grid gap-2 sm:grid-cols-2">{attention.items.map(r=><li key={r.kind+':'+r.id} className="rounded-lg border border-slate-200 p-3 text-sm"><div className="flex justify-between gap-2"><span className="font-semibold">{labels[r.kind]}</span><span className={r.priority==='urgent'?'text-red-700':'text-amber-700'}>{priorities[r.priority]}</span></div><p className="mt-1 text-xs text-slate-500">{attentionReasons[r.reason_code]}</p><p className="mt-1 text-xs text-slate-500">{productDate(r.due_on)} · <Status value={r.status}/></p><Link className="mt-2 inline-flex text-xs font-semibold text-indigo-700" href={attentionHref(r)}>Abrir contexto</Link></li>)}</ul>:<p className="text-sm text-slate-500">No hay prioridades en esta ventana.</p>}<Link className="mt-3 inline-flex text-xs font-semibold text-indigo-700" href="/attention">Abrir centro de atención</Link></details></section>
}
