'use client'
import Link from 'next/link'
import { IntegratedCalendar } from '@/features/calendar/IntegratedCalendar'
import { IntegratedDocuments } from '@/features/documents/IntegratedDocuments'
import { IntegratedBilling } from '@/features/billing/IntegratedBilling'
import { control, Status } from '@/features/product/ui'
import type { CustomerEditorV1 } from '@/lib/contracts/product-v1'
export const customerAreas=['Resumen','Empresa','Contactos','Contratos','Servicios','Líneas','Renovaciones','Permanencias','Oportunidades','Agenda','Documentos','Facturación','Actividad','Comunicaciones']
export function CustomerIntegratedPanels({customer,area}:{customer:CustomerEditorV1;area:string}){
 if(area==='Agenda'||area==='Renovaciones'||area==='Permanencias')return <IntegratedCalendar customerId={customer.id}/>
 if(area==='Documentos')return <IntegratedDocuments customerId={customer.id}/>
 if(area==='Facturación')return <IntegratedBilling initialCustomerId={customer.id}/>
 if(area==='Contactos')return null
 if(area==='Empresa')return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Datos de empresa</h2><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Razón social</dt><dd>{customer.legal_name}</dd></div><div><dt className="text-slate-500">Nombre comercial</dt><dd>{customer.trade_name??'Sin nombre comercial'}</dd></div><div><dt className="text-slate-500">Relación comercial</dt><dd>{{lead:'Lead',prospect:'Prospecto',customer:'Cliente',former_customer:'Antiguo cliente'}[customer.lifecycle]}</dd></div><div><dt className="text-slate-500">Estado</dt><dd><Status value={customer.status}/></dd></div><div><dt className="text-slate-500">Origen</dt><dd>{customer.source}</dd></div><div><dt className="text-slate-500">Responsable</dt><dd>{customer.assigned_user_id?'Responsable asignado':'Sin asignar'}</dd></div></dl></section>
 if(area==='Resumen')return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Customer 360</h2><p className="mt-2 text-sm text-slate-500">Empresa, contactos, agenda, documentos y facturación consultan sus servicios autorizados. La cobertura de agenda está limitada al intervalo visible. El resumen conjunto de activos y actividad aún está pendiente.</p><div className="mt-3 flex flex-wrap gap-2"><Link className={control} href={`/documents?customer=${customer.id}`}>Documentos del cliente</Link><Link className={control} href={`/facturacion?customer=${customer.id}`}>Facturación del cliente</Link><Link className={control} href={`/assistant?customer=${customer.id}`}>Consultar este cliente</Link><Link className={control} href={`/assistant?customer=${customer.id}&intent=invoice`}>Crear factura con IA</Link></div></section>
 return <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{area}</h2><p className="mt-2 text-sm text-slate-500">{['Contratos','Servicios','Líneas','Oportunidades'].includes(area)?'La colección completa vinculada al cliente requiere un servicio de lectura con alcance y paginación. La búsqueda global disponible tiene cobertura limitada y no sustituye este inventario.':area==='Actividad'?'El historial transversal del cliente aún no dispone de lectura normal aceptada.':'El servicio de comunicaciones aún no está disponible; no se ejecutan envíos.'}</p>{['Contratos','Servicios','Líneas','Oportunidades'].includes(area)&&<Link className={`${control} mt-3 inline-flex`} href={area==='Oportunidades'?'/opportunities':'/portfolio'}>Consultar en el módulo</Link>}</section>
}
