'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {MessageSquare,Plus,ArrowLeft,RefreshCw,ExternalLink} from 'lucide-react'
import {PageHeader} from '@/components/PageHeader'
import {useProduct} from '@/features/product/integration/Provider'
import {CustomerSelect} from '@/features/product/integration/CustomerSelect'
import {ProductUiError,safeMessage,type InboxPage,type InboxThread} from '@/features/product/integration/repository'
import {control,primary,Drawer,Empty,Unavailable,PreviewNotice} from '@/features/product/ui'
import type {InboxInputV1,InboxOperationV1,InboxReceiptV1,InboxStatusV1} from '@/lib/contracts/inbox-v1'
import type {TeamMemberV1} from '@/lib/contracts/team-v1'
import type {ContactEditorPageV1} from '@/lib/contracts/product-v1'
const statuses={open:'Abiertas',closed:'Cerradas',archived:'Archivadas'}
const date=(v:string)=>new Intl.DateTimeFormat('es-ES',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Madrid'}).format(new Date(v))
type Intent={operation:InboxOperationV1;input:InboxInputV1;receipt?:InboxReceiptV1}
/** Internal notes only. Every refresh reauthorizes private bodies; no persistent client cache. */
export function IntegratedInbox(){
 const {repository,role,actorId}=useProduct(),manager=role==='owner'||role==='admin',allowed=manager||role==='member'
 const [status,setStatus]=useState<InboxStatusV1>('open'),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[list,setList]=useState<{key:string;data?:InboxPage;error?:string}|null>(null),[unread,setUnread]=useState<number|null>(null)
 const [selected,setSelected]=useState<string|null>(null),[messageCursors,setMessageCursors]=useState<number[]>([]),[thread,setThread]=useState<{key:string;data?:InboxThread;error?:string}|null>(null),[roster,setRoster]=useState<readonly TeamMemberV1[]>([])
 const [draft,setDraft]=useState(''),[create,setCreate]=useState(false),[newCustomer,setNewCustomer]=useState(''),[newAssignee,setNewAssignee]=useState(actorId??''),[linkCustomer,setLinkCustomer]=useState(''),[linkContact,setLinkContact]=useState(''),[contactPages,setContactPages]=useState<{customer:string;data:ContactEditorPageV1}|null>(null),[contactsError,setContactsError]=useState('')
 const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),intent=useRef<Intent|null>(null)
 const listKey=JSON.stringify([status,cursors.at(-1)??null,revision]),threadKey=JSON.stringify([selected,messageCursors.at(-1)??null,revision])
 const page=list?.key===listKey?list.data:undefined,current=thread?.key===threadKey?thread.data:undefined,record=current?.conversation
 useEffect(()=>{if(!allowed)return;let active=true;const input={status,limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})};void repository.inbox(input).then(data=>{if(active)setList({key:listKey,data})}).catch(e=>{if(active)setList({key:listKey,error:safeMessage(e)})});void repository.inboxUnread().then(v=>{if(active)setUnread(v.unread_count)}).catch(()=>{if(active)setUnread(null)});return()=>{active=false}},[repository,allowed,status,cursors,listKey])
 useEffect(()=>{if(!selected||!allowed)return;let active=true;void repository.inboxThread({id:selected,limit:20,...(messageCursors.length?{after_seq:messageCursors.at(-1)}:{})}).then(data=>{if(active)setThread({key:threadKey,data})}).catch(e=>{if(active)setThread({key:threadKey,error:safeMessage(e)})});return()=>{active=false}},[repository,allowed,selected,messageCursors,threadKey])
 useEffect(()=>{if(!manager)return;let active=true;void repository.team().then(v=>{if(active)setRoster(v.items.filter(m=>m.status==='active'&&m.role!=='viewer'))}).catch(()=>{});return()=>{active=false}},[repository,manager])
 useEffect(()=>{if(!linkCustomer)return;let active=true;void repository.contacts(linkCustomer).then(data=>{if(active){setContactPages({customer:linkCustomer,data});setContactsError('')}}).catch(e=>{if(active)setContactsError(safeMessage(e))});return()=>{active=false}},[repository,linkCustomer])
 function refresh(){setThread(null);setList(null);setRevision(v=>v+1)}
 function choose(id:string){if(busy||uncertain)return;setSelected(id);setMessageCursors([]);setThread(null);setDraft('');setLinkCustomer('');setLinkContact('');setError('');setNotice('')}
 async function run(next:Intent){if(busy)return;intent.current=next;setBusy(true);setUncertain(false);setError('');setNotice('');try{
  const receipt=next.receipt??await repository.inboxCommand(next.operation,next.input);next.receipt=receipt
  // Read the committed state before presenting success; a reassignment may revoke this actor's access.
  let fresh:InboxThread|null=null
  try{fresh=await repository.inboxThread({id:receipt.id,limit:20})}catch(e){if(e instanceof ProductUiError&&['access_denied','not_found'].includes(e.code)){setSelected(null);setThread(null)}else throw e}
  intent.current=null;setUncertain(false);setDraft('');setCreate(false);setMessageCursors([]);setList(null);setRevision(v=>v+1)
  if(fresh){setSelected(receipt.id);setStatus(fresh.conversation.status);setCursors([])}
  setNotice('Cambio guardado. La conversación se ha actualizado.')
 }catch(e){setError(next.receipt?'El cambio está guardado. Falta comprobar su estado actual.':safeMessage(e));const retry=!!next.receipt||e instanceof ProductUiError&&e.code==='transport_uncertain';setUncertain(retry);if(!retry){intent.current=null;if(e instanceof ProductUiError&&['conflict','access_denied','not_found'].includes(e.code))refresh()}}finally{setBusy(false)}}
 function command(operation:InboxOperationV1,fields:Record<string,unknown>={}){if(!record||busy||uncertain)return;void run({operation,input:Object.freeze({command_id:crypto.randomUUID(),id:record.id,expected_version:operation==='conversation.mark_read'||operation==='conversation.mark_unread'?record.read_version:record.version,...fields})})}
 const locked=busy||uncertain
 const members=manager?roster:[{user_id:actorId??'',role:'member'}]
 async function nextContacts(){const next=contactPages?.data.next_id;if(!next||contactPages?.customer!==linkCustomer)return;try{const data=await repository.contacts(linkCustomer,next);setContactPages(v=>v?.customer===linkCustomer?{customer:linkCustomer,data:{...data,items:[...v.data.items,...data.items]}}:v)}catch(e){setContactsError(safeMessage(e))}}
 if(!allowed)return <div className="space-y-4"><PageHeader title="Inbox interno" description="Conversaciones y notas del equipo."/><Unavailable title="Acceso restringido">Las notas internas están disponibles para los miembros asignados y los responsables del espacio.</Unavailable></div>
 return <div className="space-y-4"><PreviewNotice/><PageHeader title="Inbox interno" description="Notas compartidas, seguimiento y contexto del cliente. No envía mensajes externos." action={<button className={primary} disabled={locked} onClick={()=>{setDraft('');setNewCustomer('');setNewAssignee(actorId??'');setCreate(true);setError('')}}><Plus size={16}/>Nueva conversación</button>}/>
 <div className="flex flex-wrap items-center gap-3 text-sm"><span className="rounded-full bg-indigo-50 px-3 py-1 font-medium text-indigo-700">{unread===null?'Pendientes de leer: no disponibles':`${unread} conversaciones sin leer`}</span><span className="text-slate-500">Canal interno · Integraciones externas sin configurar</span><button className={`${control} ml-auto`} disabled={locked} onClick={refresh}><RefreshCw className="inline mr-1" size={14}/>Actualizar Inbox</button></div>
 {error&&<div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}{uncertain&&<button className={`${control} ml-2`} disabled={busy} onClick={()=>{if(intent.current)void run(intent.current)}}>Comprobar la misma acción</button>}</div>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}
 <div className="grid min-h-[550px] min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white lg:grid-cols-[280px_minmax(0,1fr)_260px]">
 <section aria-label="Conversaciones" className={`${selected?'hidden lg:block':''} min-w-0 border-r border-slate-200`}><div className="p-4"><label className="text-sm">Estado de conversaciones<select aria-label="Estado de conversaciones" className={`${control} mt-2 w-full`} value={status} disabled={locked} onChange={e=>{setStatus(e.target.value as InboxStatusV1);setCursors([]);setSelected(null);setThread(null)}}>{Object.entries(statuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div>
 {list?.key===listKey&&list.error?<p role="alert" className="p-4 text-sm text-red-700">{list.error}</p>:!page?<p role="status" className="p-4 text-sm text-slate-500">Cargando conversaciones…</p>:!page.items.length?<Empty text="No hay conversaciones en esta página."/>:<ul>{page.items.map(c=><li key={c.id}><button data-conversation-id={c.id} disabled={locked} onClick={()=>choose(c.id)} className={`w-full border-t border-slate-100 p-4 text-left hover:bg-slate-50 ${selected===c.id?'bg-indigo-50':''}`}><div className="flex items-center gap-2 text-sm font-semibold"><MessageSquare size={16}/><span>Conversación {c.id.slice(0,8)}</span>{c.unread&&<span aria-label="Sin leer" className="h-2 w-2 rounded-full bg-indigo-600"/>}</div><p className="mt-2 text-xs text-slate-500">{date(c.updated_at)} · {c.last_seq} notas</p><p className="mt-1 text-xs text-slate-500">{c.customer_id?'Con cliente vinculado':'Sin cliente vinculado'}</p></button></li>)}</ul>}
 <div className="flex items-center justify-between gap-2 border-t p-3"><button className={control} disabled={locked||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anterior</button><span className="text-xs">{cursors.length+1}</span><button className={control} disabled={locked||!page?.next_id} onClick={()=>{if(page?.next_id)setCursors(v=>[...v,page.next_id!])}}>Siguiente</button></div></section>
 <section aria-label="Hilo interno" className={`${!selected?'hidden lg:flex lg:items-center lg:justify-center':''} min-w-0`}>
 {!selected?<Empty text="Selecciona una conversación o crea una nota interna."/>:<><div className="flex flex-wrap items-center gap-3 border-b p-4"><button className={`${control} lg:hidden`} disabled={locked} onClick={()=>{setSelected(null);setThread(null)}}><ArrowLeft size={16}/>Conversaciones</button><h2 className="font-semibold">Notas internas</h2>{record&&<><span className="text-xs text-slate-500">{statuses[record.status]}</span><button className={`${control} ml-auto`} disabled={locked} onClick={()=>command(record.unread?'conversation.mark_read':'conversation.mark_unread')}>{record.unread?'Marcar leído':'Marcar no leído'}</button></>}</div>
 {thread?.key===threadKey&&thread.error?<p role="alert" className="p-4 text-sm text-red-700">{thread.error}</p>:!current?<p role="status" className="p-4 text-sm text-slate-500">Cargando notas autorizadas…</p>:<><ol className="space-y-4 p-4">{current.messages.map(m=><li data-message-seq={m.seq} key={m.id} className="rounded-lg border border-slate-100 bg-slate-50 p-3"><div className="mb-2 flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{m.actor_user_id===actorId?'Tú':`Miembro ${m.actor_user_id.slice(0,8)}`} · Nota {m.seq}</span><time dateTime={m.created_at}>{date(m.created_at)}</time></div><p className="whitespace-pre-wrap break-words text-sm text-slate-800">{m.body}</p></li>)}</ol><div className="flex flex-wrap items-center justify-between gap-2 px-4 pb-4"><button className={control} disabled={locked||!messageCursors.length} onClick={()=>setMessageCursors(v=>v.slice(0,-1))}>Notas anteriores</button><span className="text-xs text-slate-500">Página {messageCursors.length+1} · Hasta 20 notas</span><button className={control} disabled={locked||current.next_seq===null} onClick={()=>{if(current.next_seq!==null)setMessageCursors(v=>[...v,current.next_seq!])}}>Más notas</button></div>
 {record?.status==='open'?<form className="space-y-2 border-t p-4" onSubmit={e=>{e.preventDefault();command('message.add_internal_note',{body:draft.trim()})}}><label className="block text-sm font-medium">Nueva nota interna<textarea aria-label="Nueva nota interna" className={`${control} mt-2 min-h-28 w-full resize-y`} disabled={locked} value={draft} maxLength={4000} onChange={e=>setDraft(e.target.value)}/></label><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs text-slate-500">{[...draft.trim()].length}/2000 · Solo el equipo autorizado</span><button className={primary} disabled={locked||!draft.trim()||[...draft.trim()].length>2000}>{busy?'Guardando…':'Guardar nota'}</button></div></form>:<p className="border-t p-4 text-sm text-slate-500">Esta conversación no admite nuevas notas. Puedes {record?.status==='closed'?'reabrirla':'restaurarla'} desde su contexto.</p>}</>}
 </>}
 </section>
 {selected&&record&&<aside aria-label="Contexto de conversación" className="space-y-5 border-l border-slate-200 p-4"><h2 className="font-semibold">Contexto</h2><p className="text-xs text-slate-500">Nota manual interna · {date(record.created_at)}</p>{record.customer_id?<Link className="flex items-center gap-1 text-sm font-semibold text-indigo-700" href={'/clients/'+record.customer_id}>Abrir Cliente 360<ExternalLink size={14}/></Link>:<p className="text-sm text-slate-500">Sin empresa vinculada</p>}<p className="break-words text-xs text-slate-500">Responsable: {record.assigned_user_id===actorId?'Tú':record.assigned_user_id?`Miembro ${record.assigned_user_id.slice(0,8)}`:'Sin asignar'}</p>
 {manager&&record.status!=='archived'&&<><label className="block text-sm">Asignar responsable<select aria-label="Asignar responsable de conversación" className={`${control} mt-2 w-full`} value={record.assigned_user_id??''} disabled={locked} onChange={e=>command('conversation.assign',{assigned_user_id:e.target.value||null})}><option value="">Sin asignar</option>{record.assigned_user_id&&!roster.some(m=>m.user_id===record.assigned_user_id)&&<option value={record.assigned_user_id}>Responsable actual</option>}{roster.map(m=><option key={m.id} value={m.user_id}>{m.user_id===actorId?'Tú':`Miembro ${m.user_id.slice(0,8)}`} · {m.role==='owner'?'Titular':m.role==='admin'?'Administrador':'Miembro'}</option>)}</select></label>
 <div className="space-y-2"><h3 className="text-sm font-medium">Cambiar vínculo de cliente</h3><CustomerSelect value={linkCustomer} onChange={id=>{setLinkCustomer(id);setLinkContact('');setContactPages(null);setContactsError('')}} disabled={locked}/><label className="block text-sm">Contacto<select aria-label="Contacto de conversación" className={`${control} mt-1 w-full`} value={linkContact} disabled={locked||!linkCustomer} onChange={e=>setLinkContact(e.target.value)}><option value="">Sin contacto</option>{contactPages?.customer===linkCustomer&&contactPages.data.items.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.display_name??'Contacto'}</option>)}</select></label>{contactPages?.customer===linkCustomer&&contactPages.data.next_id&&<button className={control} disabled={locked} onClick={()=>void nextContacts()}>Cargar más contactos</button>}{contactsError&&<p role="alert" className="text-xs text-red-700">{contactsError}</p>}<button className={control} disabled={locked} onClick={()=>command('conversation.link_customer',{customer_id:linkCustomer||null,contact_id:linkContact||null})}>Guardar vínculo</button><p className="text-xs text-slate-500">Sin selección elimina el vínculo actual.</p></div></>}
 <div className="flex flex-wrap gap-2">{record.status==='open'&&<button className={control} disabled={locked} onClick={()=>command('conversation.close')}>Cerrar conversación</button>}{record.status==='closed'&&<button className={control} disabled={locked} onClick={()=>command('conversation.reopen')}>Reabrir conversación</button>}{record.status!=='archived'?<button className={control} disabled={locked} onClick={()=>command('conversation.archive')}>Archivar conversación</button>:<button className={control} disabled={locked} onClick={()=>command('conversation.restore')}>Restaurar conversación</button>}</div></aside>}
 </div>
 {create&&<Drawer title="Nueva conversación interna" onClose={()=>{if(!locked)setCreate(false)}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();void run({operation:'conversation.create_internal',input:Object.freeze({command_id:crypto.randomUUID(),assigned_user_id:newAssignee||null,customer_id:newCustomer||null,body:draft.trim()})})}}><p className="text-sm text-slate-500">Inicia un seguimiento con una nota privada. No se envía al cliente.</p><CustomerSelect value={newCustomer} onChange={setNewCustomer} disabled={locked}/><label className="block text-sm">Responsable<select aria-label="Responsable de nueva conversación" className={`${control} mt-1 w-full`} disabled={locked||!manager} value={newAssignee} onChange={e=>setNewAssignee(e.target.value)}>{manager&&<option value="">Sin asignar</option>}{members.map(m=><option key={m.user_id} value={m.user_id}>{m.user_id===actorId?'Tú':`Miembro ${m.user_id.slice(0,8)}`}</option>)}</select></label><label className="block text-sm">Primera nota<textarea aria-label="Primera nota interna" className={`${control} mt-1 min-h-32 w-full`} disabled={locked} maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)}/></label><p className="text-xs text-slate-500">{[...draft.trim()].length}/2000 caracteres</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{uncertain&&<button type="button" className={control} disabled={busy} onClick={()=>{if(intent.current)void run(intent.current)}}>Comprobar la misma acción</button>}<button className={primary} disabled={locked||!draft.trim()||[...draft.trim()].length>2000}>{busy?'Guardando…':'Crear conversación'}</button></form></Drawer>}
 </div>
}
