'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {useProduct} from '@/features/product/integration/Provider'
import {useReviewedCommand} from '@/features/product/integration/ReviewedCommand'
import {CustomerCreationChoice} from '@/features/product/integration/CustomerCreationChoice'
import {OperatorSelect} from '@/features/product/integration/OperatorSelect'
import {AssigneeSelect} from '@/features/product/integration/AssigneeSelect'
import {ContractVersionSelect} from '@/features/product/integration/ContractVersionSelect'
import {VersionTerms} from '@/features/catalog/IntegratedCatalog'
import {CustomerDomainPages,NamedCustomer} from '@/features/customers/CustomerDomainPages'
import {customerCollectionIdentity} from '@/features/customers/customer-identity'
import {safeMessage,ProductUiError} from '@/features/product/integration/repository'
import {Drawer,control,primary} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
import type {PortfolioInputsV1} from '@/lib/contracts/portfolio-v1'
import type {PlanVersionRowV1,OperatorRowV1} from '@/lib/contracts/telecom-collections-v1'
type Proposal={input:PortfolioInputsV1['contract.create_manual'];description:string}
export function ContractsInventory({customerId,createAllowed=false}:{customerId?:string;createAllowed?:boolean}){
 const {role}=useProduct(),[creating,setCreating]=useState(false),[revision,setRevision]=useState(0),[created,setCreated]=useState('')
 return <div className="space-y-3">{created&&<p role="status">Contrato manual registrado. <Link className="font-semibold text-indigo-700" href={'/portfolio?kind=contract&id='+created}>Ver contrato creado</Link></p>}{role&&role!=='viewer'&&(!customerId||createAllowed)&&<button className={primary} onClick={()=>setCreating(true)}>Registrar contrato manual</button>}<CustomerDomainPages key={revision} area="Contratos" customerId={customerId}/>{creating&&<CustomerCreationChoice customerId={customerId} title="Registrar contrato manual" onClose={()=>setCreating(false)}>{id=><ContractCreate key={id} customerId={id} onClose={()=>setCreating(false)} onCreated={id=>{setCreating(false);setCreated(id);setRevision(r=>r+1)}}/>}</CustomerCreationChoice>}</div>
}
function ContractCreate({customerId,onClose,onCreated}:{customerId:string;onClose:()=>void;onCreated:(id:string)=>void}){
 const {repository}=useProduct(),[operator,setOperator]=useState(''),[operatorState,setOperatorState]=useState<{id:string;row?:OperatorRowV1;error?:string}>(),[customerActive,setCustomerActive]=useState(false),[customerError,setCustomerError]=useState(''),[customerRevision,setCustomerRevision]=useState(0),[date,setDate]=useState(''),[version,setVersion]=useState<PlanVersionRowV1|null>(null),[assignee,setAssignee]=useState(''),[terms,setTerms]=useState(false),receiptId=useRef('')
 const command=useReviewedCommand<Proposal>(async p=>{const receipt=await repository.portfolioCommand('contract.create_manual',p.input);receiptId.current=receipt.id;return receipt},async()=>{const id=receiptId.current;if(!id)throw new ProductUiError('internal_safe');const fresh=await repository.portfolio('contract',id);if(fresh.kind!=='contract'||fresh.record.customer_id!==customerId)throw new ProductUiError('internal_safe');onCreated(id)},'Registrar contrato manual')
 useEffect(()=>{let active=true;setCustomerActive(false);setCustomerError('');void customerCollectionIdentity(repository,customerId).then(c=>{if(active)setCustomerActive(c.status==='active')}).catch(e=>{if(active)setCustomerError(safeMessage(e))});return()=>{active=false}},[repository,customerId,customerRevision])
 useEffect(()=>{if(!operator)return;let active=true;void repository.collection('operator.get',{id:operator}).then(r=>{if(active)setOperatorState({id:operator,row:r.record})}).catch(e=>{if(active)setOperatorState({id:operator,error:safeMessage(e)})});return()=>{active=false}},[repository,operator])
 const selected=operatorState?.id===operator?operatorState:undefined,allowed=customerActive&&selected?.row?.status==='active'
 return <Drawer title="Registrar contrato manual" onClose={()=>{if(!command.locked)onClose()}}><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!allowed)return;command.propose({input:{command_id:crypto.randomUUID(),customer_id:customerId,operator_id:operator,start_date:date,plan_version_id:version?.id??null,assigned_user_id:assignee||null},description:'Registrar un contrato manual en borrador con '+selected!.row!.display_name+' desde '+productDate(date)+'. '+(version?'Conservar la versión vendida '+version.version_number+' y sus condiciones históricas.':'Sin versión vendida ni condiciones comerciales registradas.')+' No activa servicios ni líneas.'})}}><NamedCustomer id={customerId}/>{customerError?<div><p role="alert">{customerError}</p><button type="button" className={control} disabled={command.locked} onClick={()=>setCustomerRevision(v=>v+1)}>Reintentar cliente del contrato</button></div>:!customerActive&&<p role="status">El cliente debe estar activo para registrar un contrato.</p>}<fieldset disabled={command.locked||!customerActive} className="space-y-3"><OperatorSelect activeOnly value={operator} label="Operador del nuevo contrato" disabled={command.locked} onChange={id=>{setOperator(id);setVersion(null)}}/>{selected?.error&&<p role="alert">{selected.error}</p>}<label className="block text-sm">Fecha de inicio del contrato<input aria-label="Fecha de inicio del contrato" type="date" min="1900-01-01" max="2199-12-31" required className={control+' mt-1 w-full'} value={date} onChange={e=>{setDate(e.target.value);setVersion(null)}}/></label>{operator&&date&&<ContractVersionSelect key={operator+':'+date} operatorId={operator} date={date} value={version} onChange={v=>{setVersion(v);setTerms(false)}} disabled={command.locked}/>}<AssigneeSelect allowClear value={assignee} onChange={setAssignee} disabled={command.locked}/></fieldset>{version&&<button type="button" className={control} disabled={command.locked} onClick={()=>setTerms(true)}>Consultar condiciones vendidas</button>}<button className={primary} disabled={command.locked||!allowed||!date}>Revisar contrato manual</button></form>{command.feedback}{terms&&version&&<VersionTerms key={version.id} id={version.id} onClose={()=>setTerms(false)}/>}</Drawer>
}
