import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { stagingTarget,probe } from '../../scripts/platform/staging-probe.mjs'
import { bootstrapContract,configDrift } from '../../scripts/platform/bootstrap-policy.mjs'
const fixture=()=>({runtime:{TARGET_ENV:'STAGING',SYNTHETIC_STAGING_AUTHORIZED:'true',STAGING_APPROVAL_REF:'https://github.com/Asier-Comba/CRM-Telecomunicaciones/issues/12',STAGING_APPROVED_PROJECT_REF:'syntheticstage',PROD_SUPABASE_PROJECT_REF:'syntheticprod',PROD_APP_HOSTNAME:'prod.example.invalid',SUPABASE_ANON_KEY:'synthetic-public'},cfg:{target:'STAGING',values:{SUPABASE_PROJECT_REF:'syntheticstage',SUPABASE_URL:'https://syntheticstage.supabase.co',PUBLIC_APP_URL:'https://stage.example.invalid'}}})
test('declared synthetic staging target validates',()=>{const f=fixture();assert.equal(stagingTarget(f.runtime,f.cfg),'https://syntheticstage.supabase.co')})
for(const [name,mutate]of Object.entries({missingTarget:f=>delete f.runtime.TARGET_ENV,prod:f=>f.runtime.TARGET_ENV='PROD',noApproval:f=>delete f.runtime.SYNTHETIC_STAGING_AUTHORIZED,noEvidence:f=>delete f.runtime.STAGING_APPROVAL_REF,noProdDeclaration:f=>delete f.runtime.PROD_SUPABASE_PROJECT_REF,prodRef:f=>f.runtime.PROD_SUPABASE_PROJECT_REF='syntheticstage',prodHost:f=>f.runtime.PROD_APP_HOSTNAME='stage.example.invalid',foreignHost:f=>f.cfg.values.SUPABASE_URL='https://evil.example',userinfo:f=>f.cfg.values.SUPABASE_URL='https://syntheticstage.supabase.co@evil.example',query:f=>f.cfg.values.SUPABASE_URL+='?next=prod',http:f=>f.cfg.values.SUPABASE_URL='http://syntheticstage.supabase.co',encoded:f=>f.cfg.values.SUPABASE_URL='https://%73yntheticstage.supabase.co'}))test('staging fail before network: '+name,async()=>{const f=fixture();mutate(f);let calls=0;await assert.rejects(()=>probe(f.runtime,f.cfg,async()=>{calls++;return {status:200}}));assert.equal(calls,0)})
test('probe only GET two endpoints, no redirect following',async()=>{const f=fixture(),seen=[];const r=await probe(f.runtime,f.cfg,async(url,o)=>{seen.push([url,o.method,o.redirect]);return {status:url.includes('/settings')?200:401}});assert.equal(r.writes,0);assert.equal(seen.length,2);assert.ok(seen.every(([,m,r])=>m==='GET'&&r==='error'))})
test('bootstrap includes ordered human and separate restore gates',()=>{const m=JSON.parse(readFileSync('platform/company-project-bootstrap.json'));assert.deepEqual(bootstrapContract(m),[]);const bad=structuredClone(m);bad.steps=bad.steps.filter(s=>s.id!=='storage-restore');assert.ok(bootstrapContract(bad).length)})
test('configuration drift needs actual human-approved manifest and outputs names only',()=>{assert.equal(configDrift({status:'PROPOSED'},{}).result,'FAIL');const r=configDrift({status:'HUMAN_APPROVED',settings:{site_url:'first'}},{site_url:'second',smtp_pass:'NEVER_PRINT'});assert.ok(r.differingNames.includes('site_url'));assert.ok(!JSON.stringify(r).includes('NEVER_PRINT'))})
