'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {Bell,RefreshCw} from 'lucide-react'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage,type NotificationPage,type NotificationCount,type NotificationReceipt} from '@/features/product/integration/repository'
import type {NotificationInputV1,NotificationOperationV1} from '@/lib/contracts/notifications-v1'
import {Drawer,control,primary,Empty} from '@/features/product/ui'
type Intent={operation:NotificationOperationV1;input:NotificationInputV1;receipt?:NotificationReceipt}
/** Self-only center. Fixed server text; targets use closed descriptors, never arbitrary URLs. */
export function NotificationCenter(){
 const {repository,role}=useProduct(),allowed=repository.mode==='integrated_local'&&!!role&&role!=='viewer'
 const [open,setOpen]=useState(false),[summary,setSummary]=useState<NotificationCount|null>(null),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[state,setState]=useState<{key:string;data?:NotificationPage;error?:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[notice,setNotice]=useState('')
 const intent=useRef<Intent|null>(null),key=JSON.stringify([cursors.at(-1)??null,revision]),data=state?.key===key?state.data:undefined
 useEffect(()=>{if(!allowed)return;let active=true;const read=()=>{void repository.notificationCount().then(v=>{if(active)setSummary(v)}).catch(()=>{if(active)setSummary(null)})};read();window.addEventListener('crm-notifications-changed',read);return()=>{active=false;window.removeEventListener('crm-notifications-changed',read)}},[repository,allowed,revision])
 useEffect(()=>{if(!open||!allowed)return;let active=true;void repository.notifications({limit:20,...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(data=>{if(active)setState({key,data})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,allowed,open,cursors,key])
 async function run(next:Intent){if(busy)return;intent.current=next;setBusy(true);setError('');try{const receipt=next.receipt??await repository.notificationCommand(next.operation,next.input);next.receipt=receipt;const [fresh,count]=await Promise.all([repository.notifications({limit:20}),repository.notificationCount()]);if(fresh.version<receipt.version)throw new ProductUiError('internal_safe');intent.current=null;setUncertain(false);setCursors([]);setRevision(v=>v+1);setSummary(count);setState(null);setNotice(next.operation==='notification.refresh'?`${receipt.affected} avisos generados. ${receipt.has_more?'Hay más tareas pendientes de revisar; pulsa Generar avisos de nuevo.':'La revisión ha terminado.'}`:`${receipt.affected} avisos marcados como leídos. ${receipt.has_more?'Hay más avisos sin leer; repite la acción.':''}`)}
 catch(e){setError(next.receipt?'Cambio guardado. Falta comprobar el centro actualizado.':safeMessage(e));const retry=!!next.receipt||e instanceof ProductUiError&&e.code==='transport_uncertain';setUncertain(retry);if(!retry){intent.current=null;setState(null);setRevision(v=>v+1)}}finally{setBusy(false)}}
 function command(operation:NotificationOperationV1,id?:string){const version=data?.version??summary?.version;if(version===undefined||busy||uncertain)return;void run({operation,input:Object.freeze({command_id:crypto.randomUUID(),expected_version:version,...(id?{id}:{})})})}
 useEffect(()=>{if(!allowed)return;const show=()=>{if(!busy&&!uncertain){setOpen(true);setState(null);setRevision(v=>v+1)}};window.addEventListener('crm-notifications-open',show);return()=>window.removeEventListener('crm-notifications-open',show)},[allowed,busy,uncertain])
 const locked=busy||uncertain
 if(!allowed)return null
 return <><button aria-label="Abrir notificaciones" title={summary?`${summary.unread_count} notificaciones sin leer`:'Notificaciones: recuento no disponible'} className="relative shrink-0 rounded-lg p-2 text-slate-600 hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-indigo-500" onClick={()=>{setOpen(true);setState(null);setRevision(v=>v+1)}}><Bell size={18}/>{summary&&summary.unread_count>0&&<span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-indigo-600 px-1 text-[9px] text-white">{summary.unread_count>99?'99+':summary.unread_count}</span>}</button>
 {open&&<Drawer title="Notificaciones personales" onClose={()=>{if(!locked){setOpen(false);setState(null);setError('');setNotice('')}}}><p className="text-sm text-slate-500">Avisos privados de los registros que puedes consultar. La revisión de tareas vencidas es manual; no hay envíos externos.</p><div className="flex flex-wrap gap-2"><button className={primary} disabled={locked||!data} onClick={()=>command('notification.refresh')}><RefreshCw size={14}/>Generar avisos de tareas vencidas</button><button className={control} disabled={locked||!data} onClick={()=>command('notification.mark_all_read')}>Marcar todos como leídos</button><button className={control} disabled={locked} onClick={()=>{setState(null);setRevision(v=>v+1)}}>Actualizar notificaciones</button></div>
 {notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{uncertain&&<button className={control} disabled={busy} onClick={()=>{if(intent.current)void run(intent.current)}}>Comprobar la misma acción</button>}
 {state?.key===key&&state.error?<p role="alert" className="text-sm text-red-700">{state.error}</p>:!data?<p role="status" className="text-sm text-slate-500">Cargando avisos autorizados…</p>:!data.items.length?<Empty text="No hay avisos en esta página."/>:<ul className="space-y-3">{data.items.map(n=><li data-notification-id={n.id} key={n.id} className={`space-y-2 rounded-lg border p-3 ${n.read_at?'border-slate-200':'border-indigo-200 bg-indigo-50'}`}><h3 className="text-sm font-semibold">{n.title}</h3><p className="text-xs text-slate-500">{n.summary}</p><p className="text-xs text-slate-500">{new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Madrid'}).format(new Date(n.created_at))} · {n.read_at?'Leído':'Sin leer'}</p><div className="flex flex-wrap gap-2"><Link className={control} href={n.target.kind==='customer'?'/clients/'+n.target.id:'/calendar?task='+n.target.id} onClick={e=>{if(locked)e.preventDefault();else{setOpen(false);setState(null)}}}>Abrir registro</Link>{!n.read_at&&<button className={control} disabled={locked} onClick={()=>command('notification.mark_read',n.id)}>Marcar leído</button>}</div></li>)}</ul>}
 <div className="flex flex-wrap items-center gap-3"><button className={control} disabled={locked||!data||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Avisos anteriores</button><span className="text-xs text-slate-500">Página {cursors.length+1} · Hasta 20 avisos</span><button className={control} disabled={locked||!data?.next_id} onClick={()=>{if(data?.next_id)setCursors(v=>[...v,data.next_id!])}}>Más avisos</button></div></Drawer>}
 </>
}
