'use client'
import {useEffect,useRef,useState} from 'react'
import {ConfirmDialog} from '@/components/ConfirmDialog'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import {Drawer,control,primary} from '@/features/product/ui'
import type {ServiceLocationInputsV1,ServiceLocationRowV1} from '@/lib/contracts/service-location-v1'
import type {SensitiveResultV1} from '@/lib/contracts/sensitive-v1'
const addressFields=['address_line1','address_line2','postal_code','city','region','country'] as const
const fields={label:'Nombre de ubicación',address_line1:'Dirección',address_line2:'Dirección adicional',postal_code:'Código postal',city:'Ciudad',region:'Provincia',country:'País (ISO)'}
export function ServiceLocations({customerId,createAllowed=false}:{customerId:string;createAllowed?:boolean}){
 const {repository,role}=useProduct(),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),[create,setCreate]=useState(false),[reveal,setReveal]=useState<string|null>(null),[notice,setNotice]=useState('')
 const key=JSON.stringify([customerId,cursors,revision]),[state,setState]=useState<{key:string;items?:readonly ServiceLocationRowV1[];next?:string|null;error?:string}>(),current=state?.key===key?state:undefined
 useEffect(()=>{let active=true;void repository.telecom('service_location.list',{customer_id:customerId,limit:20,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})}).then(p=>{if(active)setState({key,items:p.items,next:p.next_id})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,customerId,cursors,key])
 return <section className="space-y-3 rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Ubicaciones de instalación</h2><div className="flex gap-2"><button className={control} onClick={()=>setRevision(v=>v+1)}>Actualizar ubicaciones</button>{createAllowed&&role&&role!=='viewer'&&<button className={primary} onClick={()=>setCreate(true)}>Nueva ubicación</button>}</div></div><p className="text-xs text-slate-500">Inventario del cliente; hasta 20 ubicaciones por página. Las direcciones requieren una consulta explícita.</p>{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}{current?.error?<p role="alert" className="text-sm text-red-700">{current.error}</p>:!current?.items?<p role="status">Consultando ubicaciones…</p>:!current.items.length?<p className="text-sm text-slate-500">No hay ubicaciones en esta página.</p>:<ul className="divide-y">{current.items.map(r=><li key={r.id} data-location-id={r.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="break-words font-medium">{r.label}</p><p className="text-xs text-slate-500">{r.country} · {{manual:'Manual',import:'Importada',integration:'Integración'}[r.source]}</p></div>{role&&role!=='viewer'&&<button className={control} onClick={()=>setReveal(r.id)}>Revelar dirección</button>}</li>)}</ul>}<footer className="flex flex-wrap justify-between gap-2"><button className={control} disabled={!current?.items||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Ubicaciones anteriores</button><span className="self-center text-xs">Página {cursors.length+1}{current?.items?' · '+current.items.length+' ubicaciones':''}</span><button className={control} disabled={!current?.next} onClick={()=>{if(current?.next)setCursors(v=>[...v,current.next!])}}>Más ubicaciones</button></footer>{create&&<LocationCreate customerId={customerId} onClose={()=>setCreate(false)} onCreated={()=>{setCreate(false);setNotice('Ubicación registrada.');setCursors([]);setRevision(v=>v+1)}}/>}{reveal&&<LocationAddress key={reveal} id={reveal} onClose={()=>setReveal(null)}/>}</section>
}
function LocationCreate({customerId,onClose,onCreated}:{customerId:string;onClose:()=>void;onCreated:()=>void}){
 const {repository}=useProduct(),[form,setForm]=useState({label:'',address_line1:'',address_line2:'',postal_code:'',city:'',region:'',country:'ES'}),[proposal,setProposal]=useState<ServiceLocationInputsV1['service_location.create']|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[locked,setLocked]=useState(false),[frozen,setFrozen]=useState(false),pending=useRef<ServiceLocationInputsV1['service_location.create']|null>(null),inFlight=useRef(false)
 async function save(){if(inFlight.current||locked||!proposal)return;inFlight.current=true;setBusy(true);setError('');const input=pending.current??proposal;pending.current=input;setFrozen(true);try{await repository.telecom('service_location.create',input);pending.current=null;setFrozen(false);onCreated()}catch(e){setError(safeMessage(e));if(e instanceof ProductUiError&&e.code!=='transport_uncertain'&&e.code!=='internal_safe'){pending.current=null;setFrozen(false);setLocked(e.code==='access_denied')}}finally{inFlight.current=false;setBusy(false)}}
 return <Drawer title="Nueva ubicación" onClose={()=>{if(!busy&&!pending.current)onClose()}}><p className="text-sm text-slate-500">Registra una ubicación del cliente. No solicita instalación al operador.</p><form className="grid gap-3" onSubmit={e=>{e.preventDefault();setError('');setProposal({...form,address_line2:form.address_line2||null,region:form.region||null,customer_id:customerId,command_id:crypto.randomUUID()})}}>{(Object.keys(fields) as (keyof typeof fields)[]).map(k=><label key={k} className="text-sm">{fields[k]}<input aria-label={fields[k]} className={control+' mt-1 w-full'} value={form[k]} required={!['region','address_line2'].includes(k)} maxLength={k==='country'?2:k==='address_line1'?300:k==='address_line2'?150:k==='postal_code'?20:100} disabled={busy||!!proposal||locked} onChange={e=>setForm(v=>({...v,[k]:k==='country'?e.target.value.toUpperCase():e.target.value}))}/></label>)}<button className={primary} disabled={busy||!!proposal||locked}>Revisar ubicación</button></form><ConfirmDialog open={!!proposal} title="Registrar ubicación" description="Confirma la ubicación revisada. La dirección quedará protegida y solo se mostrará mediante una consulta autorizada." confirmLabel={frozen?'Reintentar registro':'Registrar ubicación'} loading={busy} error={error} onConfirm={()=>void save()} onCancel={()=>{if(!pending.current&&!busy)setProposal(null)}}/>{error&&locked&&<p role="alert">{error}</p>}</Drawer>
}
function LocationAddress({id,onClose}:{id:string;onClose:()=>void}){
 const {repository}=useProduct(),[values,setValues]=useState<SensitiveResultV1['values']>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),active=useRef(true)
 useEffect(()=>{active.current=true;return()=>{active.current=false}},[])
 async function read(){if(busy)return;setBusy(true);setValues(undefined);setError('');try{const r=await repository.sensitive({entity_kind:'service_location',entity_id:id,fields:addressFields});if(active.current)setValues(r.values)}catch(e){if(active.current)setError(safeMessage(e))}finally{if(active.current)setBusy(false)}}
 return <Drawer title="Dirección de instalación" onClose={()=>{active.current=false;setValues(undefined);onClose()}}><p className="text-sm text-slate-500">Cada consulta comprueba los permisos actuales. La dirección se elimina de esta pantalla al cerrar.</p><button className={primary} disabled={busy} onClick={()=>void read()}>Consultar dirección autorizada</button>{error&&<p role="alert">{error}</p>}{values&&<dl className="grid gap-3" data-sensitive-value>{addressFields.map(k=><div key={k}><dt className="text-xs text-slate-500">{fields[k]}</dt><dd className="break-words">{values[k]??'No registrado'}</dd></div>)}</dl>}</Drawer>
}
