'use client'
import {useEffect,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage,ProductUiError} from '@/features/product/integration/repository'
import {control} from '@/features/product/ui'
type Option={id:string;name:string}
export function ServiceAssociationSelect({kind,customerId,value,onChange,disabled=false}:{kind:'location'|'contact';customerId:string;value:string;onChange:(v:string)=>void;disabled?:boolean}){
 const {repository}=useProduct(),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),key=JSON.stringify([kind,customerId,cursors,revision]),[state,setState]=useState<{key:string;options?:Option[];next?:string|null;error?:string}>(),[selected,setSelected]=useState<{key:string;option?:Option}>(),current=state?.key===key?state:undefined,label=kind==='location'?'Ubicación del servicio':'Contacto de instalación',selectedKey=JSON.stringify([kind,customerId,value,cursors,revision])
 useEffect(()=>{let active=true;const input={customer_id:customerId,limit:20,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})};const read=kind==='location'?repository.telecom('service_location.list',input).then(p=>({options:p.items.map(r=>({id:r.id,name:r.label+' · '+r.country})),next:p.next_id})):repository.collection('contact.list',{...input,status:'active'}).then(p=>({options:p.items.map(r=>({id:r.id,name:r.display_name})),next:p.next_id}));void read.then(p=>{if(active)setState({key,...p})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,kind,customerId,cursors,key])
 useEffect(()=>{if(!value)return;let active=true;async function read(){if(kind==='location'){const r=(await repository.telecom('service_location.get',{id:value})).record;if(r.customer_id!==customerId)throw new ProductUiError('not_found');return{id:r.id,name:r.label+' · '+r.country}}const n=BigInt('0x'+value.replaceAll('-',''));if(n===BigInt(0))throw new ProductUiError('not_found');const hex=(n-BigInt(1)).toString(16).padStart(32,'0'),after=hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20);const r=(await repository.collection('contact.list',{customer_id:customerId,status:'active',sort:'id_asc',limit:1,after_id:after})).items[0];if(!r||r.id!==value||r.customer_id!==customerId||r.status!=='active')throw new ProductUiError('not_found');return{id:r.id,name:r.display_name}}
 void read().then(option=>{if(active)setSelected({key:selectedKey,option})}).catch(()=>{if(active)setSelected({key:selectedKey})});return()=>{active=false}},[repository,kind,customerId,value,revision,selectedKey])
 const options=current?.options??[],outside=value&&!options.some(r=>r.id===value),verified=selected?.key===selectedKey&&current?.options?selected.option:undefined
 return <div className="space-y-2"><label className="block text-sm">{label}<select aria-label={label} className={control+' mt-1 w-full'} disabled={disabled||!current?.options} value={value} onChange={e=>onChange(e.target.value)}><option value="">Sin {kind==='location'?'ubicación':'contacto'}</option>{outside&&<option value={value} disabled={!verified}>{verified?.name??'Selección no disponible'}</option>}{options.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{current?.error&&<p role="alert" className="text-xs text-red-700">{current.error}</p>}<div className="flex flex-wrap gap-2"><button type="button" className={control} disabled={disabled||!current?.options||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Anteriores de {label.toLowerCase()}</button><button type="button" className={control} disabled={disabled||!current?.next} onClick={()=>{if(current?.next)setCursors(v=>[...v,current.next!])}}>Más de {label.toLowerCase()}</button><button type="button" className={control} disabled={disabled} onClick={()=>setRevision(v=>v+1)}>Actualizar {label.toLowerCase()}</button></div></div>
}
