'use client'
import {ScopedCollectionLabels} from '@/features/product/integration/ScopedCollectionLabels'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {PageHeader} from '@/components/PageHeader'
import {control,Status,PreviewNotice} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {AssigneeSelect} from '@/features/product/integration/AssigneeSelect'
import {CustomerSelect} from '@/features/product/integration/CustomerSelect'
import {AssignedCommercial} from '@/features/product/integration/AssignedCommercial'
import {NamedCustomer} from '@/features/customers/CustomerDomainPages'
import {attentionKinds,attentionReasons,attentionBucket,attentionHref} from './presentation'
import type {TelecomAttentionKindV1,TelecomAttentionPageV1,TelecomAttentionCursorV1} from '@/lib/contracts/telecom-attention-v1'
function madridDay(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function offset(day:string,n:number){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
export function IntegratedAttention(){
 const {repository}=useProduct(),[today]=useState(madridDay),[from,setFrom]=useState(()=>offset(today,-30)),[to,setTo]=useState(()=>offset(today,30)),[kind,setKind]=useState(''),[owner,setOwner]=useState(''),[customer,setCustomer]=useState(''),[cursors,setCursors]=useState<TelecomAttentionCursorV1[]>([]),[revision,setRevision]=useState(0),[state,setState]=useState<{key:string;page?:TelecomAttentionPageV1;error?:string}|null>(null)
 const valid=!!from&&!!to&&to>=from&&(Date.parse(to)-Date.parse(from))/86400000<=366,key=JSON.stringify([from,to,kind,owner,customer,cursors,revision]),current=state?.key===key?state:null,page=current?.page
 useEffect(()=>{if(!valid)return;let active=true;void repository.telecom('telecom.attention',{window_from:from,window_to:to,...(kind?{kind:kind as TelecomAttentionKindV1}:{}),...(owner?{owner_user_id:owner}:{}),...(customer?{customer_id:customer}:{}),...(cursors.at(-1)??{}),limit:20}).then(page=>{if(active)setState({key,page})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,valid,from,to,kind,owner,customer,cursors,key])
 function filter(setter:(s:string)=>void,v:string){setCursors([]);setter(v)}
 return <div className="space-y-4"><PageHeader title="Centro de atención" description="Seguimientos que requieren atención, hoy y en los próximos días"/><PreviewNotice/>
 <section className="space-y-3 rounded-xl border bg-white p-4" aria-label="Filtros de atención"><div className="flex flex-wrap gap-3"><label className="text-sm">Desde<input aria-label="Atención desde" type="date" min="2000-01-01" max="2100-12-31" className={control+' ml-2'} value={from} onChange={e=>filter(setFrom,e.target.value)}/></label><label className="text-sm">Hasta<input aria-label="Atención hasta" type="date" min="2000-01-01" max="2100-12-31" className={control+' ml-2'} value={to} onChange={e=>filter(setTo,e.target.value)}/></label><select aria-label="Tipo de seguimiento" className={control} value={kind} onChange={e=>filter(setKind,e.target.value)}><option value="">Todos los tipos</option>{Object.entries(attentionKinds).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select><button className={control} onClick={()=>setRevision(v=>v+1)}>Actualizar atención</button><button className={control} onClick={()=>{setFrom(offset(today,-30));setTo(offset(today,30));setKind('');setOwner('');setCustomer('');setCursors([])}}>Limpiar filtros</button></div><div className="grid gap-4 md:grid-cols-2"><AssigneeSelect value={owner} onChange={v=>filter(setOwner,v)} allowClear clearLabel="Todos los responsables"/><CustomerSelect value={customer} onChange={v=>filter(setCustomer,v)} inputLabel="Buscar empresa para atención" clearLabel="Todos los clientes"/></div></section>
 {!valid?<p role="alert" className="text-sm text-red-700">Selecciona fechas válidas, ordenadas y separadas por un máximo de 366 días.</p>:current?.error?<div className="rounded-lg bg-red-50 p-4"><p role="alert" className="text-sm text-red-700">{current.error}</p><button className={control+' mt-3'} onClick={()=>setRevision(v=>v+1)}>Reintentar atención</button></div>:!page?<p role="status" className="text-sm text-slate-500">Consultando seguimientos autorizados…</p>:<ScopedCollectionLabels rows={page.items}><p className="text-xs text-slate-500">Estado consultado el {productDate(page.as_of)} · {page.items.length} seguimientos en esta página. La explicación y prioridad proceden del registro autorizado.</p>{!page.items.length?<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">No hay seguimientos en esta ventana con los filtros seleccionados.</p>:<div className="grid items-start gap-4 xl:grid-cols-3">{['Requiere atención','Hoy','Próximos días'].map(bucket=><section key={bucket} className="min-w-0 rounded-xl border bg-white"><h2 className="border-b p-4 font-semibold">{bucket}</h2><div className="space-y-3 p-3">{page.items.filter(r=>attentionBucket(r,page.as_of)===bucket).map(r=><article key={r.kind+':'+r.id} data-attention-ref={r.kind+':'+r.id} className="space-y-2 rounded-lg border border-slate-100 p-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">{attentionKinds[r.kind]}</h3><Status value={r.status}/></div><p className="text-sm text-slate-600">{attentionReasons[r.reason_code]}</p><p className="text-xs text-slate-500">Fecha: {productDate(r.due_on??r.sort_on)} · Prioridad: {{low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente'}[r.priority]}{r.due_on===null?' · Sin fecha de vencimiento registrada':''}</p>{r.customer_id&&<p className="text-sm"><NamedCustomer id={r.customer_id}/></p>}<p className="text-xs text-slate-500">Responsable: <AssignedCommercial id={r.owner_user_id}/></p><Link className="inline-block text-sm font-semibold text-indigo-700" href={attentionHref(r)}>{r.kind==='case'?'Ver incidencia':r.kind==='portability'?'Ver portabilidad':'Abrir seguimiento'}</Link></article>)}{!page.items.some(r=>attentionBucket(r,page.as_of)===bucket)&&<p className="p-2 text-xs text-slate-500">Sin seguimientos de esta categoría en esta página.</p>}</div></section>)}</div>}<footer className="flex flex-wrap justify-between gap-2"><button className={control} disabled={!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Página anterior de atención</button><span className="self-center text-xs text-slate-500">Página {cursors.length+1} · Orden por fecha del registro</span><button className={control} disabled={!page.next_cursor} onClick={()=>{if(page.next_cursor)setCursors(v=>[...v,page.next_cursor!])}}>Siguiente página de atención</button></footer></ScopedCollectionLabels>}
 </div>
}
