'use client'
import {productDate} from '@/features/product/presentation'
import {TelecomReports} from './TelecomReports'
import {BillingAnalytics} from '@/features/billing/BillingAnalytics'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {Download,RefreshCw} from 'lucide-react'
import {PageHeader} from '@/components/PageHeader'
import {SectionCard} from '@/components/SectionCard'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {PeriodSelect,PreviewNotice,control,primary,Unavailable} from '@/features/product/ui'
import {periods,type Period} from '@/features/product/model'
import type {DashboardV2} from '@/lib/contracts/product-dashboard-v2'
const snapshotLabels={customers:'Clientes',contracts:'Contratos',services:'Servicios',lines:'Líneas',opportunities:'Oportunidades',tasks:'Tareas',meetings:'Reuniones',renewals:'Renovaciones',permanences:'Permanencias'}
const periodLabels={customers_created:'Clientes creados',tasks_due:'Tareas con vencimiento',meetings_scheduled:'Reuniones programadas',renewals_due:'Renovaciones previstas',permanences_due:'Permanencias que terminan',opportunities_closed:'Oportunidades cerradas'}
const moneyKeys=['issued_minor','paid_minor','outstanding_minor','overdue_minor'] as const
const moneyLabels={issued_minor:'Emitido',paid_minor:'Cobrado',outstanding_minor:'Pendiente',overdue_minor:'Vencido'}
const money=(n:number,c:string)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:c}).format(n/100)
export function IntegratedReports(){
 const {repository,role}=useProduct(),[audience,setAudience]=useState<'my'|'workspace'>('my'),[period,setPeriod]=useState<Period>('month'),[revision,setRevision]=useState(0),[state,setState]=useState<{key:string;data?:DashboardV2;error?:string;readAt?:string}|null>(null),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('')
 const key=JSON.stringify([audience,period,revision]),current=state?.key===key?state:null,data=current?.data,scope=audience==='my'?'Tu ámbito':'Todo el espacio'
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get('period');if(periods.some(v=>v.value===p))queueMicrotask(()=>setPeriod(p as Period))},[])
 useEffect(()=>{let active=true;void repository.dashboard({audience,period}).then(data=>{if(active)setState({key,data,readAt:new Date().toISOString()})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,audience,period,key])
 async function exportCsv(){if(exporting||!data)return;setExporting(true);setExportError('');try{
  // A fresh authorized reader is required even when the visible snapshot is already loaded.
  const fresh=await repository.dashboard({audience,period}),readAt=new Date().toISOString(),rows:unknown[][]=[['Sección','Medida','Valor','Moneda','Unidad','Ámbito','Periodo','Inicio','Fin exclusivo','Consultado en']]
  const add=(section:string,label:string,value:number,currency='',unit='recuento')=>rows.push([section,label,value,currency,unit,fresh.audience==='my'?'Personal':'Espacio',fresh.period.kind,fresh.period.start??'',fresh.period.end_exclusive??'',readAt])
  Object.entries(snapshotLabels).forEach(([k,label])=>add('Instantánea',label,fresh.snapshot_counts[k as keyof typeof snapshotLabels]))
  Object.entries(periodLabels).forEach(([k,label])=>add('Periodo',label,fresh.period_counts[k as keyof typeof periodLabels]))
  fresh.financial?.currencies.forEach(c=>moneyKeys.forEach(k=>add('Facturación',moneyLabels[k],c[k],c.currency,'unidad menor')))
  const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download='informe-telecom-'+fresh.audience+'-'+fresh.period.kind+'.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
  setState({key,data:fresh,readAt})
 }catch(e){setExportError(safeMessage(e))}finally{setExporting(false)}}
 return <div className="space-y-4"><PageHeader title="Informes" description="Instantánea autorizada y actividad del periodo, sin extrapolar listas parciales." action={<button className={primary} disabled={!data||exporting} onClick={()=>void exportCsv()}><Download size={16}/>{exporting?'Comprobando permisos…':'Exportar resumen CSV'}</button>}/><PreviewNotice/>
 <div className="flex flex-wrap items-center gap-3"><select aria-label="Ámbito del informe" className={control} value={audience} disabled={exporting} onChange={e=>{setAudience(e.target.value as typeof audience);setExportError('')}}><option value="my">Tu ámbito</option>{(role==='owner'||role==='admin')&&<option value="workspace">Todo el espacio</option>}</select><PeriodSelect value={period} onChange={p=>{setPeriod(p);setExportError('');const url=new URL(location.href);url.searchParams.set('period',p);history.replaceState(null,'',url)}}/><button className={control} disabled={exporting} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={14}/>Actualizar informe</button></div>
 {exportError&&<p role="alert" aria-label="Error al exportar el informe" className="text-sm text-red-700">{exportError}</p>}{current?.error?<div className="rounded-xl border border-red-100 bg-red-50 p-4"><p role="alert" aria-label="Error al consultar el informe" className="text-sm text-red-700">{current.error}</p><button className={`${control} mt-3`} onClick={()=>setRevision(v=>v+1)}>Reintentar informe</button></div>:!data?<p role="status" className="text-sm text-slate-500">Consultando informe autorizado…</p>:<>
 <p className="text-xs text-slate-500">{scope} · {data.period.start?productDate(data.period.start):'Desde el inicio'} — {data.period.end_exclusive?productDate(data.period.end_exclusive):'Sin límite'} (fin exclusivo). Consultado {new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Madrid'}).format(new Date(current!.readAt!))}.</p>
 <div className="grid gap-4 xl:grid-cols-2"><SectionCard title="Cartera y trabajo actual" description="Instantánea del ámbito seleccionado; no es una serie histórica."><dl className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(snapshotLabels).map(([k,label])=><div key={k} className="rounded-lg border border-slate-100 p-3"><dt className="text-xs text-slate-500">{label}</dt><dd data-report-count={k} className="mt-1 text-xl font-semibold text-slate-800">{data.snapshot_counts[k as keyof typeof snapshotLabels]}</dd></div>)}</dl><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold text-indigo-700"><Link href="/portfolio">Abrir cartera</Link><Link href="/opportunities">Abrir pipeline</Link><Link href="/calendar">Abrir agenda</Link></div></SectionCard>
 <SectionCard title="Actividad del periodo" description="Recuentos exactos publicados por el servidor para este ámbito y periodo."><dl className="space-y-3">{Object.entries(periodLabels).map(([k,label])=><div key={k} className="flex justify-between gap-3 border-b border-slate-100 pb-2 text-sm"><dt className="text-slate-500">{label}</dt><dd data-report-period={k} className="font-semibold">{data.period_counts[k as keyof typeof periodLabels]}</dd></div>)}</dl></SectionCard></div>
 <SectionCard title="Facturación del periodo" description={`${data.audience==='my'?'Facturas creadas por ti':'Facturas del espacio'}; cada moneda se mantiene separada.`}>{data.financial_status==='unavailable'?<p className="text-sm text-slate-500">Información financiera no disponible para tu rol.</p>:!data.financial?.currencies.length?<p className="text-sm text-slate-500">Sin facturas emitidas en este ámbito y periodo.</p>:<div className="grid gap-4 lg:grid-cols-2">{data.financial.currencies.map(c=><section aria-label={`Informe financiero ${c.currency}`} key={c.currency} className="rounded-lg border border-slate-100 p-4"><h3 className="font-semibold">{c.currency}</h3><dl className="mt-3 space-y-3">{moneyKeys.map(k=><div key={k}><div className="flex justify-between gap-2 text-sm"><dt className="text-slate-500">{moneyLabels[k]}</dt><dd className="font-semibold">{money(c[k],c.currency)}</dd></div><div aria-hidden="true" className="mt-1 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${k==='overdue_minor'?'bg-amber-500':'bg-indigo-500'}`} style={{width:`${100*c[k]/Math.max(1,...moneyKeys.map(key=>c[key]))}%`}}/></div></div>)}</dl></section>)}</div>}<p className="mt-4 text-xs text-slate-500">Vencido forma parte de Pendiente. Las categorías no se suman. La exportación usa unidades menores y consulta de nuevo los permisos.</p></SectionCard>
 </>}<TelecomReports/><BillingAnalytics/><Unavailable title="Previsiones y objetivos pendientes">Los objetivos comerciales y las previsiones aún no están publicados.</Unavailable></div>
}
