'use client'
import {ScopedCollectionLabels} from '@/features/product/integration/ScopedCollectionLabels'
import {useEffect,useState,useMemo} from 'react'
import {Tabs,control,statusLabel} from '@/features/product/ui'
import {useProduct} from '@/features/product/integration/Provider'
import {safeMessage} from '@/features/product/integration/repository'
import {productDate} from '@/features/product/presentation'
import {NamedOperator} from '@/features/customers/CustomerDomainPages'
import {NamedStage} from '@/features/product/integration/NamedStage'
import {AssignedCommercial} from '@/features/product/integration/AssignedCommercial'
import {CustomerSelect} from '@/features/product/integration/CustomerSelect'
import type {TelecomReadInputsV1,TelecomReadOperationV1} from '@/lib/contracts/telecom-reads-v1'
type ReportOperation=Exclude<TelecomReadOperationV1,'customer360.summary'>
type ReportPage={as_of:string;items:readonly Record<string,unknown>[];next_id:string|null;unassigned_counts?:Readonly<Record<string,number>>}
const reports={Operadores:{op:'report.operator_portfolio',fields:['customers','contracts','services','lines'],key:'operator'},Servicios:{op:'report.services_by_kind',fields:['pending','active','suspended','ended','cancelled'],key:'service_kind'},Líneas:{op:'report.lines_by_status',fields:['count'],key:'status'},Renovaciones:{op:'report.renewals_by_month',fields:['open','completed','dismissed','not_applicable'],key:'month'},Permanencias:{op:'report.permanences_by_month',fields:['open','cancelled'],key:'month'},Portabilidades:{op:'report.portabilities_by_status',fields:['count'],key:'status'},Incidencias:{op:'report.cases_by_priority_status',fields:['count'],key:'case'},Pipeline:{op:'report.pipeline_by_stage',fields:['open','won','lost','cancelled'],key:'stage'},Comerciales:{op:'report.commercial_owner_counts',fields:['contracts','opportunities','tasks','cases'],key:'owner'}} as const
type Area=keyof typeof reports
const names:Record<string,string>={customers:'Clientes',contracts:'Contratos',services:'Servicios',lines:'Líneas',count:'Recuento',opportunities:'Oportunidades',tasks:'Tareas',cases:'Incidencias',low:'Baja',normal:'Normal',high:'Alta',urgent:'Urgente',mobile:'Móvil',fiber:'Fibra',fixed_voice:'Voz fija',data_connectivity:'Conectividad',other:'Otros'}
function initialMonth(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit'}).format(new Date())}
export function TelecomReports(){
 const [area,setArea]=useState<Area>('Operadores'),[customer,setCustomer]=useState(''),[from,setFrom]=useState(initialMonth),[to,setTo]=useState(initialMonth)
 return <section className="space-y-4"><div><h2 className="text-lg font-semibold">Informes Telecom</h2><p className="mt-1 text-sm text-slate-500">Recuentos completos de cada grupo autorizado. Las listas de operadores, etapas y comerciales se paginan sin extrapolar sus totales.</p></div><div className="rounded-xl border bg-white p-4"><CustomerSelect value={customer} onChange={setCustomer} inputLabel="Buscar empresa para informes Telecom" clearLabel="Todos los clientes"/></div><Tabs prefix="telecom-report-" items={Object.keys(reports)} value={area} onChange={s=>setArea(s as Area)}/>{(area==='Renovaciones'||area==='Permanencias')&&<div className="flex flex-wrap gap-3"><label className="text-sm">Desde<input aria-label="Informes Telecom desde" className={control+' ml-2'} type="month" min="2000-01" max="2100-12" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Hasta<input aria-label="Informes Telecom hasta" className={control+' ml-2'} type="month" min="2000-01" max="2100-12" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<section tabIndex={0} role="tabpanel" id={`telecom-report-panel-${area}`} aria-labelledby={`telecom-report-tab-${area}`}><Report key={JSON.stringify([area,customer,from,to])} area={area} customer={customer} from={from} to={to}/></section></section>
}
function Report({area,customer,from,to}:{area:Area;customer:string;from:string;to:string}){
 const {repository}=useProduct(),definition=reports[area],operation=definition.op,[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),key=JSON.stringify([area,customer,from,to,cursors,revision]),[state,setState]=useState<{key:string;data?:ReportPage;error?:string}|null>(null),current=state?.key===key?state:null,data=current?.data

 useEffect(()=>{let active=true;const input={...(customer?{customer_id:customer}:{}),...(['Renovaciones','Permanencias'].includes(area)?{from_month:from+'-01',to_month:to+'-01'}:{}),...(['Operadores','Pipeline','Comerciales'].includes(area)?{limit:20,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})}:{})};void repository.telecom(operation,input as TelecomReadInputsV1[ReportOperation]).then(d=>{if(active)setState({key,data:d as unknown as ReportPage})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,operation,area,customer,from,to,cursors,key])
 const labelRows=useMemo(()=>data?.items.map(r=>definition.key==='operator'?{operator_id:r.id}:definition.key==='owner'?{assigned_user_id:r.id}:definition.key==='stage'?{stage_id:r.id}:r)??[],[data,definition.key])
 function label(row:Record<string,unknown>){if(definition.key==='operator')return <NamedOperator id={String(row.id)}/>;if(definition.key==='owner')return <AssignedCommercial id={String(row.id)}/>;if(definition.key==='stage')return <NamedStage id={String(row.id)}/>;if(definition.key==='case')return (names[String(row.priority)]??'Prioridad no disponible')+' · '+statusLabel(String(row.status));if(definition.key==='month')return productDate(String(row.month));return names[String(row[definition.key])]??statusLabel(String(row[definition.key]))}
 return <section className="overflow-hidden rounded-xl border bg-white" aria-label={'Informe Telecom '+area}><div className="flex flex-wrap justify-between gap-3 border-b p-4"><h3 className="font-semibold">{area}</h3><button className={control} onClick={()=>setRevision(v=>v+1)}>Actualizar informe {area}</button></div>{current?.error?<div className="p-4"><p role="alert" className="text-sm text-red-700">{current.error}</p><button className={control+' mt-3'} onClick={()=>setRevision(v=>v+1)}>Reintentar informe {area}</button></div>:!data?<p role="status" className="p-4 text-sm text-slate-500">Consultando informe {area.toLowerCase()}…</p>:<ScopedCollectionLabels rows={labelRows}>{!data.items.length?<p className="p-5 text-sm text-slate-500">No hay grupos registrados en esta consulta.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><caption className="sr-only">Recuentos completos por grupo del informe {area}</caption><thead className="bg-slate-50 text-slate-500"><tr><th scope="col" className="p-3">Grupo</th>{definition.fields.map(f=><th scope="col" className="p-3" key={f}>{names[f]??statusLabel(f)}</th>)}</tr></thead><tbody className="divide-y">{data.items.map((r,i)=><tr key={String(r.id??r.month??r.service_kind??r.status??i)+String(r.priority??'')} data-telecom-report-row={operation}><th scope="row" className="min-w-36 p-3 font-medium">{label(r)}</th>{definition.fields.map(f=><td className="p-3" key={f}>{Number(r[f]).toLocaleString('es-ES')}</td>)}</tr>)}</tbody></table></div>}{data.unassigned_counts&&<dl className="grid grid-cols-2 gap-3 border-t p-4 sm:grid-cols-4">{Object.entries(data.unassigned_counts).map(([k,v])=><div key={k}><dt className="text-xs text-slate-500">{names[k]} sin responsable</dt><dd className="mt-1 font-semibold">{v.toLocaleString('es-ES')}</dd></div>)}</dl>}<footer className="flex flex-wrap justify-between gap-2 border-t p-4"><button className={control} disabled={!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Grupos anteriores de {area}</button><span className="self-center text-xs text-slate-500">Página {cursors.length+1} · {data.items.length} grupos · {productDate(data.as_of)}</span><button className={control} disabled={!data.next_id} onClick={()=>{if(data.next_id)setCursors(v=>[...v,data.next_id!])}}>Más grupos de {area}</button></footer></ScopedCollectionLabels>}</section>
}
