'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
import { Opportunities } from './Opportunities'
import { Drawer, control, primary, Status } from '@/features/product/ui'
import { useProduct } from '@/features/product/integration/Provider'
import { commandIntent, ProductUiError, safeMessage } from '@/features/product/integration/repository'
import type { StageCatalogV1, WorkGetV1 } from '@/lib/contracts/product-queries-v1'
import type { OpportunityItemV1 } from '@/lib/contracts/telecom-v1'
import type { ProductReceiptV1 } from '@/lib/contracts/product-v1'
type Opportunity=Extract<WorkGetV1,{kind:'opportunity'}>
export function IntegratedOpportunities(){
  const {repository,role}=useProduct(),[query,setQuery]=useState(''),[customers,setCustomers]=useState<{id:string;name:string}[]>([]),[records,setRecords]=useState<Opportunity[]>([]),[stages,setStages]=useState<StageCatalogV1|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState<{record?:Opportunity}|null>(null)
  useEffect(()=>{let current=true;void repository.stages().then(v=>{if(current)setStages(v)}).catch(e=>{if(current)setError(safeMessage(e))});return()=>{current=false}},[repository])
  const search=useCallback(async()=>{setBusy(true);setError('');try{const data=await repository.search(query);setCustomers(data.items.filter(i=>i.kind==='customer').map(i=>({id:i.id,name:i.label})));const found=await Promise.all(data.items.filter(i=>i.kind==='opportunity').map(i=>repository.work('opportunity',i.id)));setRecords(found.filter((i):i is Opportunity=>i.kind==='opportunity'))}catch(e){setRecords([]);setError(safeMessage(e))}finally{setBusy(false)}},[repository,query])
  const rows:OpportunityItemV1[]=records.map(({record:r})=>({id:r.id,kind:'opportunity',title:r.title,status:r.status as OpportunityItemV1['status'],customer:r.customer_id?{kind:'customer',id:r.customer_id,display_name:'Cliente vinculado'}:null,destination:null,capabilities:[],stage:{kind:'opportunity_stage',id:r.stage_id,display_name:stages?.items.find(s=>s.id===r.stage_id)?.display_name??'Etapa no disponible'},next_follow_up_at:r.next_follow_up_at,follow_up_state:r.next_follow_up_at?'scheduled':'none',amount:r.amount_minor!==null&&r.currency?{minor_units:r.amount_minor,currency:r.currency}:null,owner:r.owner_user_id?{kind:'user',id:r.owner_user_id,display_name:'Responsable asignado'}:null}))
  return <div className="space-y-4"><form onSubmit={e=>{e.preventDefault();void search()}} className="flex flex-wrap gap-2"><input aria-label="Consultar pipeline local" placeholder="Buscar empresa u oportunidad" minLength={2} maxLength={100} required className={control} value={query} onChange={e=>setQuery(e.target.value)}/><button className={primary} disabled={busy}>Consultar pipeline</button></form><p className="text-xs text-slate-500">Hasta cinco oportunidades y cinco clientes por consulta. Las columnas usan el catálogo autorizado de etapas; los recuentos corresponden a los resultados visibles.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{stages?.next_id&&<p className="text-xs text-amber-800">Catálogo parcial: primeras 100 etapas.</p>}
    <Opportunities items={rows} stageCatalog={stages?.items.filter(s=>s.status==='active').sort((a,b)=>a.position-b.position).map(s=>({id:s.id,label:s.display_name}))} onCreate={role&&role!=='viewer'&&customers.length&&stages?()=>setEditor({}):undefined} onSelect={async id=>{try{const v=await repository.work('opportunity',id);if(v.kind==='opportunity')setEditor({record:v})}catch(e){setError(safeMessage(e))}}}/>
    {editor&&stages&&<OpportunityEditor record={editor.record} stages={stages} customers={customers} canWrite={role!==null&&role!=='viewer'} onClose={()=>setEditor(null)} onSaved={async receipt=>{const value=await repository.work('opportunity',receipt.id);if(value.kind==='opportunity')setRecords(current=>[...current.filter(r=>r.record.id!==value.record.id),value]);setEditor(null)}}/>}
  </div>
}
function OpportunityEditor({record,stages,customers,canWrite,onClose,onSaved}:{record?:Opportunity;stages:StageCatalogV1;customers:{id:string;name:string}[];canWrite:boolean;onClose:()=>void;onSaved:(receipt:ProductReceiptV1)=>Promise<void>}){
  const {repository}=useProduct(),r=record?.record
  const [title,setTitle]=useState(r?.title??''),[customerId,setCustomerId]=useState(r?.customer_id??customers[0]?.id??''),[stageId,setStageId]=useState(r?.stage_id??stages.items.find(s=>!s.outcome&&s.status==='active')?.id??'')
  const [amount,setAmount]=useState(r?.amount_minor===null||r?.amount_minor===undefined?'':String(r.amount_minor/100)),[currency,setCurrency]=useState(r?.currency??'EUR'),[expectedClose,setExpectedClose]=useState(r?.expected_close_date??''),[nextAction,setNextAction]=useState(r?.next_action??''),[reason,setReason]=useState('customer_decision'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(null)
  const pending=useRef<{execute:()=>Promise<ProductReceiptV1>}|null>(null),uncertain=error instanceof ProductUiError&&error.code==='transport_uncertain',conflict=error instanceof ProductUiError&&error.code==='conflict'
  const stage=stages.items.find(s=>s.id===stageId)
  async function execute(action:'save'|'stage'|'archive'){
    if(busy||conflict||!canWrite)return;setBusy(true);setError(null)
    try{if(!pending.current){const base=r?{id:r.id,expected_version:r.version}:null;let command
      if(action==='archive'&&base)command=commandIntent('opportunity.archive',base)
      else if(action==='stage'&&base){if(!stage)throw new ProductUiError('validation');command=stage.outcome==='won'?commandIntent('opportunity.win',{...base,stage_id:stage.id}):stage.outcome==='lost'?commandIntent('opportunity.lose',{...base,stage_id:stage.id,close_reason_code:reason}):r?.status==='won'||r?.status==='lost'?commandIntent('opportunity.reopen',{...base,stage_id:stage.id}):commandIntent('opportunity.change_stage',{...base,stage_id:stage.id})}
      else{if(amount&&!/^\d+(\.\d{1,2})?$/.test(amount))throw new ProductUiError('validation');const fields={title,amount_minor:amount?Math.round(Number(amount)*100):null,currency:currency as 'EUR'|'USD'|'GBP',expected_close_date:expectedClose||null,next_action:nextAction||null};command=base?commandIntent('opportunity.update',{...base,...fields}):commandIntent('opportunity.create',{...fields,customer_id:customerId,stage_id:stageId})}
      pending.current={execute:()=>command.execute(repository)}
    }
    const receipt=await pending.current.execute();pending.current=null;await onSaved(receipt)
    }catch(e){setError(e);if(!(e instanceof ProductUiError&&e.code==='transport_uncertain'))pending.current=null}finally{setBusy(false)}
  }
  const locked=busy||uncertain||conflict||!canWrite
  return <Drawer title={r?'Detalle de oportunidad':'Nueva oportunidad'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={e=>{e.preventDefault();void execute('save')}} className="space-y-4">{r&&<><Status value={r.status}/><p className="text-xs text-slate-500">Origen: {r.source}</p></>}<fieldset disabled={locked||r?.source==='import'||r?.source==='integration'} className="space-y-3"><label className="block text-sm">Título comercial<input className={`${control} mt-1 w-full`} required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block text-sm">Cliente<select className={`${control} mt-1 w-full`} disabled={!!r} value={customerId} onChange={e=>setCustomerId(e.target.value)}>{r&&<option value={r.customer_id??''}>Cliente vinculado</option>}{!r&&customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block text-sm">Importe<input className={`${control} mt-1 w-full`} inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value.replace(',','.'))}/></label><label className="block text-sm">Moneda<select className={`${control} mt-1 w-full`} value={currency} onChange={e=>setCurrency(e.target.value as typeof currency)}><option value="EUR">EUR</option><option value="USD">USD</option><option value="GBP">GBP</option></select></label><label className="block text-sm">Cierre previsto<input className={`${control} mt-1 w-full`} type="date" value={expectedClose} onChange={e=>setExpectedClose(e.target.value)}/></label><label className="block text-sm">Próxima acción<input className={`${control} mt-1 w-full`} maxLength={200} value={nextAction} onChange={e=>setNextAction(e.target.value)}/></label><label className="block text-sm">Etapa<select aria-label="Etapa comercial" className={`${control} mt-1 w-full`} value={stageId} onChange={e=>setStageId(e.target.value)}>{stages.items.filter(s=>s.status==='active'&&(r||!s.outcome)).map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select></label>{stage?.outcome==='lost'&&<label className="block text-sm">Motivo<select className={control} value={reason} onChange={e=>setReason(e.target.value)}><option value="customer_decision">Decisión del cliente</option><option value="price">Precio</option><option value="timing">Momento</option></select></label>}</fieldset>
    {!!error&&<p role="alert" className="text-red-700">{safeMessage(error)}</p>}{conflict&&<button type="button" className={control} onClick={onClose}>Cerrar y consultar la versión actual</button>}{canWrite&&r?.source!=='import'&&r?.source!=='integration'&&<div className="flex flex-wrap gap-2"><button className={primary} disabled={busy||conflict}>{busy?'Guardando…':uncertain?'Reintentar la misma acción':'Guardar oportunidad'}</button>{r&&!uncertain&&<><button type="button" className={control} disabled={locked} onClick={()=>execute('stage')}>Aplicar etapa</button><button type="button" className={control} disabled={locked} onClick={()=>execute('archive')}>Archivar oportunidad</button></>}</div>}
    {r&&<section><h3 className="font-semibold">Historial de cambios</h3>{r.history.map(h=><p key={h.version} className="py-2 text-xs text-slate-500">{{'opportunity.create':'Oportunidad creada','opportunity.update':'Datos actualizados','opportunity.change_stage':'Etapa cambiada','opportunity.win':'Ganada','opportunity.lose':'Perdida','opportunity.reopen':'Reabierta','opportunity.archive':'Archivada','opportunity.assign':'Responsable cambiado'}[h.operation]??'Cambio registrado'} · {h.occurred_at}</p>)}{r.history_partial&&<p className="text-xs text-amber-800">Historial parcial: últimos 50 cambios.</p>}</section>}<p className="text-xs text-slate-500">Responsables, nuevos vínculos de cartera y arrastre del tablero pendientes. No se modifican hechos importados.</p></form></Drawer>
}
