'use client'
import Link from 'next/link'
import {useRef,useState} from 'react'
import {useProduct} from '@/features/product/integration/Provider'
import {ProductUiError,safeMessage} from '@/features/product/integration/repository'
import {control,primary} from '@/features/product/ui'
type Candidate={kind:'contract'|'service';id:string;label:string;contractId:string}
export function OpportunityProductLinks({customerId,value,existing,disabled,onChange}:{customerId:string;value:{contractId:string|null;serviceId:string|null};existing:readonly {kind:'contract'|'service'|'plan';id:string}[];disabled:boolean;onChange:(contractId:string|null,serviceId:string|null)=>void}){
 const {repository}=useProduct(),[query,setQuery]=useState(''),[state,setState]=useState<{customerId:string;items:Candidate[];excluded:number;error:string}|null>(null),[busy,setBusy]=useState(false),attempt=useRef(0)
 const current=state?.customerId===customerId?state:null
 async function search(){if(disabled||busy||query.trim().length<2)return;const n=++attempt.current;setBusy(true);setState(null);try{const matches=(await repository.search(query)).items.filter(i=>i.kind==='contract'||i.kind==='service');const items:Candidate[]=[];let excluded=0;for(const i of matches){const kind=i.kind as 'contract'|'service',v=await repository.portfolio(kind,i.id);if(v.kind!=='contract'&&v.kind!=='service')throw new ProductUiError('internal_safe');if(v.record.customer_id!==customerId){excluded++;continue}if(v.kind==='contract')items.push({kind,id:i.id,label:i.label,contractId:i.id});else if(v.kind==='service')items.push({kind,id:i.id,label:i.label,contractId:v.record.contract_id})}if(attempt.current===n)setState({customerId,items,excluded,error:''})}catch(e){if(attempt.current===n)setState({customerId,items:[],excluded:0,error:safeMessage(e)})}finally{if(attempt.current===n)setBusy(false)}}
 return <section aria-label="Productos de la oportunidad" className="space-y-3 rounded-lg border p-3"><h3 className="font-semibold">Productos vinculados</h3><p className="text-xs text-slate-500">Los cambios se guardan con la oportunidad. Seleccionar un contrato quita el servicio anterior; seleccionar un servicio conserva su contrato autorizado.</p><div className="flex flex-wrap gap-2">{value.contractId&&<Link className={control} href={'/portfolio?kind=contract&id='+value.contractId}>Consultar contrato vinculado</Link>}{value.serviceId&&<Link className={control} href={'/portfolio?kind=service&id='+value.serviceId}>Consultar servicio vinculado</Link>}{existing.some(l=>l.kind==='plan')&&<p className="text-xs text-slate-500">Plan registrado. Se conserva su referencia; catálogo de selección pendiente.</p>}{!value.contractId&&!value.serviceId&&<p className="text-sm text-slate-500">Sin contrato o servicio seleccionado.</p>}</div>{!disabled&&<><label className="block text-sm">Buscar productos de esta empresa<input aria-label="Buscar productos de esta empresa" className={control+' mt-1 w-full'} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search()}}}/></label><button type="button" className={primary} disabled={busy||query.trim().length<2} onClick={search}>{busy?'Consultando productos…':'Consultar productos autorizados'}</button><p className="text-xs text-slate-500">Hasta cinco contratos y cinco servicios por consulta. Solo se pueden seleccionar registros de esta empresa.</p>{current?.error&&<p role="alert" className="text-red-700">{current.error}</p>}{current?.items.map(i=><button type="button" data-link-target={i.id} key={i.kind+i.id} className={control+' block max-w-full whitespace-normal text-left'} onClick={()=>onChange(i.contractId,i.kind==='service'?i.id:null)}>{i.kind==='contract'?'Seleccionar contrato':'Seleccionar servicio'} · {i.label}</button>)}{current&&!current.error&&!current.items.length&&<p className="text-sm text-slate-500">Sin productos seleccionables en estos resultados.</p>}{!!current?.excluded&&<p className="text-xs text-slate-500">Se han excluido registros de otra empresa.</p>}{(value.contractId||value.serviceId)&&<button type="button" className={control} onClick={()=>onChange(null,null)}>Quitar contrato y servicio seleccionados</button>}</>}</section>
}
