-- Normal commercial service cases and private append-only internal notes. Apply once.
-- No legacy origin certification, free text audit, external provider action or AI grant.
begin;
alter table public.service_cases add column version bigint not null default 1 check(version>0 and version<1000000000000000),add column internal_note_count bigint not null default 0 check(internal_note_count between 0 and 1000000),add column resolution_code text check(resolution_code in('issue_fixed','request_fulfilled','customer_confirmed','no_action_required')),add column cancellation_code text check(cancellation_code in('customer_withdrew','duplicate','no_longer_needed','entered_in_error'));
create trigger service_case_version before insert or update on public.service_cases for each row execute function public.manage_task_version();
create trigger service_case_no_delete before delete on public.service_cases for each row execute function public.reject_activity_mutation();
create table public.service_case_internal_notes(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),case_id uuid not null,seq bigint not null check(seq between 1 and 1000000),body text not null check(char_length(btrim(body))between 1 and 4000 and body!~'[\x01-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]'),actor_user_id uuid not null references auth.users(id),created_at timestamptz not null default statement_timestamp(),unique(workspace_id,case_id,seq),foreign key(case_id,workspace_id)references public.service_cases(id,workspace_id)
);
alter table public.service_case_internal_notes enable row level security;alter table public.service_case_internal_notes force row level security;
revoke all on public.service_cases,public.service_case_internal_notes from public,anon,authenticated,service_role;
create trigger service_case_note_append_only before update or delete on public.service_case_internal_notes for each row execute function public.reject_activity_mutation();
create index service_case_page on public.service_cases(workspace_id,id);
create function public.case_v1_guard_row()returns trigger language plpgsql set search_path=''as $$begin
 if tg_op='UPDATE'and(new.customer_id,new.contract_id,new.service_id,new.line_id,new.source,new.created_at)is distinct from(old.customer_id,old.contract_id,old.service_id,old.line_id,old.source,old.created_at)then raise exception using errcode='55000',message='case_context_immutable';end if;return new;
end$$;
create trigger service_case_frozen_context before update on public.service_cases for each row execute function public.case_v1_guard_row();
do $$declare expr text;begin select pg_get_expr(conbin,conrelid)into expr from pg_constraint where conrelid='public.product_commands'::regclass and conname='product_commands_operation_check';alter table public.product_commands drop constraint product_commands_operation_check;execute 'alter table public.product_commands add constraint product_commands_operation_check check(('||expr||')or operation in(''case.create'',''case.update'',''case.assign'',''case.change_status'',''case.resolve'',''case.reopen'',''case.close'',''case.cancel'',''case.note_create''))';end$$;
create function public.case_v1_validate(op text,inp jsonb)returns void language plpgsql set search_path=''as $$declare req text[];opt text[]:=array[]::text[];k text;v jsonb;s text;begin
 case op
when 'case.create'then req:=array['command_id','customer_id','contract_id','service_id','line_id','case_type','title','priority','due_on','assigned_user_id']::text[];
when 'case.update'then req:=array['command_id','id','expected_version','case_type','title','priority','due_on']::text[];
when 'case.assign'then req:=array['command_id','id','expected_version','assigned_user_id']::text[];
when 'case.change_status'then req:=array['command_id','id','expected_version','status']::text[];
when 'case.resolve'then req:=array['command_id','id','expected_version','resolution_code']::text[];
when 'case.reopen'then req:=array['command_id','id','expected_version']::text[];
when 'case.close'then req:=array['command_id','id','expected_version']::text[];
when 'case.cancel'then req:=array['command_id','id','expected_version','cancellation_code']::text[];
when 'case.note_create'then req:=array['command_id','id','expected_version','body']::text[];
when 'case.list'then req:=array[]::text[];
when 'case.get'then req:=array['id']::text[];
when 'case.note_list'then req:=array['id']::text[];
 else raise exception using errcode='22023',message='case_invalid_operation';end case;
 if op='case.list'then opt:=array['limit','after_id','customer_id','contract_id','service_id','line_id','assigned_user_id','case_type','priority','status','source','due_from','due_to','overdue'];elsif op='case.note_list'then opt:=array['limit','after_seq'];end if;
 if inp is null or jsonb_typeof(inp)<>'object'or octet_length(inp::text)>20000 or exists(select 1 from jsonb_object_keys(inp)x where not x=any(req||opt))or exists(select 1 from unnest(req)x where not inp?x)then raise exception using errcode='22023',message='case_invalid_input';end if;
 for k,v in select key,value from jsonb_each(inp)loop s:=inp->>k;
 if v='null'::jsonb and k in('contract_id','service_id','line_id','assigned_user_id','due_on')and op<>'case.list'then continue;end if;
 if k='id'or k like '%_id'then if jsonb_typeof(v)is distinct from 'string'or s!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='case_invalid_input';end if;
 elsif k in('expected_version','limit','after_seq')then if jsonb_typeof(v)is distinct from 'number'or s!~'^(0|[1-9][0-9]{0,14})$'or(k<>'after_seq'and s::bigint<1)or(k='limit'and s::bigint>100)or(k='after_seq'and s::bigint>1000000)then raise exception using errcode='22023',message='case_invalid_input';end if;
 elsif k in('due_on','due_from','due_to')then if jsonb_typeof(v)is distinct from 'string'or s!~'^(19|20|21)[0-9]{2}-[0-9]{2}-[0-9]{2}$'or to_char(s::date,'YYYY-MM-DD')<>s then raise exception using errcode='22023',message='case_invalid_input';end if;
 elsif k='overdue'then if jsonb_typeof(v)is distinct from 'boolean'then raise exception using errcode='22023',message='case_invalid_input';end if;
 else if jsonb_typeof(v)is distinct from 'string'or(k='body'and(char_length(btrim(s))not between 1 and 4000 or s~'[\x01-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]'))or(k='title'and(char_length(btrim(s))not between 1 and 200 or s~'[[:cntrl:]]'))or(k='case_type'and s not in('activation','portability','technical','billing','renewal','cancellation','documentation','other'))or(k='priority'and s not in('low','normal','high','urgent'))or(k='status'and s not in('open','in_progress','waiting_customer','waiting_operator','resolved','closed','cancelled'))or(k='source'and s not in('manual','import','integration','system'))or(k='resolution_code'and s not in('issue_fixed','request_fulfilled','customer_confirmed','no_action_required'))or(k='cancellation_code'and s not in('customer_withdrew','duplicate','no_longer_needed','entered_in_error'))then raise exception using errcode='22023',message='case_invalid_input';end if;end if;
 end loop;
 if op='case.create'and((inp->>'service_id'is not null and inp->>'contract_id'is null)or(inp->>'line_id'is not null and inp->>'service_id'is null))or op='case.change_status'and inp->>'status'not in('open','in_progress','waiting_customer','waiting_operator')or op='case.list'and((inp?'due_from')<>(inp?'due_to')or inp?'due_from'and((inp->>'due_to')::date<(inp->>'due_from')::date or(inp->>'due_to')::date-(inp->>'due_from')::date>366))then raise exception using errcode='22023',message='case_invalid_input';end if;
end$$;
create function public.case_v1_command(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare a uuid;prior jsonb;c public.service_cases%rowtype;note_id uuid;begin
 a:=public.product_v1_assert_scope(p_workspace_id,true);perform public.case_v1_validate(p_operation,p_input);if p_operation in('case.list','case.get','case.note_list')then raise exception using errcode='22023',message='case_invalid_operation';end if;
 prior:=public.product_v1_begin_command(p_workspace_id,a,p_operation,p_input);if prior is not null then return prior;end if;
 if p_operation='case.create'then
 perform 1 from public.customers where workspace_id=p_workspace_id and id=(p_input->>'customer_id')::uuid and status='active'for share;if not found then raise exception using errcode='P0002',message='case_customer_not_found';end if;
 if p_input->>'contract_id'is not null then perform 1 from public.telecom_contracts where workspace_id=p_workspace_id and id=(p_input->>'contract_id')::uuid and customer_id=(p_input->>'customer_id')::uuid for share;if not found then raise exception using errcode='P0002',message='case_context_not_found';end if;end if;
 if p_input->>'service_id'is not null then perform 1 from public.telecom_services where workspace_id=p_workspace_id and id=(p_input->>'service_id')::uuid and customer_id=(p_input->>'customer_id')::uuid and contract_id=(p_input->>'contract_id')::uuid for share;if not found then raise exception using errcode='P0002',message='case_context_not_found';end if;end if;
 if p_input->>'line_id'is not null then perform 1 from public.telecom_lines where workspace_id=p_workspace_id and id=(p_input->>'line_id')::uuid and service_id=(p_input->>'service_id')::uuid for share;if not found then raise exception using errcode='P0002',message='case_context_not_found';end if;end if;
 else select *into c from public.service_cases where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid for update;if not found then raise exception using errcode='P0002',message='case_not_found';end if;
 if c.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='case_conflict';end if;
 if c.status in('closed','cancelled')then raise exception using errcode='22023',message='case_invalid_transition';end if;
 if p_operation not in('case.assign','case.note_create')and c.source<>'manual'then raise exception using errcode='42501',message='case_external_read_only';end if;end if;
 if p_operation in('case.create','case.assign')and p_input->>'assigned_user_id'is not null then perform 1 from public.workspace_members wm join public.workspaces w on w.id=wm.workspace_id where wm.workspace_id=p_workspace_id and wm.user_id=(p_input->>'assigned_user_id')::uuid and wm.status='active'and wm.role in('owner','admin','member')and w.status='active'for share of wm,w;if not found then raise exception using errcode='42501',message='case_invalid_assignee';end if;end if;
 if p_operation='case.create'then insert into public.service_cases(workspace_id,customer_id,contract_id,service_id,line_id,case_type,title,priority,due_on,assigned_user_id,created_by_user_id)values(p_workspace_id,(p_input->>'customer_id')::uuid,(p_input->>'contract_id')::uuid,(p_input->>'service_id')::uuid,(p_input->>'line_id')::uuid,p_input->>'case_type',p_input->>'title',p_input->>'priority',(p_input->>'due_on')::date,(p_input->>'assigned_user_id')::uuid,a)returning *into c;
 elsif p_operation='case.update'then if c.status='resolved'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set case_type=p_input->>'case_type',title=p_input->>'title',priority=p_input->>'priority',due_on=(p_input->>'due_on')::date where id=c.id returning *into c;
 elsif p_operation='case.assign'then update public.service_cases set assigned_user_id=(p_input->>'assigned_user_id')::uuid where id=c.id returning *into c;
 elsif p_operation='case.change_status'then if c.status='resolved'or c.status=p_input->>'status'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set status=p_input->>'status'where id=c.id returning *into c;
 elsif p_operation='case.resolve'then if c.status='resolved'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set status='resolved',resolved_at=statement_timestamp(),resolution_code=p_input->>'resolution_code'where id=c.id returning *into c;
 elsif p_operation='case.reopen'then if c.status<>'resolved'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set status='open',resolved_at=null,resolution_code=null where id=c.id returning *into c;
 elsif p_operation='case.close'then if c.status<>'resolved'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set status='closed',closed_at=statement_timestamp()where id=c.id returning *into c;
 elsif p_operation='case.cancel'then if c.status='resolved'then raise exception using errcode='22023',message='case_invalid_transition';end if;update public.service_cases set status='cancelled',closed_at=statement_timestamp(),cancellation_code=p_input->>'cancellation_code'where id=c.id returning *into c;
 else update public.service_cases set internal_note_count=internal_note_count+1 where id=c.id returning *into c;insert into public.service_case_internal_notes(workspace_id,case_id,seq,body,actor_user_id)values(p_workspace_id,c.id,c.internal_note_count,p_input->>'body',a)returning id into note_id;end if;
 prior:=jsonb_build_object('contract_version','case.v1','operation',p_operation,'command_id',p_input->>'command_id','id',c.id,'version',c.version,'status',c.status,'source',c.source,'resolution_code',c.resolution_code,'cancellation_code',c.cancellation_code,'note_id',note_id,'note_seq',case when note_id is not null then c.internal_note_count else null end);
 insert into public.product_audit_events(workspace_id,actor_id,command_id,operation,entity_id,entity_version)values(p_workspace_id,a,(p_input->>'command_id')::uuid,p_operation,c.id,c.version);
 update public.product_commands set receipt=prior where workspace_id=p_workspace_id and actor_id=a and command_id=(p_input->>'command_id')::uuid;return prior;
 exception when unique_violation then raise exception using errcode='40001',message='case_conflict';when integrity_constraint_violation or data_exception then raise exception using errcode='22023',message='case_invalid_input';end$$;
create function public.case_v1_query(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare rows jsonb;lim int;next_id uuid;next_seq bigint;begin
 perform public.product_v1_assert_scope(p_workspace_id,false);perform public.case_v1_validate(p_operation,p_input);if p_operation not in('case.list','case.get','case.note_list')then raise exception using errcode='22023',message='case_invalid_operation';end if;
 lim:=case when p_operation='case.get'then 1 else coalesce((p_input->>'limit')::int,50)end;
 if p_operation='case.note_list'then
 perform 1 from public.workspace_members where workspace_id=p_workspace_id and user_id=auth.uid()and status='active'and role in('owner','admin','member');if not found then raise exception using errcode='42501',message='case_private_notes_denied';end if;
 perform 1 from public.service_cases where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid;if not found then raise exception using errcode='P0002',message='case_not_found';end if;
 select coalesce(jsonb_agg(to_jsonb(x)order by seq),'[]'::jsonb)into rows from(select id,seq,body,actor_user_id,created_at from public.service_case_internal_notes where workspace_id=p_workspace_id and case_id=(p_input->>'id')::uuid and seq>coalesce((p_input->>'after_seq')::bigint,0)order by seq limit lim+1)x;
 if jsonb_array_length(rows)>lim then rows:=rows-lim;next_seq:=(rows->(lim-1)->>'seq')::bigint;end if;
 return jsonb_build_object('contract_version','case.v1','operation',p_operation,'case_id',p_input->>'id','items',rows,'next_seq',next_seq);
 end if;
 select coalesce(jsonb_agg(to_jsonb(x)order by id),'[]'::jsonb)into rows from(select c.id,c.version,c.customer_id,c.contract_id,c.service_id,c.line_id,c.case_type,c.title,c.priority,c.due_on,c.assigned_user_id,c.status,c.source,c.resolved_at,c.closed_at,c.resolution_code,c.cancellation_code,c.internal_note_count,c.created_at,c.updated_at,coalesce(c.due_on<(statement_timestamp()at time zone'Europe/Madrid')::date and c.status in('open','in_progress','waiting_customer','waiting_operator'),false)as overdue from public.service_cases c where c.workspace_id=p_workspace_id and(p_operation<>'case.get'or c.id=(p_input->>'id')::uuid)and(not p_input?'after_id'or c.id>(p_input->>'after_id')::uuid)and(not p_input?'customer_id'or c.customer_id=(p_input->>'customer_id')::uuid)and(not p_input?'contract_id'or c.contract_id=(p_input->>'contract_id')::uuid)and(not p_input?'service_id'or c.service_id=(p_input->>'service_id')::uuid)and(not p_input?'line_id'or c.line_id=(p_input->>'line_id')::uuid)and(not p_input?'assigned_user_id'or c.assigned_user_id=(p_input->>'assigned_user_id')::uuid)and(not p_input?'case_type'or c.case_type=p_input->>'case_type')and(not p_input?'priority'or c.priority=p_input->>'priority')and(not p_input?'status'or c.status=p_input->>'status')and(not p_input?'source'or c.source=p_input->>'source')and(not p_input?'due_from'or c.due_on between(p_input->>'due_from')::date and(p_input->>'due_to')::date)and(not p_input?'overdue'or coalesce(c.due_on<(statement_timestamp()at time zone'Europe/Madrid')::date and c.status in('open','in_progress','waiting_customer','waiting_operator'),false)=(p_input->>'overdue')::boolean)order by c.id limit lim+1)x;
 if p_operation='case.get'then if jsonb_array_length(rows)=0 then return null;end if;return jsonb_build_object('contract_version','case.v1','operation',p_operation,'record',rows->0);end if;
 if jsonb_array_length(rows)>lim then rows:=rows-lim;next_id:=(rows->(lim-1)->>'id')::uuid;end if;return jsonb_build_object('contract_version','case.v1','operation',p_operation,'items',rows,'next_id',next_id);
end$$;
revoke all on function public.case_v1_guard_row(),public.case_v1_validate(text,jsonb),public.case_v1_command(uuid,text,jsonb),public.case_v1_query(uuid,text,jsonb)from public,anon,authenticated,service_role;
grant execute on function public.case_v1_command(uuid,text,jsonb),public.case_v1_query(uuid,text,jsonb)to authenticated;
commit;
