-- Forward-only, ledger-applied once. Read-only functions; no provider success or stored derived state.
begin;
create function public.telecom_attention_v1_validate(inp jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare k text; v jsonb; s text; n int; begin
 if inp is null or jsonb_typeof(inp)<>'object' or octet_length(inp::text)>4096
 or not(inp?'window_from' and inp?'window_to')
 or exists(select 1 from jsonb_object_keys(inp)x where not x=any(array['window_from','window_to','customer_id','owner_user_id','kind','limit','fallback_on','after_sort_on','after_kind','after_id']))
 then raise exception using errcode='22023',message='attention_invalid_input';end if;
 for k,v in select key,value from jsonb_each(inp)loop s:=inp->>k;
 if k='limit' then
 if jsonb_typeof(v)<>'number' or s!~'^[1-9][0-9]{0,2}$' or s::int>100 then raise exception using errcode='22023',message='attention_invalid_input';end if;
 elsif k in('customer_id','owner_user_id','after_id')then
 if jsonb_typeof(v)<>'string' or s!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then raise exception using errcode='22023',message='attention_invalid_input';end if;
 elsif k in('kind','after_kind')then
 if jsonb_typeof(v)<>'string' or not s=any(array['renewal','permanence','case','task','meeting','opportunity','portability'])then raise exception using errcode='22023',message='attention_invalid_input';end if;
 else
 if jsonb_typeof(v)<>'string' or s!~'^[0-9]{4}-[0-9]{2}-[0-9]{2}$' or s::date not between date'2000-01-01' and date'2100-12-31' or to_char(s::date,'YYYY-MM-DD')<>s then raise exception using errcode='22023',message='attention_invalid_input';end if;
 end if;end loop;
 if (inp->>'window_to')::date-(inp->>'window_from')::date not between 0 and 366 then raise exception using errcode='22023',message='attention_invalid_input';end if;
 n:=(inp?'after_sort_on')::int+(inp?'after_kind')::int+(inp?'after_id')::int;
 if n not in(0,3)or(n=3 and(not inp?'fallback_on' or (inp->>'after_sort_on')::date not between(inp->>'window_from')::date and(inp->>'window_to')::date or(inp?'kind'and inp->>'kind'<>inp->>'after_kind')))then raise exception using errcode='22023',message='attention_invalid_cursor';end if;
 exception when data_exception then raise exception using errcode='22023',message='attention_invalid_input';
end$$;
create function public.telecom_attention_v1_query(p_workspace_id uuid,p_input jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare actor uuid; customer uuid; owner_id uuid; wanted text; lo date; hi date; today date:=(statement_timestamp()at time zone'Europe/Madrid')::date; fallback date; lim int; a_date date; a_kind text; a_id uuid; rows jsonb; last_row jsonb; cursor jsonb:='null'::jsonb;
begin
 actor:=public.product_v1_assert_scope(p_workspace_id,false);perform public.telecom_attention_v1_validate(p_input);
 customer:=(p_input->>'customer_id')::uuid;owner_id:=(p_input->>'owner_user_id')::uuid;wanted:=p_input->>'kind';lo:=(p_input->>'window_from')::date;hi:=(p_input->>'window_to')::date;lim:=coalesce((p_input->>'limit')::int,50);
 fallback:=coalesce((p_input->>'fallback_on')::date,today);
 if fallback not between today-7 and today then raise exception using errcode='22023',message='attention_stale_cursor';end if;
 a_date:=(p_input->>'after_sort_on')::date;a_kind:=p_input->>'after_kind';a_id:=(p_input->>'after_id')::uuid;
 if customer is not null and not exists(select 1 from public.customers where workspace_id=p_workspace_id and id=customer)then raise exception using errcode='P0002',message='attention_customer_not_found';end if;
 with f0 as(select *from(select 'renewal'::text as kind,x.id,c.customer_id,c.assigned_user_id as owner_user_id,x.target_on as sort_on,x.target_on as due_on,x.status,case when x.target_on<today then 'renewal_overdue' else 'renewal_upcoming'end as reason_code,'normal'::text as priority from public.telecom_renewals x join public.telecom_contracts c on c.id=x.contract_id and c.workspace_id=x.workspace_id where x.workspace_id=p_workspace_id and x.status='open'and x.target_on<=today+30)z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f1 as(select *from(select 'permanence'::text as kind,x.id,c.customer_id,c.assigned_user_id as owner_user_id,x.ends_on as sort_on,x.ends_on as due_on,x.administrative_status as status,'permanence_ending'::text as reason_code,'normal'::text as priority from public.telecom_commitments x join public.telecom_contracts c on c.id=x.contract_id and c.workspace_id=x.workspace_id where x.workspace_id=p_workspace_id and x.administrative_status='open'and x.ends_on between today and today+30)z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f2 as(select *from(select 'case'::text as kind,x.id,x.customer_id,x.assigned_user_id as owner_user_id,coalesce(x.due_on,fallback)as sort_on,x.due_on,x.status,case when x.priority in('high','urgent')then 'case_urgent'else 'case_overdue'end as reason_code,x.priority from public.service_cases x where x.workspace_id=p_workspace_id and x.status in('open','in_progress','waiting_customer','waiting_operator')and(x.priority in('high','urgent')or x.due_on<today))z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f3 as(select *from(select 'task'::text as kind,x.id,x.customer_id,x.assigned_user_id as owner_user_id,(x.due_at at time zone'Europe/Madrid')::date as sort_on,(x.due_at at time zone'Europe/Madrid')::date as due_on,x.status,'task_overdue'::text as reason_code,coalesce(x.priority,'normal')as priority from public.tasks x where x.workspace_id=p_workspace_id and x.status in('pending','in_progress')and x.due_at<statement_timestamp())z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f4 as(select *from(select 'meeting'::text as kind,x.id,x.customer_id,x.assigned_user_id as owner_user_id,(x.starts_at at time zone'Europe/Madrid')::date as sort_on,(x.starts_at at time zone'Europe/Madrid')::date as due_on,x.status,'meeting_upcoming'::text as reason_code,'normal'::text as priority from public.calendar_events x where x.workspace_id=p_workspace_id and x.status='scheduled'and x.starts_at>=statement_timestamp()and(x.starts_at at time zone'Europe/Madrid')::date<=today+30)z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f5 as(select *from(select 'opportunity'::text as kind,x.id,x.customer_id,x.owner_user_id,fallback as sort_on,null::date as due_on,x.status,'opportunity_missing_next_action'::text as reason_code,'normal'::text as priority from public.opportunities x where x.workspace_id=p_workspace_id and x.status='open'and nullif(btrim(x.next_action),'')is null and not exists(select 1 from public.tasks t where t.workspace_id=x.workspace_id and t.opportunity_id=x.id and t.status in('pending','in_progress'))and not exists(select 1 from public.calendar_events e where e.workspace_id=x.workspace_id and e.opportunity_id=x.id and e.status='scheduled'and e.starts_at>=statement_timestamp()))z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),
f6 as(select *from(select 'portability'::text as kind,x.id,x.customer_id,x.owner_user_id,coalesce(x.scheduled_on,x.requested_on)as sort_on,coalesce(x.scheduled_on,x.requested_on)as due_on,x.status,case when x.status='rejected'then 'portability_blocked'else 'portability_pending'end as reason_code,case when x.status='rejected'then 'high'else 'normal'end as priority from public.telecom_portabilities x where x.workspace_id=p_workspace_id and x.status in('draft','requested','scheduled','in_progress','rejected')and not exists(select 1 from public.telecom_portabilities n where n.workspace_id=x.workspace_id and n.line_id=x.line_id and(n.created_at,n.id)>(x.created_at,x.id)))z where(wanted is null or wanted=kind)and(customer is null or customer_id=customer)and(owner_id is null or owner_user_id=owner_id)and sort_on between lo and hi and(a_date is null or(sort_on,kind collate "C",id)>(a_date,a_kind collate "C",a_id))order by sort_on,kind collate "C",id limit lim+1),all_rows as(select *from f0 union all select *from f1 union all select *from f2 union all select *from f3 union all select *from f4 union all select *from f5 union all select *from f6)select coalesce(jsonb_agg(to_jsonb(z)order by sort_on,kind collate "C",id),'[]'::jsonb)into rows from(select *from all_rows order by sort_on,kind collate "C",id limit lim+1)z;
 if jsonb_array_length(rows)>lim then
 rows:=rows-(jsonb_array_length(rows)-1);last_row:=rows->(lim-1);
 cursor:=jsonb_build_object('after_sort_on',last_row->>'sort_on','after_kind',last_row->>'kind','after_id',last_row->>'id','fallback_on',fallback);
 end if;
 return jsonb_build_object('contract_version','telecom.attention.v1','operation','telecom.attention','as_of',today,'fallback_on',fallback,'items',rows,'next_cursor',cursor);
end$$;
revoke all on function public.telecom_attention_v1_validate(jsonb),public.telecom_attention_v1_query(uuid,jsonb) from public,anon,authenticated,service_role;
grant execute on function public.telecom_attention_v1_query(uuid,jsonb) to authenticated;
commit;
