-- Commercial number portability, manual provider truth only. Applied once by migration runner.
-- No carrier integration, hidden provisioning, raw number copy, delete or AI write grant.
begin;
create table public.telecom_portabilities(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),customer_id uuid not null,contract_id uuid not null,service_id uuid not null,line_id uuid not null,number_identifier_id uuid not null,
 direction text not null check(direction in('inbound','outbound')),donor_operator_id uuid not null,target_operator_id uuid not null,
 requested_on date not null,submitted_on date,scheduled_on date,started_on date,completed_on date,closed_on date,
 status text not null default 'draft'check(status in('draft','requested','scheduled','in_progress','completed','rejected','cancelled')),
 reason_code text check(reason_code in('subscriber_mismatch','number_not_found','authorization_missing','ineligible_contract','donor_rejected','technical_failure','customer_withdrew','duplicate_request')),
 owner_user_id uuid references auth.users(id),source text not null default 'manual'check(source in('manual','import','integration')),
 version bigint not null default 1 check(version>0 and version<1000000000000000),created_by_user_id uuid not null references auth.users(id),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),unique(id,workspace_id),
 foreign key(customer_id,workspace_id)references public.customers(id,workspace_id),foreign key(contract_id,workspace_id)references public.telecom_contracts(id,workspace_id),foreign key(service_id,workspace_id)references public.telecom_services(id,workspace_id),foreign key(line_id,workspace_id)references public.telecom_lines(id,workspace_id),foreign key(number_identifier_id,workspace_id)references public.telecom_identifiers(id,workspace_id),foreign key(donor_operator_id,workspace_id)references public.telecom_operators(id,workspace_id),foreign key(target_operator_id,workspace_id)references public.telecom_operators(id,workspace_id),
 check(donor_operator_id<>target_operator_id),check(submitted_on is null or submitted_on>=requested_on),check(scheduled_on is null or scheduled_on>=submitted_on),check(started_on is null or started_on>=scheduled_on),check(completed_on is null or completed_on>=greatest(requested_on,submitted_on,scheduled_on,started_on)),check(closed_on is null or closed_on>=greatest(requested_on,submitted_on,scheduled_on,started_on)),
 check((status='draft'and submitted_on is null and scheduled_on is null and started_on is null and completed_on is null and closed_on is null and reason_code is null)or(status='requested'and submitted_on is not null and scheduled_on is null and started_on is null and completed_on is null and closed_on is null and reason_code is null)or(status='scheduled'and submitted_on is not null and scheduled_on is not null and started_on is null and completed_on is null and closed_on is null and reason_code is null)or(status='in_progress'and submitted_on is not null and scheduled_on is not null and started_on is not null and completed_on is null and closed_on is null and reason_code is null)or(status='completed'and submitted_on is not null and scheduled_on is not null and completed_on is not null and closed_on is null and reason_code is null)or(status in('rejected','cancelled')and closed_on is not null and completed_on is null and reason_code is not null))
);
create unique index telecom_portability_open_line on public.telecom_portabilities(workspace_id,line_id)where status in('draft','requested','scheduled','in_progress');
create index telecom_portability_page on public.telecom_portabilities(workspace_id,id);
create index telecom_portability_customer on public.telecom_portabilities(workspace_id,customer_id,status,requested_on);
alter table public.telecom_portabilities enable row level security;alter table public.telecom_portabilities force row level security;revoke all on public.telecom_portabilities from public,anon,authenticated,service_role;
create trigger telecom_portability_version before insert or update on public.telecom_portabilities for each row execute function public.manage_task_version();
create trigger telecom_portability_no_delete before delete on public.telecom_portabilities for each row execute function public.reject_activity_mutation();
create function public.portability_v1_guard_row()returns trigger language plpgsql set search_path=''as $$declare c uuid;con uuid;s uuid;o uuid;begin
 if tg_op='UPDATE'then
 if(new.id,new.workspace_id,new.customer_id,new.contract_id,new.service_id,new.line_id,new.number_identifier_id,new.direction,new.source,new.created_by_user_id,new.created_at)is distinct from(old.id,old.workspace_id,old.customer_id,old.contract_id,old.service_id,old.line_id,old.number_identifier_id,old.direction,old.source,old.created_by_user_id,old.created_at)or(old.status<>'draft'and(new.donor_operator_id,new.target_operator_id,new.requested_on)is distinct from(old.donor_operator_id,old.target_operator_id,old.requested_on))then raise exception using errcode='55000',message='portability_identity_immutable';end if;
 end if;
 select svc.customer_id,svc.contract_id,svc.id,svc.operator_id into c,con,s,o from public.telecom_lines l join public.telecom_services svc on svc.id=l.service_id and svc.workspace_id=l.workspace_id where l.workspace_id=new.workspace_id and l.id=new.line_id;
 if c is null or(c,con,s)is distinct from(new.customer_id,new.contract_id,new.service_id)or(new.direction='inbound'and new.target_operator_id<>o)or(new.direction='outbound'and new.donor_operator_id<>o)or not exists(select 1 from public.telecom_identifiers where workspace_id=new.workspace_id and id=new.number_identifier_id and line_id=new.line_id and identifier_kind='msisdn')then raise exception using errcode='23514',message='portability_invalid_ancestry';end if;
 new.updated_at:=statement_timestamp();return new;
end$$;
create trigger telecom_portability_ancestry before insert or update on public.telecom_portabilities for each row execute function public.portability_v1_guard_row();
do $$declare expr text;begin select pg_get_expr(conbin,conrelid)into expr from pg_constraint where conrelid='public.product_commands'::regclass and conname='product_commands_operation_check';alter table public.product_commands drop constraint product_commands_operation_check;execute 'alter table public.product_commands add constraint product_commands_operation_check check(('||expr||')or operation in(''portability.create'',''portability.update_draft'',''portability.assign'',''portability.transition'',''portability.complete''))';end$$;
create function public.portability_v1_validate(op text,inp jsonb)returns void language plpgsql set search_path=''as $$declare required text[];optional text[]:=array[]::text[];k text;v jsonb;s text;begin
 case op
when 'portability.create'then required:=array['command_id','line_id','number_identifier_id','direction','donor_operator_id','target_operator_id','requested_on','owner_user_id']::text[];
when 'portability.update_draft'then required:=array['command_id','id','expected_version','donor_operator_id','target_operator_id','requested_on']::text[];
when 'portability.assign'then required:=array['command_id','id','expected_version','owner_user_id']::text[];
when 'portability.transition'then required:=array['command_id','id','expected_version','status','effective_on','reason_code','evidence_source']::text[];
when 'portability.complete'then required:=array['command_id','id','expected_version','completed_on','evidence_source','provider_outcome','line_action','expected_line_version']::text[];
when 'portability.list'then required:=array[]::text[];
when 'portability.get'then required:=array['id']::text[];
else raise exception using errcode='22023',message='portability_invalid_operation';end case;
 if op='portability.list'then optional:=array['limit','after_id','customer_id','contract_id','service_id','line_id','owner_user_id','operator_id','status','source','direction','window_from','window_to'];end if;
 if inp is null or jsonb_typeof(inp)<>'object'or octet_length(inp::text)>4096 or exists(select 1 from jsonb_object_keys(inp)x where not x=any(required||optional))or exists(select 1 from unnest(required)x where not inp?x)then raise exception using errcode='22023',message='portability_invalid_input';end if;
 for k,v in select key,value from jsonb_each(inp)loop
 s:=inp->>k;
 if v='null'::jsonb and ((k='owner_user_id'and op<>'portability.list')or k in('reason_code','expected_line_version'))then continue;end if;
 if k='id'or k like '%_id'then if jsonb_typeof(v)is distinct from 'string'or s!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='portability_invalid_input';end if;
 elsif k in('expected_version','expected_line_version','limit')then if jsonb_typeof(v)is distinct from 'number'or s!~'^[1-9][0-9]{0,14}$'or(k='limit'and s::bigint>100)then raise exception using errcode='22023',message='portability_invalid_input';end if;
 elsif k in('requested_on','effective_on','completed_on','window_from','window_to')then if jsonb_typeof(v)is distinct from 'string'or s!~'^(19|20|21)[0-9]{2}-[0-9]{2}-[0-9]{2}$'or to_char(s::date,'YYYY-MM-DD')<>s then raise exception using errcode='22023',message='portability_invalid_input';end if;
 else
 if jsonb_typeof(v)is distinct from 'string'or(k='direction'and s not in('inbound','outbound'))or(k='source'and s not in('manual','import','integration'))or(k='evidence_source'and s<>'manual')or(k='provider_outcome'and s<>'confirmed_completed')or(k='line_action'and s not in('none','activate','end'))or(k='status'and s not in('draft','requested','scheduled','in_progress','completed','rejected','cancelled'))or(k='reason_code'and s not in('subscriber_mismatch','number_not_found','authorization_missing','ineligible_contract','donor_rejected','technical_failure','customer_withdrew','duplicate_request'))then raise exception using errcode='22023',message='portability_invalid_input';end if;end if;
 end loop;
 if op='portability.transition'and((inp->>'status'not in('requested','scheduled','in_progress','rejected','cancelled'))or((inp->>'status'in('rejected','cancelled'))<>(inp->>'reason_code'is not null))or(inp->>'status'='cancelled'and inp->>'reason_code'not in('customer_withdrew','duplicate_request'))or(inp->>'status'='rejected'and inp->>'reason_code'in('customer_withdrew','duplicate_request')))then raise exception using errcode='22023',message='portability_invalid_input';end if;
 if op='portability.complete'and((inp->>'line_action'='none')<>(inp->>'expected_line_version'is null))then raise exception using errcode='22023',message='portability_invalid_input';end if;
 if op='portability.list'and((inp?'window_from')<>(inp?'window_to')or inp?'window_from'and((inp->>'window_to')::date<(inp->>'window_from')::date or(inp->>'window_to')::date-(inp->>'window_from')::date>366))then raise exception using errcode='22023',message='portability_invalid_input';end if;
end$$;
create function public.portability_v1_command(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare a uuid;prior jsonb;d public.telecom_portabilities%rowtype;l public.telecom_lines%rowtype;s public.telecom_services%rowtype;c public.telecom_contracts%rowtype;n public.telecom_identifiers%rowtype;target uuid;at date;child uuid;effect jsonb:=null;child_receipt jsonb;begin
 a:=public.product_v1_assert_scope(p_workspace_id,true);perform public.portability_v1_validate(p_operation,p_input);if p_operation in('portability.list','portability.get')then raise exception using errcode='22023',message='portability_invalid_operation';end if;
 prior:=public.product_v1_begin_command(p_workspace_id,a,p_operation,p_input);if prior is not null then return prior;end if;
 if p_operation='portability.create'then target:=(p_input->>'line_id')::uuid;
 else select *into d from public.telecom_portabilities where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid;if not found then raise exception using errcode='P0002',message='portability_not_found';end if;target:=d.line_id;end if;
 -- Same ancestor-first lock order as normal portfolio writes; an explicit line action stays atomic.
 select con.*into c from public.telecom_contracts con join public.telecom_services svc on svc.contract_id=con.id and svc.workspace_id=con.workspace_id join public.telecom_lines lin on lin.service_id=svc.id and lin.workspace_id=svc.workspace_id where lin.workspace_id=p_workspace_id and lin.id=target for update of con;
 if not found then raise exception using errcode='P0002',message='portability_not_found';end if;
 select svc.*into s from public.telecom_services svc join public.telecom_lines lin on lin.service_id=svc.id and lin.workspace_id=svc.workspace_id where lin.workspace_id=p_workspace_id and lin.id=target for update of svc;
 select *into l from public.telecom_lines where workspace_id=p_workspace_id and id=target for update;
 if p_operation<>'portability.create'then select *into d from public.telecom_portabilities where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid for update;
 if d.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='portability_conflict';end if;
 if d.status in('completed','rejected','cancelled')then raise exception using errcode='22023',message='portability_invalid_transition';end if;
 if p_operation<>'portability.assign'and d.source<>'manual'then raise exception using errcode='42501',message='portability_external_read_only';end if;end if;
 if p_operation<>'portability.assign'and(c.source<>'manual'or s.source<>'manual'or l.source<>'manual')then raise exception using errcode='42501',message='portability_external_read_only';end if;
 if p_operation in('portability.create','portability.assign')and p_input->>'owner_user_id'is not null then perform 1 from public.workspace_members wm join public.workspaces w on w.id=wm.workspace_id where wm.workspace_id=p_workspace_id and wm.user_id=(p_input->>'owner_user_id')::uuid and wm.status='active'and wm.role in('owner','admin','member')and w.status='active'for share of wm,w;if not found then raise exception using errcode='42501',message='portability_invalid_owner';end if;end if;
 if p_operation='portability.create'then
 perform 1 from public.customers where workspace_id=p_workspace_id and id=c.customer_id and status='active'for share;if not found or c.status not in('draft','active')or s.status not in('pending','active','suspended')or l.status not in('pending','active','suspended')then raise exception using errcode='22023',message='portability_parent_inactive';end if;
 select *into n from public.telecom_identifiers where workspace_id=p_workspace_id and id=(p_input->>'number_identifier_id')::uuid and line_id=l.id and identifier_kind='msisdn'and status='active'for share;if not found then raise exception using errcode='P0002',message='portability_number_not_found';end if;
 insert into public.telecom_portabilities(workspace_id,customer_id,contract_id,service_id,line_id,number_identifier_id,direction,donor_operator_id,target_operator_id,requested_on,owner_user_id,created_by_user_id)values(p_workspace_id,c.customer_id,c.id,s.id,l.id,n.id,p_input->>'direction',(p_input->>'donor_operator_id')::uuid,(p_input->>'target_operator_id')::uuid,(p_input->>'requested_on')::date,(p_input->>'owner_user_id')::uuid,a)returning *into d;
 elsif p_operation='portability.update_draft'then
 if d.status<>'draft'then raise exception using errcode='22023',message='portability_invalid_transition';end if;
 update public.telecom_portabilities set donor_operator_id=(p_input->>'donor_operator_id')::uuid,target_operator_id=(p_input->>'target_operator_id')::uuid,requested_on=(p_input->>'requested_on')::date where id=d.id returning *into d;
 elsif p_operation='portability.assign'then
 update public.telecom_portabilities set owner_user_id=(p_input->>'owner_user_id')::uuid where id=d.id returning *into d;
 elsif p_operation='portability.transition'then
 if not((d.status='draft'and p_input->>'status'in('requested','cancelled'))or(d.status='requested'and p_input->>'status'in('scheduled','rejected','cancelled'))or(d.status='scheduled'and p_input->>'status'in('in_progress','rejected','cancelled'))or(d.status='in_progress'and p_input->>'status'in('rejected','cancelled')))then raise exception using errcode='22023',message='portability_invalid_transition';end if;
 at:=(p_input->>'effective_on')::date;if at<greatest(d.requested_on,d.submitted_on,d.scheduled_on,d.started_on)then raise exception using errcode='22023',message='portability_invalid_date';end if;
 if p_input->>'status'in('requested','scheduled','in_progress')then perform 1 from public.telecom_identifiers where workspace_id=p_workspace_id and id=d.number_identifier_id and status='active'for share;if not found then raise exception using errcode='22023',message='portability_number_retired';end if;end if;
 update public.telecom_portabilities set status=p_input->>'status',submitted_on=case when p_input->>'status'='requested'then at else submitted_on end,scheduled_on=case when p_input->>'status'='scheduled'then at else scheduled_on end,started_on=case when p_input->>'status'='in_progress'then at else started_on end,closed_on=case when p_input->>'status'in('rejected','cancelled')then at else null end,reason_code=p_input->>'reason_code'where id=d.id returning *into d;
 else
 if d.status not in('scheduled','in_progress')or(p_input->>'completed_on')::date<greatest(d.requested_on,d.submitted_on,d.scheduled_on,d.started_on)then raise exception using errcode='22023',message='portability_invalid_transition';end if;
 perform 1 from public.telecom_identifiers where workspace_id=p_workspace_id and id=d.number_identifier_id and status='active'for share;if not found then raise exception using errcode='22023',message='portability_number_retired';end if;
 if p_input->>'line_action'<>'none'then
 if(d.direction='inbound'and p_input->>'line_action'<>'activate')or(d.direction='outbound'and p_input->>'line_action'<>'end')then raise exception using errcode='22023',message='portability_invalid_line_action';end if;
 child:=md5(p_workspace_id::text||':'||a::text||':'||(p_input->>'command_id')||':portability-line')::uuid;
 child_receipt:=public.portfolio_v1_line_transition(p_workspace_id,jsonb_build_object('command_id',child,'id',l.id,'expected_version',p_input->'expected_line_version','status',case p_input->>'line_action'when 'activate'then 'active'else 'ended'end,'effective_on',p_input->>'completed_on'));
 effect:=jsonb_build_object('line_id',l.id,'version',child_receipt->'version','status',child_receipt->>'status');end if;
 update public.telecom_portabilities set status='completed',completed_on=(p_input->>'completed_on')::date where id=d.id returning *into d;
 end if;
 if p_operation in('portability.create','portability.update_draft')then perform 1 from public.telecom_operators where workspace_id=p_workspace_id and id=d.donor_operator_id and status='active'for share;if not found then raise exception using errcode='22023',message='portability_operator_inactive';end if;perform 1 from public.telecom_operators where workspace_id=p_workspace_id and id=d.target_operator_id and status='active'for share;if not found then raise exception using errcode='22023',message='portability_operator_inactive';end if;end if;
 prior:=jsonb_build_object('contract_version','portability.v1','operation',p_operation,'command_id',p_input->>'command_id','id',d.id,'version',d.version,'status',d.status,'source',d.source,'line_effect',effect);
 insert into public.product_audit_events(workspace_id,actor_id,command_id,operation,entity_id,entity_version)values(p_workspace_id,a,(p_input->>'command_id')::uuid,p_operation,d.id,d.version);
 update public.product_commands set receipt=prior where workspace_id=p_workspace_id and actor_id=a and command_id=(p_input->>'command_id')::uuid;return prior;
 exception when unique_violation then raise exception using errcode='40001',message='portability_conflict';when integrity_constraint_violation or data_exception then raise exception using errcode='22023',message='portability_invalid_input';
end$$;
create function public.portability_v1_query(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare rows jsonb;lim int;has_more boolean;next_id uuid;begin
 perform public.product_v1_assert_scope(p_workspace_id,false);perform public.portability_v1_validate(p_operation,p_input);if p_operation not in('portability.list','portability.get')then raise exception using errcode='22023',message='portability_invalid_operation';end if;
 lim:=case when p_operation='portability.get'then 1 else coalesce((p_input->>'limit')::int,50)end;
 select coalesce(jsonb_agg(to_jsonb(x)order by id),'[]'::jsonb)into rows from(select p.id,p.version,p.customer_id,p.contract_id,p.service_id,p.line_id,p.number_identifier_id,n.masked_display,p.direction,p.donor_operator_id,p.target_operator_id,p.requested_on,p.submitted_on,p.scheduled_on,p.started_on,p.completed_on,p.closed_on,p.status,p.reason_code,p.owner_user_id,p.source,p.created_at,p.updated_at from public.telecom_portabilities p join public.telecom_identifiers n on n.id=p.number_identifier_id and n.workspace_id=p.workspace_id where p.workspace_id=p_workspace_id and(p_operation<>'portability.get'or p.id=(p_input->>'id')::uuid)and(not p_input?'after_id'or p.id>(p_input->>'after_id')::uuid)and(not p_input?'customer_id'or p.customer_id=(p_input->>'customer_id')::uuid)and(not p_input?'contract_id'or p.contract_id=(p_input->>'contract_id')::uuid)and(not p_input?'service_id'or p.service_id=(p_input->>'service_id')::uuid)and(not p_input?'line_id'or p.line_id=(p_input->>'line_id')::uuid)and(not p_input?'owner_user_id'or p.owner_user_id=(p_input->>'owner_user_id')::uuid)and(not p_input?'operator_id'or p.donor_operator_id=(p_input->>'operator_id')::uuid or p.target_operator_id=(p_input->>'operator_id')::uuid)and(not p_input?'status'or p.status=p_input->>'status')and(not p_input?'source'or p.source=p_input->>'source')and(not p_input?'direction'or p.direction=p_input->>'direction')and(not p_input?'window_from'or p.requested_on between(p_input->>'window_from')::date and(p_input->>'window_to')::date)order by p.id limit lim+1)x;
 if p_operation='portability.get'then if jsonb_array_length(rows)=0 then return null;end if;return jsonb_build_object('contract_version','portability.v1','operation',p_operation,'record',rows->0);end if;
 has_more:=jsonb_array_length(rows)>lim;if has_more then rows:=rows-lim;next_id:=(rows->(lim-1)->>'id')::uuid;end if;
 return jsonb_build_object('contract_version','portability.v1','operation',p_operation,'items',rows,'next_id',next_id);
end$$;
revoke all on function public.portability_v1_guard_row(),public.portability_v1_validate(text,jsonb),public.portability_v1_command(uuid,text,jsonb),public.portability_v1_query(uuid,text,jsonb)from public,anon,authenticated,service_role;
grant execute on function public.portability_v1_command(uuid,text,jsonb),public.portability_v1_query(uuid,text,jsonb)to authenticated;
commit;
