-- Safe orchestration management only. Ciphertext/quarantine/apply adapters remain unavailable.
begin;
alter table public.import_jobs add column version bigint not null default 1 check(version>0 and version<1000000000000000);
create trigger import_jobs_product_version before update on public.import_jobs for each row execute function public.manage_task_version();
do $$declare expr text;begin select pg_get_expr(conbin,conrelid)into expr from pg_constraint where conrelid='public.product_commands'::regclass and conname='product_commands_operation_check';alter table public.product_commands drop constraint product_commands_operation_check;execute 'alter table public.product_commands add constraint product_commands_operation_check check(('||expr||')or operation=''importjob.cancel'')';end$$;
create function public.importjob_v1_metadata(j public.import_jobs)returns jsonb language sql immutable set search_path=''as $$select jsonb_build_object('id',j.id,'version',j.version,'kind',j.import_kind,'status',j.status,'total_rows',j.total_rows,'valid_rows',j.valid_rows,'invalid_rows',j.invalid_rows,'applied_rows',j.applied_rows,'failed_rows',j.failed_rows,'checkpoint',j.checkpoint_rows_processed,'failure_code',j.failure_code,'can_cancel',j.status in('uploaded','mapping','validating','ready'),'processing_status','blocked_encrypted_staging_adapter')$$;
revoke all on function public.importjob_v1_metadata(public.import_jobs)from public,anon,authenticated,service_role;
create function public.importjob_v1_get(p_workspace_id uuid,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare j public.import_jobs%rowtype;begin
 perform public.billing_v1_assert_scope(p_workspace_id);
 if p_input is null or jsonb_typeof(p_input)<>'object'or octet_length(p_input::text)>4096 or(select array_agg(key)from jsonb_object_keys(p_input)key)is distinct from array['id']::text[]or jsonb_typeof(p_input->'id')is distinct from 'string'or p_input->>'id'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='importjob_invalid_input';end if;
 select *into j from public.import_jobs where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid;if not found then return null;end if;
 return jsonb_build_object('contract_version','importjob.v1','operation','importjob.get','record',public.importjob_v1_metadata(j));end$$;
create function public.importjob_v1_list(p_workspace_id uuid,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare lim int:=20;after_id uuid;items jsonb;last_id uuid;begin
 perform public.billing_v1_assert_scope(p_workspace_id);
 if p_input is null or jsonb_typeof(p_input)<>'object'or octet_length(p_input::text)>4096 or exists(select 1 from jsonb_object_keys(p_input)k where k not in('limit','after_id','status'))then raise exception using errcode='22023',message='importjob_invalid_input';end if;
 if p_input?'limit'then if jsonb_typeof(p_input->'limit')is distinct from 'number'or p_input->>'limit'!~'^[1-9][0-9]{0,2}$'or(p_input->>'limit')::int>100 then raise exception using errcode='22023',message='importjob_invalid_input';end if;lim:=(p_input->>'limit')::int;end if;
 if p_input?'after_id'then if jsonb_typeof(p_input->'after_id')is distinct from 'string'or p_input->>'after_id'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='importjob_invalid_input';end if;after_id:=(p_input->>'after_id')::uuid;end if;
 if p_input?'status'and(jsonb_typeof(p_input->'status')is distinct from 'string'or p_input->>'status'not in('uploaded','mapping','validating','ready','applying','completed','failed','cancelled'))then raise exception using errcode='22023',message='importjob_invalid_input';end if;
 select coalesce(jsonb_agg(public.importjob_v1_metadata(q)order by q.id),'[]'::jsonb)into items from(select j.*from public.import_jobs j where j.workspace_id=p_workspace_id and(after_id is null or j.id>after_id)and(not p_input?'status'or j.status=p_input->>'status')order by j.id limit lim)q;
 if jsonb_array_length(items)=lim then last_id:=(items->(lim-1)->>'id')::uuid;end if;
 return jsonb_build_object('contract_version','importjob.v1','operation','importjob.list','items',items,'next_id',last_id);end$$;
create function public.importjob_v1_cancel(p_workspace_id uuid,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare actor uuid;prior jsonb;j public.import_jobs%rowtype;begin
 actor:=public.billing_v1_assert_scope(p_workspace_id);
 if p_input is null or jsonb_typeof(p_input)<>'object'or octet_length(p_input::text)>4096 or(select array_agg(key order by key)from jsonb_object_keys(p_input)key)is distinct from array['command_id','expected_version','id']::text[]or jsonb_typeof(p_input->'id')is distinct from 'string'or p_input->>'id'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'or jsonb_typeof(p_input->'command_id')is distinct from 'string'or p_input->>'command_id'!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'or jsonb_typeof(p_input->'expected_version')is distinct from 'number'or p_input->>'expected_version'!~'^[1-9][0-9]{0,14}$'then raise exception using errcode='22023',message='importjob_invalid_input';end if;
 prior:=public.product_v1_begin_command(p_workspace_id,actor,'importjob.cancel',p_input);if prior is not null then return prior;end if;
 select *into j from public.import_jobs where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid for update;if not found then raise exception using errcode='P0002',message='importjob_not_found';end if;
 if j.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='importjob_conflict';end if;
 if j.status not in('uploaded','mapping','validating','ready')then raise exception using errcode='22023',message='importjob_cannot_cancel';end if;
 update public.import_jobs set status='cancelled',cancelled_at=statement_timestamp() where id=j.id returning *into j;
 insert into public.product_audit_events(workspace_id,actor_id,command_id,operation,entity_id,entity_version)values(p_workspace_id,actor,(p_input->>'command_id')::uuid,'importjob.cancel',j.id,j.version);
 insert into public.business_audit_events(workspace_id,actor_kind,actor_user_id,action_code,target_kind,target_id,outcome,request_ref_id,occurred_at)values(p_workspace_id,'user',actor,'import.cancelled.v1','import_job',j.id,'succeeded',(p_input->>'command_id')::uuid,statement_timestamp());
 prior:=jsonb_build_object('contract_version','importjob.v1','operation','importjob.cancel','command_id',p_input->>'command_id','id',j.id,'version',j.version,'status',j.status);
 update public.product_commands set receipt=prior where workspace_id=p_workspace_id and actor_id=actor and command_id=(p_input->>'command_id')::uuid;return prior;end$$;
revoke all on function public.importjob_v1_get(uuid,jsonb),public.importjob_v1_list(uuid,jsonb),public.importjob_v1_cancel(uuid,jsonb)from public,anon,authenticated,service_role;
grant execute on function public.importjob_v1_get(uuid,jsonb),public.importjob_v1_list(uuid,jsonb),public.importjob_v1_cancel(uuid,jsonb)to authenticated;
commit;
