-- Customer-bound SIM/eSIM commercial resources, protected identity and historical association.
-- Apply once; no stock ERP, PIN/PUK, credentials, carrier API or AI grant.
begin;
create table public.telecom_sims(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),customer_id uuid not null,operator_id uuid not null,kind text not null check(kind in('physical','esim')),display_label text not null check(char_length(btrim(display_label))between 1 and 200),status text not null default 'prepared'check(status in('prepared','assigned','active','replaced','inactive','cancelled')),source text not null default 'manual'check(source in('manual','import','integration')),version bigint not null default 1 check(version>0 and version<1000000000000000),activated_at timestamptz,replaced_at timestamptz,deactivated_at timestamptz,cancelled_at timestamptz,created_by_user_id uuid not null references auth.users(id),created_at timestamptz not null default statement_timestamp(),updated_at timestamptz not null default statement_timestamp(),unique(id,workspace_id),foreign key(customer_id,workspace_id)references public.customers(id,workspace_id),foreign key(operator_id,workspace_id)references public.telecom_operators(id,workspace_id),check(activated_at is null or activated_at>=created_at),check(replaced_at is null or replaced_at>=greatest(created_at,activated_at)),check(deactivated_at is null or deactivated_at>=greatest(created_at,activated_at)),check(cancelled_at is null or cancelled_at>=created_at),check((status in('prepared','assigned')and activated_at is null and replaced_at is null and deactivated_at is null and cancelled_at is null)or(status='active'and activated_at is not null and replaced_at is null and deactivated_at is null and cancelled_at is null)or(status='replaced'and replaced_at is not null and deactivated_at is null and cancelled_at is null)or(status='inactive'and deactivated_at is not null and replaced_at is null and cancelled_at is null)or(status='cancelled'and cancelled_at is not null and activated_at is null and replaced_at is null and deactivated_at is null))
);
create trigger telecom_sim_version before insert or update on public.telecom_sims for each row execute function public.manage_task_version();
create trigger telecom_sim_no_delete before delete on public.telecom_sims for each row execute function public.reject_activity_mutation();
alter table public.telecom_sims enable row level security;alter table public.telecom_sims force row level security;revoke all on public.telecom_sims from public,anon,authenticated,service_role;
create index telecom_sim_page on public.telecom_sims(workspace_id,id);
alter table public.telecom_identifiers add column sim_id uuid,add foreign key(sim_id,workspace_id)references public.telecom_sims(id,workspace_id);
-- Replace only closed kind/pair/value checks, preserving all historical rows/status checks.
do $$declare r record;begin for r in select conname from pg_constraint where conrelid='public.telecom_identifiers'::regclass and contype='c'and(pg_get_expr(conbin,conrelid)like '%entity_kind%'or pg_get_expr(conbin,conrelid)like '%identifier_kind%')loop execute format('alter table public.telecom_identifiers drop constraint %I',r.conname);end loop;end$$;
alter table public.telecom_identifiers add constraint telecom_identifier_entity_kinds check(entity_kind in('line','service','contract','sim')),add constraint telecom_identifier_registered_kinds check(identifier_kind in('msisdn','circuit_reference','provider_account_reference','provider_contract_reference','iccid','eid')),add constraint telecom_identifier_entity_pairs check((entity_kind='line'and line_id is not null and service_id is null and contract_id is null and sim_id is null and identifier_kind='msisdn')or(entity_kind='service'and service_id is not null and line_id is null and contract_id is null and sim_id is null and identifier_kind='circuit_reference')or(entity_kind='contract'and contract_id is not null and service_id is null and line_id is null and sim_id is null and identifier_kind in('provider_account_reference','provider_contract_reference'))or(entity_kind='sim'and sim_id is not null and line_id is null and service_id is null and contract_id is null and identifier_kind in('iccid','eid'))),add constraint telecom_identifier_canonical_values check((identifier_kind='msisdn'and canonical_value~'^\+[1-9][0-9]{7,14}$')or(identifier_kind='iccid'and canonical_value~'^89[0-9]{16,20}$')or(identifier_kind='eid'and canonical_value~'^[0-9]{32}$')or(identifier_kind in('circuit_reference','provider_account_reference','provider_contract_reference')and canonical_value~'^[A-Za-z0-9][A-Za-z0-9._/-]{7,95}$'));
drop index public.telecom_identifier_entity_active;create unique index telecom_identifier_entity_active on public.telecom_identifiers(workspace_id,entity_kind,coalesce(line_id,service_id,contract_id,sim_id),identifier_kind)where status='active';
drop index public.telecom_identifier_page;create index telecom_identifier_page on public.telecom_identifiers(workspace_id,entity_kind,coalesce(line_id,service_id,contract_id,sim_id),id);
create unique index telecom_identifier_iccid_lifetime on public.telecom_identifiers(workspace_id,canonical_value)where identifier_kind='iccid';
-- EID identifies an eUICC which can hold multiple eSIM profiles; do not impose incorrect uniqueness.

create or replace function public.identifier_v1_guard_row()returns trigger language plpgsql set search_path=''as $$declare c uuid;o uuid;begin
 if tg_op='UPDATE'then
 if (new.id,new.workspace_id,new.entity_kind,new.line_id,new.service_id,new.contract_id,new.sim_id,new.customer_id,new.operator_id,new.identifier_kind,new.canonical_value,new.source,new.valid_from,new.created_by_user_id,new.created_at)is distinct from(old.id,old.workspace_id,old.entity_kind,old.line_id,old.service_id,old.contract_id,old.sim_id,old.customer_id,old.operator_id,old.identifier_kind,old.canonical_value,old.source,old.valid_from,old.created_by_user_id,old.created_at)or old.status<>'active'or new.status<>'retired'or new.version<>old.version+1 then raise exception using errcode='55000',message='identifier_immutable_identity';end if;
 if old.sim_id is not null and not exists(select 1 from public.telecom_sims where workspace_id=old.workspace_id and id=old.sim_id and status='prepared')then raise exception using errcode='55000',message='identifier_sim_identity_frozen';end if;
 return new;end if;
 if new.entity_kind='line'then select s.customer_id,s.operator_id into c,o from public.telecom_lines l join public.telecom_services s on s.id=l.service_id and s.workspace_id=l.workspace_id where l.workspace_id=new.workspace_id and l.id=new.line_id;
 elsif new.entity_kind='service'then select customer_id,operator_id into c,o from public.telecom_services where workspace_id=new.workspace_id and id=new.service_id;
 elsif new.entity_kind='sim'then select customer_id,operator_id into c,o from public.telecom_sims where workspace_id=new.workspace_id and id=new.sim_id and(new.identifier_kind<>'eid'or kind='esim');
 else select customer_id,operator_id into c,o from public.telecom_contracts where workspace_id=new.workspace_id and id=new.contract_id;end if;
 if c is null or c<>new.customer_id or o<>new.operator_id then raise exception using errcode='23514',message='identifier_invalid_ancestry';end if;return new;end$$;
create or replace function public.identifier_v1_validate(op text,inp jsonb)returns void language plpgsql set search_path=''as $$declare required text[];optional text[];k text;v jsonb;s text;begin
 required:=case op when 'identifier.create_manual'then array['command_id','entity_kind','entity_id','identifier_kind','canonical_value']when 'identifier.retire'then array['command_id','id','expected_version']when 'identifier.list'then array['entity_kind','entity_id']when 'identifier.get'then array['id']else null end;
 optional:=case op when 'identifier.list'then array['limit','after_id','status']else array[]::text[]end;
 if required is null or inp is null or jsonb_typeof(inp)<>'object'or octet_length(inp::text)>4096 or exists(select 1 from jsonb_object_keys(inp)x where not x=any(required||optional))or exists(select 1 from unnest(required)x where not inp?x)then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 for k,v in select key,value from jsonb_each(inp)loop
 s:=inp->>k;
 if k in('command_id','id','entity_id','after_id')then
  if jsonb_typeof(v)is distinct from 'string'or s!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 elsif k in('expected_version','limit')then
  if jsonb_typeof(v)is distinct from 'number'or s!~'^[1-9][0-9]{0,14}$'or(k='limit'and s::bigint>100)then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 elsif k='entity_kind'then
  if jsonb_typeof(v)is distinct from 'string'or s not in('line','service','contract','sim')then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 elsif k='identifier_kind'then
  if jsonb_typeof(v)is distinct from 'string'or s not in('msisdn','circuit_reference','provider_account_reference','provider_contract_reference','iccid','eid')then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 elsif k='status'then
  if jsonb_typeof(v)is distinct from 'string'or s not in('active','retired')then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 elsif k='canonical_value'then
  if jsonb_typeof(v)is distinct from 'string'or char_length(s)not between 8 and 96 or s~'[[:cntrl:]]'then raise exception using errcode='22023',message='identifier_invalid_input';end if;
 end if;
 end loop;
 if op='identifier.create_manual'and not((inp->>'entity_kind'='sim'and((inp->>'identifier_kind'='iccid'and inp->>'canonical_value'~'^89[0-9]{16,20}$')or(inp->>'identifier_kind'='eid'and inp->>'canonical_value'~'^[0-9]{32}$')))or(inp->>'entity_kind'='line'and inp->>'identifier_kind'='msisdn'and inp->>'canonical_value'~'^\+[1-9][0-9]{7,14}$')or(inp->>'entity_kind'='service'and inp->>'identifier_kind'='circuit_reference'and inp->>'canonical_value'~'^[A-Za-z0-9][A-Za-z0-9._/-]{7,95}$')or(inp->>'entity_kind'='contract'and inp->>'identifier_kind'in('provider_account_reference','provider_contract_reference')and inp->>'canonical_value'~'^[A-Za-z0-9][A-Za-z0-9._/-]{7,95}$'))then raise exception using errcode='22023',message='identifier_invalid_input';end if;
end$$;
create or replace function public.identifier_v1_command(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare a uuid;prior jsonb;d public.telecom_identifiers%rowtype;customer uuid;operator uuid;src text;begin
 a:=public.product_v1_assert_scope(p_workspace_id,true);perform public.identifier_v1_validate(p_operation,p_input);
 if p_operation not in('identifier.create_manual','identifier.retire')then raise exception using errcode='22023',message='identifier_invalid_operation';end if;
 prior:=public.product_v1_begin_command(p_workspace_id,a,p_operation,p_input);if prior is not null then return prior;end if;
 if p_operation='identifier.create_manual'then
 if p_input->>'entity_kind'='line'then select s.customer_id,s.operator_id,l.source into customer,operator,src from public.telecom_lines l join public.telecom_services s on s.id=l.service_id and s.workspace_id=l.workspace_id join public.telecom_contracts c on c.id=s.contract_id and c.workspace_id=s.workspace_id join public.customers x on x.id=s.customer_id and x.workspace_id=s.workspace_id where l.workspace_id=p_workspace_id and l.id=(p_input->>'entity_id')::uuid and x.status='active'and l.status not in('ended','cancelled')and s.status not in('ended','cancelled')and c.status not in('ended','cancelled')for share of l,s,c,x;
 elsif p_input->>'entity_kind'='service'then select s.customer_id,s.operator_id,s.source into customer,operator,src from public.telecom_services s join public.telecom_contracts c on c.id=s.contract_id and c.workspace_id=s.workspace_id join public.customers x on x.id=s.customer_id and x.workspace_id=s.workspace_id where s.workspace_id=p_workspace_id and s.id=(p_input->>'entity_id')::uuid and x.status='active'and s.status not in('ended','cancelled')and c.status not in('ended','cancelled')for share of s,c,x;
 elsif p_input->>'entity_kind'='sim'then select sim.customer_id,sim.operator_id,sim.source into customer,operator,src from public.telecom_sims sim join public.customers x on x.id=sim.customer_id and x.workspace_id=sim.workspace_id where sim.workspace_id=p_workspace_id and sim.id=(p_input->>'entity_id')::uuid and sim.status='prepared'and x.status='active'and(p_input->>'identifier_kind'<>'eid'or sim.kind='esim')for update of sim;
 else select c.customer_id,c.operator_id,c.source into customer,operator,src from public.telecom_contracts c join public.customers x on x.id=c.customer_id and x.workspace_id=c.workspace_id where c.workspace_id=p_workspace_id and c.id=(p_input->>'entity_id')::uuid and x.status='active'and c.status not in('ended','cancelled')for share of c,x;end if;
 if customer is null then raise exception using errcode='P0002',message='identifier_not_found';end if;
 if src<>'manual'then raise exception using errcode='42501',message='identifier_external_read_only';end if;
 insert into public.telecom_identifiers(workspace_id,entity_kind,line_id,service_id,contract_id,sim_id,customer_id,operator_id,identifier_kind,canonical_value,created_by_user_id)values(p_workspace_id,p_input->>'entity_kind',case when p_input->>'entity_kind'='line'then(p_input->>'entity_id')::uuid end,case when p_input->>'entity_kind'='service'then(p_input->>'entity_id')::uuid end,case when p_input->>'entity_kind'='contract'then(p_input->>'entity_id')::uuid end,case when p_input->>'entity_kind'='sim'then(p_input->>'entity_id')::uuid end,customer,operator,p_input->>'identifier_kind',p_input->>'canonical_value',a)returning *into d;
 else
 select *into d from public.telecom_identifiers where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid;
 if d.sim_id is not null then perform 1 from public.telecom_sims where workspace_id=p_workspace_id and id=d.sim_id and status='prepared'and source='manual'for update;if not found then raise exception using errcode='42501',message='identifier_sim_identity_frozen';end if;end if;
 select *into d from public.telecom_identifiers where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid for update;
 if not found then raise exception using errcode='P0002',message='identifier_not_found';end if;
 if d.source<>'manual'then raise exception using errcode='42501',message='identifier_external_read_only';end if;
 if d.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='identifier_conflict';end if;
 if d.status<>'active'then raise exception using errcode='22023',message='identifier_invalid_transition';end if;
 update public.telecom_identifiers set status='retired',valid_until=statement_timestamp(),version=version+1 where id=d.id returning *into d;
 end if;
 prior:=jsonb_build_object('contract_version','identifiers.v1','operation',p_operation,'command_id',p_input->>'command_id','id',d.id,'version',d.version,'status',d.status);
 insert into public.product_audit_events(workspace_id,actor_id,command_id,operation,entity_id,entity_version)values(p_workspace_id,a,(p_input->>'command_id')::uuid,p_operation,d.id,d.version);
 update public.product_commands set receipt=prior where workspace_id=p_workspace_id and actor_id=a and command_id=(p_input->>'command_id')::uuid;return prior;
exception when unique_violation then raise exception using errcode='40001',message='identifier_conflict';when integrity_constraint_violation then raise exception using errcode='22023',message='identifier_invalid_input';
end$$;
create or replace function public.identifier_v1_query(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare rows jsonb;lim int;next_id uuid;begin
 perform public.product_v1_assert_scope(p_workspace_id,false);perform public.identifier_v1_validate(p_operation,p_input);
 if p_operation not in('identifier.list','identifier.get')then raise exception using errcode='22023',message='identifier_invalid_operation';end if;
 lim:=case when p_operation='identifier.get'then 1 else coalesce((p_input->>'limit')::int,50)end;
 select coalesce(jsonb_agg(to_jsonb(x)order by id),'[]'::jsonb)into rows from(select id,entity_kind,coalesce(line_id,service_id,contract_id,sim_id)as entity_id,identifier_kind,masked_display,status,source,valid_from,valid_until,version from public.telecom_identifiers where workspace_id=p_workspace_id and(p_operation<>'identifier.get'or id=(p_input->>'id')::uuid)and(p_operation<>'identifier.list'or entity_kind=p_input->>'entity_kind'and coalesce(line_id,service_id,contract_id,sim_id)=(p_input->>'entity_id')::uuid and(not p_input?'after_id'or id>(p_input->>'after_id')::uuid)and(not p_input?'status'or status=p_input->>'status'))order by id limit lim)x;
 if p_operation='identifier.get'then if jsonb_array_length(rows)=0 then return null;end if;return jsonb_build_object('contract_version','identifiers.v1','operation',p_operation,'record',rows->0);end if;
 next_id:=case when jsonb_array_length(rows)=lim then(rows->(lim-1)->>'id')::uuid end;
 return jsonb_build_object('contract_version','identifiers.v1','operation',p_operation,'items',rows,'next_id',next_id);
end$$;

create table public.telecom_sim_associations(
 id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id),sim_id uuid not null,line_id uuid not null,iccid_identifier_id uuid not null,eid_identifier_id uuid,assigned_at timestamptz not null default statement_timestamp(),activated_at timestamptz,ended_at timestamptz,end_reason text check(end_reason in('replaced','deactivated')),replacement_sim_id uuid,created_by_user_id uuid not null references auth.users(id),unique(id,workspace_id),foreign key(sim_id,workspace_id)references public.telecom_sims(id,workspace_id),foreign key(line_id,workspace_id)references public.telecom_lines(id,workspace_id),foreign key(iccid_identifier_id,workspace_id)references public.telecom_identifiers(id,workspace_id),foreign key(eid_identifier_id,workspace_id)references public.telecom_identifiers(id,workspace_id),foreign key(replacement_sim_id,workspace_id)references public.telecom_sims(id,workspace_id),check(activated_at is null or activated_at>=assigned_at),check(ended_at is null or ended_at>=greatest(assigned_at,activated_at)),check((ended_at is null and end_reason is null and replacement_sim_id is null)or(ended_at is not null and end_reason='replaced'and replacement_sim_id is not null and replacement_sim_id<>sim_id)or(ended_at is not null and end_reason='deactivated'and replacement_sim_id is null))
);
create unique index telecom_sim_open_line on public.telecom_sim_associations(workspace_id,line_id)where ended_at is null;
create unique index telecom_sim_open_resource on public.telecom_sim_associations(workspace_id,sim_id)where ended_at is null;
create index telecom_sim_history_page on public.telecom_sim_associations(workspace_id,sim_id,id);
alter table public.telecom_sim_associations enable row level security;alter table public.telecom_sim_associations force row level security;revoke all on public.telecom_sim_associations from public,anon,authenticated,service_role;
create trigger telecom_sim_association_no_delete before delete on public.telecom_sim_associations for each row execute function public.reject_activity_mutation();
create function public.sim_v1_guard_resource()returns trigger language plpgsql set search_path=''as $$begin
 if tg_op='UPDATE'then if(new.id,new.workspace_id,new.customer_id,new.operator_id,new.kind,new.display_label,new.source,new.created_by_user_id,new.created_at)is distinct from(old.id,old.workspace_id,old.customer_id,old.operator_id,old.kind,old.display_label,old.source,old.created_by_user_id,old.created_at)or not((old.status='prepared'and new.status in('assigned','active','cancelled'))or(old.status='assigned'and new.status in('active','replaced','inactive'))or(old.status='active'and new.status in('replaced','inactive')))then raise exception using errcode='55000',message='sim_identity_or_transition_immutable';end if;
 if(new.status in('assigned','active'))<>exists(select 1 from public.telecom_sim_associations where workspace_id=new.workspace_id and sim_id=new.id and ended_at is null)then raise exception using errcode='23514',message='sim_association_state_mismatch';end if;
 end if;new.updated_at:=statement_timestamp();return new;end$$;
create trigger telecom_sim_identity before insert or update on public.telecom_sims for each row execute function public.sim_v1_guard_resource();
create function public.sim_v1_guard_association()returns trigger language plpgsql set search_path=''as $$declare c uuid;o uuid;begin
 if tg_op='UPDATE'then if(new.id,new.workspace_id,new.sim_id,new.line_id,new.iccid_identifier_id,new.eid_identifier_id,new.assigned_at,new.created_by_user_id)is distinct from(old.id,old.workspace_id,old.sim_id,old.line_id,old.iccid_identifier_id,old.eid_identifier_id,old.assigned_at,old.created_by_user_id)or old.ended_at is not null or old.activated_at is not null and new.activated_at is distinct from old.activated_at then raise exception using errcode='55000',message='sim_history_immutable';end if;end if;
 select s.customer_id,s.operator_id into c,o from public.telecom_lines l join public.telecom_services s on s.id=l.service_id and s.workspace_id=l.workspace_id where l.workspace_id=new.workspace_id and l.id=new.line_id;
 if c is null or not exists(select 1 from public.telecom_sims where workspace_id=new.workspace_id and id=new.sim_id and customer_id=c and operator_id=o)or not exists(select 1 from public.telecom_identifiers where workspace_id=new.workspace_id and id=new.iccid_identifier_id and sim_id=new.sim_id and identifier_kind='iccid')or(new.eid_identifier_id is not null and not exists(select 1 from public.telecom_identifiers where workspace_id=new.workspace_id and id=new.eid_identifier_id and sim_id=new.sim_id and identifier_kind='eid'))or(new.replacement_sim_id is not null and not exists(select 1 from public.telecom_sims where workspace_id=new.workspace_id and id=new.replacement_sim_id and customer_id=c and operator_id=o))then raise exception using errcode='23514',message='sim_invalid_ancestry';end if;return new;end$$;
create trigger telecom_sim_association_ancestry before insert or update on public.telecom_sim_associations for each row execute function public.sim_v1_guard_association();

do $$declare expr text;begin select pg_get_expr(conbin,conrelid)into expr from pg_constraint where conrelid='public.product_commands'::regclass and conname='product_commands_operation_check';alter table public.product_commands drop constraint product_commands_operation_check;execute 'alter table public.product_commands add constraint product_commands_operation_check check(('||expr||')or operation in(''sim.create'',''sim.assign'',''sim.activate'',''sim.replace'',''sim.deactivate'',''sim.cancel''))';end$$;
create function public.sim_v1_validate(op text,inp jsonb)returns void language plpgsql set search_path=''as $$declare req text[];opt text[]:=array[]::text[];k text;v jsonb;s text;begin
 case op
when 'sim.create'then req:=array['command_id','customer_id','operator_id','kind','display_label']::text[];
when 'sim.assign'then req:=array['command_id','id','expected_version','line_id','expected_line_version']::text[];
when 'sim.activate'then req:=array['command_id','id','expected_version','expected_line_version','evidence_source','provider_confirmation']::text[];
when 'sim.replace'then req:=array['command_id','id','expected_version','replacement_sim_id','expected_replacement_version','expected_line_version','replacement_status','evidence_source','provider_confirmation']::text[];
when 'sim.deactivate'then req:=array['command_id','id','expected_version','expected_line_version','evidence_source']::text[];
when 'sim.cancel'then req:=array['command_id','id','expected_version']::text[];
when 'sim.list'then req:=array[]::text[];
when 'sim.get'then req:=array['id']::text[];
when 'sim.history'then req:=array['line_id']::text[];
 else raise exception using errcode='22023',message='sim_invalid_operation';end case;
 if op='sim.list'then opt:=array['limit','after_id','customer_id','operator_id','line_id','kind','status','source'];elsif op='sim.history'then opt:=array['limit','after_id'];end if;
 if inp is null or jsonb_typeof(inp)<>'object'or octet_length(inp::text)>4096 or exists(select 1 from jsonb_object_keys(inp)x where not x=any(req||opt))or exists(select 1 from unnest(req)x where not inp?x)then raise exception using errcode='22023',message='sim_invalid_input';end if;
 for k,v in select key,value from jsonb_each(inp)loop s:=inp->>k;
 if k='id'or k like '%_id'then if jsonb_typeof(v)is distinct from 'string'or s!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'then raise exception using errcode='22023',message='sim_invalid_input';end if;
 elsif k in('expected_version','expected_replacement_version','expected_line_version','limit')then if jsonb_typeof(v)is distinct from 'number'or s!~'^[1-9][0-9]{0,14}$'or(k='limit'and s::bigint>100)then raise exception using errcode='22023',message='sim_invalid_input';end if;
 else if jsonb_typeof(v)is distinct from 'string'or(k='display_label'and(char_length(btrim(s))not between 1 and 200 or s~'[[:cntrl:]]'))or(k='kind'and s not in('physical','esim'))or(k='status'and s not in('prepared','assigned','active','replaced','inactive','cancelled'))or(k='source'and s not in('manual','import','integration'))or(k='evidence_source'and s<>'manual')or(k='replacement_status'and s not in('assigned','active'))or(k='provider_confirmation'and s not in('confirmed_active','not_recorded'))then raise exception using errcode='22023',message='sim_invalid_input';end if;end if;
 end loop;
 if op='sim.activate'and inp->>'provider_confirmation'<>'confirmed_active'or op='sim.replace'and((inp->>'replacement_status'='active')<>(inp->>'provider_confirmation'='confirmed_active')or inp->>'id'=inp->>'replacement_sim_id')then raise exception using errcode='22023',message='sim_invalid_input';end if;
end$$;
create function public.sim_v1_command(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare a uuid;prior jsonb;q public.telecom_sims%rowtype;replacement public.telecom_sims%rowtype;assoc public.telecom_sim_associations%rowtype;new_assoc uuid;line uuid;c public.telecom_contracts%rowtype;s public.telecom_services%rowtype;l public.telecom_lines%rowtype;iccid uuid;eid uuid;target_sim uuid;begin
 a:=public.product_v1_assert_scope(p_workspace_id,true);perform public.sim_v1_validate(p_operation,p_input);if p_operation in('sim.list','sim.get','sim.history')then raise exception using errcode='22023',message='sim_invalid_operation';end if;
 prior:=public.product_v1_begin_command(p_workspace_id,a,p_operation,p_input);if prior is not null then return prior;end if;
 if p_operation='sim.create'then
 perform 1 from public.customers where workspace_id=p_workspace_id and id=(p_input->>'customer_id')::uuid and status='active'for share;if not found then raise exception using errcode='P0002',message='sim_customer_not_found';end if;
 perform 1 from public.telecom_operators where workspace_id=p_workspace_id and id=(p_input->>'operator_id')::uuid and status='active'for share;if not found then raise exception using errcode='P0002',message='sim_operator_not_found';end if;
 insert into public.telecom_sims(workspace_id,customer_id,operator_id,kind,display_label,created_by_user_id)values(p_workspace_id,(p_input->>'customer_id')::uuid,(p_input->>'operator_id')::uuid,p_input->>'kind',p_input->>'display_label',a)returning *into q;
 else
 select *into q from public.telecom_sims where workspace_id=p_workspace_id and id=(p_input->>'id')::uuid;if not found then raise exception using errcode='P0002',message='sim_not_found';end if;
 if q.source<>'manual'then raise exception using errcode='42501',message='sim_external_read_only';end if;if q.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='sim_conflict';end if;
 if p_operation='sim.assign'then line:=(p_input->>'line_id')::uuid;elsif p_operation<>'sim.cancel'then select *into assoc from public.telecom_sim_associations where workspace_id=p_workspace_id and sim_id=q.id and ended_at is null;if not found then raise exception using errcode='22023',message='sim_invalid_transition';end if;line:=assoc.line_id;end if;
 if line is not null then
 select con.*into c from public.telecom_contracts con join public.telecom_services svc on svc.contract_id=con.id and svc.workspace_id=con.workspace_id join public.telecom_lines lin on lin.service_id=svc.id and lin.workspace_id=svc.workspace_id where lin.workspace_id=p_workspace_id and lin.id=line for update of con;if not found then raise exception using errcode='P0002',message='sim_line_not_found';end if;
 select svc.*into s from public.telecom_services svc join public.telecom_lines lin on lin.service_id=svc.id and lin.workspace_id=svc.workspace_id where lin.workspace_id=p_workspace_id and lin.id=line for update of svc;
 select *into l from public.telecom_lines where workspace_id=p_workspace_id and id=line for update;
 if l.version<>(p_input->>'expected_line_version')::bigint then raise exception using errcode='40001',message='sim_line_conflict';end if;
 if c.source<>'manual'or s.source<>'manual'or l.source<>'manual'then raise exception using errcode='42501',message='sim_external_line_read_only';end if;
 if s.service_kind not in('mobile','data_connectivity')or l.status not in('pending','active','suspended')or s.status not in('pending','active','suspended')or c.status not in('draft','active')then raise exception using errcode='22023',message='sim_line_inactive';end if;
 end if;
 -- Lock both resources deterministically after the same portfolio ancestor order.
 perform 1 from public.telecom_sims where workspace_id=p_workspace_id and(id=q.id or p_operation='sim.replace'and id=(p_input->>'replacement_sim_id')::uuid)order by id for update;
 select *into q from public.telecom_sims where workspace_id=p_workspace_id and id=q.id;
 if q.source<>'manual'then raise exception using errcode='42501',message='sim_external_read_only';end if;if q.version<>(p_input->>'expected_version')::bigint then raise exception using errcode='40001',message='sim_conflict';end if;
 perform 1 from public.customers where workspace_id=p_workspace_id and id=q.customer_id and status='active'for share;if not found then raise exception using errcode='22023',message='sim_customer_inactive';end if;
 if line is not null and(q.customer_id<>s.customer_id or q.operator_id<>s.operator_id)then raise exception using errcode='22023',message='sim_invalid_ancestry';end if;
 if p_operation not in('sim.assign','sim.cancel')then select *into assoc from public.telecom_sim_associations where workspace_id=p_workspace_id and id=assoc.id and sim_id=q.id and ended_at is null for update;if not found then raise exception using errcode='40001',message='sim_conflict';end if;end if;
 if p_operation='sim.cancel'then if q.status<>'prepared'then raise exception using errcode='22023',message='sim_invalid_transition';end if;update public.telecom_sims set status='cancelled',cancelled_at=statement_timestamp()where id=q.id returning *into q;
 elsif p_operation='sim.assign'then
 if q.status<>'prepared'then raise exception using errcode='22023',message='sim_invalid_transition';end if;
 select id into iccid from public.telecom_identifiers where workspace_id=p_workspace_id and sim_id=q.id and identifier_kind='iccid'and status='active'for share;if not found then raise exception using errcode='22023',message='sim_iccid_required';end if;
 select id into eid from public.telecom_identifiers where workspace_id=p_workspace_id and sim_id=q.id and identifier_kind='eid'and status='active'for share;
 insert into public.telecom_sim_associations(workspace_id,sim_id,line_id,iccid_identifier_id,eid_identifier_id,created_by_user_id)values(p_workspace_id,q.id,l.id,iccid,eid,a)returning *into assoc;
 update public.telecom_sims set status='assigned'where id=q.id returning *into q;
 elsif p_operation='sim.activate'then
 if q.status<>'assigned'then raise exception using errcode='22023',message='sim_invalid_transition';end if;
 update public.telecom_sim_associations set activated_at=statement_timestamp()where id=assoc.id returning *into assoc;update public.telecom_sims set status='active',activated_at=statement_timestamp()where id=q.id returning *into q;
 elsif p_operation='sim.deactivate'then
 if q.status not in('assigned','active')then raise exception using errcode='22023',message='sim_invalid_transition';end if;
 update public.telecom_sim_associations set ended_at=statement_timestamp(),end_reason='deactivated'where id=assoc.id returning *into assoc;update public.telecom_sims set status='inactive',deactivated_at=statement_timestamp()where id=q.id returning *into q;
 else
 if q.status not in('assigned','active')then raise exception using errcode='22023',message='sim_invalid_transition';end if;
 select *into replacement from public.telecom_sims where workspace_id=p_workspace_id and id=(p_input->>'replacement_sim_id')::uuid;if not found then raise exception using errcode='P0002',message='sim_replacement_not_found';end if;
 if replacement.source<>'manual'then raise exception using errcode='42501',message='sim_external_read_only';end if;if replacement.version<>(p_input->>'expected_replacement_version')::bigint then raise exception using errcode='40001',message='sim_conflict';end if;if replacement.status<>'prepared'or replacement.customer_id<>q.customer_id or replacement.operator_id<>q.operator_id then raise exception using errcode='22023',message='sim_invalid_replacement';end if;
 select id into iccid from public.telecom_identifiers where workspace_id=p_workspace_id and sim_id=replacement.id and identifier_kind='iccid'and status='active'for share;if not found then raise exception using errcode='22023',message='sim_iccid_required';end if;
 select id into eid from public.telecom_identifiers where workspace_id=p_workspace_id and sim_id=replacement.id and identifier_kind='eid'and status='active'for share;
 update public.telecom_sim_associations set ended_at=statement_timestamp(),end_reason='replaced',replacement_sim_id=replacement.id where id=assoc.id returning *into assoc;
 insert into public.telecom_sim_associations(workspace_id,sim_id,line_id,iccid_identifier_id,eid_identifier_id,activated_at,created_by_user_id)values(p_workspace_id,replacement.id,l.id,iccid,eid,case when p_input->>'replacement_status'='active'then statement_timestamp()end,a)returning id into new_assoc;
 update public.telecom_sims set status='replaced',replaced_at=statement_timestamp()where id=q.id returning *into q;
 update public.telecom_sims set status=p_input->>'replacement_status',activated_at=case when p_input->>'replacement_status'='active'then statement_timestamp()end where id=replacement.id returning *into replacement;
 end if;end if;
 prior:=jsonb_build_object('contract_version','sim.v1','operation',p_operation,'command_id',p_input->>'command_id','id',q.id,'version',q.version,'status',q.status,'source',q.source,'association_id',assoc.id,'replacement_id',replacement.id,'replacement_version',replacement.version,'replacement_status',replacement.status,'replacement_association_id',new_assoc);
 insert into public.product_audit_events(workspace_id,actor_id,command_id,operation,entity_id,entity_version)values(p_workspace_id,a,(p_input->>'command_id')::uuid,p_operation,q.id,q.version);
 update public.product_commands set receipt=prior where workspace_id=p_workspace_id and actor_id=a and command_id=(p_input->>'command_id')::uuid;return prior;
 exception when unique_violation then raise exception using errcode='40001',message='sim_conflict';when integrity_constraint_violation or data_exception then raise exception using errcode='22023',message='sim_invalid_input';
end$$;
create function public.sim_v1_query(p_workspace_id uuid,p_operation text,p_input jsonb)returns jsonb language plpgsql security definer set search_path=''as $$declare rows jsonb;lim int;next_id uuid;begin
 perform public.product_v1_assert_scope(p_workspace_id,false);perform public.sim_v1_validate(p_operation,p_input);if p_operation not in('sim.list','sim.get','sim.history')then raise exception using errcode='22023',message='sim_invalid_operation';end if;
 lim:=case when p_operation='sim.get'then 1 else coalesce((p_input->>'limit')::int,50)end;
 if p_operation='sim.history'then
 perform 1 from public.telecom_lines where workspace_id=p_workspace_id and id=(p_input->>'line_id')::uuid;if not found then raise exception using errcode='P0002',message='sim_line_not_found';end if;
 select coalesce(jsonb_agg(to_jsonb(x)order by id),'[]'::jsonb)into rows from(select a.id,a.sim_id,a.line_id,s.kind,ic.masked_display as masked_iccid,e.masked_display as masked_eid,case when a.end_reason='replaced'then 'replaced'when a.end_reason='deactivated'then 'inactive'when a.activated_at is not null then 'active'else 'assigned'end as status,a.assigned_at,a.activated_at,a.ended_at,a.replacement_sim_id from public.telecom_sim_associations a join public.telecom_sims s on s.id=a.sim_id and s.workspace_id=a.workspace_id join public.telecom_identifiers ic on ic.id=a.iccid_identifier_id and ic.workspace_id=a.workspace_id left join public.telecom_identifiers e on e.id=a.eid_identifier_id and e.workspace_id=a.workspace_id where a.workspace_id=p_workspace_id and a.line_id=(p_input->>'line_id')::uuid and(not p_input?'after_id'or a.id>(p_input->>'after_id')::uuid)order by a.id limit lim+1)x;
 else
 select coalesce(jsonb_agg(to_jsonb(x)order by id),'[]'::jsonb)into rows from(select s.id,s.version,s.customer_id,s.operator_id,s.kind,s.display_label,s.status,s.source,ic.masked_display as masked_iccid,e.masked_display as masked_eid,a.line_id as assigned_line_id,s.activated_at,s.replaced_at,s.deactivated_at,s.cancelled_at,s.created_at,s.updated_at from public.telecom_sims s left join public.telecom_identifiers ic on ic.sim_id=s.id and ic.workspace_id=s.workspace_id and ic.identifier_kind='iccid'and ic.status='active'left join public.telecom_identifiers e on e.sim_id=s.id and e.workspace_id=s.workspace_id and e.identifier_kind='eid'and e.status='active'left join public.telecom_sim_associations a on a.sim_id=s.id and a.workspace_id=s.workspace_id and a.ended_at is null where s.workspace_id=p_workspace_id and(p_operation<>'sim.get'or s.id=(p_input->>'id')::uuid)and(not p_input?'after_id'or s.id>(p_input->>'after_id')::uuid)and(not p_input?'customer_id'or s.customer_id=(p_input->>'customer_id')::uuid)and(not p_input?'operator_id'or s.operator_id=(p_input->>'operator_id')::uuid)and(not p_input?'line_id'or a.line_id=(p_input->>'line_id')::uuid)and(not p_input?'kind'or s.kind=p_input->>'kind')and(not p_input?'status'or s.status=p_input->>'status')and(not p_input?'source'or s.source=p_input->>'source')order by s.id limit lim+1)x;
 end if;
 if p_operation='sim.get'then if jsonb_array_length(rows)=0 then return null;end if;return jsonb_build_object('contract_version','sim.v1','operation',p_operation,'record',rows->0);end if;
 if jsonb_array_length(rows)>lim then rows:=rows-lim;next_id:=(rows->(lim-1)->>'id')::uuid;end if;
 return jsonb_build_object('contract_version','sim.v1','operation',p_operation,'items',rows,'next_id',next_id)||case when p_operation='sim.history'then jsonb_build_object('line_id',p_input->>'line_id')else '{}'::jsonb end;
end$$;
revoke all on function public.sim_v1_guard_resource(),public.sim_v1_guard_association(),public.sim_v1_validate(text,jsonb),public.sim_v1_command(uuid,text,jsonb),public.sim_v1_query(uuid,text,jsonb)from public,anon,authenticated,service_role;
grant execute on function public.sim_v1_command(uuid,text,jsonb),public.sim_v1_query(uuid,text,jsonb)to authenticated;
commit;
