'use client'
import {useEffect,useState} from 'react'
import {useProduct} from './Provider'
import {safeMessage} from './repository'
import {control} from '@/features/product/ui'
import {exactMinor} from '@/features/customers/CustomerDomainPages'
import {productDate} from '@/features/product/presentation'
import type {PlanRowV1,PlanVersionRowV1} from '@/lib/contracts/telecom-collections-v1'
type Page<T>={items:readonly T[];next_id:string|null}
export function ContractVersionSelect({operatorId,date,value,onChange,disabled=false}:{operatorId:string;date:string;value:PlanVersionRowV1|null;onChange:(v:PlanVersionRowV1|null,planLabel?:string)=>void;disabled?:boolean}){
 const {repository}=useProduct(),[plan,setPlan]=useState(''),[planLabel,setPlanLabel]=useState(''),[planCursors,setPlanCursors]=useState<string[]>([]),[versionCursors,setVersionCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),planKey=JSON.stringify([operatorId,planCursors,revision]),versionKey=JSON.stringify([operatorId,date,plan,versionCursors,revision]),[plans,setPlans]=useState<{key:string;page?:Page<PlanRowV1>;error?:string}>(),[versions,setVersions]=useState<{key:string;page?:Page<PlanVersionRowV1>;error?:string}>()
 const p=plans?.key===planKey?plans:undefined,v=versions?.key===versionKey?versions:undefined
 useEffect(()=>{if(!operatorId)return;let active=true;void repository.collection('plan.list',{operator_id:operatorId,status:'active',limit:20,sort:'id_asc',...(planCursors.at(-1)?{after_id:planCursors.at(-1)}:{})}).then(page=>{if(active)setPlans({key:planKey,page})}).catch(e=>{if(active)setPlans({key:planKey,error:safeMessage(e)})});return()=>{active=false}},[repository,operatorId,planCursors,planKey])
 useEffect(()=>{if(!plan||!date)return;let active=true;void repository.collection('plan_version.list',{operator_id:operatorId,plan_id:plan,status:'active',valid_on:date,limit:20,sort:'id_asc',...(versionCursors.at(-1)?{after_id:versionCursors.at(-1)}:{})}).then(page=>{if(active)setVersions({key:versionKey,page})}).catch(e=>{if(active)setVersions({key:versionKey,error:safeMessage(e)})});return()=>{active=false}},[repository,operatorId,date,plan,versionCursors,versionKey])
 return <div className="space-y-3"><p className="text-xs text-slate-500">Puedes registrar el contrato sin una tarifa vendida. Seleccionar una versión conserva sus condiciones históricas.</p><label className="block text-sm">Tarifa del contrato<select aria-label="Tarifa del contrato" className={control+' mt-1 w-full'} disabled={disabled||!p?.page} value={plan} onChange={e=>{setPlan(e.target.value);setPlanLabel(p?.page?.items.find(r=>r.id===e.target.value)?.display_name??'');setVersionCursors([]);onChange(null)}}><option value="">Sin tarifa seleccionada</option>{plan&&!p?.page?.items.some(r=>r.id===plan)&&<option value={plan} disabled>Tarifa seleccionada · otra página</option>}{p?.page?.items.map(r=><option key={r.id} value={r.id}>{r.display_name}</option>)}</select></label>{(planCursors.length>0||p?.page?.next_id)&&<div className="flex flex-wrap gap-2"><button type="button" className={control} disabled={disabled||!p?.page||!planCursors.length} onClick={()=>setPlanCursors(c=>c.slice(0,-1))}>Tarifas anteriores del contrato</button><button type="button" className={control} disabled={disabled||!p?.page?.next_id} onClick={()=>{if(p?.page?.next_id)setPlanCursors(c=>[...c,p.page!.next_id!])}}>Más tarifas del contrato</button></div>}{plan&&<><label className="block text-sm">Versión vendida<select aria-label="Versión vendida del contrato" className={control+' mt-1 w-full'} value={value?.id??''} disabled={disabled||!v?.page} onChange={e=>onChange(v?.page?.items.find(r=>r.id===e.target.value)??null,planLabel)}><option value="">Sin versión vendida registrada</option>{value&&!v?.page?.items.some(r=>r.id===value.id)&&<option value={value.id} disabled>Versión {value.version_number} seleccionada · otra página</option>}{v?.page?.items.map(r=><option key={r.id} value={r.id}>Versión {r.version_number} · {productDate(r.valid_from)} · {r.recurring_amount_minor===null?'Precio no registrado':exactMinor(r.recurring_amount_minor,r.currency)}</option>)}</select></label>{v?.page&&!v.page.items.length&&<p className="text-sm text-slate-500">No hay versiones vigentes para la fecha de inicio.</p>}{(versionCursors.length>0||v?.page?.next_id)&&<div className="flex flex-wrap gap-2"><button type="button" className={control} disabled={disabled||!v?.page||!versionCursors.length} onClick={()=>setVersionCursors(c=>c.slice(0,-1))}>Versiones anteriores del contrato</button><button type="button" className={control} disabled={disabled||!v?.page?.next_id} onClick={()=>{if(v?.page?.next_id)setVersionCursors(c=>[...c,v.page!.next_id!])}}>Más versiones del contrato</button></div>}</>}{(p?.error||v?.error)&&<div><p role="alert">{p?.error||v?.error}</p><button type="button" className={control} disabled={disabled} onClick={()=>setRevision(r=>r+1)}>Reintentar tarifas del contrato</button></div>}</div>
}
