import type {DocumentMaintenanceInputV1,DocumentMaintenanceOperationV1,DocumentMaintenanceReceiptV1} from '@/lib/contracts/document-maintenance-v1'
import {isClosedObjectV1 as plain,isUuidV1 as uuid} from '@/lib/server/product-work-runtime-v1'
import type {TeamListInputV1} from '@/lib/contracts/team-v1'
export const DOCUMENT_MAINTENANCE_RPC_V1={'document.verify_content':'document_integrity_v1_verify','document.cleanup_claim':'document_cleanup_v1_claim','document.cleanup_finish':'document_cleanup_v1_finish','document.expired_list':'document_cleanup_v1_expired_list'} as const
// Pure exact W1 input/receipt guards copied from the accepted server service; no crypto/provider authority enters the client.
export function parseDocumentMaintenanceInputV1(op:DocumentMaintenanceOperationV1,v:unknown):DocumentMaintenanceInputV1|null{
 try{return Object.hasOwn(DOCUMENT_MAINTENANCE_RPC_V1,op)&&op!=='document.expired_list'&&plain(v)&&Object.keys(v).sort().join(',')===(op==='document.verify_content'?'command_id,expected_version,id,ticket_id':'command_id,expected_version,id')&&uuid(v.command_id)&&uuid(v.id)&&Number.isSafeInteger(v.expected_version)&&(v.expected_version as number)>0&&(v.expected_version as number)<1e15&&(op!=='document.verify_content'||uuid(v.ticket_id))?Object.freeze({...v,command_id:v.command_id.toLowerCase(),id:v.id.toLowerCase(),...(op==='document.verify_content'?{ticket_id:(v.ticket_id as string).toLowerCase()}:{})})as DocumentMaintenanceInputV1:null}catch{return null}
}
export function parseDocumentMaintenanceReceiptV1(op:DocumentMaintenanceOperationV1,i:DocumentMaintenanceInputV1,v:unknown):DocumentMaintenanceReceiptV1|null{
 try{const integrity=op==='document.verify_content';if(!plain(v)||Object.keys(v).sort().join(',')!==(integrity?'command_id,contract_version,id,integrity,operation,scan_status,status,version':'command_id,contract_version,id,operation,status,version')||v.contract_version!==(integrity?'document.integrity.v1':'document.cleanup.v1')||v.operation!==op||v.command_id!==i.command_id||v.id!==i.id||v.version!==i.expected_version+1||v.status!==(integrity?'active':op==='document.cleanup_claim'?'pending':'archived')||integrity&&(v.integrity!=='verified_sha256'||v.scan_status!=='not_scanned'))return null;return Object.freeze({...v})as DocumentMaintenanceReceiptV1}catch{return null}
}

export type ExpiredDocumentPage={contract_version:'document.cleanup.v1';operation:'document.expired_list';items:readonly {id:string;version:number}[];next_id:string|null}
export function parseExpiredDocumentPage(input:TeamListInputV1,v:unknown):ExpiredDocumentPage|null{try{if(!plain(v)||Object.keys(v).sort().join(',')!=='contract_version,items,next_id,operation'||v.contract_version!=='document.cleanup.v1'||v.operation!=='document.expired_list'||!Array.isArray(v.items)||v.items.length>(input.limit??20))return null;let last=input.after_id??'';for(const row of v.items){if(!plain(row)||Object.keys(row).sort().join(',')!=='id,version'||!uuid(row.id)||row.id<=last||!Number.isSafeInteger(row.version)||(row.version as number)<1)return null;last=row.id}if(v.next_id!==null&&(v.next_id!==last||v.items.length!==(input.limit??20)))return null;return Object.freeze({...v,items:Object.freeze(v.items.map(row=>Object.freeze({...row})))}) as ExpiredDocumentPage}catch{return null}}
