'use client'
import {useEffect,useState} from 'react'
import {control,statusLabel} from '@/features/product/ui'
import {useProduct} from './Provider'
import {safeMessage} from './repository'
import type {LineRowV1} from '@/lib/contracts/telecom-collections-v1'
export function LineSelect({customerId,operatorId,onChange,value,disabled=false,label='Línea para SIM'}:{customerId:string;operatorId?:string;onChange:(row:LineRowV1|undefined)=>void;value:string;disabled?:boolean;label?:string}){
 const {repository}=useProduct(),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),key=JSON.stringify([customerId,operatorId,cursors,revision]),[state,setState]=useState<{key:string;rows?:readonly LineRowV1[];next?:string|null;error?:string}>(),current=state?.key===key?state:undefined
 useEffect(()=>{let active=true;void repository.collection('line.list',{customer_id:customerId,...(operatorId?{operator_id:operatorId}:{}),source:'manual',limit:20,sort:'id_asc',...(cursors.at(-1)?{after_id:cursors.at(-1)}:{})}).then(p=>{if(active)setState({key,rows:p.items,next:p.next_id})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,customerId,operatorId,cursors,key])
 const rows=current?.rows??[]
 return <div className="space-y-2"><label className="block text-sm">{label}<select aria-label={label} className={control+' mt-1 w-full'} value={value} disabled={disabled||!current?.rows} onChange={e=>onChange(rows.find(r=>r.id===e.target.value))}><option value="">Selecciona una línea</option>{value&&!rows.some(r=>r.id===value)&&<option value={value} disabled>Línea seleccionada · otra página</option>}{rows.filter(r=>!['ended','cancelled'].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.display_name||'Línea sin nombre'} · {r.masked_msisdn??'Número no registrado'} · {statusLabel(r.status)}</option>)}</select></label>{current?.error&&<p role="alert">{current.error}</p>}<div className="flex flex-wrap gap-2"><button type="button" className={control} disabled={disabled||!current?.rows||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Líneas anteriores</button><button type="button" className={control} disabled={disabled||!current?.next} onClick={()=>{if(current?.next)setCursors(v=>[...v,current.next!])}}>Más líneas</button><button type="button" className={control} disabled={disabled} onClick={()=>{onChange(undefined);setRevision(v=>v+1)}}>Actualizar líneas disponibles</button></div><p className="text-xs text-slate-500">Líneas manuales autorizadas, hasta 20 por página. El servidor comprueba contrato, servicio y versión antes de guardar.</p></div>
}
