'use client'
import {useEffect,useState} from 'react'
import {useProduct} from './Provider'
import {safeMessage} from './repository'
import {control} from '@/features/product/ui'
import type {TelecomCollectionPageV1} from '@/lib/contracts/telecom-collections-v1'
export function OperatorSelect({value,onChange,disabled=false}:{value:string;onChange:(id:string)=>void;disabled?:boolean}){
 const {repository}=useProduct(),[page,setPage]=useState<TelecomCollectionPageV1<'operator.list'>|null>(null),[status,setStatus]=useState<'active'|'inactive'>('active'),[cursors,setCursors]=useState<string[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{let active=true;void repository.collection('operator.list',{limit:20,status,sort:'id_asc',...(cursors.length?{after_id:cursors.at(-1)}:{})}).then(v=>{if(active){setPage(v);setError('')}}).catch(e=>{if(active){setPage(null);setError(safeMessage(e))}});return()=>{active=false}},[repository,status,cursors,revision])
 return <div className="space-y-1"><label className="block text-sm">Operador<select aria-label="Operador de clientes" className={control+' mt-1 w-full'} value={value} disabled={disabled||!page} onChange={e=>onChange(e.target.value)}><option value="">Todos los operadores</option>{value&&!page?.items.some(r=>r.id===value)&&<option value={value} disabled>Operador seleccionado · otra página</option>}{page?.items.map(r=><option value={r.id} key={r.id}>{r.display_name}</option>)}</select></label><div className="flex flex-wrap gap-1"><select aria-label="Estado de operadores disponibles" className={control+' text-xs'} value={status} disabled={disabled} onChange={e=>{setPage(null);setError('');setCursors([]);setStatus(e.target.value as typeof status)}}><option value="active">Operadores activos</option><option value="inactive">Operadores inactivos</option></select>{(cursors.length>0||page?.next_id)&&<><button type="button" className={control} disabled={disabled||!page||!cursors.length} onClick={()=>{setPage(null);setCursors(v=>v.slice(0,-1))}}>Operadores anteriores</button><button type="button" className={control} disabled={disabled||!page?.next_id} onClick={()=>{if(page?.next_id){setPage(null);setCursors(v=>[...v,page.next_id!])}}}>Más operadores</button></>}</div>{error&&<div><p role="alert" className="text-xs text-red-700">{error}</p><button type="button" className={control} onClick={()=>{setError('');setRevision(v=>v+1)}}>Reintentar operadores</button></div>}</div>
}
