'use client'
import {useEffect,useState} from 'react'
import {useProduct} from './Provider'
import {safeMessage} from './repository'
import {control,statusLabel} from '@/features/product/ui'
import {productDate} from '@/features/product/presentation'
type Kind='contract'|'service'|'line'
type Choice={id:string;name:string}
const titles={contract:'Contrato de la incidencia',service:'Servicio de la incidencia',line:'Línea de la incidencia'}
/** Complete bounded ordinary selectors; children are scoped to the chosen parent. */
export function PortfolioRelationSelect({kind,customerId,parentId,value,onChange,disabled=false,label=titles[kind],allowCustomerServices=false}:{kind:Kind;label?:string;customerId:string;parentId?:string;value:string;onChange:(id:string)=>void;disabled?:boolean;allowCustomerServices?:boolean}){
 const {repository}=useProduct(),[cursors,setCursors]=useState<string[]>([]),[revision,setRevision]=useState(0),canRead=!!customerId&&(kind==='contract'||!!parentId||kind==='service'&&allowCustomerServices),key=JSON.stringify([kind,customerId,parentId,cursors,revision,canRead]),[state,setState]=useState<{key:string;choices?:Choice[];next?:string|null;error?:string}>(),[selected,setSelected]=useState<{key:string;choice?:Choice}>(),selectedKey=JSON.stringify([key,value]),current=state?.key===key?state:undefined
 useEffect(()=>{if(!canRead)return;let active=true;async function read(){const input={customer_id:customerId,limit:20,sort:'id_asc' as const,...(cursors.at(-1)?{after_id:cursors.at(-1)}:{}),...(kind==='service'&&parentId?{contract_id:parentId}:kind==='line'&&parentId?{service_id:parentId}:{})};const page=await repository.collection(`${kind}.list`,input);return{next:page.next_id,choices:page.items.map(r=>({id:r.id,name:('display_name'in r&&r.display_name?r.display_name:kind==='contract'?'Contrato del '+productDate('start_date'in r?r.start_date:null):'Línea sin nombre')+' · '+statusLabel(r.status)}))}}void read().then(p=>{if(active)setState({key,...p})}).catch(e=>{if(active)setState({key,error:safeMessage(e)})});return()=>{active=false}},[repository,kind,customerId,parentId,cursors,key,canRead])
 useEffect(()=>{if(!value||!canRead)return;let active=true;async function read(){const n=BigInt('0x'+value.replaceAll('-',''));if(n===BigInt(0))return;const h=(n-BigInt(1)).toString(16).padStart(32,'0'),after=h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20),p=await repository.collection(`${kind}.list`,{customer_id:customerId,limit:1,sort:'id_asc',after_id:after,...(kind==='service'&&parentId?{contract_id:parentId}:kind==='line'&&parentId?{service_id:parentId}:{})}),r=p.items[0];if(r?.id!==value)return;return{id:r.id,name:('display_name'in r&&r.display_name?r.display_name:kind==='contract'?'Contrato del '+productDate('start_date'in r?r.start_date:null):'Línea sin nombre')+' · '+statusLabel(r.status)}}void read().then(choice=>{if(active)setSelected({key:selectedKey,choice})}).catch(()=>{if(active)setSelected({key:selectedKey})});return()=>{active=false}},[repository,kind,customerId,parentId,value,selectedKey,canRead])
 const choices=current?.choices??[],outside=value&&!choices.some(r=>r.id===value),choice=selected?.key===selectedKey&&current?.choices?selected.choice:undefined
 return <div className="space-y-2"><label className="block text-sm">{label}<select aria-label={label} className={control+' mt-1 w-full'} disabled={disabled||!current?.choices} value={value} onChange={e=>onChange(e.target.value)}><option value="">Sin {kind==='contract'?'contrato':kind==='service'?'servicio':'línea'}</option>{outside&&<option value={value} disabled={!choice}>{choice?.name??'Relación no disponible'}</option>}{choices.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{current?.error&&<p role="alert" className="text-xs text-red-700">{current.error}</p>}<div className="flex flex-wrap gap-2"><button type="button" className={control} disabled={disabled||!current?.choices||!cursors.length} onClick={()=>setCursors(v=>v.slice(0,-1))}>Relaciones anteriores de {kind==='contract'?'contrato':kind==='service'?'servicio':'línea'}</button><button type="button" className={control} disabled={disabled||!current?.next} onClick={()=>{if(current?.next)setCursors(v=>[...v,current.next!])}}>Más relaciones de {kind==='contract'?'contrato':kind==='service'?'servicio':'línea'}</button><button type="button" className={control} disabled={disabled} onClick={()=>setRevision(v=>v+1)}>Actualizar relaciones de {kind==='contract'?'contrato':kind==='service'?'servicio':'línea'}</button></div></div>
}
